// AUTO-GENERATED. DO NOT MODIFY this file.
@file:Suppress(
    "UndocumentedPublicClass",
    "UndocumentedPublicProperty",
    "ktlint:standard:max-line-length",
)

package com.plasma.sd.service.integration

import com.sdds.sandbox.AndroidViewStyleProvider
import com.sdds.sandbox.AndroidViewStyleReference
import com.sdds.sandbox.viewStyleReference
import com.sdds.plasma.sd.service.R as DsR

internal object PlasmaB2cIconButtonVariationsView : AndroidViewStyleProvider() {
    override val variations: Map<String, AndroidViewStyleReference> =
        mapOf(
            "Xl" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXl),
            "Xl.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlDefault),
            "Xl.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlSecondary),
            "Xl.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlAccent),
            "Xl.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPositive),
            "Xl.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlNegative),
            "Xl.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlWarning),
            "Xl.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlClear),
            "Xl.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlDark),
            "Xl.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlBlack),
            "Xl.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlWhite),
            "Xl.Pilled" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPilled),
            "Xl.Pilled.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPilledDefault),
            "Xl.Pilled.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPilledSecondary),
            "Xl.Pilled.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPilledAccent),
            "Xl.Pilled.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPilledPositive),
            "Xl.Pilled.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPilledNegative),
            "Xl.Pilled.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPilledWarning),
            "Xl.Pilled.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPilledClear),
            "Xl.Pilled.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPilledDark),
            "Xl.Pilled.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPilledBlack),
            "Xl.Pilled.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXlPilledWhite),
            "L" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonL),
            "L.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLDefault),
            "L.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLSecondary),
            "L.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLAccent),
            "L.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPositive),
            "L.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLNegative),
            "L.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLWarning),
            "L.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLClear),
            "L.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLDark),
            "L.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLBlack),
            "L.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLWhite),
            "L.Pilled" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPilled),
            "L.Pilled.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledDefault),
            "L.Pilled.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledSecondary),
            "L.Pilled.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledAccent),
            "L.Pilled.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledPositive),
            "L.Pilled.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledNegative),
            "L.Pilled.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledWarning),
            "L.Pilled.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledClear),
            "L.Pilled.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledDark),
            "L.Pilled.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledBlack),
            "L.Pilled.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledWhite),
            "M" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonM),
            "M.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMDefault),
            "M.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMSecondary),
            "M.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMAccent),
            "M.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPositive),
            "M.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMNegative),
            "M.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMWarning),
            "M.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMClear),
            "M.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMDark),
            "M.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMBlack),
            "M.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMWhite),
            "M.Pilled" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPilled),
            "M.Pilled.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledDefault),
            "M.Pilled.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledSecondary),
            "M.Pilled.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledAccent),
            "M.Pilled.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledPositive),
            "M.Pilled.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledNegative),
            "M.Pilled.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledWarning),
            "M.Pilled.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledClear),
            "M.Pilled.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledDark),
            "M.Pilled.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledBlack),
            "M.Pilled.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledWhite),
            "S" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonS),
            "S.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSDefault),
            "S.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSSecondary),
            "S.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSAccent),
            "S.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPositive),
            "S.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSNegative),
            "S.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSWarning),
            "S.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSClear),
            "S.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSDark),
            "S.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSBlack),
            "S.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSWhite),
            "S.Pilled" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPilled),
            "S.Pilled.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledDefault),
            "S.Pilled.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledSecondary),
            "S.Pilled.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledAccent),
            "S.Pilled.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledPositive),
            "S.Pilled.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledNegative),
            "S.Pilled.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledWarning),
            "S.Pilled.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledClear),
            "S.Pilled.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledDark),
            "S.Pilled.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledBlack),
            "S.Pilled.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledWhite),
            "Xs" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXs),
            "Xs.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsDefault),
            "Xs.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsSecondary),
            "Xs.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsAccent),
            "Xs.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPositive),
            "Xs.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsNegative),
            "Xs.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsWarning),
            "Xs.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsClear),
            "Xs.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsDark),
            "Xs.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsBlack),
            "Xs.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsWhite),
            "Xs.Pilled" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilled),
            "Xs.Pilled.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledDefault),
            "Xs.Pilled.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledSecondary),
            "Xs.Pilled.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledAccent),
            "Xs.Pilled.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledPositive),
            "Xs.Pilled.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledNegative),
            "Xs.Pilled.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledWarning),
            "Xs.Pilled.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledClear),
            "Xs.Pilled.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledDark),
            "Xs.Pilled.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledBlack),
            "Xs.Pilled.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledWhite),
            "Xxs" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxs),
            "Xxs.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsDefault),
            "Xxs.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsSecondary),
            "Xxs.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsAccent),
            "Xxs.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPositive),
            "Xxs.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsNegative),
            "Xxs.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsWarning),
            "Xxs.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsClear),
            "Xxs.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsDark),
            "Xxs.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsBlack),
            "Xxs.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsWhite),
            "Xxs.Pilled" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPilled),
            "Xxs.Pilled.Default" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPilledDefault),
            "Xxs.Pilled.Secondary" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPilledSecondary),
            "Xxs.Pilled.Accent" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPilledAccent),
            "Xxs.Pilled.Positive" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPilledPositive),
            "Xxs.Pilled.Negative" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPilledNegative),
            "Xxs.Pilled.Warning" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPilledWarning),
            "Xxs.Pilled.Clear" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPilledClear),
            "Xxs.Pilled.Dark" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPilledDark),
            "Xxs.Pilled.Black" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPilledBlack),
            "Xxs.Pilled.White" to viewStyleReference(DsR.style.Plasma_SdService_ComponentOverlays_IconButtonXxsPilledWhite),
        )
}
