package com.sdds.playground.sandbox.stylessalute.integration.badge.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.stylessalute.integration.s

internal object StylesSaluteIconBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> = mapOf(
        "LDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLDefault,
        "LAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLAccent,
        "LPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPositive,
        "LWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLWarning,
        "LNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLNegative,
        "LWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLWhite,
        "LBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLBlack,
        "LPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledDefault,
        "LPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledAccent,
        "LPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledPositive,
        "LPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledWarning,
        "LPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledNegative,
        "LPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledWhite,
        "LPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledBlack,
        "MDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMDefault,
        "MAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMAccent,
        "MPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPositive,
        "MWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMWarning,
        "MNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMNegative,
        "MWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMWhite,
        "MBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMBlack,
        "MPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledDefault,
        "MPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledAccent,
        "MPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledPositive,
        "MPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledWarning,
        "MPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledNegative,
        "MPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledWhite,
        "MPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledBlack,
        "SDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSDefault,
        "SAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSAccent,
        "SPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPositive,
        "SWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSNegative,
        "SNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSWarning,
        "SWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSWhite,
        "SBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSBlack,
        "SPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledDefault,
        "SPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledAccent,
        "SPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledPositive,
        "SPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledWarning,
        "SPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledNegative,
        "SPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledWhite,
        "SPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledBlack,
        "XsDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsDefault,
        "XsAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsAccent,
        "XsPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPositive,
        "XsWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsWarning,
        "XsNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsNegative,
        "XsWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsWhite,
        "XsBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsBlack,
        "XsPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledDefault,
        "XsPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledAccent,
        "XsPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledPositive,
        "XsPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledWarning,
        "XsPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledNegative,
        "XsPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledWhite,
        "XsPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledBlack,
    )
}
