package com.sdds.playground.sandbox.stylessalute.integration.badge.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.stylessalute.integration.s

internal object StylesSaluteIconBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> = mapOf(
        "LDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLDefault,
        "LAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLAccent,
        "LPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPositive,
        "LWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLWarning,
        "LNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLNegative,
        "LLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLLight,
        "LDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLDark,
        "LPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledDefault,
        "LPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledAccent,
        "LPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledPositive,
        "LPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledWarning,
        "LPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledNegative,
        "LPilledLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledLight,
        "LPilledDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledDark,
        "MDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMDefault,
        "MAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMAccent,
        "MPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPositive,
        "MWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMWarning,
        "MNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMNegative,
        "MLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMLight,
        "MDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMDark,
        "MPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledDefault,
        "MPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledAccent,
        "MPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledPositive,
        "MPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledWarning,
        "MPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledNegative,
        "MPilledLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledLight,
        "MPilledDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledDark,
        "SDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSDefault,
        "SAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSAccent,
        "SPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPositive,
        "SWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSNegative,
        "SNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSWarning,
        "SLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSLight,
        "SDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSDark,
        "SPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledDefault,
        "SPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledAccent,
        "SPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledPositive,
        "SPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledWarning,
        "SPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledNegative,
        "SPilledLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledLight,
        "SPilledDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledDark,
        "XsDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsDefault,
        "XsAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsAccent,
        "XsPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPositive,
        "XsWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsWarning,
        "XsNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsNegative,
        "XsLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsLight,
        "XsDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsDark,
        "XsPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledDefault,
        "XsPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledAccent,
        "XsPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledPositive,
        "XsPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledWarning,
        "XsPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledNegative,
        "XsPilledLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledLight,
        "XsPilledDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledDark,
    )
}
