package com.sdds.playground.sandbox.stylessalute.integration.badge.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.stylessalute.integration.s

internal object StylesSaluteIconBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> = mapOf(
        "LDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLDefault,
        "LAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLAccent,
        "LPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLPositive,
        "LWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLWarning,
        "LNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLNegative,
        "LWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLWhite,
        "LBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLBlack,
        "LPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLPilledDefault,
        "LPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLPilledAccent,
        "LPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLPilledPositive,
        "LPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLPilledWarning,
        "LPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLPilledNegative,
        "LPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLPilledWhite,
        "LPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeLPilledBlack,
        "MDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMDefault,
        "MAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMAccent,
        "MPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMPositive,
        "MWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMWarning,
        "MNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMNegative,
        "MWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMWhite,
        "MBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMBlack,
        "MPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMPilledDefault,
        "MPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMPilledAccent,
        "MPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMPilledPositive,
        "MPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMPilledWarning,
        "MPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMPilledNegative,
        "MPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMPilledWhite,
        "MPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeMPilledBlack,
        "SDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSDefault,
        "SAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSAccent,
        "SPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSPositive,
        "SWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSNegative,
        "SNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSWarning,
        "SWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSWhite,
        "SBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSBlack,
        "SPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSPilledDefault,
        "SPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSPilledAccent,
        "SPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSPilledPositive,
        "SPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSPilledWarning,
        "SPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSPilledNegative,
        "SPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSPilledWhite,
        "SPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeSPilledBlack,
        "XsDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsDefault,
        "XsAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsAccent,
        "XsPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsPositive,
        "XsWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsWarning,
        "XsNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsNegative,
        "XsWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsWhite,
        "XsBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsBlack,
        "XsPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsPilledDefault,
        "XsPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsPilledAccent,
        "XsPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsPilledPositive,
        "XsPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsPilledWarning,
        "XsPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsPilledNegative,
        "XsPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsPilledWhite,
        "XsPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeXsPilledBlack,
    )
}
