package com.sdds.playground.sandbox.stylessalute.integration.badge.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.stylessalute.integration.s

internal object StylesSaluteIconBadgeTransparentVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> = mapOf(
        "TransparentLDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLDefault,
        "TransparentLAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLAccent,
        "TransparentLPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPositive,
        "TransparentLWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLWarning,
        "TransparentLNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLNegative,
        "TransparentLLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLLight,
        "TransparentLDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLDark,
        "TransparentLPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledDefault,
        "TransparentLPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledAccent,
        "TransparentLPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledPositive,
        "TransparentLPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledWarning,
        "TransparentLPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledNegative,
        "TransparentLPilledLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledLight,
        "TransparentLPilledDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledDark,
        "TransparentMDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMDefault,
        "TransparentMAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMAccent,
        "TransparentMPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPositive,
        "TransparentMWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMWarning,
        "TransparentMNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMNegative,
        "TransparentMLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMLight,
        "TransparentMDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMDark,
        "TransparentMPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledDefault,
        "TransparentMPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledAccent,
        "TransparentMPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledPositive,
        "TransparentMPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledWarning,
        "TransparentMPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledNegative,
        "TransparentMPilledLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledLight,
        "TransparentMPilledDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledDark,
        "TransparentSDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSDefault,
        "TransparentSAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSAccent,
        "TransparentSPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPositive,
        "TransparentSWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSNegative,
        "TransparentSNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSWarning,
        "TransparentSLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSLight,
        "TransparentSDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSDark,
        "TransparentSPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledDefault,
        "TransparentSPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledAccent,
        "TransparentSPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledPositive,
        "TransparentSPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledWarning,
        "TransparentSPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledNegative,
        "TransparentSPilledLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledLight,
        "TransparentSPilledDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledDark,
        "TransparentXsDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsDefault,
        "TransparentXsAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsAccent,
        "TransparentXsPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPositive,
        "TransparentXsWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsWarning,
        "TransparentXsNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsNegative,
        "TransparentXsLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsLight,
        "TransparentXsDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsDark,
        "TransparentXsPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledDefault,
        "TransparentXsPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledAccent,
        "TransparentXsPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledPositive,
        "TransparentXsPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledWarning,
        "TransparentXsPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledNegative,
        "TransparentXsPilledLight" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledLight,
        "TransparentXsPilledDark" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledDark,
    )
}
