package com.sdds.playground.sandbox.stylessalute.integration.badge.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.stylessalute.integration.s

internal object StylesSaluteIconBadgeTransparentVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> = mapOf(
        "TransparentLDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLDefault,
        "TransparentLAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLAccent,
        "TransparentLPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPositive,
        "TransparentLWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLWarning,
        "TransparentLNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLNegative,
        "TransparentLWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLWhite,
        "TransparentLBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLBlack,
        "TransparentLPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledDefault,
        "TransparentLPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledAccent,
        "TransparentLPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledPositive,
        "TransparentLPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledWarning,
        "TransparentLPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledNegative,
        "TransparentLPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledWhite,
        "TransparentLPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledBlack,
        "TransparentMDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMDefault,
        "TransparentMAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMAccent,
        "TransparentMPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPositive,
        "TransparentMWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMWarning,
        "TransparentMNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMNegative,
        "TransparentMWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMWhite,
        "TransparentMBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMBlack,
        "TransparentMPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledDefault,
        "TransparentMPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledAccent,
        "TransparentMPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledPositive,
        "TransparentMPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledWarning,
        "TransparentMPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledNegative,
        "TransparentMPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledWhite,
        "TransparentMPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledBlack,
        "TransparentSDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSDefault,
        "TransparentSAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSAccent,
        "TransparentSPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPositive,
        "TransparentSWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSNegative,
        "TransparentSNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSWarning,
        "TransparentSWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSWhite,
        "TransparentSBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSBlack,
        "TransparentSPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledDefault,
        "TransparentSPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledAccent,
        "TransparentSPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledPositive,
        "TransparentSPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledWarning,
        "TransparentSPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledNegative,
        "TransparentSPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledWhite,
        "TransparentSPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledBlack,
        "TransparentXsDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsDefault,
        "TransparentXsAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsAccent,
        "TransparentXsPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPositive,
        "TransparentXsWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsWarning,
        "TransparentXsNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsNegative,
        "TransparentXsWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsWhite,
        "TransparentXsBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsBlack,
        "TransparentXsPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledDefault,
        "TransparentXsPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledAccent,
        "TransparentXsPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledPositive,
        "TransparentXsPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledWarning,
        "TransparentXsPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledNegative,
        "TransparentXsPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledWhite,
        "TransparentXsPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledBlack,
    )
}
