// AUTO-GENERATED. DO NOT MODIFY this file.
@file:Suppress(
    "UndocumentedPublicClass",
    "UndocumentedPublicProperty",
    "ktlint:standard:max-line-length",
)

package com.sdds.serv.integration

import com.sdds.compose.sandbox.ComposeStyleProvider
import com.sdds.compose.sandbox.ComposeStyleReference
import com.sdds.compose.uikit.FormItemStyle
import com.sdds.compose.uikit.style.style
import com.sdds.serv.styles.formitem.Default
import com.sdds.serv.styles.formitem.FormItem
import com.sdds.serv.styles.formitem.L
import com.sdds.serv.styles.formitem.M
import com.sdds.serv.styles.formitem.Negative
import com.sdds.serv.styles.formitem.Positive
import com.sdds.serv.styles.formitem.RequiredEnd
import com.sdds.serv.styles.formitem.RequiredStart
import com.sdds.serv.styles.formitem.S
import com.sdds.serv.styles.formitem.TitleStart
import com.sdds.serv.styles.formitem.TitleTop
import com.sdds.serv.styles.formitem.Warning
import com.sdds.serv.styles.formitem.Xs

internal object SddsServFormItemVariationsCompose : ComposeStyleProvider<FormItemStyle>() {
    override val variations: Map<String, ComposeStyleReference<FormItemStyle>> =
        mapOf(
            "Xs.Default" to ComposeStyleReference { FormItem.Xs.Default.style() },
            "Xs.Positive" to ComposeStyleReference { FormItem.Xs.Positive.style() },
            "Xs.Negative" to ComposeStyleReference { FormItem.Xs.Negative.style() },
            "Xs.Warning" to ComposeStyleReference { FormItem.Xs.Warning.style() },
            "Xs.RequiredStart.Default" to ComposeStyleReference { FormItem.Xs.RequiredStart.Default.style() },
            "Xs.RequiredStart.Positive" to ComposeStyleReference { FormItem.Xs.RequiredStart.Positive.style() },
            "Xs.RequiredStart.Negative" to ComposeStyleReference { FormItem.Xs.RequiredStart.Negative.style() },
            "Xs.RequiredStart.Warning" to ComposeStyleReference { FormItem.Xs.RequiredStart.Warning.style() },
            "Xs.RequiredEnd.Default" to ComposeStyleReference { FormItem.Xs.RequiredEnd.Default.style() },
            "Xs.RequiredEnd.Positive" to ComposeStyleReference { FormItem.Xs.RequiredEnd.Positive.style() },
            "Xs.RequiredEnd.Negative" to ComposeStyleReference { FormItem.Xs.RequiredEnd.Negative.style() },
            "Xs.RequiredEnd.Warning" to ComposeStyleReference { FormItem.Xs.RequiredEnd.Warning.style() },
            "Xs.TitleTop.Default" to ComposeStyleReference { FormItem.Xs.TitleTop.Default.style() },
            "Xs.TitleTop.Positive" to ComposeStyleReference { FormItem.Xs.TitleTop.Positive.style() },
            "Xs.TitleTop.Negative" to ComposeStyleReference { FormItem.Xs.TitleTop.Negative.style() },
            "Xs.TitleTop.Warning" to ComposeStyleReference { FormItem.Xs.TitleTop.Warning.style() },
            "Xs.TitleTop.RequiredStart.Default" to ComposeStyleReference { FormItem.Xs.TitleTop.RequiredStart.Default.style() },
            "Xs.TitleTop.RequiredStart.Positive" to ComposeStyleReference { FormItem.Xs.TitleTop.RequiredStart.Positive.style() },
            "Xs.TitleTop.RequiredStart.Negative" to ComposeStyleReference { FormItem.Xs.TitleTop.RequiredStart.Negative.style() },
            "Xs.TitleTop.RequiredStart.Warning" to ComposeStyleReference { FormItem.Xs.TitleTop.RequiredStart.Warning.style() },
            "Xs.TitleTop.RequiredEnd.Default" to ComposeStyleReference { FormItem.Xs.TitleTop.RequiredEnd.Default.style() },
            "Xs.TitleTop.RequiredEnd.Positive" to ComposeStyleReference { FormItem.Xs.TitleTop.RequiredEnd.Positive.style() },
            "Xs.TitleTop.RequiredEnd.Negative" to ComposeStyleReference { FormItem.Xs.TitleTop.RequiredEnd.Negative.style() },
            "Xs.TitleTop.RequiredEnd.Warning" to ComposeStyleReference { FormItem.Xs.TitleTop.RequiredEnd.Warning.style() },
            "Xs.TitleStart.Default" to ComposeStyleReference { FormItem.Xs.TitleStart.Default.style() },
            "Xs.TitleStart.Positive" to ComposeStyleReference { FormItem.Xs.TitleStart.Positive.style() },
            "Xs.TitleStart.Negative" to ComposeStyleReference { FormItem.Xs.TitleStart.Negative.style() },
            "Xs.TitleStart.Warning" to ComposeStyleReference { FormItem.Xs.TitleStart.Warning.style() },
            "Xs.TitleStart.RequiredStart.Default" to ComposeStyleReference { FormItem.Xs.TitleStart.RequiredStart.Default.style() },
            "Xs.TitleStart.RequiredStart.Positive" to ComposeStyleReference {
                FormItem.Xs.TitleStart.RequiredStart.Positive.style()
            },
            "Xs.TitleStart.RequiredStart.Negative" to ComposeStyleReference {
                FormItem.Xs.TitleStart.RequiredStart.Negative.style()
            },
            "Xs.TitleStart.RequiredStart.Warning" to ComposeStyleReference { FormItem.Xs.TitleStart.RequiredStart.Warning.style() },
            "Xs.TitleStart.RequiredEnd.Default" to ComposeStyleReference { FormItem.Xs.TitleStart.RequiredEnd.Default.style() },
            "Xs.TitleStart.RequiredEnd.Positive" to ComposeStyleReference { FormItem.Xs.TitleStart.RequiredEnd.Positive.style() },
            "Xs.TitleStart.RequiredEnd.Negative" to ComposeStyleReference { FormItem.Xs.TitleStart.RequiredEnd.Negative.style() },
            "Xs.TitleStart.RequiredEnd.Warning" to ComposeStyleReference { FormItem.Xs.TitleStart.RequiredEnd.Warning.style() },
            "S.Default" to ComposeStyleReference { FormItem.S.Default.style() },
            "S.Positive" to ComposeStyleReference { FormItem.S.Positive.style() },
            "S.Negative" to ComposeStyleReference { FormItem.S.Negative.style() },
            "S.Warning" to ComposeStyleReference { FormItem.S.Warning.style() },
            "S.RequiredStart.Default" to ComposeStyleReference { FormItem.S.RequiredStart.Default.style() },
            "S.RequiredStart.Positive" to ComposeStyleReference { FormItem.S.RequiredStart.Positive.style() },
            "S.RequiredStart.Negative" to ComposeStyleReference { FormItem.S.RequiredStart.Negative.style() },
            "S.RequiredStart.Warning" to ComposeStyleReference { FormItem.S.RequiredStart.Warning.style() },
            "S.RequiredEnd.Default" to ComposeStyleReference { FormItem.S.RequiredEnd.Default.style() },
            "S.RequiredEnd.Positive" to ComposeStyleReference { FormItem.S.RequiredEnd.Positive.style() },
            "S.RequiredEnd.Negative" to ComposeStyleReference { FormItem.S.RequiredEnd.Negative.style() },
            "S.RequiredEnd.Warning" to ComposeStyleReference { FormItem.S.RequiredEnd.Warning.style() },
            "S.TitleTop.Default" to ComposeStyleReference { FormItem.S.TitleTop.Default.style() },
            "S.TitleTop.Positive" to ComposeStyleReference { FormItem.S.TitleTop.Positive.style() },
            "S.TitleTop.Negative" to ComposeStyleReference { FormItem.S.TitleTop.Negative.style() },
            "S.TitleTop.Warning" to ComposeStyleReference { FormItem.S.TitleTop.Warning.style() },
            "S.TitleTop.RequiredStart.Default" to ComposeStyleReference { FormItem.S.TitleTop.RequiredStart.Default.style() },
            "S.TitleTop.RequiredStart.Positive" to ComposeStyleReference { FormItem.S.TitleTop.RequiredStart.Positive.style() },
            "S.TitleTop.RequiredStart.Negative" to ComposeStyleReference { FormItem.S.TitleTop.RequiredStart.Negative.style() },
            "S.TitleTop.RequiredStart.Warning" to ComposeStyleReference { FormItem.S.TitleTop.RequiredStart.Warning.style() },
            "S.TitleTop.RequiredEnd.Default" to ComposeStyleReference { FormItem.S.TitleTop.RequiredEnd.Default.style() },
            "S.TitleTop.RequiredEnd.Positive" to ComposeStyleReference { FormItem.S.TitleTop.RequiredEnd.Positive.style() },
            "S.TitleTop.RequiredEnd.Negative" to ComposeStyleReference { FormItem.S.TitleTop.RequiredEnd.Negative.style() },
            "S.TitleTop.RequiredEnd.Warning" to ComposeStyleReference { FormItem.S.TitleTop.RequiredEnd.Warning.style() },
            "S.TitleStart.Default" to ComposeStyleReference { FormItem.S.TitleStart.Default.style() },
            "S.TitleStart.Positive" to ComposeStyleReference { FormItem.S.TitleStart.Positive.style() },
            "S.TitleStart.Negative" to ComposeStyleReference { FormItem.S.TitleStart.Negative.style() },
            "S.TitleStart.Warning" to ComposeStyleReference { FormItem.S.TitleStart.Warning.style() },
            "S.TitleStart.RequiredStart.Default" to ComposeStyleReference { FormItem.S.TitleStart.RequiredStart.Default.style() },
            "S.TitleStart.RequiredStart.Positive" to ComposeStyleReference { FormItem.S.TitleStart.RequiredStart.Positive.style() },
            "S.TitleStart.RequiredStart.Negative" to ComposeStyleReference { FormItem.S.TitleStart.RequiredStart.Negative.style() },
            "S.TitleStart.RequiredStart.Warning" to ComposeStyleReference { FormItem.S.TitleStart.RequiredStart.Warning.style() },
            "S.TitleStart.RequiredEnd.Default" to ComposeStyleReference { FormItem.S.TitleStart.RequiredEnd.Default.style() },
            "S.TitleStart.RequiredEnd.Positive" to ComposeStyleReference { FormItem.S.TitleStart.RequiredEnd.Positive.style() },
            "S.TitleStart.RequiredEnd.Negative" to ComposeStyleReference { FormItem.S.TitleStart.RequiredEnd.Negative.style() },
            "S.TitleStart.RequiredEnd.Warning" to ComposeStyleReference { FormItem.S.TitleStart.RequiredEnd.Warning.style() },
            "M.Default" to ComposeStyleReference { FormItem.M.Default.style() },
            "M.Positive" to ComposeStyleReference { FormItem.M.Positive.style() },
            "M.Negative" to ComposeStyleReference { FormItem.M.Negative.style() },
            "M.Warning" to ComposeStyleReference { FormItem.M.Warning.style() },
            "M.RequiredStart.Default" to ComposeStyleReference { FormItem.M.RequiredStart.Default.style() },
            "M.RequiredStart.Positive" to ComposeStyleReference { FormItem.M.RequiredStart.Positive.style() },
            "M.RequiredStart.Negative" to ComposeStyleReference { FormItem.M.RequiredStart.Negative.style() },
            "M.RequiredStart.Warning" to ComposeStyleReference { FormItem.M.RequiredStart.Warning.style() },
            "M.RequiredEnd.Default" to ComposeStyleReference { FormItem.M.RequiredEnd.Default.style() },
            "M.RequiredEnd.Positive" to ComposeStyleReference { FormItem.M.RequiredEnd.Positive.style() },
            "M.RequiredEnd.Negative" to ComposeStyleReference { FormItem.M.RequiredEnd.Negative.style() },
            "M.RequiredEnd.Warning" to ComposeStyleReference { FormItem.M.RequiredEnd.Warning.style() },
            "M.TitleTop.Default" to ComposeStyleReference { FormItem.M.TitleTop.Default.style() },
            "M.TitleTop.Positive" to ComposeStyleReference { FormItem.M.TitleTop.Positive.style() },
            "M.TitleTop.Negative" to ComposeStyleReference { FormItem.M.TitleTop.Negative.style() },
            "M.TitleTop.Warning" to ComposeStyleReference { FormItem.M.TitleTop.Warning.style() },
            "M.TitleTop.RequiredStart.Default" to ComposeStyleReference { FormItem.M.TitleTop.RequiredStart.Default.style() },
            "M.TitleTop.RequiredStart.Positive" to ComposeStyleReference { FormItem.M.TitleTop.RequiredStart.Positive.style() },
            "M.TitleTop.RequiredStart.Negative" to ComposeStyleReference { FormItem.M.TitleTop.RequiredStart.Negative.style() },
            "M.TitleTop.RequiredStart.Warning" to ComposeStyleReference { FormItem.M.TitleTop.RequiredStart.Warning.style() },
            "M.TitleTop.RequiredEnd.Default" to ComposeStyleReference { FormItem.M.TitleTop.RequiredEnd.Default.style() },
            "M.TitleTop.RequiredEnd.Positive" to ComposeStyleReference { FormItem.M.TitleTop.RequiredEnd.Positive.style() },
            "M.TitleTop.RequiredEnd.Negative" to ComposeStyleReference { FormItem.M.TitleTop.RequiredEnd.Negative.style() },
            "M.TitleTop.RequiredEnd.Warning" to ComposeStyleReference { FormItem.M.TitleTop.RequiredEnd.Warning.style() },
            "M.TitleStart.Default" to ComposeStyleReference { FormItem.M.TitleStart.Default.style() },
            "M.TitleStart.Positive" to ComposeStyleReference { FormItem.M.TitleStart.Positive.style() },
            "M.TitleStart.Negative" to ComposeStyleReference { FormItem.M.TitleStart.Negative.style() },
            "M.TitleStart.Warning" to ComposeStyleReference { FormItem.M.TitleStart.Warning.style() },
            "M.TitleStart.RequiredStart.Default" to ComposeStyleReference { FormItem.M.TitleStart.RequiredStart.Default.style() },
            "M.TitleStart.RequiredStart.Positive" to ComposeStyleReference { FormItem.M.TitleStart.RequiredStart.Positive.style() },
            "M.TitleStart.RequiredStart.Negative" to ComposeStyleReference { FormItem.M.TitleStart.RequiredStart.Negative.style() },
            "M.TitleStart.RequiredStart.Warning" to ComposeStyleReference { FormItem.M.TitleStart.RequiredStart.Warning.style() },
            "M.TitleStart.RequiredEnd.Default" to ComposeStyleReference { FormItem.M.TitleStart.RequiredEnd.Default.style() },
            "M.TitleStart.RequiredEnd.Positive" to ComposeStyleReference { FormItem.M.TitleStart.RequiredEnd.Positive.style() },
            "M.TitleStart.RequiredEnd.Negative" to ComposeStyleReference { FormItem.M.TitleStart.RequiredEnd.Negative.style() },
            "M.TitleStart.RequiredEnd.Warning" to ComposeStyleReference { FormItem.M.TitleStart.RequiredEnd.Warning.style() },
            "L.Default" to ComposeStyleReference { FormItem.L.Default.style() },
            "L.Positive" to ComposeStyleReference { FormItem.L.Positive.style() },
            "L.Negative" to ComposeStyleReference { FormItem.L.Negative.style() },
            "L.Warning" to ComposeStyleReference { FormItem.L.Warning.style() },
            "L.RequiredStart.Default" to ComposeStyleReference { FormItem.L.RequiredStart.Default.style() },
            "L.RequiredStart.Positive" to ComposeStyleReference { FormItem.L.RequiredStart.Positive.style() },
            "L.RequiredStart.Negative" to ComposeStyleReference { FormItem.L.RequiredStart.Negative.style() },
            "L.RequiredStart.Warning" to ComposeStyleReference { FormItem.L.RequiredStart.Warning.style() },
            "L.RequiredEnd.Default" to ComposeStyleReference { FormItem.L.RequiredEnd.Default.style() },
            "L.RequiredEnd.Positive" to ComposeStyleReference { FormItem.L.RequiredEnd.Positive.style() },
            "L.RequiredEnd.Negative" to ComposeStyleReference { FormItem.L.RequiredEnd.Negative.style() },
            "L.RequiredEnd.Warning" to ComposeStyleReference { FormItem.L.RequiredEnd.Warning.style() },
            "L.TitleTop.Default" to ComposeStyleReference { FormItem.L.TitleTop.Default.style() },
            "L.TitleTop.Positive" to ComposeStyleReference { FormItem.L.TitleTop.Positive.style() },
            "L.TitleTop.Negative" to ComposeStyleReference { FormItem.L.TitleTop.Negative.style() },
            "L.TitleTop.Warning" to ComposeStyleReference { FormItem.L.TitleTop.Warning.style() },
            "L.TitleTop.RequiredStart.Default" to ComposeStyleReference { FormItem.L.TitleTop.RequiredStart.Default.style() },
            "L.TitleTop.RequiredStart.Positive" to ComposeStyleReference { FormItem.L.TitleTop.RequiredStart.Positive.style() },
            "L.TitleTop.RequiredStart.Negative" to ComposeStyleReference { FormItem.L.TitleTop.RequiredStart.Negative.style() },
            "L.TitleTop.RequiredStart.Warning" to ComposeStyleReference { FormItem.L.TitleTop.RequiredStart.Warning.style() },
            "L.TitleTop.RequiredEnd.Default" to ComposeStyleReference { FormItem.L.TitleTop.RequiredEnd.Default.style() },
            "L.TitleTop.RequiredEnd.Positive" to ComposeStyleReference { FormItem.L.TitleTop.RequiredEnd.Positive.style() },
            "L.TitleTop.RequiredEnd.Negative" to ComposeStyleReference { FormItem.L.TitleTop.RequiredEnd.Negative.style() },
            "L.TitleTop.RequiredEnd.Warning" to ComposeStyleReference { FormItem.L.TitleTop.RequiredEnd.Warning.style() },
            "L.TitleStart.Default" to ComposeStyleReference { FormItem.L.TitleStart.Default.style() },
            "L.TitleStart.Positive" to ComposeStyleReference { FormItem.L.TitleStart.Positive.style() },
            "L.TitleStart.Negative" to ComposeStyleReference { FormItem.L.TitleStart.Negative.style() },
            "L.TitleStart.Warning" to ComposeStyleReference { FormItem.L.TitleStart.Warning.style() },
            "L.TitleStart.RequiredStart.Default" to ComposeStyleReference { FormItem.L.TitleStart.RequiredStart.Default.style() },
            "L.TitleStart.RequiredStart.Positive" to ComposeStyleReference { FormItem.L.TitleStart.RequiredStart.Positive.style() },
            "L.TitleStart.RequiredStart.Negative" to ComposeStyleReference { FormItem.L.TitleStart.RequiredStart.Negative.style() },
            "L.TitleStart.RequiredStart.Warning" to ComposeStyleReference { FormItem.L.TitleStart.RequiredStart.Warning.style() },
            "L.TitleStart.RequiredEnd.Default" to ComposeStyleReference { FormItem.L.TitleStart.RequiredEnd.Default.style() },
            "L.TitleStart.RequiredEnd.Positive" to ComposeStyleReference { FormItem.L.TitleStart.RequiredEnd.Positive.style() },
            "L.TitleStart.RequiredEnd.Negative" to ComposeStyleReference { FormItem.L.TitleStart.RequiredEnd.Negative.style() },
            "L.TitleStart.RequiredEnd.Warning" to ComposeStyleReference { FormItem.L.TitleStart.RequiredEnd.Warning.style() },
        )
}
