package com.sdds.playground.sandbox.plasma.sd.service.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.plasma.sd.service.R as DsR

internal object PlasmaB2cChipVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Plasma_SdService_ComponentOverlays_ChipL,
            "L.Default" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLDefault,
            "L.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLAccent,
            "L.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLNegative,
            "L.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLPositive,
            "L.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLSecondary,
            "L.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLWarning,
            "L.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLPilled,
            "L.Pilled.Default" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLPilledDefault,
            "L.Pilled.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLPilledAccent,
            "L.Pilled.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLPilledNegative,
            "L.Pilled.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLPilledPositive,
            "L.Pilled.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLPilledSecondary,
            "L.Pilled.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_ChipLPilledWarning,
            "M" to DsR.style.Plasma_SdService_ComponentOverlays_ChipM,
            "M.Default" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMDefault,
            "M.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMAccent,
            "M.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMNegative,
            "M.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMPositive,
            "M.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMSecondary,
            "M.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMWarning,
            "M.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMPilled,
            "M.Pilled.Default" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMPilledDefault,
            "M.Pilled.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMPilledAccent,
            "M.Pilled.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMPilledNegative,
            "M.Pilled.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMPilledPositive,
            "M.Pilled.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMPilledSecondary,
            "M.Pilled.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_ChipMPilledWarning,
            "S" to DsR.style.Plasma_SdService_ComponentOverlays_ChipS,
            "S.Default" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSDefault,
            "S.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSAccent,
            "S.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSNegative,
            "S.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSPositive,
            "S.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSSecondary,
            "S.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSWarning,
            "S.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSPilled,
            "S.Pilled.Default" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSPilledDefault,
            "S.Pilled.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSPilledAccent,
            "S.Pilled.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSPilledNegative,
            "S.Pilled.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSPilledPositive,
            "S.Pilled.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSPilledSecondary,
            "S.Pilled.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_ChipSPilledWarning,
            "Xs" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXs,
            "Xs.Default" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsDefault,
            "Xs.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsAccent,
            "Xs.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsNegative,
            "Xs.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsPositive,
            "Xs.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsSecondary,
            "Xs.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsWarning,
            "Xs.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsPilled,
            "Xs.Pilled.Default" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsPilledDefault,
            "Xs.Pilled.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsPilledAccent,
            "Xs.Pilled.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsPilledNegative,
            "Xs.Pilled.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsPilledPositive,
            "Xs.Pilled.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsPilledSecondary,
            "Xs.Pilled.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_ChipXsPilledWarning,
        )
}
