package com.sdds.playground.sandbox.plasma.sd.service.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.plasma.sd.service.R as DsR

internal object PlasmaB2cSpinnerVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "Xxl" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxl,
            "Xxl.Default" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxlDefault,
            "Xxl.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxlSecondary,
            "Xxl.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxlAccent,
            "Xxl.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxlPositive,
            "Xxl.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxlNegative,
            "Xxl.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxlWarning,
            "Xxl.Info" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxlInfo,
            "Xl" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXl,
            "Xl.Default" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXlDefault,
            "Xl.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXlSecondary,
            "Xl.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXlAccent,
            "Xl.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXlPositive,
            "Xl.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXlNegative,
            "Xl.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXlWarning,
            "Xl.Info" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXlInfo,
            "L" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerL,
            "L.Default" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerLDefault,
            "L.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerLSecondary,
            "L.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerLAccent,
            "L.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerLPositive,
            "L.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerLNegative,
            "L.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerLWarning,
            "L.Info" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerLInfo,
            "M" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerM,
            "M.Default" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerMDefault,
            "M.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerMSecondary,
            "M.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerMAccent,
            "M.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerMPositive,
            "M.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerMNegative,
            "M.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerMWarning,
            "M.Info" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerMInfo,
            "S" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerS,
            "S.Default" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerSDefault,
            "S.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerSSecondary,
            "S.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerSAccent,
            "S.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerSPositive,
            "S.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerSNegative,
            "S.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerSWarning,
            "S.Info" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerSInfo,
            "Xs" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXs,
            "Xs.Default" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXsDefault,
            "Xs.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXsSecondary,
            "Xs.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXsAccent,
            "Xs.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXsPositive,
            "Xs.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXsNegative,
            "Xs.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXsWarning,
            "Xs.Info" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXsInfo,
            "Xxs" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxs,
            "Xxs.Default" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxsDefault,
            "Xxs.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxsSecondary,
            "Xxs.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxsAccent,
            "Xxs.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxsPositive,
            "Xxs.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxsNegative,
            "Xxs.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxsWarning,
            "Xxs.Info" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerXxsInfo,
            "Scalable" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerScalable,
            "Scalable.Default" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerScalableDefault,
            "Scalable.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerScalableSecondary,
            "Scalable.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerScalableAccent,
            "Scalable.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerScalablePositive,
            "Scalable.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerScalableNegative,
            "Scalable.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerScalableWarning,
            "Scalable.Info" to DsR.style.Plasma_SdService_ComponentOverlays_SpinnerScalableInfo,
        )
}
