package com.sdds.playground.sandbox.plasma.sd.service.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.plasma.sd.service.R as DsR

internal object PlasmaB2cBasicButtonVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "Xl" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXl,
            "Xl.Default" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXlDefault,
            "Xl.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXlSecondary,
            "Xl.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXlAccent,
            "Xl.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXlPositive,
            "Xl.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXlNegative,
            "Xl.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXlWarning,
            "Xl.Clear" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXlClear,
            "Xl.Dark" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXlDark,
            "Xl.Black" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXlBlack,
            "Xl.White" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXlWhite,
            "L" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonL,
            "L.Default" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonLDefault,
            "L.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonLSecondary,
            "L.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonLAccent,
            "L.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonLPositive,
            "L.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonLNegative,
            "L.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonLWarning,
            "L.Clear" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonLClear,
            "L.Dark" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonLDark,
            "L.Black" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonLBlack,
            "L.White" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonLWhite,
            "M" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonM,
            "M.Default" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonMDefault,
            "M.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonMSecondary,
            "M.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonMAccent,
            "M.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonMPositive,
            "M.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonMNegative,
            "M.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonMWarning,
            "M.Clear" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonMClear,
            "M.Dark" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonMDark,
            "M.Black" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonMBlack,
            "M.White" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonMWhite,
            "S" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonS,
            "S.Default" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonSDefault,
            "S.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonSSecondary,
            "S.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonSAccent,
            "S.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonSPositive,
            "S.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonSNegative,
            "S.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonSWarning,
            "S.Clear" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonSClear,
            "S.Dark" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonSDark,
            "S.Black" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonSBlack,
            "S.White" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonSWhite,
            "Xs" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXs,
            "Xs.Default" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXsDefault,
            "Xs.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXsSecondary,
            "Xs.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXsAccent,
            "Xs.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXsPositive,
            "Xs.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXsNegative,
            "Xs.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXsWarning,
            "Xs.Clear" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXsClear,
            "Xs.Dark" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXsDark,
            "Xs.Black" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXsBlack,
            "Xs.White" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXsWhite,
            "Xxs" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXxs,
            "Xxs.Default" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXxsDefault,
            "Xxs.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXxsSecondary,
            "Xxs.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXxsAccent,
            "Xxs.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXxsPositive,
            "Xxs.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXxsNegative,
            "Xxs.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXxsWarning,
            "Xxs.Clear" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXxsClear,
            "Xxs.Dark" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXxsDark,
            "Xxs.Black" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXxsBlack,
            "Xxs.White" to DsR.style.Plasma_SdService_ComponentOverlays_BasicButtonXxsWhite,
        )
}
