package com.sdds.playground.sandbox.plasma.sd.service.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.plasma.sd.service.R as DsR

internal object PlasmaB2cIconButtonGroupVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "Xs" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXs,
            "Xs.Wide" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsWide,
            "Xs.Wide.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsWideDefault,
            "Xs.Wide.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsWidePilled,
            "Xs.Wide.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsWideSegmented,
            "Xs.Dense" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsDense,
            "Xs.Dense.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsDenseDefault,
            "Xs.Dense.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsDensePilled,
            "Xs.Dense.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsDenseSegmented,
            "Xs.NoGap" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsNoGap,
            "Xs.NoGap.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsNoGapDefault,
            "Xs.NoGap.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsNoGapPilled,
            "Xs.NoGap.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupXsNoGapSegmented,
            "S" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupS,
            "S.Wide" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSWide,
            "S.Wide.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSWideDefault,
            "S.Wide.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSWidePilled,
            "S.Wide.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSWideSegmented,
            "S.Dense" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSDense,
            "S.Dense.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSDenseDefault,
            "S.Dense.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSDensePilled,
            "S.Dense.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSDenseSegmented,
            "S.NoGap" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSNoGap,
            "S.NoGap.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSNoGapDefault,
            "S.NoGap.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSNoGapPilled,
            "S.NoGap.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupSNoGapSegmented,
            "M" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupM,
            "M.Wide" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMWide,
            "M.Wide.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMWideDefault,
            "M.Wide.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMWidePilled,
            "M.Wide.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMWideSegmented,
            "M.Dense" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMDense,
            "M.Dense.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMDenseDefault,
            "M.Dense.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMDensePilled,
            "M.Dense.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMDenseSegmented,
            "M.NoGap" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMNoGap,
            "M.NoGap.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMNoGapDefault,
            "M.NoGap.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMNoGapPilled,
            "M.NoGap.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupMNoGapSegmented,
            "L" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupL,
            "L.Wide" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLWide,
            "L.Wide.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLWideDefault,
            "L.Wide.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLWidePilled,
            "L.Wide.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLWideSegmented,
            "L.Dense" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLDense,
            "L.Dense.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLDenseDefault,
            "L.Dense.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLDensePilled,
            "L.Dense.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLDenseSegmented,
            "L.NoGap" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLNoGap,
            "L.NoGap.Default" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLNoGapDefault,
            "L.NoGap.Pilled" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLNoGapPilled,
            "L.NoGap.Segmented" to DsR.style.Plasma_SdService_ComponentOverlays_IconButtonGroupLNoGapSegmented,
        )
}
