package com.sdds.playground.sandbox.plasma.sd.service.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.plasma.sd.service.R as DsR

internal object PlasmaB2cCircularProgressBarVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "Xxl" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxl,
            "Xxl.Default" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxlDefault,
            "Xxl.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxlSecondary,
            "Xxl.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxlAccent,
            "Xxl.Gradient" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxlGradient,
            "Xxl.Info" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxlInfo,
            "Xxl.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxlNegative,
            "Xxl.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxlPositive,
            "Xxl.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxlWarning,
            "Xl" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXl,
            "Xl.Default" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXlDefault,
            "Xl.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXlSecondary,
            "Xl.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXlAccent,
            "Xl.Gradient" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXlGradient,
            "Xl.Info" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXlInfo,
            "Xl.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXlNegative,
            "Xl.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXlPositive,
            "Xl.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXlWarning,
            "L" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarL,
            "L.Default" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarLDefault,
            "L.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarLSecondary,
            "L.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarLAccent,
            "L.Gradient" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarLGradient,
            "L.Info" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarLInfo,
            "L.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarLNegative,
            "L.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarLPositive,
            "L.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarLWarning,
            "M" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarM,
            "M.Default" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarMDefault,
            "M.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarMSecondary,
            "M.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarMAccent,
            "M.Gradient" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarMGradient,
            "M.Info" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarMInfo,
            "M.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarMNegative,
            "M.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarMPositive,
            "M.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarMWarning,
            "S" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarS,
            "S.Default" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarSDefault,
            "S.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarSSecondary,
            "S.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarSAccent,
            "S.Gradient" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarSGradient,
            "S.Info" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarSInfo,
            "S.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarSNegative,
            "S.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarSPositive,
            "S.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarSWarning,
            "Xs" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXs,
            "Xs.Default" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXsDefault,
            "Xs.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXsSecondary,
            "Xs.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXsAccent,
            "Xs.Gradient" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXsGradient,
            "Xs.Info" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXsInfo,
            "Xs.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXsNegative,
            "Xs.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXsPositive,
            "Xs.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXsWarning,
            "Xxs" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxs,
            "Xxs.Default" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxsDefault,
            "Xxs.Secondary" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxsSecondary,
            "Xxs.Accent" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxsAccent,
            "Xxs.Gradient" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxsGradient,
            "Xxs.Info" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxsInfo,
            "Xxs.Negative" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxsNegative,
            "Xxs.Positive" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxsPositive,
            "Xxs.Warning" to DsR.style.Plasma_SdService_ComponentOverlays_CircularProgressBarXxsWarning,
        )
}
