package com.sdds.playground.sandbox.sdds.serv.integration.badge.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.sdds.serv.integration.s

internal object SddsServIconBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "LDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLDefault,
            "LAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLAccent,
            "LPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLPositive,
            "LWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLWarning,
            "LNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLNegative,
            "LWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLWhite,
            "LBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLBlack,
            "LPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLPilledDefault,
            "LPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLPilledAccent,
            "LPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLPilledPositive,
            "LPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLPilledWarning,
            "LPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLPilledNegative,
            "LPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLPilledWhite,
            "LPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidLPilledBlack,
            "MDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMDefault,
            "MAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMAccent,
            "MPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMPositive,
            "MWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMWarning,
            "MNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMNegative,
            "MWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMWhite,
            "MBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMBlack,
            "MPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMPilledDefault,
            "MPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMPilledAccent,
            "MPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMPilledPositive,
            "MPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMPilledWarning,
            "MPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMPilledNegative,
            "MPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMPilledWhite,
            "MPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidMPilledBlack,
            "SDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSDefault,
            "SAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSAccent,
            "SPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSPositive,
            "SWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSNegative,
            "SNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSWarning,
            "SWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSWhite,
            "SBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSBlack,
            "SPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSPilledDefault,
            "SPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSPilledAccent,
            "SPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSPilledPositive,
            "SPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSPilledWarning,
            "SPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSPilledNegative,
            "SPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSPilledWhite,
            "SPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidSPilledBlack,
            "XsDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsDefault,
            "XsAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsAccent,
            "XsPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsPositive,
            "XsWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsWarning,
            "XsNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsNegative,
            "XsWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsWhite,
            "XsBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsBlack,
            "XsPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsPilledDefault,
            "XsPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsPilledAccent,
            "XsPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsPilledPositive,
            "XsPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsPilledWarning,
            "XsPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsPilledNegative,
            "XsPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsPilledWhite,
            "XsPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeSolidXsPilledBlack,
        )
}
