package com.sdds.playground.sandbox.sdds.serv.integration.badge.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.sdds.serv.integration.s

internal object SddsServIconBadgeTransparentVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "TransparentLDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLDefault,
            "TransparentLAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLAccent,
            "TransparentLPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLPositive,
            "TransparentLWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLWarning,
            "TransparentLNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLNegative,
            "TransparentLLight" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLLight,
            "TransparentLDark" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLDark,
            "TransparentLPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLPilledDefault,
            "TransparentLPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLPilledAccent,
            "TransparentLPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLPilledPositive,
            "TransparentLPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLPilledWarning,
            "TransparentLPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLPilledNegative,
            "TransparentLPilledLight" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLPilledLight,
            "TransparentLPilledDark" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentLPilledDark,
            "TransparentMDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMDefault,
            "TransparentMAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMAccent,
            "TransparentMPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMPositive,
            "TransparentMWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMWarning,
            "TransparentMNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMNegative,
            "TransparentMLight" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMLight,
            "TransparentMDark" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMDark,
            "TransparentMPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMPilledDefault,
            "TransparentMPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMPilledAccent,
            "TransparentMPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMPilledPositive,
            "TransparentMPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMPilledWarning,
            "TransparentMPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMPilledNegative,
            "TransparentMPilledLight" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMPilledLight,
            "TransparentMPilledDark" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentMPilledDark,
            "TransparentSDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSDefault,
            "TransparentSAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSAccent,
            "TransparentSPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSPositive,
            "TransparentSWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSNegative,
            "TransparentSNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSWarning,
            "TransparentSLight" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSLight,
            "TransparentSDark" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSDark,
            "TransparentSPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSPilledDefault,
            "TransparentSPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSPilledAccent,
            "TransparentSPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSPilledPositive,
            "TransparentSPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSPilledWarning,
            "TransparentSPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSPilledNegative,
            "TransparentSPilledLight" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSPilledLight,
            "TransparentSPilledDark" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentSPilledDark,
            "TransparentXsDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsDefault,
            "TransparentXsAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsAccent,
            "TransparentXsPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsPositive,
            "TransparentXsWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsWarning,
            "TransparentXsNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsNegative,
            "TransparentXsLight" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsLight,
            "TransparentXsDark" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsDark,
            "TransparentXsPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsPilledDefault,
            "TransparentXsPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsPilledAccent,
            "TransparentXsPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsPilledPositive,
            "TransparentXsPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsPilledWarning,
            "TransparentXsPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsPilledNegative,
            "TransparentXsPilledLight" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsPilledLight,
            "TransparentXsPilledDark" to s.Serv_Sdds_ComponentOverlays_IconBadgeTransparentXsPilledDark,
        )
}
