package com.sdds.playground.sandbox.sdds.serv.integration.badge.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.sdds.serv.integration.s

internal object SddsServIconBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "LDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeLDefault,
            "LAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeLAccent,
            "LPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeLPositive,
            "LWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeLWarning,
            "LNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeLNegative,
            "LWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeLWhite,
            "LBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeLBlack,
            "LPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeLPilledDefault,
            "LPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeLPilledAccent,
            "LPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeLPilledPositive,
            "LPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeLPilledWarning,
            "LPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeLPilledNegative,
            "LPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeLPilledWhite,
            "LPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeLPilledBlack,
            "MDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeMDefault,
            "MAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeMAccent,
            "MPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeMPositive,
            "MWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeMWarning,
            "MNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeMNegative,
            "MWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeMWhite,
            "MBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeMBlack,
            "MPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeMPilledDefault,
            "MPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeMPilledAccent,
            "MPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeMPilledPositive,
            "MPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeMPilledWarning,
            "MPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeMPilledNegative,
            "MPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeMPilledWhite,
            "MPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeMPilledBlack,
            "SDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeSDefault,
            "SAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeSAccent,
            "SPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeSPositive,
            "SWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeSNegative,
            "SNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeSWarning,
            "SWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeSWhite,
            "SBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeSBlack,
            "SPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeSPilledDefault,
            "SPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeSPilledAccent,
            "SPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeSPilledPositive,
            "SPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeSPilledWarning,
            "SPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeSPilledNegative,
            "SPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeSPilledWhite,
            "SPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeSPilledBlack,
            "XsDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsDefault,
            "XsAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsAccent,
            "XsPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsPositive,
            "XsWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsWarning,
            "XsNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsNegative,
            "XsWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsWhite,
            "XsBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsBlack,
            "XsPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsPilledDefault,
            "XsPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsPilledAccent,
            "XsPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsPilledPositive,
            "XsPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsPilledWarning,
            "XsPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsPilledNegative,
            "XsPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsPilledWhite,
            "XsPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconBadgeXsPilledBlack,
        )
}
