package com.sdds.playground.sandbox.stylessalute.integration.compose

import androidx.compose.runtime.Composable
import com.sdds.compose.uikit.TextFieldStyle
import com.sdds.compose.uikit.style.style
import com.sdds.playground.sandbox.core.integration.ComposeStyleProvider
import com.sdds.stylessalute.styles.textfield.Default
import com.sdds.stylessalute.styles.textfield.Error
import com.sdds.stylessalute.styles.textfield.InnerLabel
import com.sdds.stylessalute.styles.textfield.L
import com.sdds.stylessalute.styles.textfield.M
import com.sdds.stylessalute.styles.textfield.OuterLabel
import com.sdds.stylessalute.styles.textfield.RequiredEnd
import com.sdds.stylessalute.styles.textfield.RequiredStart
import com.sdds.stylessalute.styles.textfield.S
import com.sdds.stylessalute.styles.textfield.Success
import com.sdds.stylessalute.styles.textfield.TextField
import com.sdds.stylessalute.styles.textfield.Warning
import com.sdds.stylessalute.styles.textfield.Xs

internal object StylesSaluteTextFieldVariationsCompose : ComposeStyleProvider<String, TextFieldStyle>() {
    override val variations: Map<String, @Composable () -> TextFieldStyle> =
        mapOf(
            "Xs.Default" to { TextField.Xs.Default.style() },
            "Xs.Success" to { TextField.Xs.Success.style() },
            "Xs.Warning" to { TextField.Xs.Warning.style() },
            "Xs.Error" to { TextField.Xs.Error.style() },
            "Xs.RequiredStart.Default" to { TextField.Xs.RequiredStart.Default.style() },
            "Xs.RequiredStart.Success" to { TextField.Xs.RequiredStart.Success.style() },
            "Xs.RequiredStart.Warning" to { TextField.Xs.RequiredStart.Warning.style() },
            "Xs.RequiredStart.Error" to { TextField.Xs.RequiredStart.Error.style() },
            "Xs.RequiredEnd.Default" to { TextField.Xs.RequiredEnd.Default.style() },
            "Xs.RequiredEnd.Success" to { TextField.Xs.RequiredEnd.Success.style() },
            "Xs.RequiredEnd.Warning" to { TextField.Xs.RequiredEnd.Warning.style() },
            "Xs.RequiredEnd.Error" to { TextField.Xs.RequiredEnd.Error.style() },
            "Xs.OuterLabel.Default" to { TextField.Xs.OuterLabel.Default.style() },
            "Xs.OuterLabel.Success" to { TextField.Xs.OuterLabel.Success.style() },
            "Xs.OuterLabel.Warning" to { TextField.Xs.OuterLabel.Warning.style() },
            "Xs.OuterLabel.Error" to { TextField.Xs.OuterLabel.Error.style() },
            "Xs.OuterLabel.RequiredStart.Default" to { TextField.Xs.OuterLabel.RequiredStart.Default.style() },
            "Xs.OuterLabel.RequiredStart.Success" to { TextField.Xs.OuterLabel.RequiredStart.Success.style() },
            "Xs.OuterLabel.RequiredStart.Warning" to { TextField.Xs.OuterLabel.RequiredStart.Warning.style() },
            "Xs.OuterLabel.RequiredStart.Error" to { TextField.Xs.OuterLabel.RequiredStart.Error.style() },
            "Xs.OuterLabel.RequiredEnd.Default" to { TextField.Xs.OuterLabel.RequiredEnd.Default.style() },
            "Xs.OuterLabel.RequiredEnd.Success" to { TextField.Xs.OuterLabel.RequiredEnd.Success.style() },
            "Xs.OuterLabel.RequiredEnd.Warning" to { TextField.Xs.OuterLabel.RequiredEnd.Warning.style() },
            "Xs.OuterLabel.RequiredEnd.Error" to { TextField.Xs.OuterLabel.RequiredEnd.Error.style() },
            "S.Default" to { TextField.S.Default.style() },
            "S.Success" to { TextField.S.Success.style() },
            "S.Warning" to { TextField.S.Warning.style() },
            "S.Error" to { TextField.S.Error.style() },
            "S.RequiredStart.Default" to { TextField.S.RequiredStart.Default.style() },
            "S.RequiredStart.Success" to { TextField.S.RequiredStart.Success.style() },
            "S.RequiredStart.Warning" to { TextField.S.RequiredStart.Warning.style() },
            "S.RequiredStart.Error" to { TextField.S.RequiredStart.Error.style() },
            "S.RequiredEnd.Default" to { TextField.S.RequiredEnd.Default.style() },
            "S.RequiredEnd.Success" to { TextField.S.RequiredEnd.Success.style() },
            "S.RequiredEnd.Warning" to { TextField.S.RequiredEnd.Warning.style() },
            "S.RequiredEnd.Error" to { TextField.S.RequiredEnd.Error.style() },
            "S.OuterLabel.Default" to { TextField.S.OuterLabel.Default.style() },
            "S.OuterLabel.Success" to { TextField.S.OuterLabel.Success.style() },
            "S.OuterLabel.Warning" to { TextField.S.OuterLabel.Warning.style() },
            "S.OuterLabel.Error" to { TextField.S.OuterLabel.Error.style() },
            "S.OuterLabel.RequiredStart.Default" to { TextField.S.OuterLabel.RequiredStart.Default.style() },
            "S.OuterLabel.RequiredStart.Success" to { TextField.S.OuterLabel.RequiredStart.Success.style() },
            "S.OuterLabel.RequiredStart.Warning" to { TextField.S.OuterLabel.RequiredStart.Warning.style() },
            "S.OuterLabel.RequiredStart.Error" to { TextField.S.OuterLabel.RequiredStart.Error.style() },
            "S.OuterLabel.RequiredEnd.Default" to { TextField.S.OuterLabel.RequiredEnd.Default.style() },
            "S.OuterLabel.RequiredEnd.Success" to { TextField.S.OuterLabel.RequiredEnd.Success.style() },
            "S.OuterLabel.RequiredEnd.Warning" to { TextField.S.OuterLabel.RequiredEnd.Warning.style() },
            "S.OuterLabel.RequiredEnd.Error" to { TextField.S.OuterLabel.RequiredEnd.Error.style() },
            "S.InnerLabel.Default" to { TextField.S.InnerLabel.Default.style() },
            "S.InnerLabel.Success" to { TextField.S.InnerLabel.Success.style() },
            "S.InnerLabel.Warning" to { TextField.S.InnerLabel.Warning.style() },
            "S.InnerLabel.Error" to { TextField.S.InnerLabel.Error.style() },
            "S.InnerLabel.RequiredStart.Default" to { TextField.S.InnerLabel.RequiredStart.Default.style() },
            "S.InnerLabel.RequiredStart.Success" to { TextField.S.InnerLabel.RequiredStart.Success.style() },
            "S.InnerLabel.RequiredStart.Warning" to { TextField.S.InnerLabel.RequiredStart.Warning.style() },
            "S.InnerLabel.RequiredStart.Error" to { TextField.S.InnerLabel.RequiredStart.Error.style() },
            "S.InnerLabel.RequiredEnd.Default" to { TextField.S.InnerLabel.RequiredEnd.Default.style() },
            "S.InnerLabel.RequiredEnd.Success" to { TextField.S.InnerLabel.RequiredEnd.Success.style() },
            "S.InnerLabel.RequiredEnd.Warning" to { TextField.S.InnerLabel.RequiredEnd.Warning.style() },
            "S.InnerLabel.RequiredEnd.Error" to { TextField.S.InnerLabel.RequiredEnd.Error.style() },
            "M.Default" to { TextField.M.Default.style() },
            "M.Success" to { TextField.M.Success.style() },
            "M.Warning" to { TextField.M.Warning.style() },
            "M.Error" to { TextField.M.Error.style() },
            "M.RequiredStart.Default" to { TextField.M.RequiredStart.Default.style() },
            "M.RequiredStart.Success" to { TextField.M.RequiredStart.Success.style() },
            "M.RequiredStart.Warning" to { TextField.M.RequiredStart.Warning.style() },
            "M.RequiredStart.Error" to { TextField.M.RequiredStart.Error.style() },
            "M.RequiredEnd.Default" to { TextField.M.RequiredEnd.Default.style() },
            "M.RequiredEnd.Success" to { TextField.M.RequiredEnd.Success.style() },
            "M.RequiredEnd.Warning" to { TextField.M.RequiredEnd.Warning.style() },
            "M.RequiredEnd.Error" to { TextField.M.RequiredEnd.Error.style() },
            "M.OuterLabel.Default" to { TextField.M.OuterLabel.Default.style() },
            "M.OuterLabel.Success" to { TextField.M.OuterLabel.Success.style() },
            "M.OuterLabel.Warning" to { TextField.M.OuterLabel.Warning.style() },
            "M.OuterLabel.Error" to { TextField.M.OuterLabel.Error.style() },
            "M.OuterLabel.RequiredStart.Default" to { TextField.M.OuterLabel.RequiredStart.Default.style() },
            "M.OuterLabel.RequiredStart.Success" to { TextField.M.OuterLabel.RequiredStart.Success.style() },
            "M.OuterLabel.RequiredStart.Warning" to { TextField.M.OuterLabel.RequiredStart.Warning.style() },
            "M.OuterLabel.RequiredStart.Error" to { TextField.M.OuterLabel.RequiredStart.Error.style() },
            "M.OuterLabel.RequiredEnd.Default" to { TextField.M.OuterLabel.RequiredEnd.Default.style() },
            "M.OuterLabel.RequiredEnd.Success" to { TextField.M.OuterLabel.RequiredEnd.Success.style() },
            "M.OuterLabel.RequiredEnd.Warning" to { TextField.M.OuterLabel.RequiredEnd.Warning.style() },
            "M.OuterLabel.RequiredEnd.Error" to { TextField.M.OuterLabel.RequiredEnd.Error.style() },
            "M.InnerLabel.Default" to { TextField.M.InnerLabel.Default.style() },
            "M.InnerLabel.Success" to { TextField.M.InnerLabel.Success.style() },
            "M.InnerLabel.Warning" to { TextField.M.InnerLabel.Warning.style() },
            "M.InnerLabel.Error" to { TextField.M.InnerLabel.Error.style() },
            "M.InnerLabel.RequiredStart.Default" to { TextField.M.InnerLabel.RequiredStart.Default.style() },
            "M.InnerLabel.RequiredStart.Success" to { TextField.M.InnerLabel.RequiredStart.Success.style() },
            "M.InnerLabel.RequiredStart.Warning" to { TextField.M.InnerLabel.RequiredStart.Warning.style() },
            "M.InnerLabel.RequiredStart.Error" to { TextField.M.InnerLabel.RequiredStart.Error.style() },
            "M.InnerLabel.RequiredEnd.Default" to { TextField.M.InnerLabel.RequiredEnd.Default.style() },
            "M.InnerLabel.RequiredEnd.Success" to { TextField.M.InnerLabel.RequiredEnd.Success.style() },
            "M.InnerLabel.RequiredEnd.Warning" to { TextField.M.InnerLabel.RequiredEnd.Warning.style() },
            "M.InnerLabel.RequiredEnd.Error" to { TextField.M.InnerLabel.RequiredEnd.Error.style() },
            "L.Default" to { TextField.L.Default.style() },
            "L.Success" to { TextField.L.Success.style() },
            "L.Warning" to { TextField.L.Warning.style() },
            "L.Error" to { TextField.L.Error.style() },
            "L.RequiredStart.Default" to { TextField.L.RequiredStart.Default.style() },
            "L.RequiredStart.Success" to { TextField.L.RequiredStart.Success.style() },
            "L.RequiredStart.Warning" to { TextField.L.RequiredStart.Warning.style() },
            "L.RequiredStart.Error" to { TextField.L.RequiredStart.Error.style() },
            "L.RequiredEnd.Default" to { TextField.L.RequiredEnd.Default.style() },
            "L.RequiredEnd.Success" to { TextField.L.RequiredEnd.Success.style() },
            "L.RequiredEnd.Warning" to { TextField.L.RequiredEnd.Warning.style() },
            "L.RequiredEnd.Error" to { TextField.L.RequiredEnd.Error.style() },
            "L.OuterLabel.Default" to { TextField.L.OuterLabel.Default.style() },
            "L.OuterLabel.Success" to { TextField.L.OuterLabel.Success.style() },
            "L.OuterLabel.Warning" to { TextField.L.OuterLabel.Warning.style() },
            "L.OuterLabel.Error" to { TextField.L.OuterLabel.Error.style() },
            "L.OuterLabel.RequiredStart.Default" to { TextField.L.OuterLabel.RequiredStart.Default.style() },
            "L.OuterLabel.RequiredStart.Success" to { TextField.L.OuterLabel.RequiredStart.Success.style() },
            "L.OuterLabel.RequiredStart.Warning" to { TextField.L.OuterLabel.RequiredStart.Warning.style() },
            "L.OuterLabel.RequiredStart.Error" to { TextField.L.OuterLabel.RequiredStart.Error.style() },
            "L.OuterLabel.RequiredEnd.Default" to { TextField.L.OuterLabel.RequiredEnd.Default.style() },
            "L.OuterLabel.RequiredEnd.Success" to { TextField.L.OuterLabel.RequiredEnd.Success.style() },
            "L.OuterLabel.RequiredEnd.Warning" to { TextField.L.OuterLabel.RequiredEnd.Warning.style() },
            "L.OuterLabel.RequiredEnd.Error" to { TextField.L.OuterLabel.RequiredEnd.Error.style() },
            "L.InnerLabel.Default" to { TextField.L.InnerLabel.Default.style() },
            "L.InnerLabel.Success" to { TextField.L.InnerLabel.Success.style() },
            "L.InnerLabel.Warning" to { TextField.L.InnerLabel.Warning.style() },
            "L.InnerLabel.Error" to { TextField.L.InnerLabel.Error.style() },
            "L.InnerLabel.RequiredStart.Default" to { TextField.L.InnerLabel.RequiredStart.Default.style() },
            "L.InnerLabel.RequiredStart.Success" to { TextField.L.InnerLabel.RequiredStart.Success.style() },
            "L.InnerLabel.RequiredStart.Warning" to { TextField.L.InnerLabel.RequiredStart.Warning.style() },
            "L.InnerLabel.RequiredStart.Error" to { TextField.L.InnerLabel.RequiredStart.Error.style() },
            "L.InnerLabel.RequiredEnd.Default" to { TextField.L.InnerLabel.RequiredEnd.Default.style() },
            "L.InnerLabel.RequiredEnd.Success" to { TextField.L.InnerLabel.RequiredEnd.Success.style() },
            "L.InnerLabel.RequiredEnd.Warning" to { TextField.L.InnerLabel.RequiredEnd.Warning.style() },
            "L.InnerLabel.RequiredEnd.Error" to { TextField.L.InnerLabel.RequiredEnd.Error.style() },
        )
}
