package com.sdds.playground.sandbox.sdds.serv.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.serv.R as DsR

internal object SddsServSliderVerticalLabelOuterVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterL,
            "L.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLDefault,
            "L.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAccent,
            "L.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLGradient,
            "L.AlignmentEnd" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEnd,
            "L.AlignmentEnd.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndDefault,
            "L.AlignmentEnd.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndAccent,
            "L.AlignmentEnd.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndGradient,
            "L.AlignmentEnd.LabelEnd" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndLabelEnd,
            "L.AlignmentEnd.LabelEnd.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndLabelEndDefault,
            "L.AlignmentEnd.LabelEnd.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndLabelEndAccent,
            "L.AlignmentEnd.LabelEnd.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndLabelEndGradient,
            "L.AlignmentEnd.LabelEnd.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndLabelEndThumbS,
            "L.AlignmentEnd.LabelEnd.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndLabelEndThumbSDefault,
            "L.AlignmentEnd.LabelEnd.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndLabelEndThumbSAccent,
            "L.AlignmentEnd.LabelEnd.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndLabelEndThumbSGradient,
            "L.AlignmentEnd.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndThumbS,
            "L.AlignmentEnd.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndThumbSDefault,
            "L.AlignmentEnd.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndThumbSAccent,
            "L.AlignmentEnd.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLAlignmentEndThumbSGradient,
            "L.LabelEnd" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLLabelEnd,
            "L.LabelEnd.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLLabelEndDefault,
            "L.LabelEnd.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLLabelEndAccent,
            "L.LabelEnd.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLLabelEndGradient,
            "L.LabelEnd.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLLabelEndThumbS,
            "L.LabelEnd.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLLabelEndThumbSDefault,
            "L.LabelEnd.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLLabelEndThumbSAccent,
            "L.LabelEnd.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLLabelEndThumbSGradient,
            "L.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLThumbS,
            "L.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLThumbSDefault,
            "L.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLThumbSAccent,
            "L.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterLThumbSGradient,
            "M" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterM,
            "M.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMDefault,
            "M.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAccent,
            "M.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMGradient,
            "M.AlignmentEnd" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEnd,
            "M.AlignmentEnd.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndDefault,
            "M.AlignmentEnd.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndAccent,
            "M.AlignmentEnd.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndGradient,
            "M.AlignmentEnd.LabelEnd" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndLabelEnd,
            "M.AlignmentEnd.LabelEnd.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndLabelEndDefault,
            "M.AlignmentEnd.LabelEnd.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndLabelEndAccent,
            "M.AlignmentEnd.LabelEnd.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndLabelEndGradient,
            "M.AlignmentEnd.LabelEnd.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndLabelEndThumbS,
            "M.AlignmentEnd.LabelEnd.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndLabelEndThumbSDefault,
            "M.AlignmentEnd.LabelEnd.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndLabelEndThumbSAccent,
            "M.AlignmentEnd.LabelEnd.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndLabelEndThumbSGradient,
            "M.AlignmentEnd.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndThumbS,
            "M.AlignmentEnd.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndThumbSDefault,
            "M.AlignmentEnd.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndThumbSAccent,
            "M.AlignmentEnd.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMAlignmentEndThumbSGradient,
            "M.LabelEnd" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMLabelEnd,
            "M.LabelEnd.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMLabelEndDefault,
            "M.LabelEnd.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMLabelEndAccent,
            "M.LabelEnd.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMLabelEndGradient,
            "M.LabelEnd.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMLabelEndThumbS,
            "M.LabelEnd.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMLabelEndThumbSDefault,
            "M.LabelEnd.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMLabelEndThumbSAccent,
            "M.LabelEnd.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMLabelEndThumbSGradient,
            "M.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMThumbS,
            "M.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMThumbSDefault,
            "M.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMThumbSAccent,
            "M.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterMThumbSGradient,
            "S" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterS,
            "S.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSDefault,
            "S.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAccent,
            "S.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSGradient,
            "S.AlignmentEnd" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEnd,
            "S.AlignmentEnd.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndDefault,
            "S.AlignmentEnd.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndAccent,
            "S.AlignmentEnd.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndGradient,
            "S.AlignmentEnd.LabelEnd" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndLabelEnd,
            "S.AlignmentEnd.LabelEnd.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndLabelEndDefault,
            "S.AlignmentEnd.LabelEnd.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndLabelEndAccent,
            "S.AlignmentEnd.LabelEnd.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndLabelEndGradient,
            "S.AlignmentEnd.LabelEnd.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndLabelEndThumbS,
            "S.AlignmentEnd.LabelEnd.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndLabelEndThumbSDefault,
            "S.AlignmentEnd.LabelEnd.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndLabelEndThumbSAccent,
            "S.AlignmentEnd.LabelEnd.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndLabelEndThumbSGradient,
            "S.AlignmentEnd.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndThumbS,
            "S.AlignmentEnd.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndThumbSDefault,
            "S.AlignmentEnd.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndThumbSAccent,
            "S.AlignmentEnd.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSAlignmentEndThumbSGradient,
            "S.LabelEnd" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSLabelEnd,
            "S.LabelEnd.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSLabelEndDefault,
            "S.LabelEnd.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSLabelEndAccent,
            "S.LabelEnd.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSLabelEndGradient,
            "S.LabelEnd.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSLabelEndThumbS,
            "S.LabelEnd.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSLabelEndThumbSDefault,
            "S.LabelEnd.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSLabelEndThumbSAccent,
            "S.LabelEnd.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSLabelEndThumbSGradient,
            "S.ThumbS" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSThumbS,
            "S.ThumbS.Default" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSThumbSDefault,
            "S.ThumbS.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSThumbSAccent,
            "S.ThumbS.Gradient" to DsR.style.Serv_Sdds_ComponentOverlays_SliderVerticalLabelOuterSThumbSGradient,
        )
}
