package com.sdds.playground.sandbox.sdds.serv.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.serv.R as DsR

internal object SddsServBasicButtonGroupVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "Xxs" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXxs,
            "Xxs.Wide" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXxsWide,
            "Xxs.Wide.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXxsWideDefault,
            "Xxs.Wide.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXxsWideSegmented,
            "Xxs.Dense" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXxsDense,
            "Xxs.Dense.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXxsDenseDefault,
            "Xxs.Dense.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXxsDenseSegmented,
            "Xxs.NoGap" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXxsNoGap,
            "Xxs.NoGap.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXxsNoGapDefault,
            "Xxs.NoGap.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXxsNoGapSegmented,
            "Xs" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXs,
            "Xs.Wide" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXsWide,
            "Xs.Wide.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXsWideDefault,
            "Xs.Wide.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXsWideSegmented,
            "Xs.Dense" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXsDense,
            "Xs.Dense.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXsDenseDefault,
            "Xs.Dense.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXsDenseSegmented,
            "Xs.NoGap" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXsNoGap,
            "Xs.NoGap.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXsNoGapDefault,
            "Xs.NoGap.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupXsNoGapSegmented,
            "S" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupS,
            "S.Wide" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupSWide,
            "S.Wide.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupSWideDefault,
            "S.Wide.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupSWideSegmented,
            "S.Dense" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupSDense,
            "S.Dense.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupSDenseDefault,
            "S.Dense.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupSDenseSegmented,
            "S.NoGap" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupSNoGap,
            "S.NoGap.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupSNoGapDefault,
            "S.NoGap.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupSNoGapSegmented,
            "M" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupM,
            "M.Wide" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupMWide,
            "M.Wide.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupMWideDefault,
            "M.Wide.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupMWideSegmented,
            "M.Dense" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupMDense,
            "M.Dense.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupMDenseDefault,
            "M.Dense.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupMDenseSegmented,
            "M.NoGap" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupMNoGap,
            "M.NoGap.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupMNoGapDefault,
            "M.NoGap.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupMNoGapSegmented,
            "L" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupL,
            "L.Wide" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupLWide,
            "L.Wide.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupLWideDefault,
            "L.Wide.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupLWideSegmented,
            "L.Dense" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupLDense,
            "L.Dense.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupLDenseDefault,
            "L.Dense.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupLDenseSegmented,
            "L.NoGap" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupLNoGap,
            "L.NoGap.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupLNoGapDefault,
            "L.NoGap.Segmented" to DsR.style.Serv_Sdds_ComponentOverlays_BasicButtonGroupLNoGapSegmented,
        )
}
