package com.sdds.playground.sandbox.sdds.serv.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.serv.R as DsR

internal object SddsServBadgeClearVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearL,
            "L.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLDefault,
            "L.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLAccent,
            "L.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLNegative,
            "L.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLPositive,
            "L.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLWarning,
            "L.Dark" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLDark,
            "L.Light" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLLight,
            "L.Pilled" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLPilled,
            "L.Pilled.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLPilledDefault,
            "L.Pilled.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLPilledAccent,
            "L.Pilled.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLPilledNegative,
            "L.Pilled.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLPilledPositive,
            "L.Pilled.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLPilledWarning,
            "L.Pilled.Dark" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLPilledDark,
            "L.Pilled.Light" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearLPilledLight,
            "M" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearM,
            "M.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMDefault,
            "M.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMAccent,
            "M.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMNegative,
            "M.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMPositive,
            "M.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMWarning,
            "M.Dark" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMDark,
            "M.Light" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMLight,
            "M.Pilled" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMPilled,
            "M.Pilled.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMPilledDefault,
            "M.Pilled.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMPilledAccent,
            "M.Pilled.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMPilledNegative,
            "M.Pilled.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMPilledPositive,
            "M.Pilled.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMPilledWarning,
            "M.Pilled.Dark" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMPilledDark,
            "M.Pilled.Light" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearMPilledLight,
            "S" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearS,
            "S.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSDefault,
            "S.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSAccent,
            "S.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSNegative,
            "S.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSPositive,
            "S.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSWarning,
            "S.Dark" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSDark,
            "S.Light" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSLight,
            "S.Pilled" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSPilled,
            "S.Pilled.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSPilledDefault,
            "S.Pilled.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSPilledAccent,
            "S.Pilled.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSPilledNegative,
            "S.Pilled.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSPilledPositive,
            "S.Pilled.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSPilledWarning,
            "S.Pilled.Dark" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSPilledDark,
            "S.Pilled.Light" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearSPilledLight,
            "Xs" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXs,
            "Xs.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsDefault,
            "Xs.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsAccent,
            "Xs.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsNegative,
            "Xs.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsPositive,
            "Xs.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsWarning,
            "Xs.Dark" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsDark,
            "Xs.Light" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsLight,
            "Xs.Pilled" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsPilled,
            "Xs.Pilled.Default" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsPilledDefault,
            "Xs.Pilled.Accent" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsPilledAccent,
            "Xs.Pilled.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsPilledNegative,
            "Xs.Pilled.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsPilledPositive,
            "Xs.Pilled.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsPilledWarning,
            "Xs.Pilled.Dark" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsPilledDark,
            "Xs.Pilled.Light" to DsR.style.Serv_Sdds_ComponentOverlays_BadgeClearXsPilledLight,
        )
}
