package com.sdds.playground.sandbox.sdds.serv.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.serv.R as DsR

internal object SddsServNoteCompactVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactL,
            "L.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLDefault,
            "L.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLPositive,
            "L.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLNegative,
            "L.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLWarning,
            "L.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLInfo,
            "L.HasClose" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasClose,
            "L.HasClose.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseDefault,
            "L.HasClose.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasClosePositive,
            "L.HasClose.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseNegative,
            "L.HasClose.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseWarning,
            "L.HasClose.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseInfo,
            "L.ContentScalable" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalable,
            "L.ContentScalable.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalableDefault,
            "L.ContentScalable.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalablePositive,
            "L.ContentScalable.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalableNegative,
            "L.ContentScalable.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalableWarning,
            "L.ContentScalable.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalableInfo,
            "L.HasCloseContentScalable" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalable,
            "L.HasCloseContentScalable.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalableDefault,
            "L.HasCloseContentScalable.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalablePositive,
            "L.HasCloseContentScalable.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalableNegative,
            "L.HasCloseContentScalable.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalableWarning,
            "L.HasCloseContentScalable.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalableInfo,
            "M" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactM,
            "M.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMDefault,
            "M.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMPositive,
            "M.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMNegative,
            "M.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMWarning,
            "M.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMInfo,
            "M.HasClose" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasClose,
            "M.HasClose.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseDefault,
            "M.HasClose.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasClosePositive,
            "M.HasClose.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseNegative,
            "M.HasClose.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseWarning,
            "M.HasClose.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseInfo,
            "M.ContentScalable" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalable,
            "M.ContentScalable.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalableDefault,
            "M.ContentScalable.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalablePositive,
            "M.ContentScalable.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalableNegative,
            "M.ContentScalable.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalableWarning,
            "M.ContentScalable.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalableInfo,
            "M.HasCloseContentScalable" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalable,
            "M.HasCloseContentScalable.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalableDefault,
            "M.HasCloseContentScalable.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalablePositive,
            "M.HasCloseContentScalable.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalableNegative,
            "M.HasCloseContentScalable.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalableWarning,
            "M.HasCloseContentScalable.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalableInfo,
            "S" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactS,
            "S.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSDefault,
            "S.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSPositive,
            "S.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSNegative,
            "S.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSWarning,
            "S.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSInfo,
            "S.HasClose" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasClose,
            "S.HasClose.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseDefault,
            "S.HasClose.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasClosePositive,
            "S.HasClose.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseNegative,
            "S.HasClose.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseWarning,
            "S.HasClose.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseInfo,
            "S.ContentScalable" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalable,
            "S.ContentScalable.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalableDefault,
            "S.ContentScalable.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalablePositive,
            "S.ContentScalable.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalableNegative,
            "S.ContentScalable.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalableWarning,
            "S.ContentScalable.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalableInfo,
            "S.HasCloseContentScalable" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalable,
            "S.HasCloseContentScalable.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalableDefault,
            "S.HasCloseContentScalable.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalablePositive,
            "S.HasCloseContentScalable.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalableNegative,
            "S.HasCloseContentScalable.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalableWarning,
            "S.HasCloseContentScalable.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalableInfo,
            "Xs" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXs,
            "Xs.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsDefault,
            "Xs.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsPositive,
            "Xs.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsNegative,
            "Xs.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsWarning,
            "Xs.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsInfo,
            "Xs.HasClose" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasClose,
            "Xs.HasClose.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseDefault,
            "Xs.HasClose.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasClosePositive,
            "Xs.HasClose.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseNegative,
            "Xs.HasClose.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseWarning,
            "Xs.HasClose.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseInfo,
            "Xs.ContentScalable" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalable,
            "Xs.ContentScalable.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalableDefault,
            "Xs.ContentScalable.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalablePositive,
            "Xs.ContentScalable.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalableNegative,
            "Xs.ContentScalable.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalableWarning,
            "Xs.ContentScalable.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalableInfo,
            "Xs.HasCloseContentScalable" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalable,
            "Xs.HasCloseContentScalable.Default" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalableDefault,
            "Xs.HasCloseContentScalable.Positive" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalablePositive,
            "Xs.HasCloseContentScalable.Negative" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalableNegative,
            "Xs.HasCloseContentScalable.Warning" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalableWarning,
            "Xs.HasCloseContentScalable.Info" to DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalableInfo,
        )
}
