package com.sdds.playground.sandbox.plasma.sd.service.integration.badge

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.plasma.sd.service.integration.s

internal object PlasmaSdServiceBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "LDefault" to s.Plasma_SdService_ComponentOverlays_BadgeLDefault,
            "LAccent" to s.Plasma_SdService_ComponentOverlays_BadgeLAccent,
            "LPositive" to s.Plasma_SdService_ComponentOverlays_BadgeLPositive,
            "LWarning" to s.Plasma_SdService_ComponentOverlays_BadgeLWarning,
            "LNegative" to s.Plasma_SdService_ComponentOverlays_BadgeLNegative,
            "LWhite" to s.Plasma_SdService_ComponentOverlays_BadgeLWhite,
            "LBlack" to s.Plasma_SdService_ComponentOverlays_BadgeLBlack,
            "LPilledDefault" to s.Plasma_SdService_ComponentOverlays_BadgeLPilledDefault,
            "LPilledAccent" to s.Plasma_SdService_ComponentOverlays_BadgeLPilledAccent,
            "LPilledPositive" to s.Plasma_SdService_ComponentOverlays_BadgeLPilledPositive,
            "LPilledWarning" to s.Plasma_SdService_ComponentOverlays_BadgeLPilledWarning,
            "LPilledNegative" to s.Plasma_SdService_ComponentOverlays_BadgeLPilledNegative,
            "LPilledWhite" to s.Plasma_SdService_ComponentOverlays_BadgeLPilledWhite,
            "LPilledBlack" to s.Plasma_SdService_ComponentOverlays_BadgeLPilledBlack,
            "MDefault" to s.Plasma_SdService_ComponentOverlays_BadgeMDefault,
            "MAccent" to s.Plasma_SdService_ComponentOverlays_BadgeMAccent,
            "MPositive" to s.Plasma_SdService_ComponentOverlays_BadgeMPositive,
            "MWarning" to s.Plasma_SdService_ComponentOverlays_BadgeMWarning,
            "MNegative" to s.Plasma_SdService_ComponentOverlays_BadgeMNegative,
            "MWhite" to s.Plasma_SdService_ComponentOverlays_BadgeMWhite,
            "MBlack" to s.Plasma_SdService_ComponentOverlays_BadgeMBlack,
            "MPilledDefault" to s.Plasma_SdService_ComponentOverlays_BadgeMPilledDefault,
            "MPilledAccent" to s.Plasma_SdService_ComponentOverlays_BadgeMPilledAccent,
            "MPilledPositive" to s.Plasma_SdService_ComponentOverlays_BadgeMPilledPositive,
            "MPilledWarning" to s.Plasma_SdService_ComponentOverlays_BadgeMPilledWarning,
            "MPilledNegative" to s.Plasma_SdService_ComponentOverlays_BadgeMPilledNegative,
            "MPilledWhite" to s.Plasma_SdService_ComponentOverlays_BadgeMPilledWhite,
            "MPilledBlack" to s.Plasma_SdService_ComponentOverlays_BadgeMPilledBlack,
            "SDefault" to s.Plasma_SdService_ComponentOverlays_BadgeSDefault,
            "SAccent" to s.Plasma_SdService_ComponentOverlays_BadgeSAccent,
            "SPositive" to s.Plasma_SdService_ComponentOverlays_BadgeSPositive,
            "SWarning" to s.Plasma_SdService_ComponentOverlays_BadgeSNegative,
            "SNegative" to s.Plasma_SdService_ComponentOverlays_BadgeSWarning,
            "SWhite" to s.Plasma_SdService_ComponentOverlays_BadgeSWhite,
            "SBlack" to s.Plasma_SdService_ComponentOverlays_BadgeSBlack,
            "SPilledDefault" to s.Plasma_SdService_ComponentOverlays_BadgeSPilledDefault,
            "SPilledAccent" to s.Plasma_SdService_ComponentOverlays_BadgeSPilledAccent,
            "SPilledPositive" to s.Plasma_SdService_ComponentOverlays_BadgeSPilledPositive,
            "SPilledWarning" to s.Plasma_SdService_ComponentOverlays_BadgeSPilledWarning,
            "SPilledNegative" to s.Plasma_SdService_ComponentOverlays_BadgeSPilledNegative,
            "SPilledWhite" to s.Plasma_SdService_ComponentOverlays_BadgeSPilledWhite,
            "SPilledBlack" to s.Plasma_SdService_ComponentOverlays_BadgeSPilledBlack,
            "XsDefault" to s.Plasma_SdService_ComponentOverlays_BadgeXsDefault,
            "XsAccent" to s.Plasma_SdService_ComponentOverlays_BadgeXsAccent,
            "XsPositive" to s.Plasma_SdService_ComponentOverlays_BadgeXsPositive,
            "XsWarning" to s.Plasma_SdService_ComponentOverlays_BadgeXsWarning,
            "XsNegative" to s.Plasma_SdService_ComponentOverlays_BadgeXsNegative,
            "XsWhite" to s.Plasma_SdService_ComponentOverlays_BadgeXsWhite,
            "XsBlack" to s.Plasma_SdService_ComponentOverlays_BadgeXsBlack,
            "XsPilledDefault" to s.Plasma_SdService_ComponentOverlays_BadgeXsPilledDefault,
            "XsPilledAccent" to s.Plasma_SdService_ComponentOverlays_BadgeXsPilledAccent,
            "XsPilledPositive" to s.Plasma_SdService_ComponentOverlays_BadgeXsPilledPositive,
            "XsPilledWarning" to s.Plasma_SdService_ComponentOverlays_BadgeXsPilledWarning,
            "XsPilledNegative" to s.Plasma_SdService_ComponentOverlays_BadgeXsPilledNegative,
            "XsPilledWhite" to s.Plasma_SdService_ComponentOverlays_BadgeXsPilledWhite,
            "XsPilledBlack" to s.Plasma_SdService_ComponentOverlays_BadgeXsPilledBlack,
        )
}
