package com.sdds.playground.sandbox.plasma.sd.service.integration.badge

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.plasma.sd.service.integration.s

internal object PlasmaSdServiceBadgeTransparentVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "TransparentLDefault" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLDefault,
            "TransparentLAccent" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLAccent,
            "TransparentLPositive" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLPositive,
            "TransparentLWarning" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLWarning,
            "TransparentLNegative" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLNegative,
            "TransparentLLight" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLLight,
            "TransparentLDark" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLDark,
            "TransparentLPilledDefault" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLPilledDefault,
            "TransparentLPilledAccent" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLPilledAccent,
            "TransparentLPilledPositive" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLPilledPositive,
            "TransparentLPilledWarning" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLPilledWarning,
            "TransparentLPilledNegative" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLPilledNegative,
            "TransparentLPilledLight" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLPilledLight,
            "TransparentLPilledDark" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentLPilledDark,
            "TransparentMDefault" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMDefault,
            "TransparentMAccent" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMAccent,
            "TransparentMPositive" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMPositive,
            "TransparentMWarning" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMWarning,
            "TransparentMNegative" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMNegative,
            "TransparentMLight" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMLight,
            "TransparentMDark" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMDark,
            "TransparentMPilledDefault" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMPilledDefault,
            "TransparentMPilledAccent" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMPilledAccent,
            "TransparentMPilledPositive" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMPilledPositive,
            "TransparentMPilledWarning" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMPilledWarning,
            "TransparentMPilledNegative" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMPilledNegative,
            "TransparentMPilledLight" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMPilledLight,
            "TransparentMPilledDark" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentMPilledDark,
            "TransparentSDefault" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSDefault,
            "TransparentSAccent" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSAccent,
            "TransparentSPositive" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSPositive,
            "TransparentSWarning" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSNegative,
            "TransparentSNegative" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSWarning,
            "TransparentSLight" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSLight,
            "TransparentSDark" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSDark,
            "TransparentSPilledDefault" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSPilledDefault,
            "TransparentSPilledAccent" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSPilledAccent,
            "TransparentSPilledPositive" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSPilledPositive,
            "TransparentSPilledWarning" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSPilledWarning,
            "TransparentSPilledNegative" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSPilledNegative,
            "TransparentSPilledLight" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSPilledLight,
            "TransparentSPilledDark" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentSPilledDark,
            "TransparentXsDefault" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsDefault,
            "TransparentXsAccent" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsAccent,
            "TransparentXsPositive" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsPositive,
            "TransparentXsWarning" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsWarning,
            "TransparentXsNegative" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsNegative,
            "TransparentXsLight" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsLight,
            "TransparentXsDark" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsDark,
            "TransparentXsPilledDefault" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsPilledDefault,
            "TransparentXsPilledAccent" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsPilledAccent,
            "TransparentXsPilledPositive" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsPilledPositive,
            "TransparentXsPilledWarning" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsPilledWarning,
            "TransparentXsPilledNegative" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsPilledNegative,
            "TransparentXsPilledLight" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsPilledLight,
            "TransparentXsPilledDark" to s.Plasma_SdService_ComponentOverlays_BadgeTransparentXsPilledDark,
        )
}
