package com.sdds.playground.sandbox.plasma.giga.integration.textfield.clear

import androidx.compose.runtime.Composable
import com.sdds.compose.uikit.TextFieldStyle
import com.sdds.compose.uikit.style.style
import com.sdds.plasma.giga.styles.textfield.clear.Default
import com.sdds.plasma.giga.styles.textfield.clear.Error
import com.sdds.plasma.giga.styles.textfield.clear.InnerLabel
import com.sdds.plasma.giga.styles.textfield.clear.L
import com.sdds.plasma.giga.styles.textfield.clear.M
import com.sdds.plasma.giga.styles.textfield.clear.OuterLabel
import com.sdds.plasma.giga.styles.textfield.clear.RequiredEnd
import com.sdds.plasma.giga.styles.textfield.clear.RequiredStart
import com.sdds.plasma.giga.styles.textfield.clear.S
import com.sdds.plasma.giga.styles.textfield.clear.Success
import com.sdds.plasma.giga.styles.textfield.clear.TextFieldClear
import com.sdds.plasma.giga.styles.textfield.clear.Warning
import com.sdds.plasma.giga.styles.textfield.clear.Xl
import com.sdds.plasma.giga.styles.textfield.clear.Xs
import com.sdds.playground.sandbox.core.integration.ComposeStyleProvider

internal object PlasmaGigaTextFieldClearVariationsCompose : ComposeStyleProvider<String, TextFieldStyle>() {

    override val variations: Map<String, @Composable () -> TextFieldStyle> =
        mapOf(
            "XLDefault" to { TextFieldClear.Xl.Default.style() },
            "XLRequiredStartDefault" to { TextFieldClear.Xl.RequiredStart.Default.style() },
            "XLRequiredEndDefault" to { TextFieldClear.Xl.RequiredEnd.Default.style() },
            "XLOuterLabelDefault" to { TextFieldClear.Xl.OuterLabel.Default.style() },
            "XLOuterLabelRequiredStartDefault" to { TextFieldClear.Xl.OuterLabel.RequiredStart.Default.style() },
            "XLOuterLabelRequiredEndDefault" to { TextFieldClear.Xl.OuterLabel.RequiredEnd.Default.style() },
            "XLInnerLabelDefault" to { TextFieldClear.Xl.InnerLabel.Default.style() },
            "XLInnerLabelRequiredStartDefault" to { TextFieldClear.Xl.InnerLabel.RequiredStart.Default.style() },
            "XLInnerLabelRequiredEndDefault" to { TextFieldClear.Xl.InnerLabel.RequiredEnd.Default.style() },
            "LDefault" to { TextFieldClear.L.Default.style() },
            "LRequiredStartDefault" to { TextFieldClear.L.RequiredStart.Default.style() },
            "LRequiredEndDefault" to { TextFieldClear.L.RequiredEnd.Default.style() },
            "LOuterLabelDefault" to { TextFieldClear.L.OuterLabel.Default.style() },
            "LOuterLabelRequiredStartDefault" to { TextFieldClear.L.OuterLabel.RequiredStart.Default.style() },
            "LOuterLabelRequiredEndDefault" to { TextFieldClear.L.OuterLabel.RequiredEnd.Default.style() },
            "LInnerLabelDefault" to { TextFieldClear.L.InnerLabel.Default.style() },
            "LInnerLabelRequiredStartDefault" to { TextFieldClear.L.InnerLabel.RequiredStart.Default.style() },
            "LInnerLabelRequiredEndDefault" to { TextFieldClear.L.InnerLabel.RequiredEnd.Default.style() },
            "MDefault" to { TextFieldClear.M.Default.style() },
            "MRequiredStartDefault" to { TextFieldClear.M.RequiredStart.Default.style() },
            "MRequiredEndDefault" to { TextFieldClear.M.RequiredEnd.Default.style() },
            "MOuterLabelDefault" to { TextFieldClear.M.OuterLabel.Default.style() },
            "MOuterLabelRequiredStartDefault" to { TextFieldClear.M.OuterLabel.RequiredStart.Default.style() },
            "MOuterLabelRequiredEndDefault" to { TextFieldClear.M.OuterLabel.RequiredEnd.Default.style() },
            "MInnerLabelDefault" to { TextFieldClear.M.InnerLabel.Default.style() },
            "MInnerLabelRequiredStartDefault" to { TextFieldClear.M.InnerLabel.RequiredStart.Default.style() },
            "MInnerLabelRequiredEndDefault" to { TextFieldClear.M.InnerLabel.RequiredEnd.Default.style() },
            "SDefault" to { TextFieldClear.S.Default.style() },
            "SRequiredStartDefault" to { TextFieldClear.S.RequiredStart.Default.style() },
            "SRequiredEndDefault" to { TextFieldClear.S.RequiredEnd.Default.style() },
            "SOuterLabelDefault" to { TextFieldClear.S.OuterLabel.Default.style() },
            "SOuterLabelRequiredStartDefault" to { TextFieldClear.S.OuterLabel.RequiredStart.Default.style() },
            "SOuterLabelRequiredEndDefault" to { TextFieldClear.S.OuterLabel.RequiredEnd.Default.style() },
            "SInnerLabelDefault" to { TextFieldClear.S.InnerLabel.Default.style() },
            "SInnerLabelRequiredStartDefault" to { TextFieldClear.S.InnerLabel.RequiredStart.Default.style() },
            "SInnerLabelRequiredEndDefault" to { TextFieldClear.S.InnerLabel.RequiredEnd.Default.style() },
            "XSDefault" to { TextFieldClear.Xs.Default.style() },
            "XSRequiredStartDefault" to { TextFieldClear.Xs.RequiredStart.Default.style() },
            "XSRequiredEndDefault" to { TextFieldClear.Xs.RequiredEnd.Default.style() },
            "XSOuterLabelDefault" to { TextFieldClear.Xs.OuterLabel.Default.style() },
            "XSOuterLabelRequiredStartDefault" to { TextFieldClear.Xs.OuterLabel.RequiredStart.Default.style() },
            "XSOuterLabelRequiredEndDefault" to { TextFieldClear.Xs.OuterLabel.RequiredEnd.Default.style() },

            "XLWarning" to { TextFieldClear.Xl.Warning.style() },
            "XLRequiredStartWarning" to { TextFieldClear.Xl.RequiredStart.Warning.style() },
            "XLRequiredEndWarning" to { TextFieldClear.Xl.RequiredEnd.Warning.style() },
            "XLOuterLabelWarning" to { TextFieldClear.Xl.OuterLabel.Warning.style() },
            "XLOuterLabelRequiredStartWarning" to { TextFieldClear.Xl.OuterLabel.RequiredStart.Warning.style() },
            "XLOuterLabelRequiredEndWarning" to { TextFieldClear.Xl.OuterLabel.RequiredEnd.Warning.style() },
            "XLInnerLabelWarning" to { TextFieldClear.Xl.InnerLabel.Warning.style() },
            "XLInnerLabelRequiredStartWarning" to { TextFieldClear.Xl.InnerLabel.RequiredStart.Warning.style() },
            "XLInnerLabelRequiredEndWarning" to { TextFieldClear.Xl.InnerLabel.RequiredEnd.Warning.style() },
            "LWarning" to { TextFieldClear.L.Warning.style() },
            "LRequiredStartWarning" to { TextFieldClear.L.RequiredStart.Warning.style() },
            "LRequiredEndWarning" to { TextFieldClear.L.RequiredEnd.Warning.style() },
            "LOuterLabelWarning" to { TextFieldClear.L.OuterLabel.Warning.style() },
            "LOuterLabelRequiredStartWarning" to { TextFieldClear.L.OuterLabel.RequiredStart.Warning.style() },
            "LOuterLabelRequiredEndWarning" to { TextFieldClear.L.OuterLabel.RequiredEnd.Warning.style() },
            "LInnerLabelWarning" to { TextFieldClear.L.InnerLabel.Warning.style() },
            "LInnerLabelRequiredStartWarning" to { TextFieldClear.L.InnerLabel.RequiredStart.Warning.style() },
            "LInnerLabelRequiredEndWarning" to { TextFieldClear.L.InnerLabel.RequiredEnd.Warning.style() },
            "MWarning" to { TextFieldClear.M.Warning.style() },
            "MRequiredStartWarning" to { TextFieldClear.M.RequiredStart.Warning.style() },
            "MRequiredEndWarning" to { TextFieldClear.M.RequiredEnd.Warning.style() },
            "MOuterLabelWarning" to { TextFieldClear.M.OuterLabel.Warning.style() },
            "MOuterLabelRequiredStartWarning" to { TextFieldClear.M.OuterLabel.RequiredStart.Warning.style() },
            "MOuterLabelRequiredEndWarning" to { TextFieldClear.M.OuterLabel.RequiredEnd.Warning.style() },
            "MInnerLabelWarning" to { TextFieldClear.M.InnerLabel.Warning.style() },
            "MInnerLabelRequiredStartWarning" to { TextFieldClear.M.InnerLabel.RequiredStart.Warning.style() },
            "MInnerLabelRequiredEndWarning" to { TextFieldClear.M.InnerLabel.RequiredEnd.Warning.style() },
            "SWarning" to { TextFieldClear.S.Warning.style() },
            "SRequiredStartWarning" to { TextFieldClear.S.RequiredStart.Warning.style() },
            "SRequiredEndWarning" to { TextFieldClear.S.RequiredEnd.Warning.style() },
            "SOuterLabelWarning" to { TextFieldClear.S.OuterLabel.Warning.style() },
            "SOuterLabelRequiredStartWarning" to { TextFieldClear.S.OuterLabel.RequiredStart.Warning.style() },
            "SOuterLabelRequiredEndWarning" to { TextFieldClear.S.OuterLabel.RequiredEnd.Warning.style() },
            "SInnerLabelWarning" to { TextFieldClear.S.InnerLabel.Warning.style() },
            "SInnerLabelRequiredStartWarning" to { TextFieldClear.S.InnerLabel.RequiredStart.Warning.style() },
            "SInnerLabelRequiredEndWarning" to { TextFieldClear.S.InnerLabel.RequiredEnd.Warning.style() },
            "XSWarning" to { TextFieldClear.Xs.Warning.style() },
            "XSRequiredStartWarning" to { TextFieldClear.Xs.RequiredStart.Warning.style() },
            "XSRequiredEndWarning" to { TextFieldClear.Xs.RequiredEnd.Warning.style() },
            "XSOuterLabelWarning" to { TextFieldClear.Xs.OuterLabel.Warning.style() },
            "XSOuterLabelRequiredStartWarning" to { TextFieldClear.Xs.OuterLabel.RequiredStart.Warning.style() },
            "XSOuterLabelRequiredEndWarning" to { TextFieldClear.Xs.OuterLabel.RequiredEnd.Warning.style() },

            "XLError" to { TextFieldClear.Xl.Error.style() },
            "XLRequiredStartError" to { TextFieldClear.Xl.RequiredStart.Error.style() },
            "XLRequiredEndError" to { TextFieldClear.Xl.RequiredEnd.Error.style() },
            "XLOuterLabelError" to { TextFieldClear.Xl.OuterLabel.Error.style() },
            "XLOuterLabelRequiredStartError" to { TextFieldClear.Xl.OuterLabel.RequiredStart.Error.style() },
            "XLOuterLabelRequiredEndError" to { TextFieldClear.Xl.OuterLabel.RequiredEnd.Error.style() },
            "XLInnerLabelError" to { TextFieldClear.Xl.InnerLabel.Error.style() },
            "XLInnerLabelRequiredStartError" to { TextFieldClear.Xl.InnerLabel.RequiredStart.Error.style() },
            "XLInnerLabelRequiredEndError" to { TextFieldClear.Xl.InnerLabel.RequiredEnd.Error.style() },
            "LError" to { TextFieldClear.L.Error.style() },
            "LRequiredStartError" to { TextFieldClear.L.RequiredStart.Error.style() },
            "LRequiredEndError" to { TextFieldClear.L.RequiredEnd.Error.style() },
            "LOuterLabelError" to { TextFieldClear.L.OuterLabel.Error.style() },
            "LOuterLabelRequiredStartError" to { TextFieldClear.L.OuterLabel.RequiredStart.Error.style() },
            "LOuterLabelRequiredEndError" to { TextFieldClear.L.OuterLabel.RequiredEnd.Error.style() },
            "LInnerLabelError" to { TextFieldClear.L.InnerLabel.Error.style() },
            "LInnerLabelRequiredStartError" to { TextFieldClear.L.InnerLabel.RequiredStart.Error.style() },
            "LInnerLabelRequiredEndError" to { TextFieldClear.L.InnerLabel.RequiredEnd.Error.style() },
            "MError" to { TextFieldClear.M.Error.style() },
            "MRequiredStartError" to { TextFieldClear.M.RequiredStart.Error.style() },
            "MRequiredEndError" to { TextFieldClear.M.RequiredEnd.Error.style() },
            "MOuterLabelError" to { TextFieldClear.M.OuterLabel.Error.style() },
            "MOuterLabelRequiredStartError" to { TextFieldClear.M.OuterLabel.RequiredStart.Error.style() },
            "MOuterLabelRequiredEndError" to { TextFieldClear.M.OuterLabel.RequiredEnd.Error.style() },
            "MInnerLabelError" to { TextFieldClear.M.InnerLabel.Error.style() },
            "MInnerLabelRequiredStartError" to { TextFieldClear.M.InnerLabel.RequiredStart.Error.style() },
            "MInnerLabelRequiredEndError" to { TextFieldClear.M.InnerLabel.RequiredEnd.Error.style() },
            "SError" to { TextFieldClear.S.Error.style() },
            "SRequiredStartError" to { TextFieldClear.S.RequiredStart.Error.style() },
            "SRequiredEndError" to { TextFieldClear.S.RequiredEnd.Error.style() },
            "SOuterLabelError" to { TextFieldClear.S.OuterLabel.Error.style() },
            "SOuterLabelRequiredStartError" to { TextFieldClear.S.OuterLabel.RequiredStart.Error.style() },
            "SOuterLabelRequiredEndError" to { TextFieldClear.S.OuterLabel.RequiredEnd.Error.style() },
            "SInnerLabelError" to { TextFieldClear.S.InnerLabel.Error.style() },
            "SInnerLabelRequiredStartError" to { TextFieldClear.S.InnerLabel.RequiredStart.Error.style() },
            "SInnerLabelRequiredEndError" to { TextFieldClear.S.InnerLabel.RequiredEnd.Error.style() },
            "XSError" to { TextFieldClear.Xs.Error.style() },
            "XSRequiredStartError" to { TextFieldClear.Xs.RequiredStart.Error.style() },
            "XSRequiredEndError" to { TextFieldClear.Xs.RequiredEnd.Error.style() },
            "XSOuterLabelError" to { TextFieldClear.Xs.OuterLabel.Error.style() },
            "XSOuterLabelRequiredStartError" to { TextFieldClear.Xs.OuterLabel.RequiredStart.Error.style() },
            "XSOuterLabelRequiredEndError" to { TextFieldClear.Xs.OuterLabel.RequiredEnd.Error.style() },

            "XLSuccess" to { TextFieldClear.Xl.Success.style() },
            "XLRequiredStartSuccess" to { TextFieldClear.Xl.RequiredStart.Success.style() },
            "XLRequiredEndSuccess" to { TextFieldClear.Xl.RequiredEnd.Success.style() },
            "XLOuterLabelSuccess" to { TextFieldClear.Xl.OuterLabel.Success.style() },
            "XLOuterLabelRequiredStartSuccess" to { TextFieldClear.Xl.OuterLabel.RequiredStart.Success.style() },
            "XLOuterLabelRequiredEndSuccess" to { TextFieldClear.Xl.OuterLabel.RequiredEnd.Success.style() },
            "XLInnerLabelSuccess" to { TextFieldClear.Xl.InnerLabel.Success.style() },
            "XLInnerLabelRequiredStartSuccess" to { TextFieldClear.Xl.InnerLabel.RequiredStart.Success.style() },
            "XLInnerLabelRequiredEndSuccess" to { TextFieldClear.Xl.InnerLabel.RequiredEnd.Success.style() },
            "LSuccess" to { TextFieldClear.L.Success.style() },
            "LRequiredStartSuccess" to { TextFieldClear.L.RequiredStart.Success.style() },
            "LRequiredEndSuccess" to { TextFieldClear.L.RequiredEnd.Success.style() },
            "LOuterLabelSuccess" to { TextFieldClear.L.OuterLabel.Success.style() },
            "LOuterLabelRequiredStartSuccess" to { TextFieldClear.L.OuterLabel.RequiredStart.Success.style() },
            "LOuterLabelRequiredEndSuccess" to { TextFieldClear.L.OuterLabel.RequiredEnd.Success.style() },
            "LInnerLabelSuccess" to { TextFieldClear.L.InnerLabel.Success.style() },
            "LInnerLabelRequiredStartSuccess" to { TextFieldClear.L.InnerLabel.RequiredStart.Success.style() },
            "LInnerLabelRequiredEndSuccess" to { TextFieldClear.L.InnerLabel.RequiredEnd.Success.style() },
            "MSuccess" to { TextFieldClear.M.Success.style() },
            "MRequiredStartSuccess" to { TextFieldClear.M.RequiredStart.Success.style() },
            "MRequiredEndSuccess" to { TextFieldClear.M.RequiredEnd.Success.style() },
            "MOuterLabelSuccess" to { TextFieldClear.M.OuterLabel.Success.style() },
            "MOuterLabelRequiredStartSuccess" to { TextFieldClear.M.OuterLabel.RequiredStart.Success.style() },
            "MOuterLabelRequiredEndSuccess" to { TextFieldClear.M.OuterLabel.RequiredEnd.Success.style() },
            "MInnerLabelSuccess" to { TextFieldClear.M.InnerLabel.Success.style() },
            "MInnerLabelRequiredStartSuccess" to { TextFieldClear.M.InnerLabel.RequiredStart.Success.style() },
            "MInnerLabelRequiredEndSuccess" to { TextFieldClear.M.InnerLabel.RequiredEnd.Success.style() },
            "SSuccess" to { TextFieldClear.S.Success.style() },
            "SRequiredStartSuccess" to { TextFieldClear.S.RequiredStart.Success.style() },
            "SRequiredEndSuccess" to { TextFieldClear.S.RequiredEnd.Success.style() },
            "SOuterLabelSuccess" to { TextFieldClear.S.OuterLabel.Success.style() },
            "SOuterLabelRequiredStartSuccess" to { TextFieldClear.S.OuterLabel.RequiredStart.Success.style() },
            "SOuterLabelRequiredEndSuccess" to { TextFieldClear.S.OuterLabel.RequiredEnd.Success.style() },
            "SInnerLabelSuccess" to { TextFieldClear.S.InnerLabel.Success.style() },
            "SInnerLabelRequiredStartSuccess" to { TextFieldClear.S.InnerLabel.RequiredStart.Success.style() },
            "SInnerLabelRequiredEndSuccess" to { TextFieldClear.S.InnerLabel.RequiredEnd.Success.style() },
            "XSSuccess" to { TextFieldClear.Xs.Success.style() },
            "XSRequiredStartSuccess" to { TextFieldClear.Xs.RequiredStart.Success.style() },
            "XSRequiredEndSuccess" to { TextFieldClear.Xs.RequiredEnd.Success.style() },
            "XSOuterLabelSuccess" to { TextFieldClear.Xs.OuterLabel.Success.style() },
            "XSOuterLabelRequiredStartSuccess" to { TextFieldClear.Xs.OuterLabel.RequiredStart.Success.style() },
            "XSOuterLabelRequiredEndSuccess" to { TextFieldClear.Xs.OuterLabel.RequiredEnd.Success.style() },
        )
}
