package com.sdds.playground.sandbox.sdds.serv.integration.badge

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.sdds.serv.integration.s

internal object SddsServBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "LDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLDefault,
            "LAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLAccent,
            "LPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPositive,
            "LWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLWarning,
            "LNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLNegative,
            "LWhite" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLWhite,
            "LBlack" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLBlack,
            "LPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledDefault,
            "LPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledAccent,
            "LPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledPositive,
            "LPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledWarning,
            "LPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledNegative,
            "LPilledWhite" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledWhite,
            "LPilledBlack" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledBlack,
            "MDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMDefault,
            "MAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMAccent,
            "MPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPositive,
            "MWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMWarning,
            "MNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMNegative,
            "MWhite" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMWhite,
            "MBlack" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMBlack,
            "MPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledDefault,
            "MPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledAccent,
            "MPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledPositive,
            "MPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledWarning,
            "MPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledNegative,
            "MPilledWhite" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledWhite,
            "MPilledBlack" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledBlack,
            "SDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSDefault,
            "SAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSAccent,
            "SPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPositive,
            "SWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSNegative,
            "SNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSWarning,
            "SWhite" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSWhite,
            "SBlack" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSBlack,
            "SPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledDefault,
            "SPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledAccent,
            "SPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledPositive,
            "SPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledWarning,
            "SPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledNegative,
            "SPilledWhite" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledWhite,
            "SPilledBlack" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledBlack,
            "XsDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsDefault,
            "XsAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsAccent,
            "XsPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPositive,
            "XsWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsWarning,
            "XsNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsNegative,
            "XsWhite" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsWhite,
            "XsBlack" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsBlack,
            "XsPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledDefault,
            "XsPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledAccent,
            "XsPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledPositive,
            "XsPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledWarning,
            "XsPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledNegative,
            "XsPilledWhite" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledWhite,
            "XsPilledBlack" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledBlack,
        )
}
