package com.sdds.playground.sandbox.sdds.serv.integration.badge

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.sdds.serv.integration.s

internal object SddsServBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "LDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLDefault,
            "LAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLAccent,
            "LPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPositive,
            "LWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLWarning,
            "LNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLNegative,
            "LLight" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLLight,
            "LDark" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLDark,
            "LPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledDefault,
            "LPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledAccent,
            "LPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledPositive,
            "LPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledWarning,
            "LPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledNegative,
            "LPilledLight" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledLight,
            "LPilledDark" to s.Serv_Sdds_ComponentOverlays_BadgeSolidLPilledDark,
            "MDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMDefault,
            "MAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMAccent,
            "MPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPositive,
            "MWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMWarning,
            "MNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMNegative,
            "MLight" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMLight,
            "MDark" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMDark,
            "MPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledDefault,
            "MPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledAccent,
            "MPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledPositive,
            "MPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledWarning,
            "MPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledNegative,
            "MPilledLight" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledLight,
            "MPilledDark" to s.Serv_Sdds_ComponentOverlays_BadgeSolidMPilledDark,
            "SDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSDefault,
            "SAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSAccent,
            "SPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPositive,
            "SWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSNegative,
            "SNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSWarning,
            "SLight" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSLight,
            "SDark" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSDark,
            "SPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledDefault,
            "SPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledAccent,
            "SPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledPositive,
            "SPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledWarning,
            "SPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledNegative,
            "SPilledLight" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledLight,
            "SPilledDark" to s.Serv_Sdds_ComponentOverlays_BadgeSolidSPilledDark,
            "XsDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsDefault,
            "XsAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsAccent,
            "XsPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPositive,
            "XsWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsWarning,
            "XsNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsNegative,
            "XsLight" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsLight,
            "XsDark" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsDark,
            "XsPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledDefault,
            "XsPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledAccent,
            "XsPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledPositive,
            "XsPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledWarning,
            "XsPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledNegative,
            "XsPilledLight" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledLight,
            "XsPilledDark" to s.Serv_Sdds_ComponentOverlays_BadgeSolidXsPilledDark,
        )
}
