package com.sdds.playground.sandbox.sdds.serv.integration.badge

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.sdds.serv.integration.s

internal object SddsServBadgeTransparentVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "TransparentLDefault" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLDefault,
            "TransparentLAccent" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLAccent,
            "TransparentLPositive" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLPositive,
            "TransparentLWarning" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLWarning,
            "TransparentLNegative" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLNegative,
            "TransparentLWhite" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLWhite,
            "TransparentLBlack" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLBlack,
            "TransparentLPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLPilledDefault,
            "TransparentLPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLPilledAccent,
            "TransparentLPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLPilledPositive,
            "TransparentLPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLPilledWarning,
            "TransparentLPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLPilledNegative,
            "TransparentLPilledWhite" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLPilledWhite,
            "TransparentLPilledBlack" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentLPilledBlack,
            "TransparentMDefault" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMDefault,
            "TransparentMAccent" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMAccent,
            "TransparentMPositive" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMPositive,
            "TransparentMWarning" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMWarning,
            "TransparentMNegative" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMNegative,
            "TransparentMWhite" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMWhite,
            "TransparentMBlack" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMBlack,
            "TransparentMPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMPilledDefault,
            "TransparentMPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMPilledAccent,
            "TransparentMPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMPilledPositive,
            "TransparentMPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMPilledWarning,
            "TransparentMPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMPilledNegative,
            "TransparentMPilledWhite" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMPilledWhite,
            "TransparentMPilledBlack" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentMPilledBlack,
            "TransparentSDefault" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSDefault,
            "TransparentSAccent" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSAccent,
            "TransparentSPositive" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSPositive,
            "TransparentSWarning" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSNegative,
            "TransparentSNegative" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSWarning,
            "TransparentSWhite" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSWhite,
            "TransparentSBlack" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSBlack,
            "TransparentSPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSPilledDefault,
            "TransparentSPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSPilledAccent,
            "TransparentSPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSPilledPositive,
            "TransparentSPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSPilledWarning,
            "TransparentSPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSPilledNegative,
            "TransparentSPilledWhite" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSPilledWhite,
            "TransparentSPilledBlack" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentSPilledBlack,
            "TransparentXsDefault" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsDefault,
            "TransparentXsAccent" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsAccent,
            "TransparentXsPositive" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsPositive,
            "TransparentXsWarning" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsWarning,
            "TransparentXsNegative" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsNegative,
            "TransparentXsWhite" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsWhite,
            "TransparentXsBlack" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsBlack,
            "TransparentXsPilledDefault" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsPilledDefault,
            "TransparentXsPilledAccent" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsPilledAccent,
            "TransparentXsPilledPositive" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsPilledPositive,
            "TransparentXsPilledWarning" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsPilledWarning,
            "TransparentXsPilledNegative" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsPilledNegative,
            "TransparentXsPilledWhite" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsPilledWhite,
            "TransparentXsPilledBlack" to s.Serv_Sdds_ComponentOverlays_BadgeTransparentXsPilledBlack,
        )
}
