// AUTO-GENERATED. DO NOT MODIFY this file.
@file:Suppress(
    "UndocumentedPublicClass",
    "UndocumentedPublicProperty",
    "ktlint:standard:max-line-length",
)

package com.sdds.serv.integration

import com.sdds.sandbox.AndroidViewStyleProvider
import com.sdds.sandbox.AndroidViewStyleReference
import com.sdds.sandbox.viewStyleReference
import com.sdds.serv.R as DsR

internal object SddsServNoteCompactVariationsView : AndroidViewStyleProvider() {
    override val variations: Map<String, AndroidViewStyleReference> =
        mapOf(
            "L" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactL),
            "L.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLDefault),
            "L.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLPositive),
            "L.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLNegative),
            "L.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLWarning),
            "L.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLInfo),
            "L.HasClose" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasClose),
            "L.HasClose.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseDefault),
            "L.HasClose.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasClosePositive),
            "L.HasClose.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseNegative),
            "L.HasClose.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseWarning),
            "L.HasClose.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseInfo),
            "L.ContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalable),
            "L.ContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalableDefault),
            "L.ContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalablePositive),
            "L.ContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalableNegative),
            "L.ContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalableWarning),
            "L.ContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLContentScalableInfo),
            "L.HasCloseContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalable),
            "L.HasCloseContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalableDefault),
            "L.HasCloseContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalablePositive),
            "L.HasCloseContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalableNegative),
            "L.HasCloseContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalableWarning),
            "L.HasCloseContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactLHasCloseContentScalableInfo),
            "M" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactM),
            "M.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMDefault),
            "M.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMPositive),
            "M.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMNegative),
            "M.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMWarning),
            "M.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMInfo),
            "M.HasClose" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasClose),
            "M.HasClose.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseDefault),
            "M.HasClose.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasClosePositive),
            "M.HasClose.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseNegative),
            "M.HasClose.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseWarning),
            "M.HasClose.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseInfo),
            "M.ContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalable),
            "M.ContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalableDefault),
            "M.ContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalablePositive),
            "M.ContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalableNegative),
            "M.ContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalableWarning),
            "M.ContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMContentScalableInfo),
            "M.HasCloseContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalable),
            "M.HasCloseContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalableDefault),
            "M.HasCloseContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalablePositive),
            "M.HasCloseContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalableNegative),
            "M.HasCloseContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalableWarning),
            "M.HasCloseContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactMHasCloseContentScalableInfo),
            "S" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactS),
            "S.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSDefault),
            "S.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSPositive),
            "S.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSNegative),
            "S.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSWarning),
            "S.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSInfo),
            "S.HasClose" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasClose),
            "S.HasClose.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseDefault),
            "S.HasClose.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasClosePositive),
            "S.HasClose.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseNegative),
            "S.HasClose.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseWarning),
            "S.HasClose.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseInfo),
            "S.ContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalable),
            "S.ContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalableDefault),
            "S.ContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalablePositive),
            "S.ContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalableNegative),
            "S.ContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalableWarning),
            "S.ContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSContentScalableInfo),
            "S.HasCloseContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalable),
            "S.HasCloseContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalableDefault),
            "S.HasCloseContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalablePositive),
            "S.HasCloseContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalableNegative),
            "S.HasCloseContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalableWarning),
            "S.HasCloseContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactSHasCloseContentScalableInfo),
            "Xs" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXs),
            "Xs.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsDefault),
            "Xs.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsPositive),
            "Xs.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsNegative),
            "Xs.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsWarning),
            "Xs.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsInfo),
            "Xs.HasClose" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasClose),
            "Xs.HasClose.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseDefault),
            "Xs.HasClose.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasClosePositive),
            "Xs.HasClose.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseNegative),
            "Xs.HasClose.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseWarning),
            "Xs.HasClose.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseInfo),
            "Xs.ContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalable),
            "Xs.ContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalableDefault),
            "Xs.ContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalablePositive),
            "Xs.ContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalableNegative),
            "Xs.ContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalableWarning),
            "Xs.ContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsContentScalableInfo),
            "Xs.HasCloseContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalable),
            "Xs.HasCloseContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalableDefault),
            "Xs.HasCloseContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalablePositive),
            "Xs.HasCloseContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalableNegative),
            "Xs.HasCloseContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalableWarning),
            "Xs.HasCloseContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteCompactXsHasCloseContentScalableInfo),
        )
}
