// AUTO-GENERATED. DO NOT MODIFY this file.
@file:Suppress(
    "UndocumentedPublicClass",
    "UndocumentedPublicProperty",
    "ktlint:standard:max-line-length",
)

package com.sdds.serv.integration

import com.sdds.sandbox.AndroidViewStyleProvider
import com.sdds.sandbox.AndroidViewStyleReference
import com.sdds.sandbox.viewStyleReference
import com.sdds.serv.R as DsR

internal object SddsServTextAreaVariationsView : AndroidViewStyleProvider() {
    override val variations: Map<String, AndroidViewStyleReference> =
        mapOf(
            "Xs" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXs),
            "Xs.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsDefault),
            "Xs.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsWarning),
            "Xs.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsError),
            "Xs.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsRequiredStart),
            "Xs.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsRequiredStartDefault),
            "Xs.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsRequiredStartWarning),
            "Xs.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsRequiredStartError),
            "Xs.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsRequiredEnd),
            "Xs.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsRequiredEndDefault),
            "Xs.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsRequiredEndWarning),
            "Xs.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsRequiredEndError),
            "Xs.OuterLabel" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabel),
            "Xs.OuterLabel.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabelDefault),
            "Xs.OuterLabel.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabelWarning),
            "Xs.OuterLabel.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabelError),
            "Xs.OuterLabel.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabelRequiredStart),
            "Xs.OuterLabel.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabelRequiredStartDefault),
            "Xs.OuterLabel.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabelRequiredStartWarning),
            "Xs.OuterLabel.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabelRequiredStartError),
            "Xs.OuterLabel.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabelRequiredEnd),
            "Xs.OuterLabel.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabelRequiredEndDefault),
            "Xs.OuterLabel.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabelRequiredEndWarning),
            "Xs.OuterLabel.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXsOuterLabelRequiredEndError),
            "S" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaS),
            "S.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSDefault),
            "S.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSWarning),
            "S.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSError),
            "S.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSRequiredStart),
            "S.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSRequiredStartDefault),
            "S.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSRequiredStartWarning),
            "S.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSRequiredStartError),
            "S.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSRequiredEnd),
            "S.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSRequiredEndDefault),
            "S.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSRequiredEndWarning),
            "S.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSRequiredEndError),
            "S.OuterLabel" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabel),
            "S.OuterLabel.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabelDefault),
            "S.OuterLabel.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabelWarning),
            "S.OuterLabel.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabelError),
            "S.OuterLabel.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabelRequiredStart),
            "S.OuterLabel.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabelRequiredStartDefault),
            "S.OuterLabel.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabelRequiredStartWarning),
            "S.OuterLabel.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabelRequiredStartError),
            "S.OuterLabel.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabelRequiredEnd),
            "S.OuterLabel.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabelRequiredEndDefault),
            "S.OuterLabel.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabelRequiredEndWarning),
            "S.OuterLabel.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSOuterLabelRequiredEndError),
            "S.InnerLabel" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabel),
            "S.InnerLabel.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabelDefault),
            "S.InnerLabel.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabelWarning),
            "S.InnerLabel.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabelError),
            "S.InnerLabel.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabelRequiredStart),
            "S.InnerLabel.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabelRequiredStartDefault),
            "S.InnerLabel.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabelRequiredStartWarning),
            "S.InnerLabel.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabelRequiredStartError),
            "S.InnerLabel.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabelRequiredEnd),
            "S.InnerLabel.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabelRequiredEndDefault),
            "S.InnerLabel.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabelRequiredEndWarning),
            "S.InnerLabel.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaSInnerLabelRequiredEndError),
            "M" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaM),
            "M.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMDefault),
            "M.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMWarning),
            "M.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMError),
            "M.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMRequiredStart),
            "M.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMRequiredStartDefault),
            "M.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMRequiredStartWarning),
            "M.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMRequiredStartError),
            "M.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMRequiredEnd),
            "M.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMRequiredEndDefault),
            "M.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMRequiredEndWarning),
            "M.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMRequiredEndError),
            "M.OuterLabel" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabel),
            "M.OuterLabel.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabelDefault),
            "M.OuterLabel.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabelWarning),
            "M.OuterLabel.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabelError),
            "M.OuterLabel.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabelRequiredStart),
            "M.OuterLabel.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabelRequiredStartDefault),
            "M.OuterLabel.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabelRequiredStartWarning),
            "M.OuterLabel.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabelRequiredStartError),
            "M.OuterLabel.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabelRequiredEnd),
            "M.OuterLabel.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabelRequiredEndDefault),
            "M.OuterLabel.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabelRequiredEndWarning),
            "M.OuterLabel.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMOuterLabelRequiredEndError),
            "M.InnerLabel" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabel),
            "M.InnerLabel.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabelDefault),
            "M.InnerLabel.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabelWarning),
            "M.InnerLabel.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabelError),
            "M.InnerLabel.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabelRequiredStart),
            "M.InnerLabel.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabelRequiredStartDefault),
            "M.InnerLabel.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabelRequiredStartWarning),
            "M.InnerLabel.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabelRequiredStartError),
            "M.InnerLabel.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabelRequiredEnd),
            "M.InnerLabel.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabelRequiredEndDefault),
            "M.InnerLabel.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabelRequiredEndWarning),
            "M.InnerLabel.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaMInnerLabelRequiredEndError),
            "L" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaL),
            "L.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLDefault),
            "L.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLWarning),
            "L.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLError),
            "L.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLRequiredStart),
            "L.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLRequiredStartDefault),
            "L.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLRequiredStartWarning),
            "L.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLRequiredStartError),
            "L.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLRequiredEnd),
            "L.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLRequiredEndDefault),
            "L.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLRequiredEndWarning),
            "L.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLRequiredEndError),
            "L.OuterLabel" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabel),
            "L.OuterLabel.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabelDefault),
            "L.OuterLabel.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabelWarning),
            "L.OuterLabel.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabelError),
            "L.OuterLabel.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabelRequiredStart),
            "L.OuterLabel.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabelRequiredStartDefault),
            "L.OuterLabel.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabelRequiredStartWarning),
            "L.OuterLabel.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabelRequiredStartError),
            "L.OuterLabel.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabelRequiredEnd),
            "L.OuterLabel.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabelRequiredEndDefault),
            "L.OuterLabel.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabelRequiredEndWarning),
            "L.OuterLabel.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLOuterLabelRequiredEndError),
            "L.InnerLabel" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabel),
            "L.InnerLabel.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabelDefault),
            "L.InnerLabel.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabelWarning),
            "L.InnerLabel.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabelError),
            "L.InnerLabel.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabelRequiredStart),
            "L.InnerLabel.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabelRequiredStartDefault),
            "L.InnerLabel.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabelRequiredStartWarning),
            "L.InnerLabel.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabelRequiredStartError),
            "L.InnerLabel.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabelRequiredEnd),
            "L.InnerLabel.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabelRequiredEndDefault),
            "L.InnerLabel.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabelRequiredEndWarning),
            "L.InnerLabel.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaLInnerLabelRequiredEndError),
            "Xl" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXl),
            "Xl.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlDefault),
            "Xl.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlWarning),
            "Xl.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlError),
            "Xl.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlRequiredStart),
            "Xl.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlRequiredStartDefault),
            "Xl.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlRequiredStartWarning),
            "Xl.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlRequiredStartError),
            "Xl.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlRequiredEnd),
            "Xl.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlRequiredEndDefault),
            "Xl.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlRequiredEndWarning),
            "Xl.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlRequiredEndError),
            "Xl.OuterLabel" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabel),
            "Xl.OuterLabel.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabelDefault),
            "Xl.OuterLabel.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabelWarning),
            "Xl.OuterLabel.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabelError),
            "Xl.OuterLabel.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabelRequiredStart),
            "Xl.OuterLabel.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabelRequiredStartDefault),
            "Xl.OuterLabel.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabelRequiredStartWarning),
            "Xl.OuterLabel.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabelRequiredStartError),
            "Xl.OuterLabel.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabelRequiredEnd),
            "Xl.OuterLabel.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabelRequiredEndDefault),
            "Xl.OuterLabel.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabelRequiredEndWarning),
            "Xl.OuterLabel.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlOuterLabelRequiredEndError),
            "Xl.InnerLabel" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabel),
            "Xl.InnerLabel.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabelDefault),
            "Xl.InnerLabel.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabelWarning),
            "Xl.InnerLabel.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabelError),
            "Xl.InnerLabel.RequiredStart" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabelRequiredStart),
            "Xl.InnerLabel.RequiredStart.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabelRequiredStartDefault),
            "Xl.InnerLabel.RequiredStart.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabelRequiredStartWarning),
            "Xl.InnerLabel.RequiredStart.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabelRequiredStartError),
            "Xl.InnerLabel.RequiredEnd" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabelRequiredEnd),
            "Xl.InnerLabel.RequiredEnd.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabelRequiredEndDefault),
            "Xl.InnerLabel.RequiredEnd.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabelRequiredEndWarning),
            "Xl.InnerLabel.RequiredEnd.Error" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_TextAreaXlInnerLabelRequiredEndError),
        )
}
