// AUTO-GENERATED. DO NOT MODIFY this file.
@file:Suppress(
    "UndocumentedPublicClass",
    "UndocumentedPublicProperty",
    "ktlint:standard:max-line-length",
)

package com.sdds.serv.integration

import com.sdds.sandbox.AndroidViewStyleProvider
import com.sdds.sandbox.AndroidViewStyleReference
import com.sdds.sandbox.viewStyleReference
import com.sdds.serv.R as DsR

internal object SddsServNoteVariationsView : AndroidViewStyleProvider() {
    override val variations: Map<String, AndroidViewStyleReference> =
        mapOf(
            "L" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteL),
            "L.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLDefault),
            "L.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLPositive),
            "L.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLNegative),
            "L.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLWarning),
            "L.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLInfo),
            "L.HasClose" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasClose),
            "L.HasClose.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasCloseDefault),
            "L.HasClose.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasClosePositive),
            "L.HasClose.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasCloseNegative),
            "L.HasClose.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasCloseWarning),
            "L.HasClose.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasCloseInfo),
            "L.ContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLContentScalable),
            "L.ContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLContentScalableDefault),
            "L.ContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLContentScalablePositive),
            "L.ContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLContentScalableNegative),
            "L.ContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLContentScalableWarning),
            "L.ContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLContentScalableInfo),
            "L.HasCloseContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasCloseContentScalable),
            "L.HasCloseContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasCloseContentScalableDefault),
            "L.HasCloseContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasCloseContentScalablePositive),
            "L.HasCloseContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasCloseContentScalableNegative),
            "L.HasCloseContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasCloseContentScalableWarning),
            "L.HasCloseContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteLHasCloseContentScalableInfo),
            "M" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteM),
            "M.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMDefault),
            "M.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMPositive),
            "M.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMNegative),
            "M.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMWarning),
            "M.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMInfo),
            "M.HasClose" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasClose),
            "M.HasClose.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasCloseDefault),
            "M.HasClose.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasClosePositive),
            "M.HasClose.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasCloseNegative),
            "M.HasClose.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasCloseWarning),
            "M.HasClose.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasCloseInfo),
            "M.ContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMContentScalable),
            "M.ContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMContentScalableDefault),
            "M.ContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMContentScalablePositive),
            "M.ContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMContentScalableNegative),
            "M.ContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMContentScalableWarning),
            "M.ContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMContentScalableInfo),
            "M.HasCloseContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasCloseContentScalable),
            "M.HasCloseContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasCloseContentScalableDefault),
            "M.HasCloseContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasCloseContentScalablePositive),
            "M.HasCloseContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasCloseContentScalableNegative),
            "M.HasCloseContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasCloseContentScalableWarning),
            "M.HasCloseContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteMHasCloseContentScalableInfo),
            "S" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteS),
            "S.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSDefault),
            "S.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSPositive),
            "S.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSNegative),
            "S.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSWarning),
            "S.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSInfo),
            "S.HasClose" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasClose),
            "S.HasClose.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasCloseDefault),
            "S.HasClose.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasClosePositive),
            "S.HasClose.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasCloseNegative),
            "S.HasClose.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasCloseWarning),
            "S.HasClose.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasCloseInfo),
            "S.ContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSContentScalable),
            "S.ContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSContentScalableDefault),
            "S.ContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSContentScalablePositive),
            "S.ContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSContentScalableNegative),
            "S.ContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSContentScalableWarning),
            "S.ContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSContentScalableInfo),
            "S.HasCloseContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasCloseContentScalable),
            "S.HasCloseContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasCloseContentScalableDefault),
            "S.HasCloseContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasCloseContentScalablePositive),
            "S.HasCloseContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasCloseContentScalableNegative),
            "S.HasCloseContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasCloseContentScalableWarning),
            "S.HasCloseContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteSHasCloseContentScalableInfo),
            "Xs" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXs),
            "Xs.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsDefault),
            "Xs.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsPositive),
            "Xs.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsNegative),
            "Xs.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsWarning),
            "Xs.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsInfo),
            "Xs.HasClose" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasClose),
            "Xs.HasClose.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasCloseDefault),
            "Xs.HasClose.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasClosePositive),
            "Xs.HasClose.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasCloseNegative),
            "Xs.HasClose.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasCloseWarning),
            "Xs.HasClose.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasCloseInfo),
            "Xs.ContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsContentScalable),
            "Xs.ContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsContentScalableDefault),
            "Xs.ContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsContentScalablePositive),
            "Xs.ContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsContentScalableNegative),
            "Xs.ContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsContentScalableWarning),
            "Xs.ContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsContentScalableInfo),
            "Xs.HasCloseContentScalable" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasCloseContentScalable),
            "Xs.HasCloseContentScalable.Default" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasCloseContentScalableDefault),
            "Xs.HasCloseContentScalable.Positive" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasCloseContentScalablePositive),
            "Xs.HasCloseContentScalable.Negative" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasCloseContentScalableNegative),
            "Xs.HasCloseContentScalable.Warning" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasCloseContentScalableWarning),
            "Xs.HasCloseContentScalable.Info" to viewStyleReference(DsR.style.Serv_Sdds_ComponentOverlays_NoteXsHasCloseContentScalableInfo),
        )
}
