package com.sdds.playground.sandbox.stylessalute.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.stylessalute.R as DsR

internal object StylesSaluteIconBadgeClearVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearL,
            "L.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLDefault,
            "L.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLAccent,
            "L.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLNegative,
            "L.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLPositive,
            "L.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLWarning,
            "L.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLDark,
            "L.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLLight,
            "L.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLPilled,
            "L.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLPilledDefault,
            "L.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLPilledAccent,
            "L.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLPilledNegative,
            "L.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLPilledPositive,
            "L.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLPilledWarning,
            "L.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLPilledDark,
            "L.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearLPilledLight,
            "M" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearM,
            "M.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMDefault,
            "M.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMAccent,
            "M.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMNegative,
            "M.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMPositive,
            "M.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMWarning,
            "M.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMDark,
            "M.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMLight,
            "M.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMPilled,
            "M.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMPilledDefault,
            "M.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMPilledAccent,
            "M.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMPilledNegative,
            "M.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMPilledPositive,
            "M.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMPilledWarning,
            "M.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMPilledDark,
            "M.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearMPilledLight,
            "S" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearS,
            "S.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSDefault,
            "S.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSAccent,
            "S.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSNegative,
            "S.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSPositive,
            "S.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSWarning,
            "S.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSDark,
            "S.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSLight,
            "S.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSPilled,
            "S.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSPilledDefault,
            "S.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSPilledAccent,
            "S.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSPilledNegative,
            "S.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSPilledPositive,
            "S.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSPilledWarning,
            "S.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSPilledDark,
            "S.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearSPilledLight,
            "Xs" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXs,
            "Xs.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsDefault,
            "Xs.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsAccent,
            "Xs.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsNegative,
            "Xs.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsPositive,
            "Xs.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsWarning,
            "Xs.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsDark,
            "Xs.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsLight,
            "Xs.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsPilled,
            "Xs.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsPilledDefault,
            "Xs.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsPilledAccent,
            "Xs.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsPilledNegative,
            "Xs.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsPilledPositive,
            "Xs.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsPilledWarning,
            "Xs.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsPilledDark,
            "Xs.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeClearXsPilledLight,
        )
}
