package com.sdds.playground.sandbox.stylessalute.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.stylessalute.R as DsR

internal object StylesSaluteIconBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidL,
            "L.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLDefault,
            "L.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLAccent,
            "L.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLNegative,
            "L.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPositive,
            "L.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLWarning,
            "L.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLDark,
            "L.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLLight,
            "L.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilled,
            "L.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledDefault,
            "L.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledAccent,
            "L.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledNegative,
            "L.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledPositive,
            "L.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledWarning,
            "L.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledDark,
            "L.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidLPilledLight,
            "M" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidM,
            "M.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMDefault,
            "M.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMAccent,
            "M.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMNegative,
            "M.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPositive,
            "M.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMWarning,
            "M.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMDark,
            "M.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMLight,
            "M.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilled,
            "M.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledDefault,
            "M.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledAccent,
            "M.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledNegative,
            "M.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledPositive,
            "M.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledWarning,
            "M.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledDark,
            "M.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidMPilledLight,
            "S" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidS,
            "S.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSDefault,
            "S.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSAccent,
            "S.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSNegative,
            "S.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPositive,
            "S.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSWarning,
            "S.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSDark,
            "S.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSLight,
            "S.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilled,
            "S.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledDefault,
            "S.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledAccent,
            "S.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledNegative,
            "S.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledPositive,
            "S.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledWarning,
            "S.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledDark,
            "S.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidSPilledLight,
            "Xs" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXs,
            "Xs.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsDefault,
            "Xs.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsAccent,
            "Xs.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsNegative,
            "Xs.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPositive,
            "Xs.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsWarning,
            "Xs.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsDark,
            "Xs.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsLight,
            "Xs.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilled,
            "Xs.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledDefault,
            "Xs.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledAccent,
            "Xs.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledNegative,
            "Xs.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledPositive,
            "Xs.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledWarning,
            "Xs.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledDark,
            "Xs.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeSolidXsPilledLight,
        )
}
