package com.sdds.playground.sandbox.stylessalute.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.stylessalute.R as DsR

internal object StylesSaluteBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidL,
            "L.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLDefault,
            "L.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLAccent,
            "L.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLNegative,
            "L.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPositive,
            "L.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLWarning,
            "L.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLDark,
            "L.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLLight,
            "L.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilled,
            "L.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledDefault,
            "L.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledAccent,
            "L.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledNegative,
            "L.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledPositive,
            "L.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledWarning,
            "L.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledDark,
            "L.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledLight,
            "M" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidM,
            "M.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMDefault,
            "M.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMAccent,
            "M.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMNegative,
            "M.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPositive,
            "M.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMWarning,
            "M.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMDark,
            "M.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMLight,
            "M.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilled,
            "M.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledDefault,
            "M.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledAccent,
            "M.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledNegative,
            "M.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledPositive,
            "M.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledWarning,
            "M.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledDark,
            "M.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledLight,
            "S" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidS,
            "S.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSDefault,
            "S.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSAccent,
            "S.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSNegative,
            "S.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPositive,
            "S.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSWarning,
            "S.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSDark,
            "S.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSLight,
            "S.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilled,
            "S.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledDefault,
            "S.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledAccent,
            "S.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledNegative,
            "S.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledPositive,
            "S.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledWarning,
            "S.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledDark,
            "S.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledLight,
            "Xs" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXs,
            "Xs.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsDefault,
            "Xs.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsAccent,
            "Xs.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsNegative,
            "Xs.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPositive,
            "Xs.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsWarning,
            "Xs.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsDark,
            "Xs.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsLight,
            "Xs.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilled,
            "Xs.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledDefault,
            "Xs.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledAccent,
            "Xs.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledNegative,
            "Xs.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledPositive,
            "Xs.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledWarning,
            "Xs.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledDark,
            "Xs.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledLight,
        )
}
