package com.sdds.playground.sandbox.stylessalute.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.stylessalute.R as DsR

internal object StylesSaluteIconBadgeTransparentVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentL,
            "L.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLDefault,
            "L.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLAccent,
            "L.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLNegative,
            "L.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPositive,
            "L.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLWarning,
            "L.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLDark,
            "L.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLLight,
            "L.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilled,
            "L.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledDefault,
            "L.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledAccent,
            "L.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledNegative,
            "L.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledPositive,
            "L.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledWarning,
            "L.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledDark,
            "L.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentLPilledLight,
            "M" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentM,
            "M.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMDefault,
            "M.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMAccent,
            "M.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMNegative,
            "M.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPositive,
            "M.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMWarning,
            "M.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMDark,
            "M.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMLight,
            "M.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilled,
            "M.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledDefault,
            "M.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledAccent,
            "M.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledNegative,
            "M.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledPositive,
            "M.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledWarning,
            "M.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledDark,
            "M.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentMPilledLight,
            "S" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentS,
            "S.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSDefault,
            "S.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSAccent,
            "S.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSNegative,
            "S.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPositive,
            "S.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSWarning,
            "S.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSDark,
            "S.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSLight,
            "S.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilled,
            "S.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledDefault,
            "S.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledAccent,
            "S.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledNegative,
            "S.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledPositive,
            "S.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledWarning,
            "S.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledDark,
            "S.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentSPilledLight,
            "Xs" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXs,
            "Xs.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsDefault,
            "Xs.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsAccent,
            "Xs.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsNegative,
            "Xs.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPositive,
            "Xs.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsWarning,
            "Xs.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsDark,
            "Xs.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsLight,
            "Xs.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilled,
            "Xs.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledDefault,
            "Xs.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledAccent,
            "Xs.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledNegative,
            "Xs.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledPositive,
            "Xs.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledWarning,
            "Xs.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledDark,
            "Xs.Pilled.Light" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconBadgeTransparentXsPilledLight,
        )
}
