package com.sdds.playground.sandbox.stylessalute.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.stylessalute.R as DsR

internal object StylesSaluteIconButtonVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonL,
            "L.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLDefault,
            "L.Secondary" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLSecondary,
            "L.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLAccent,
            "L.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPositive,
            "L.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLNegative,
            "L.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLWarning,
            "L.Clear" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLClear,
            "L.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLDark,
            "L.Black" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLBlack,
            "L.White" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLWhite,
            "L.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPilled,
            "L.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPilledDefault,
            "L.Pilled.Secondary" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPilledSecondary,
            "L.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPilledAccent,
            "L.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPilledPositive,
            "L.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPilledNegative,
            "L.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPilledWarning,
            "L.Pilled.Clear" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPilledClear,
            "L.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPilledDark,
            "L.Pilled.Black" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPilledBlack,
            "L.Pilled.White" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonLPilledWhite,
            "M" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonM,
            "M.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMDefault,
            "M.Secondary" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMSecondary,
            "M.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMAccent,
            "M.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPositive,
            "M.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMNegative,
            "M.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMWarning,
            "M.Clear" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMClear,
            "M.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMDark,
            "M.Black" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMBlack,
            "M.White" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMWhite,
            "M.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPilled,
            "M.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPilledDefault,
            "M.Pilled.Secondary" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPilledSecondary,
            "M.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPilledAccent,
            "M.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPilledPositive,
            "M.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPilledNegative,
            "M.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPilledWarning,
            "M.Pilled.Clear" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPilledClear,
            "M.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPilledDark,
            "M.Pilled.Black" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPilledBlack,
            "M.Pilled.White" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonMPilledWhite,
            "S" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonS,
            "S.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSDefault,
            "S.Secondary" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSSecondary,
            "S.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSAccent,
            "S.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPositive,
            "S.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSNegative,
            "S.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSWarning,
            "S.Clear" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSClear,
            "S.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSDark,
            "S.Black" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSBlack,
            "S.White" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSWhite,
            "S.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPilled,
            "S.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPilledDefault,
            "S.Pilled.Secondary" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPilledSecondary,
            "S.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPilledAccent,
            "S.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPilledPositive,
            "S.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPilledNegative,
            "S.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPilledWarning,
            "S.Pilled.Clear" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPilledClear,
            "S.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPilledDark,
            "S.Pilled.Black" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPilledBlack,
            "S.Pilled.White" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonSPilledWhite,
            "Xs" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXs,
            "Xs.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsDefault,
            "Xs.Secondary" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsSecondary,
            "Xs.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsAccent,
            "Xs.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPositive,
            "Xs.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsNegative,
            "Xs.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsWarning,
            "Xs.Clear" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsClear,
            "Xs.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsDark,
            "Xs.Black" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsBlack,
            "Xs.White" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsWhite,
            "Xs.Pilled" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPilled,
            "Xs.Pilled.Default" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPilledDefault,
            "Xs.Pilled.Secondary" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPilledSecondary,
            "Xs.Pilled.Accent" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPilledAccent,
            "Xs.Pilled.Positive" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPilledPositive,
            "Xs.Pilled.Negative" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPilledNegative,
            "Xs.Pilled.Warning" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPilledWarning,
            "Xs.Pilled.Clear" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPilledClear,
            "Xs.Pilled.Dark" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPilledDark,
            "Xs.Pilled.Black" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPilledBlack,
            "Xs.Pilled.White" to DsR.style.Salute_StylesSalute_ComponentOverlays_IconButtonXsPilledWhite,
        )
}
