package com.sdds.playground.sandbox.stylessalute.integration.badge

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.stylessalute.integration.s

internal object StylesSaluteBadgeTransparentVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> = mapOf(
        "TransparentLDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLDefault,
        "TransparentLAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLAccent,
        "TransparentLPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPositive,
        "TransparentLWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLWarning,
        "TransparentLNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLNegative,
        "TransparentLLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLLight,
        "TransparentLDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLDark,
        "TransparentLPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledDefault,
        "TransparentLPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledAccent,
        "TransparentLPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledPositive,
        "TransparentLPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledWarning,
        "TransparentLPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledNegative,
        "TransparentLPilledLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledLight,
        "TransparentLPilledDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledDark,
        "TransparentMDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMDefault,
        "TransparentMAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMAccent,
        "TransparentMPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPositive,
        "TransparentMWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMWarning,
        "TransparentMNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMNegative,
        "TransparentMLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMLight,
        "TransparentMDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMDark,
        "TransparentMPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledDefault,
        "TransparentMPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledAccent,
        "TransparentMPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledPositive,
        "TransparentMPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledWarning,
        "TransparentMPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledNegative,
        "TransparentMPilledLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledLight,
        "TransparentMPilledDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledDark,
        "TransparentSDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSDefault,
        "TransparentSAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSAccent,
        "TransparentSPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPositive,
        "TransparentSWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSNegative,
        "TransparentSNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSWarning,
        "TransparentSLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSLight,
        "TransparentSDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSDark,
        "TransparentSPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledDefault,
        "TransparentSPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledAccent,
        "TransparentSPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledPositive,
        "TransparentSPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledWarning,
        "TransparentSPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledNegative,
        "TransparentSPilledLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledLight,
        "TransparentSPilledDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledDark,
        "TransparentXsDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsDefault,
        "TransparentXsAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsAccent,
        "TransparentXsPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPositive,
        "TransparentXsWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsWarning,
        "TransparentXsNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsNegative,
        "TransparentXsLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsLight,
        "TransparentXsDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsDark,
        "TransparentXsPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledDefault,
        "TransparentXsPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledAccent,
        "TransparentXsPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledPositive,
        "TransparentXsPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledWarning,
        "TransparentXsPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledNegative,
        "TransparentXsPilledLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledLight,
        "TransparentXsPilledDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledDark,
    )
}
