package com.sdds.playground.sandbox.stylessalute.integration.badge

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.stylessalute.integration.s

internal object StylesSaluteBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> = mapOf(
        "LDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLDefault,
        "LAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLAccent,
        "LPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPositive,
        "LWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLWarning,
        "LNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLNegative,
        "LWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLWhite,
        "LBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLBlack,
        "LPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledDefault,
        "LPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledAccent,
        "LPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledPositive,
        "LPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledWarning,
        "LPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledNegative,
        "LPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledWhite,
        "LPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledBlack,
        "MDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMDefault,
        "MAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMAccent,
        "MPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPositive,
        "MWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMWarning,
        "MNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMNegative,
        "MWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMWhite,
        "MBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMBlack,
        "MPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledDefault,
        "MPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledAccent,
        "MPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledPositive,
        "MPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledWarning,
        "MPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledNegative,
        "MPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledWhite,
        "MPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledBlack,
        "SDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSDefault,
        "SAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSAccent,
        "SPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPositive,
        "SWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSNegative,
        "SNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSWarning,
        "SWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSWhite,
        "SBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSBlack,
        "SPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledDefault,
        "SPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledAccent,
        "SPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledPositive,
        "SPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledWarning,
        "SPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledNegative,
        "SPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledWhite,
        "SPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledBlack,
        "XsDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsDefault,
        "XsAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsAccent,
        "XsPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPositive,
        "XsWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsWarning,
        "XsNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsNegative,
        "XsWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsWhite,
        "XsBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsBlack,
        "XsPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledDefault,
        "XsPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledAccent,
        "XsPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledPositive,
        "XsPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledWarning,
        "XsPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledNegative,
        "XsPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledWhite,
        "XsPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledBlack,
    )
}
