package com.sdds.playground.sandbox.stylessalute.integration.badge

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.stylessalute.integration.s

internal object StylesSaluteBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> = mapOf(
        "LDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLDefault,
        "LAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLAccent,
        "LPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPositive,
        "LWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLWarning,
        "LNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLNegative,
        "LLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLLight,
        "LDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLDark,
        "LPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledDefault,
        "LPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledAccent,
        "LPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledPositive,
        "LPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledWarning,
        "LPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledNegative,
        "LPilledLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledLight,
        "LPilledDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidLPilledDark,
        "MDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMDefault,
        "MAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMAccent,
        "MPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPositive,
        "MWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMWarning,
        "MNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMNegative,
        "MLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMLight,
        "MDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMDark,
        "MPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledDefault,
        "MPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledAccent,
        "MPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledPositive,
        "MPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledWarning,
        "MPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledNegative,
        "MPilledLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledLight,
        "MPilledDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidMPilledDark,
        "SDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSDefault,
        "SAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSAccent,
        "SPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPositive,
        "SWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSNegative,
        "SNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSWarning,
        "SLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSLight,
        "SDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSDark,
        "SPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledDefault,
        "SPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledAccent,
        "SPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledPositive,
        "SPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledWarning,
        "SPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledNegative,
        "SPilledLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledLight,
        "SPilledDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidSPilledDark,
        "XsDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsDefault,
        "XsAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsAccent,
        "XsPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPositive,
        "XsWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsWarning,
        "XsNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsNegative,
        "XsLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsLight,
        "XsDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsDark,
        "XsPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledDefault,
        "XsPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledAccent,
        "XsPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledPositive,
        "XsPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledWarning,
        "XsPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledNegative,
        "XsPilledLight" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledLight,
        "XsPilledDark" to s.Salute_StylesSalute_ComponentOverlays_BadgeSolidXsPilledDark,
    )
}
