package com.sdds.playground.sandbox.stylessalute.integration.badge

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.stylessalute.integration.s

internal object StylesSaluteBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> = mapOf(
        "LDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeLDefault,
        "LAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeLAccent,
        "LPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeLPositive,
        "LWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeLWarning,
        "LNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeLNegative,
        "LWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeLWhite,
        "LBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeLBlack,
        "LPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeLPilledDefault,
        "LPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeLPilledAccent,
        "LPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeLPilledPositive,
        "LPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeLPilledWarning,
        "LPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeLPilledNegative,
        "LPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeLPilledWhite,
        "LPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeLPilledBlack,
        "MDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeMDefault,
        "MAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeMAccent,
        "MPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeMPositive,
        "MWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeMWarning,
        "MNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeMNegative,
        "MWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeMWhite,
        "MBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeMBlack,
        "MPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeMPilledDefault,
        "MPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeMPilledAccent,
        "MPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeMPilledPositive,
        "MPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeMPilledWarning,
        "MPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeMPilledNegative,
        "MPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeMPilledWhite,
        "MPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeMPilledBlack,
        "SDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSDefault,
        "SAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSAccent,
        "SPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSPositive,
        "SWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSNegative,
        "SNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSWarning,
        "SWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeSWhite,
        "SBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeSBlack,
        "SPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeSPilledDefault,
        "SPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeSPilledAccent,
        "SPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeSPilledPositive,
        "SPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeSPilledWarning,
        "SPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeSPilledNegative,
        "SPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeSPilledWhite,
        "SPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeSPilledBlack,
        "XsDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsDefault,
        "XsAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsAccent,
        "XsPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsPositive,
        "XsWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsWarning,
        "XsNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsNegative,
        "XsWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsWhite,
        "XsBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsBlack,
        "XsPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsPilledDefault,
        "XsPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsPilledAccent,
        "XsPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsPilledPositive,
        "XsPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsPilledWarning,
        "XsPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsPilledNegative,
        "XsPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsPilledWhite,
        "XsPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeXsPilledBlack,
    )
}
