package com.sdds.playground.sandbox.stylessalute.integration.badge

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.stylessalute.integration.s

internal object StylesSaluteBadgeTransparentVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> = mapOf(
        "TransparentLDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLDefault,
        "TransparentLAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLAccent,
        "TransparentLPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPositive,
        "TransparentLWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLWarning,
        "TransparentLNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLNegative,
        "TransparentLWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLWhite,
        "TransparentLBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLBlack,
        "TransparentLPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledDefault,
        "TransparentLPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledAccent,
        "TransparentLPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledPositive,
        "TransparentLPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledWarning,
        "TransparentLPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledNegative,
        "TransparentLPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledWhite,
        "TransparentLPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentLPilledBlack,
        "TransparentMDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMDefault,
        "TransparentMAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMAccent,
        "TransparentMPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPositive,
        "TransparentMWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMWarning,
        "TransparentMNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMNegative,
        "TransparentMWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMWhite,
        "TransparentMBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMBlack,
        "TransparentMPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledDefault,
        "TransparentMPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledAccent,
        "TransparentMPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledPositive,
        "TransparentMPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledWarning,
        "TransparentMPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledNegative,
        "TransparentMPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledWhite,
        "TransparentMPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentMPilledBlack,
        "TransparentSDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSDefault,
        "TransparentSAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSAccent,
        "TransparentSPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPositive,
        "TransparentSWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSNegative,
        "TransparentSNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSWarning,
        "TransparentSWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSWhite,
        "TransparentSBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSBlack,
        "TransparentSPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledDefault,
        "TransparentSPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledAccent,
        "TransparentSPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledPositive,
        "TransparentSPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledWarning,
        "TransparentSPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledNegative,
        "TransparentSPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledWhite,
        "TransparentSPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentSPilledBlack,
        "TransparentXsDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsDefault,
        "TransparentXsAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsAccent,
        "TransparentXsPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPositive,
        "TransparentXsWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsWarning,
        "TransparentXsNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsNegative,
        "TransparentXsWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsWhite,
        "TransparentXsBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsBlack,
        "TransparentXsPilledDefault" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledDefault,
        "TransparentXsPilledAccent" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledAccent,
        "TransparentXsPilledPositive" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledPositive,
        "TransparentXsPilledWarning" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledWarning,
        "TransparentXsPilledNegative" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledNegative,
        "TransparentXsPilledWhite" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledWhite,
        "TransparentXsPilledBlack" to s.Salute_StylesSalute_ComponentOverlays_BadgeTransparentXsPilledBlack,
    )
}
