import io.gitlab.arturbosch.detekt.extensions.DetektExtension
import utils.addDefaultTargets

plugins {
    id("convention.cmp-lib")
    id("convention.maven-publish")
    id("convention.auto-bump")
}

group = "sdds-core"

android {
    namespace = "com.sdds.icons.compose"
}

kotlin {
    addDefaultTargets()
    explicitApi()

    sourceSets {
        commonMain {
            dependencies {
                api(compose.ui)
            }
        }
    }
}

// The icons in this module are machine-generated by Valkyrie in CI. Keep them out
// of style checks so the committed files stay byte-for-byte identical to the
// generator output (otherwise CI regeneration would drift from the committed form).
spotless {
    kotlin {
        targetExclude(
            "**/build/**",
            "**/buildSrc/**",
            "**/.*",
            "**/com/sdds/icons/compose/**",
        )
    }
}

// Detekt — тоже style-check: исключаем сгенерированные Valkyrie иконки (как в spotless выше),
// иначе `UndocumentedPublicProperty` и т.п. срабатывают на каждой `SddsIcons.*`-иконке.
// `convention.detekt` задаёт source через project.files(fileTree), из-за чего per-task
// exclude(...) не фильтрует, — переопределяем source с нужным exclude (config/baseline,
// выставленные конвенцией на том же extension, сохраняются).
configure<DetektExtension> {
    source = files(
        fileTree("src") {
            include("main/kotlin/**/*.kt")
            include("*Main/kotlin/**/*.kt")
            exclude("**/com/sdds/icons/compose/**")
        },
    )
}
