// AUTO-GENERATED. DO NOT MODIFY this file.
package com.sdds.sbcom.theme.subthemes

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import com.sdds.sbcom.theme.SddsSbComColors
import com.sdds.sbcom.theme.SddsSbComGradients
import com.sdds.sbcom.theme.SddsSbComTheme
import com.sdds.sbcom.theme.darkSddsSbComColors
import com.sdds.sbcom.theme.darkSddsSbComGradients
import com.sdds.sbcom.theme.lightSddsSbComColors
import com.sdds.sbcom.theme.lightSddsSbComGradients
import com.sdds.sbcom.theme.linearGradient
import com.sdds.sbcom.tokens.DarkColorTokens
import com.sdds.sbcom.tokens.DarkGradientTokens
import com.sdds.sbcom.tokens.LightColorTokens
import com.sdds.sbcom.tokens.LightGradientTokens
import kotlin.Boolean
import kotlin.Unit

private val darkInverseColors: SddsSbComColors by lazy {
    darkSddsSbComColors {
        textInversePrimaryHover.overrideBy(DarkColorTokens.TextDefaultPrimaryHover)
        textInversePrimaryActive.overrideBy(DarkColorTokens.TextDefaultPrimaryActive)
        textInversePrimaryBrightness.overrideBy(DarkColorTokens.TextDefaultPrimaryBrightness)
        textInverseSecondaryHover.overrideBy(DarkColorTokens.TextDefaultSecondaryHover)
        textInverseSecondaryActive.overrideBy(DarkColorTokens.TextDefaultSecondaryActive)
        textInverseTertiaryHover.overrideBy(DarkColorTokens.TextDefaultTertiaryHover)
        textInverseTertiaryActive.overrideBy(DarkColorTokens.TextDefaultTertiaryActive)
        textInverseParagraphHover.overrideBy(DarkColorTokens.TextDefaultParagraphHover)
        textInverseParagraphActive.overrideBy(DarkColorTokens.TextDefaultParagraphActive)
        textInverseAccentHover.overrideBy(DarkColorTokens.TextDefaultAccentHover)
        textInverseAccentActive.overrideBy(DarkColorTokens.TextDefaultAccentActive)
        textInverseAccentMinorHover.overrideBy(DarkColorTokens.TextDefaultAccentMinorHover)
        textInverseAccentMinorActive.overrideBy(DarkColorTokens.TextDefaultAccentMinorActive)
        textInversePositiveHover.overrideBy(DarkColorTokens.TextDefaultPositiveHover)
        textInversePositiveActive.overrideBy(DarkColorTokens.TextDefaultPositiveActive)
        textInverseWarningHover.overrideBy(DarkColorTokens.TextDefaultWarningHover)
        textInverseWarningActive.overrideBy(DarkColorTokens.TextDefaultWarningActive)
        textInverseNegativeHover.overrideBy(DarkColorTokens.TextDefaultNegativeHover)
        textInverseNegativeActive.overrideBy(DarkColorTokens.TextDefaultNegativeActive)
        textInverseInfoHover.overrideBy(DarkColorTokens.TextDefaultInfoHover)
        textInverseInfoActive.overrideBy(DarkColorTokens.TextDefaultInfoActive)
        textInversePositiveMinorHover.overrideBy(DarkColorTokens.TextDefaultPositiveMinorHover)
        textInversePositiveMinorActive.overrideBy(DarkColorTokens.TextDefaultPositiveMinorActive)
        textInverseWarningMinorHover.overrideBy(DarkColorTokens.TextDefaultWarningMinorHover)
        textInverseWarningMinorActive.overrideBy(DarkColorTokens.TextDefaultWarningMinorActive)
        textInverseNegativeMinorHover.overrideBy(DarkColorTokens.TextDefaultNegativeMinorHover)
        textInverseNegativeMinorActive.overrideBy(DarkColorTokens.TextDefaultNegativeMinorActive)
        textInverseInfoMinorHover.overrideBy(DarkColorTokens.TextDefaultInfoMinorHover)
        textInverseInfoMinorActive.overrideBy(DarkColorTokens.TextDefaultInfoMinorActive)
        textInverseAccent.overrideBy(DarkColorTokens.TextDefaultAccent)
        textInversePositive.overrideBy(DarkColorTokens.TextDefaultPositive)
        textInverseAccentMinor.overrideBy(DarkColorTokens.TextDefaultAccentMinor)
        textInversePositiveMinor.overrideBy(DarkColorTokens.TextDefaultPositiveMinor)
        textInversePrimary.overrideBy(DarkColorTokens.TextDefaultPrimary)
        textInverseSecondary.overrideBy(DarkColorTokens.TextDefaultSecondary)
        textInverseTertiary.overrideBy(DarkColorTokens.TextDefaultTertiary)
        textInverseParagraph.overrideBy(DarkColorTokens.TextDefaultParagraph)
        textInverseWarning.overrideBy(DarkColorTokens.TextDefaultWarning)
        textInverseNegative.overrideBy(DarkColorTokens.TextDefaultNegative)
        textInverseInfo.overrideBy(DarkColorTokens.TextDefaultInfo)
        textInverseNegativeMinor.overrideBy(DarkColorTokens.TextDefaultNegativeMinor)
        textInverseWarningMinor.overrideBy(DarkColorTokens.TextDefaultWarningMinor)
        textInverseInfoMinor.overrideBy(DarkColorTokens.TextDefaultInfoMinor)
        surfaceInverseSolidPrimaryHover.overrideBy(DarkColorTokens.SurfaceDefaultSolidPrimaryHover)
        surfaceInverseSolidPrimaryActive.overrideBy(DarkColorTokens.SurfaceDefaultSolidPrimaryActive)
        surfaceInverseSolidPrimaryBrightness.overrideBy(DarkColorTokens.SurfaceDefaultSolidPrimaryBrightness)
        surfaceInverseSolidSecondaryHover.overrideBy(DarkColorTokens.SurfaceDefaultSolidSecondaryHover)
        surfaceInverseSolidSecondaryActive.overrideBy(DarkColorTokens.SurfaceDefaultSolidSecondaryActive)
        surfaceInverseSolidTertiaryHover.overrideBy(DarkColorTokens.SurfaceDefaultSolidTertiaryHover)
        surfaceInverseSolidTertiaryActive.overrideBy(DarkColorTokens.SurfaceDefaultSolidTertiaryActive)
        surfaceInverseSolidCardHover.overrideBy(DarkColorTokens.SurfaceDefaultSolidCardHover)
        surfaceInverseSolidCardActive.overrideBy(DarkColorTokens.SurfaceDefaultSolidCardActive)
        surfaceInverseSolidCardBrightness.overrideBy(DarkColorTokens.SurfaceDefaultSolidCardBrightness)
        surfaceInverseSolidDefaultHover.overrideBy(DarkColorTokens.SurfaceDefaultSolidDefaultHover)
        surfaceInverseSolidDefaultActive.overrideBy(DarkColorTokens.SurfaceDefaultSolidDefaultActive)
        surfaceInverseTransparentPrimaryHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentPrimaryHover)
        surfaceInverseTransparentPrimaryActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentPrimaryActive)
        surfaceInverseTransparentSecondaryHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentSecondaryHover)
        surfaceInverseTransparentSecondaryActive.overrideBy(
            DarkColorTokens.SurfaceDefaultTransparentSecondaryActive,
        )
        surfaceInverseTransparentTertiaryHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentTertiaryHover)
        surfaceInverseTransparentTertiaryActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentTertiaryActive)
        surfaceInverseTransparentDeepHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentDeepHover)
        surfaceInverseTransparentDeepActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentDeepActive)
        surfaceInverseTransparentCardHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentCardHover)
        surfaceInverseTransparentCardActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentCardActive)
        surfaceInverseTransparentCardBrightness.overrideBy(DarkColorTokens.SurfaceDefaultTransparentCardBrightness)
        surfaceInverseClearHover.overrideBy(DarkColorTokens.SurfaceDefaultClearHover)
        surfaceInverseClearActive.overrideBy(DarkColorTokens.SurfaceDefaultClearActive)
        surfaceInverseAccentHover.overrideBy(DarkColorTokens.SurfaceDefaultAccentHover)
        surfaceInverseAccentActive.overrideBy(DarkColorTokens.SurfaceDefaultAccentActive)
        surfaceInverseAccentMinorHover.overrideBy(DarkColorTokens.SurfaceDefaultAccentMinorHover)
        surfaceInverseAccentMinorActive.overrideBy(DarkColorTokens.SurfaceDefaultAccentMinorActive)
        surfaceInverseTransparentAccentHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentAccentHover)
        surfaceInverseTransparentAccentActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentAccentActive)
        surfaceInversePositiveHover.overrideBy(DarkColorTokens.SurfaceDefaultPositiveHover)
        surfaceInversePositiveActive.overrideBy(DarkColorTokens.SurfaceDefaultPositiveActive)
        surfaceInverseWarningHover.overrideBy(DarkColorTokens.SurfaceDefaultWarningHover)
        surfaceInverseWarningActive.overrideBy(DarkColorTokens.SurfaceDefaultWarningActive)
        surfaceInverseNegativeHover.overrideBy(DarkColorTokens.SurfaceDefaultNegativeHover)
        surfaceInverseNegativeActive.overrideBy(DarkColorTokens.SurfaceDefaultNegativeActive)
        surfaceInverseInfoHover.overrideBy(DarkColorTokens.SurfaceDefaultInfoHover)
        surfaceInverseInfoActive.overrideBy(DarkColorTokens.SurfaceDefaultInfoActive)
        surfaceInversePositiveMinorHover.overrideBy(DarkColorTokens.SurfaceDefaultPositiveMinorHover)
        surfaceInversePositiveMinorActive.overrideBy(DarkColorTokens.SurfaceDefaultPositiveMinorActive)
        surfaceInverseWarningMinorHover.overrideBy(DarkColorTokens.SurfaceDefaultWarningMinorHover)
        surfaceInverseWarningMinorActive.overrideBy(DarkColorTokens.SurfaceDefaultWarningMinorActive)
        surfaceInverseNegativeMinorHover.overrideBy(DarkColorTokens.SurfaceDefaultNegativeMinorHover)
        surfaceInverseNegativeMinorActive.overrideBy(DarkColorTokens.SurfaceDefaultNegativeMinorActive)
        surfaceInverseInfoMinorHover.overrideBy(DarkColorTokens.SurfaceDefaultInfoMinorHover)
        surfaceInverseInfoMinorActive.overrideBy(DarkColorTokens.SurfaceDefaultInfoMinorActive)
        surfaceInverseSolidCard.overrideBy(DarkColorTokens.SurfaceDefaultSolidCard)
        surfaceInverseSolidPrimary.overrideBy(DarkColorTokens.SurfaceDefaultSolidPrimary)
        surfaceInverseSolidSecondary.overrideBy(DarkColorTokens.SurfaceDefaultSolidSecondary)
        surfaceInverseSolidTertiary.overrideBy(DarkColorTokens.SurfaceDefaultSolidTertiary)
        surfaceInverseSolidDefault.overrideBy(DarkColorTokens.SurfaceDefaultSolidDefault)
        surfaceInverseTransparentPrimary.overrideBy(DarkColorTokens.SurfaceDefaultTransparentPrimary)
        surfaceInverseTransparentSecondary.overrideBy(DarkColorTokens.SurfaceDefaultTransparentSecondary)
        surfaceInverseTransparentTertiary.overrideBy(DarkColorTokens.SurfaceDefaultTransparentTertiary)
        surfaceInverseTransparentDeep.overrideBy(DarkColorTokens.SurfaceDefaultTransparentDeep)
        surfaceInverseClear.overrideBy(DarkColorTokens.SurfaceDefaultClear)
        surfaceInverseWarning.overrideBy(DarkColorTokens.SurfaceDefaultWarning)
        surfaceInverseNegative.overrideBy(DarkColorTokens.SurfaceDefaultNegative)
        surfaceInverseTransparentAccent.overrideBy(DarkColorTokens.SurfaceDefaultTransparentAccent)
        surfaceInverseInfo.overrideBy(DarkColorTokens.SurfaceDefaultInfo)
        surfaceInverseWarningMinor.overrideBy(DarkColorTokens.SurfaceDefaultWarningMinor)
        surfaceInverseNegativeMinor.overrideBy(DarkColorTokens.SurfaceDefaultNegativeMinor)
        surfaceInverseInfoMinor.overrideBy(DarkColorTokens.SurfaceDefaultInfoMinor)
        surfaceInverseAccent.overrideBy(DarkColorTokens.SurfaceDefaultAccent)
        surfaceInversePositive.overrideBy(DarkColorTokens.SurfaceDefaultPositive)
        surfaceInversePositiveMinor.overrideBy(DarkColorTokens.SurfaceDefaultPositiveMinor)
        surfaceInverseAccentMinor.overrideBy(DarkColorTokens.SurfaceDefaultAccentMinor)
        surfaceInverseTransparentNaviHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentNaviHover)
        surfaceInverseTransparentNaviActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentNaviActive)
        backgroundInversePrimaryBrightness.overrideBy(DarkColorTokens.BackgroundDefaultPrimaryBrightness)
        backgroundInversePrimary.overrideBy(DarkColorTokens.BackgroundDefaultPrimary)
        backgroundInverseSecondary.overrideBy(DarkColorTokens.BackgroundDefaultSecondary)
        overlayInverseSoft.overrideBy(DarkColorTokens.OverlayDefaultSoft)
        overlayInverseHard.overrideBy(DarkColorTokens.OverlayDefaultHard)
        outlineInverseTransparentPrimaryHover.overrideBy(DarkColorTokens.OutlineDefaultTransparentPrimaryHover)
        outlineInverseTransparentPrimaryActive.overrideBy(DarkColorTokens.OutlineDefaultTransparentPrimaryActive)
        outlineInverseClearHover.overrideBy(DarkColorTokens.OutlineDefaultClearHover)
        outlineInverseClearActive.overrideBy(DarkColorTokens.OutlineDefaultClearActive)
        outlineInversePositiveHover.overrideBy(DarkColorTokens.OutlineDefaultPositiveHover)
        outlineInversePositiveActive.overrideBy(DarkColorTokens.OutlineDefaultPositiveActive)
        outlineInverseWarningHover.overrideBy(DarkColorTokens.OutlineDefaultWarningHover)
        outlineInverseWarningActive.overrideBy(DarkColorTokens.OutlineDefaultWarningActive)
        outlineInverseNegativeHover.overrideBy(DarkColorTokens.OutlineDefaultNegativeHover)
        outlineInverseNegativeActive.overrideBy(DarkColorTokens.OutlineDefaultNegativeActive)
        outlineInverseInfoHover.overrideBy(DarkColorTokens.OutlineDefaultInfoHover)
        outlineInverseInfoActive.overrideBy(DarkColorTokens.OutlineDefaultInfoActive)
        outlineInverseSolidDefaultHover.overrideBy(DarkColorTokens.OutlineDefaultSolidDefaultHover)
        outlineInverseSolidDefaultActive.overrideBy(DarkColorTokens.OutlineDefaultSolidDefaultActive)
        outlineInverseTransparentSurfaceHover.overrideBy(DarkColorTokens.OutlineDefaultTransparentSurfaceHover)
        outlineInverseTransparentSurfaceActive.overrideBy(DarkColorTokens.OutlineDefaultTransparentSurfaceActive)
        outlineInverseSolidDefault.overrideBy(DarkColorTokens.OutlineDefaultSolidDefault)
        outlineInverseTransparentPrimary.overrideBy(DarkColorTokens.OutlineDefaultTransparentPrimary)
        outlineInverseClear.overrideBy(DarkColorTokens.OutlineDefaultClear)
        outlineInversePositive.overrideBy(DarkColorTokens.OutlineDefaultPositive)
        outlineInverseWarning.overrideBy(DarkColorTokens.OutlineDefaultWarning)
        outlineInverseNegative.overrideBy(DarkColorTokens.OutlineDefaultNegative)
        outlineInverseInfo.overrideBy(DarkColorTokens.OutlineDefaultInfo)
        dataInverseYellow.overrideBy(DarkColorTokens.DataDefaultYellow)
        dataInverseYellowHover.overrideBy(DarkColorTokens.DataDefaultYellowHover)
        dataInverseYellowActive.overrideBy(DarkColorTokens.DataDefaultYellowActive)
        dataInverseYellowMinor.overrideBy(DarkColorTokens.DataDefaultYellowMinor)
        dataInverseYellowMinorHover.overrideBy(DarkColorTokens.DataDefaultYellowMinorHover)
        dataInverseYellowMinorActive.overrideBy(DarkColorTokens.DataDefaultYellowMinorActive)
        dataInverseYellowTransparent.overrideBy(DarkColorTokens.DataDefaultYellowTransparent)
        dataInverseYellowTransparentHover.overrideBy(DarkColorTokens.DataDefaultYellowTransparentHover)
        dataInverseYellowTransparentActive.overrideBy(DarkColorTokens.DataDefaultYellowTransparentActive)
        textDefaultPrimaryHover.overrideBy(DarkColorTokens.TextInversePrimaryHover)
        textDefaultPrimaryActive.overrideBy(DarkColorTokens.TextInversePrimaryActive)
        textDefaultPrimaryBrightness.overrideBy(DarkColorTokens.TextInversePrimaryBrightness)
        textDefaultSecondaryHover.overrideBy(DarkColorTokens.TextInverseSecondaryHover)
        textDefaultSecondaryActive.overrideBy(DarkColorTokens.TextInverseSecondaryActive)
        textDefaultTertiaryHover.overrideBy(DarkColorTokens.TextInverseTertiaryHover)
        textDefaultTertiaryActive.overrideBy(DarkColorTokens.TextInverseTertiaryActive)
        textDefaultParagraphHover.overrideBy(DarkColorTokens.TextInverseParagraphHover)
        textDefaultParagraphActive.overrideBy(DarkColorTokens.TextInverseParagraphActive)
        textDefaultAccentHover.overrideBy(DarkColorTokens.TextInverseAccentHover)
        textDefaultAccentActive.overrideBy(DarkColorTokens.TextInverseAccentActive)
        textDefaultAccentMinorHover.overrideBy(DarkColorTokens.TextInverseAccentMinorHover)
        textDefaultAccentMinorActive.overrideBy(DarkColorTokens.TextInverseAccentMinorActive)
        textDefaultPositiveHover.overrideBy(DarkColorTokens.TextInversePositiveHover)
        textDefaultPositiveActive.overrideBy(DarkColorTokens.TextInversePositiveActive)
        textDefaultWarningHover.overrideBy(DarkColorTokens.TextInverseWarningHover)
        textDefaultWarningActive.overrideBy(DarkColorTokens.TextInverseWarningActive)
        textDefaultNegativeHover.overrideBy(DarkColorTokens.TextInverseNegativeHover)
        textDefaultNegativeActive.overrideBy(DarkColorTokens.TextInverseNegativeActive)
        textDefaultInfoHover.overrideBy(DarkColorTokens.TextInverseInfoHover)
        textDefaultInfoActive.overrideBy(DarkColorTokens.TextInverseInfoActive)
        textDefaultPositiveMinorHover.overrideBy(DarkColorTokens.TextInversePositiveMinorHover)
        textDefaultPositiveMinorActive.overrideBy(DarkColorTokens.TextInversePositiveMinorActive)
        textDefaultWarningMinorHover.overrideBy(DarkColorTokens.TextInverseWarningMinorHover)
        textDefaultWarningMinorActive.overrideBy(DarkColorTokens.TextInverseWarningMinorActive)
        textDefaultNegativeMinorHover.overrideBy(DarkColorTokens.TextInverseNegativeMinorHover)
        textDefaultNegativeMinorActive.overrideBy(DarkColorTokens.TextInverseNegativeMinorActive)
        textDefaultInfoMinorHover.overrideBy(DarkColorTokens.TextInverseInfoMinorHover)
        textDefaultInfoMinorActive.overrideBy(DarkColorTokens.TextInverseInfoMinorActive)
        textDefaultPositiveMinor.overrideBy(DarkColorTokens.TextInversePositiveMinor)
        textDefaultWarningMinor.overrideBy(DarkColorTokens.TextInverseWarningMinor)
        textDefaultInfoMinor.overrideBy(DarkColorTokens.TextInverseInfoMinor)
        textDefaultNegativeMinor.overrideBy(DarkColorTokens.TextInverseNegativeMinor)
        textDefaultPrimary.overrideBy(DarkColorTokens.TextInversePrimary)
        textDefaultSecondary.overrideBy(DarkColorTokens.TextInverseSecondary)
        textDefaultTertiary.overrideBy(DarkColorTokens.TextInverseTertiary)
        textDefaultParagraph.overrideBy(DarkColorTokens.TextInverseParagraph)
        textDefaultAccent.overrideBy(DarkColorTokens.TextInverseAccent)
        textDefaultAccentMinor.overrideBy(DarkColorTokens.TextInverseAccentMinor)
        textDefaultPositive.overrideBy(DarkColorTokens.TextInversePositive)
        textDefaultNegative.overrideBy(DarkColorTokens.TextInverseNegative)
        textDefaultWarning.overrideBy(DarkColorTokens.TextInverseWarning)
        textDefaultInfo.overrideBy(DarkColorTokens.TextInverseInfo)
        surfaceDefaultSolidPrimaryHover.overrideBy(DarkColorTokens.SurfaceInverseSolidPrimaryHover)
        surfaceDefaultSolidPrimaryActive.overrideBy(DarkColorTokens.SurfaceInverseSolidPrimaryActive)
        surfaceDefaultSolidPrimaryBrightness.overrideBy(DarkColorTokens.SurfaceInverseSolidPrimaryBrightness)
        surfaceDefaultSolidSecondaryHover.overrideBy(DarkColorTokens.SurfaceInverseSolidSecondaryHover)
        surfaceDefaultSolidSecondaryActive.overrideBy(DarkColorTokens.SurfaceInverseSolidSecondaryActive)
        surfaceDefaultSolidTertiaryHover.overrideBy(DarkColorTokens.SurfaceInverseSolidTertiaryHover)
        surfaceDefaultSolidTertiaryActive.overrideBy(DarkColorTokens.SurfaceInverseSolidTertiaryActive)
        surfaceDefaultSolidCardHover.overrideBy(DarkColorTokens.SurfaceInverseSolidCardHover)
        surfaceDefaultSolidCardActive.overrideBy(DarkColorTokens.SurfaceInverseSolidCardActive)
        surfaceDefaultSolidCardBrightness.overrideBy(DarkColorTokens.SurfaceInverseSolidCardBrightness)
        surfaceDefaultSolidDefaultHover.overrideBy(DarkColorTokens.SurfaceInverseSolidDefaultHover)
        surfaceDefaultSolidDefaultActive.overrideBy(DarkColorTokens.SurfaceInverseSolidDefaultActive)
        surfaceDefaultTransparentPrimaryHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentPrimaryHover)
        surfaceDefaultTransparentPrimaryActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentPrimaryActive)
        surfaceDefaultTransparentSecondaryHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentSecondaryHover)
        surfaceDefaultTransparentSecondaryActive.overrideBy(
            DarkColorTokens.SurfaceInverseTransparentSecondaryActive,
        )
        surfaceDefaultTransparentTertiaryHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentTertiaryHover)
        surfaceDefaultTransparentTertiaryActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentTertiaryActive)
        surfaceDefaultTransparentDeepHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentDeepHover)
        surfaceDefaultTransparentDeepActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentDeepActive)
        surfaceDefaultTransparentCardHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentCardHover)
        surfaceDefaultTransparentCardActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentCardActive)
        surfaceDefaultTransparentCardBrightness.overrideBy(DarkColorTokens.SurfaceInverseTransparentCardBrightness)
        surfaceDefaultClearHover.overrideBy(DarkColorTokens.SurfaceInverseClearHover)
        surfaceDefaultClearActive.overrideBy(DarkColorTokens.SurfaceInverseClearActive)
        surfaceDefaultAccentHover.overrideBy(DarkColorTokens.SurfaceInverseAccentHover)
        surfaceDefaultAccentActive.overrideBy(DarkColorTokens.SurfaceInverseAccentActive)
        surfaceDefaultAccentMinorHover.overrideBy(DarkColorTokens.SurfaceInverseAccentMinorHover)
        surfaceDefaultAccentMinorActive.overrideBy(DarkColorTokens.SurfaceInverseAccentMinorActive)
        surfaceDefaultTransparentAccentHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentAccentHover)
        surfaceDefaultTransparentAccentActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentAccentActive)
        surfaceDefaultPositiveHover.overrideBy(DarkColorTokens.SurfaceInversePositiveHover)
        surfaceDefaultPositiveActive.overrideBy(DarkColorTokens.SurfaceInversePositiveActive)
        surfaceDefaultWarningHover.overrideBy(DarkColorTokens.SurfaceInverseWarningHover)
        surfaceDefaultWarningActive.overrideBy(DarkColorTokens.SurfaceInverseWarningActive)
        surfaceDefaultNegativeHover.overrideBy(DarkColorTokens.SurfaceInverseNegativeHover)
        surfaceDefaultNegativeActive.overrideBy(DarkColorTokens.SurfaceInverseNegativeActive)
        surfaceDefaultInfoHover.overrideBy(DarkColorTokens.SurfaceInverseInfoHover)
        surfaceDefaultInfoActive.overrideBy(DarkColorTokens.SurfaceInverseInfoActive)
        surfaceDefaultPositiveMinorHover.overrideBy(DarkColorTokens.SurfaceInversePositiveMinorHover)
        surfaceDefaultPositiveMinorActive.overrideBy(DarkColorTokens.SurfaceInversePositiveMinorActive)
        surfaceDefaultWarningMinorHover.overrideBy(DarkColorTokens.SurfaceInverseWarningMinorHover)
        surfaceDefaultWarningMinorActive.overrideBy(DarkColorTokens.SurfaceInverseWarningMinorActive)
        surfaceDefaultNegativeMinorHover.overrideBy(DarkColorTokens.SurfaceInverseNegativeMinorHover)
        surfaceDefaultNegativeMinorActive.overrideBy(DarkColorTokens.SurfaceInverseNegativeMinorActive)
        surfaceDefaultInfoMinorHover.overrideBy(DarkColorTokens.SurfaceInverseInfoMinorHover)
        surfaceDefaultInfoMinorActive.overrideBy(DarkColorTokens.SurfaceInverseInfoMinorActive)
        surfaceDefaultSolidCard.overrideBy(DarkColorTokens.SurfaceInverseSolidCard)
        surfaceDefaultSolidPrimary.overrideBy(DarkColorTokens.SurfaceInverseSolidPrimary)
        surfaceDefaultSolidSecondary.overrideBy(DarkColorTokens.SurfaceInverseSolidSecondary)
        surfaceDefaultSolidTertiary.overrideBy(DarkColorTokens.SurfaceInverseSolidTertiary)
        surfaceDefaultSolidDefault.overrideBy(DarkColorTokens.SurfaceInverseSolidDefault)
        surfaceDefaultTransparentPrimary.overrideBy(DarkColorTokens.SurfaceInverseTransparentPrimary)
        surfaceDefaultTransparentSecondary.overrideBy(DarkColorTokens.SurfaceInverseTransparentSecondary)
        surfaceDefaultTransparentTertiary.overrideBy(DarkColorTokens.SurfaceInverseTransparentTertiary)
        surfaceDefaultTransparentDeep.overrideBy(DarkColorTokens.SurfaceInverseTransparentDeep)
        surfaceDefaultClear.overrideBy(DarkColorTokens.SurfaceInverseClear)
        surfaceDefaultWarning.overrideBy(DarkColorTokens.SurfaceInverseWarning)
        surfaceDefaultNegative.overrideBy(DarkColorTokens.SurfaceInverseNegative)
        surfaceDefaultInfo.overrideBy(DarkColorTokens.SurfaceInverseInfo)
        surfaceDefaultPositive.overrideBy(DarkColorTokens.SurfaceInversePositive)
        surfaceDefaultPositiveMinor.overrideBy(DarkColorTokens.SurfaceInversePositiveMinor)
        surfaceDefaultWarningMinor.overrideBy(DarkColorTokens.SurfaceInverseWarningMinor)
        surfaceDefaultNegativeMinor.overrideBy(DarkColorTokens.SurfaceInverseNegativeMinor)
        surfaceDefaultInfoMinor.overrideBy(DarkColorTokens.SurfaceInverseInfoMinor)
        surfaceDefaultAccent.overrideBy(DarkColorTokens.SurfaceInverseAccent)
        surfaceDefaultTransparentAccent.overrideBy(DarkColorTokens.SurfaceInverseTransparentAccent)
        surfaceDefaultAccentMinor.overrideBy(DarkColorTokens.SurfaceInverseAccentMinor)
        surfaceDefaultTransparentNaviHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentNaviHover)
        surfaceDefaultTransparentNaviActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentNaviActive)
        backgroundDefaultPrimaryBrightness.overrideBy(DarkColorTokens.BackgroundInversePrimaryBrightness)
        backgroundDefaultPrimary.overrideBy(DarkColorTokens.BackgroundInversePrimary)
        backgroundDefaultSecondary.overrideBy(DarkColorTokens.BackgroundInverseSecondary)
        overlayDefaultHard.overrideBy(DarkColorTokens.OverlayInverseHard)
        overlayDefaultSoft.overrideBy(DarkColorTokens.OverlayInverseSoft)
        outlineDefaultTransparentPrimaryHover.overrideBy(DarkColorTokens.OutlineInverseTransparentPrimaryHover)
        outlineDefaultTransparentPrimaryActive.overrideBy(DarkColorTokens.OutlineInverseTransparentPrimaryActive)
        outlineDefaultClearHover.overrideBy(DarkColorTokens.OutlineInverseClearHover)
        outlineDefaultClearActive.overrideBy(DarkColorTokens.OutlineInverseClearActive)
        outlineDefaultPositiveHover.overrideBy(DarkColorTokens.OutlineInversePositiveHover)
        outlineDefaultPositiveActive.overrideBy(DarkColorTokens.OutlineInversePositiveActive)
        outlineDefaultWarningHover.overrideBy(DarkColorTokens.OutlineInverseWarningHover)
        outlineDefaultWarningActive.overrideBy(DarkColorTokens.OutlineInverseWarningActive)
        outlineDefaultNegativeHover.overrideBy(DarkColorTokens.OutlineInverseNegativeHover)
        outlineDefaultNegativeActive.overrideBy(DarkColorTokens.OutlineInverseNegativeActive)
        outlineDefaultInfoHover.overrideBy(DarkColorTokens.OutlineInverseInfoHover)
        outlineDefaultInfoActive.overrideBy(DarkColorTokens.OutlineInverseInfoActive)
        outlineDefaultSolidDefaultHover.overrideBy(DarkColorTokens.OutlineInverseSolidDefaultHover)
        outlineDefaultSolidDefaultActive.overrideBy(DarkColorTokens.OutlineInverseSolidDefaultActive)
        outlineDefaultClear.overrideBy(DarkColorTokens.OutlineInverseClear)
        outlineDefaultTransparentSurfaceHover.overrideBy(DarkColorTokens.OutlineInverseTransparentSurfaceHover)
        outlineDefaultTransparentSurfaceActive.overrideBy(DarkColorTokens.OutlineInverseTransparentSurfaceActive)
        outlineDefaultSolidDefault.overrideBy(DarkColorTokens.OutlineInverseSolidDefault)
        outlineDefaultTransparentPrimary.overrideBy(DarkColorTokens.OutlineInverseTransparentPrimary)
        outlineDefaultPositive.overrideBy(DarkColorTokens.OutlineInversePositive)
        outlineDefaultWarning.overrideBy(DarkColorTokens.OutlineInverseWarning)
        outlineDefaultNegative.overrideBy(DarkColorTokens.OutlineInverseNegative)
        outlineDefaultInfo.overrideBy(DarkColorTokens.OutlineInverseInfo)
        dataDefaultYellow.overrideBy(DarkColorTokens.DataInverseYellow)
        dataDefaultYellowHover.overrideBy(DarkColorTokens.DataInverseYellowHover)
        dataDefaultYellowActive.overrideBy(DarkColorTokens.DataInverseYellowActive)
        dataDefaultYellowMinor.overrideBy(DarkColorTokens.DataInverseYellowMinor)
        dataDefaultYellowMinorHover.overrideBy(DarkColorTokens.DataInverseYellowMinorHover)
        dataDefaultYellowMinorActive.overrideBy(DarkColorTokens.DataInverseYellowMinorActive)
        dataDefaultYellowTransparent.overrideBy(DarkColorTokens.DataInverseYellowTransparent)
        dataDefaultYellowTransparentHover.overrideBy(DarkColorTokens.DataInverseYellowTransparentHover)
        dataDefaultYellowTransparentActive.overrideBy(DarkColorTokens.DataInverseYellowTransparentActive)
    }
}

private val lightInverseColors: SddsSbComColors by lazy {
    lightSddsSbComColors {
        textInversePrimaryHover.overrideBy(LightColorTokens.TextDefaultPrimaryHover)
        textInversePrimaryActive.overrideBy(LightColorTokens.TextDefaultPrimaryActive)
        textInversePrimaryBrightness.overrideBy(LightColorTokens.TextDefaultPrimaryBrightness)
        textInverseSecondaryHover.overrideBy(LightColorTokens.TextDefaultSecondaryHover)
        textInverseSecondaryActive.overrideBy(LightColorTokens.TextDefaultSecondaryActive)
        textInverseTertiaryHover.overrideBy(LightColorTokens.TextDefaultTertiaryHover)
        textInverseTertiaryActive.overrideBy(LightColorTokens.TextDefaultTertiaryActive)
        textInverseParagraphHover.overrideBy(LightColorTokens.TextDefaultParagraphHover)
        textInverseParagraphActive.overrideBy(LightColorTokens.TextDefaultParagraphActive)
        textInverseAccentHover.overrideBy(LightColorTokens.TextDefaultAccentHover)
        textInverseAccentActive.overrideBy(LightColorTokens.TextDefaultAccentActive)
        textInverseAccentMinorHover.overrideBy(LightColorTokens.TextDefaultAccentMinorHover)
        textInverseAccentMinorActive.overrideBy(LightColorTokens.TextDefaultAccentMinorActive)
        textInversePositiveHover.overrideBy(LightColorTokens.TextDefaultPositiveHover)
        textInversePositiveActive.overrideBy(LightColorTokens.TextDefaultPositiveActive)
        textInverseWarningHover.overrideBy(LightColorTokens.TextDefaultWarningHover)
        textInverseWarningActive.overrideBy(LightColorTokens.TextDefaultWarningActive)
        textInverseNegativeHover.overrideBy(LightColorTokens.TextDefaultNegativeHover)
        textInverseNegativeActive.overrideBy(LightColorTokens.TextDefaultNegativeActive)
        textInverseInfoHover.overrideBy(LightColorTokens.TextDefaultInfoHover)
        textInverseInfoActive.overrideBy(LightColorTokens.TextDefaultInfoActive)
        textInversePositiveMinorHover.overrideBy(LightColorTokens.TextDefaultPositiveMinorHover)
        textInversePositiveMinorActive.overrideBy(LightColorTokens.TextDefaultPositiveMinorActive)
        textInverseWarningMinorHover.overrideBy(LightColorTokens.TextDefaultWarningMinorHover)
        textInverseWarningMinorActive.overrideBy(LightColorTokens.TextDefaultWarningMinorActive)
        textInverseNegativeMinorHover.overrideBy(LightColorTokens.TextDefaultNegativeMinorHover)
        textInverseNegativeMinorActive.overrideBy(LightColorTokens.TextDefaultNegativeMinorActive)
        textInverseInfoMinorHover.overrideBy(LightColorTokens.TextDefaultInfoMinorHover)
        textInverseInfoMinorActive.overrideBy(LightColorTokens.TextDefaultInfoMinorActive)
        textInversePrimary.overrideBy(LightColorTokens.TextDefaultPrimary)
        textInverseSecondary.overrideBy(LightColorTokens.TextDefaultSecondary)
        textInverseTertiary.overrideBy(LightColorTokens.TextDefaultTertiary)
        textInverseParagraph.overrideBy(LightColorTokens.TextDefaultParagraph)
        textInverseAccent.overrideBy(LightColorTokens.TextDefaultAccent)
        textInverseAccentMinor.overrideBy(LightColorTokens.TextDefaultAccentMinor)
        textInversePositive.overrideBy(LightColorTokens.TextDefaultPositive)
        textInverseNegative.overrideBy(LightColorTokens.TextDefaultNegative)
        textInverseWarning.overrideBy(LightColorTokens.TextDefaultWarning)
        textInverseInfo.overrideBy(LightColorTokens.TextDefaultInfo)
        textInverseWarningMinor.overrideBy(LightColorTokens.TextDefaultWarningMinor)
        textInverseNegativeMinor.overrideBy(LightColorTokens.TextDefaultNegativeMinor)
        textInverseInfoMinor.overrideBy(LightColorTokens.TextDefaultInfoMinor)
        textInversePositiveMinor.overrideBy(LightColorTokens.TextDefaultPositiveMinor)
        surfaceInverseSolidPrimaryHover.overrideBy(LightColorTokens.SurfaceDefaultSolidPrimaryHover)
        surfaceInverseSolidPrimaryActive.overrideBy(LightColorTokens.SurfaceDefaultSolidPrimaryActive)
        surfaceInverseSolidPrimaryBrightness.overrideBy(LightColorTokens.SurfaceDefaultSolidPrimaryBrightness)
        surfaceInverseSolidSecondaryHover.overrideBy(LightColorTokens.SurfaceDefaultSolidSecondaryHover)
        surfaceInverseSolidSecondaryActive.overrideBy(LightColorTokens.SurfaceDefaultSolidSecondaryActive)
        surfaceInverseSolidTertiaryHover.overrideBy(LightColorTokens.SurfaceDefaultSolidTertiaryHover)
        surfaceInverseSolidTertiaryActive.overrideBy(LightColorTokens.SurfaceDefaultSolidTertiaryActive)
        surfaceInverseSolidCardHover.overrideBy(LightColorTokens.SurfaceDefaultSolidCardHover)
        surfaceInverseSolidCardActive.overrideBy(LightColorTokens.SurfaceDefaultSolidCardActive)
        surfaceInverseSolidCardBrightness.overrideBy(LightColorTokens.SurfaceDefaultSolidCardBrightness)
        surfaceInverseSolidDefaultHover.overrideBy(LightColorTokens.SurfaceDefaultSolidDefaultHover)
        surfaceInverseSolidDefaultActive.overrideBy(LightColorTokens.SurfaceDefaultSolidDefaultActive)
        surfaceInverseTransparentPrimaryHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentPrimaryHover)
        surfaceInverseTransparentPrimaryActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentPrimaryActive)
        surfaceInverseTransparentSecondaryHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentSecondaryHover)
        surfaceInverseTransparentSecondaryActive.overrideBy(
            LightColorTokens.SurfaceDefaultTransparentSecondaryActive,
        )
        surfaceInverseTransparentTertiaryHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentTertiaryHover)
        surfaceInverseTransparentTertiaryActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentTertiaryActive)
        surfaceInverseTransparentDeepHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentDeepHover)
        surfaceInverseTransparentDeepActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentDeepActive)
        surfaceInverseTransparentCardHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentCardHover)
        surfaceInverseTransparentCardActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentCardActive)
        surfaceInverseTransparentCardBrightness.overrideBy(LightColorTokens.SurfaceDefaultTransparentCardBrightness)
        surfaceInverseClearHover.overrideBy(LightColorTokens.SurfaceDefaultClearHover)
        surfaceInverseClearActive.overrideBy(LightColorTokens.SurfaceDefaultClearActive)
        surfaceInverseAccentHover.overrideBy(LightColorTokens.SurfaceDefaultAccentHover)
        surfaceInverseAccentActive.overrideBy(LightColorTokens.SurfaceDefaultAccentActive)
        surfaceInverseAccentMinorHover.overrideBy(LightColorTokens.SurfaceDefaultAccentMinorHover)
        surfaceInverseAccentMinorActive.overrideBy(LightColorTokens.SurfaceDefaultAccentMinorActive)
        surfaceInverseTransparentAccentHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentAccentHover)
        surfaceInverseTransparentAccentActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentAccentActive)
        surfaceInversePositiveHover.overrideBy(LightColorTokens.SurfaceDefaultPositiveHover)
        surfaceInversePositiveActive.overrideBy(LightColorTokens.SurfaceDefaultPositiveActive)
        surfaceInverseWarningHover.overrideBy(LightColorTokens.SurfaceDefaultWarningHover)
        surfaceInverseWarningActive.overrideBy(LightColorTokens.SurfaceDefaultWarningActive)
        surfaceInverseNegativeHover.overrideBy(LightColorTokens.SurfaceDefaultNegativeHover)
        surfaceInverseNegativeActive.overrideBy(LightColorTokens.SurfaceDefaultNegativeActive)
        surfaceInverseInfoHover.overrideBy(LightColorTokens.SurfaceDefaultInfoHover)
        surfaceInverseInfoActive.overrideBy(LightColorTokens.SurfaceDefaultInfoActive)
        surfaceInversePositiveMinorHover.overrideBy(LightColorTokens.SurfaceDefaultPositiveMinorHover)
        surfaceInversePositiveMinorActive.overrideBy(LightColorTokens.SurfaceDefaultPositiveMinorActive)
        surfaceInverseWarningMinorHover.overrideBy(LightColorTokens.SurfaceDefaultWarningMinorHover)
        surfaceInverseWarningMinorActive.overrideBy(LightColorTokens.SurfaceDefaultWarningMinorActive)
        surfaceInverseNegativeMinorHover.overrideBy(LightColorTokens.SurfaceDefaultNegativeMinorHover)
        surfaceInverseNegativeMinorActive.overrideBy(LightColorTokens.SurfaceDefaultNegativeMinorActive)
        surfaceInverseInfoMinorHover.overrideBy(LightColorTokens.SurfaceDefaultInfoMinorHover)
        surfaceInverseInfoMinorActive.overrideBy(LightColorTokens.SurfaceDefaultInfoMinorActive)
        surfaceInverseTransparentNaviHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentNaviHover)
        surfaceInverseTransparentNaviActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentNaviActive)
        surfaceInverseSolidCard.overrideBy(LightColorTokens.SurfaceDefaultSolidCard)
        surfaceInverseSolidPrimary.overrideBy(LightColorTokens.SurfaceDefaultSolidPrimary)
        surfaceInverseSolidSecondary.overrideBy(LightColorTokens.SurfaceDefaultSolidSecondary)
        surfaceInverseSolidTertiary.overrideBy(LightColorTokens.SurfaceDefaultSolidTertiary)
        surfaceInverseSolidDefault.overrideBy(LightColorTokens.SurfaceDefaultSolidDefault)
        surfaceInverseTransparentPrimary.overrideBy(LightColorTokens.SurfaceDefaultTransparentPrimary)
        surfaceInverseTransparentSecondary.overrideBy(LightColorTokens.SurfaceDefaultTransparentSecondary)
        surfaceInverseTransparentTertiary.overrideBy(LightColorTokens.SurfaceDefaultTransparentTertiary)
        surfaceInverseTransparentDeep.overrideBy(LightColorTokens.SurfaceDefaultTransparentDeep)
        surfaceInverseClear.overrideBy(LightColorTokens.SurfaceDefaultClear)
        surfaceInverseWarning.overrideBy(LightColorTokens.SurfaceDefaultWarning)
        surfaceInverseNegative.overrideBy(LightColorTokens.SurfaceDefaultNegative)
        surfaceInverseTransparentAccent.overrideBy(LightColorTokens.SurfaceDefaultTransparentAccent)
        surfaceInverseInfo.overrideBy(LightColorTokens.SurfaceDefaultInfo)
        surfaceInverseWarningMinor.overrideBy(LightColorTokens.SurfaceDefaultWarningMinor)
        surfaceInverseNegativeMinor.overrideBy(LightColorTokens.SurfaceDefaultNegativeMinor)
        surfaceInverseInfoMinor.overrideBy(LightColorTokens.SurfaceDefaultInfoMinor)
        surfaceInverseAccent.overrideBy(LightColorTokens.SurfaceDefaultAccent)
        surfaceInverseAccentMinor.overrideBy(LightColorTokens.SurfaceDefaultAccentMinor)
        surfaceInversePositive.overrideBy(LightColorTokens.SurfaceDefaultPositive)
        surfaceInversePositiveMinor.overrideBy(LightColorTokens.SurfaceDefaultPositiveMinor)
        backgroundInversePrimaryBrightness.overrideBy(LightColorTokens.BackgroundDefaultPrimaryBrightness)
        backgroundInversePrimary.overrideBy(LightColorTokens.BackgroundDefaultPrimary)
        backgroundInverseSecondary.overrideBy(LightColorTokens.BackgroundDefaultSecondary)
        overlayInverseHard.overrideBy(LightColorTokens.OverlayDefaultHard)
        overlayInverseSoft.overrideBy(LightColorTokens.OverlayDefaultSoft)
        outlineInverseTransparentPrimaryHover.overrideBy(LightColorTokens.OutlineDefaultTransparentPrimaryHover)
        outlineInverseTransparentPrimaryActive.overrideBy(LightColorTokens.OutlineDefaultTransparentPrimaryActive)
        outlineInverseClearHover.overrideBy(LightColorTokens.OutlineDefaultClearHover)
        outlineInverseClearActive.overrideBy(LightColorTokens.OutlineDefaultClearActive)
        outlineInversePositiveHover.overrideBy(LightColorTokens.OutlineDefaultPositiveHover)
        outlineInversePositiveActive.overrideBy(LightColorTokens.OutlineDefaultPositiveActive)
        outlineInverseWarningHover.overrideBy(LightColorTokens.OutlineDefaultWarningHover)
        outlineInverseWarningActive.overrideBy(LightColorTokens.OutlineDefaultWarningActive)
        outlineInverseNegativeHover.overrideBy(LightColorTokens.OutlineDefaultNegativeHover)
        outlineInverseNegativeActive.overrideBy(LightColorTokens.OutlineDefaultNegativeActive)
        outlineInverseInfoHover.overrideBy(LightColorTokens.OutlineDefaultInfoHover)
        outlineInverseInfoActive.overrideBy(LightColorTokens.OutlineDefaultInfoActive)
        outlineInverseSolidDefaultHover.overrideBy(LightColorTokens.OutlineDefaultSolidDefaultHover)
        outlineInverseSolidDefaultActive.overrideBy(LightColorTokens.OutlineDefaultSolidDefaultActive)
        outlineInverseTransparentSurfaceHover.overrideBy(LightColorTokens.OutlineDefaultTransparentSurfaceHover)
        outlineInverseTransparentSurfaceActive.overrideBy(LightColorTokens.OutlineDefaultTransparentSurfaceActive)
        outlineInverseClear.overrideBy(LightColorTokens.OutlineDefaultClear)
        outlineInverseWarning.overrideBy(LightColorTokens.OutlineDefaultWarning)
        outlineInverseNegative.overrideBy(LightColorTokens.OutlineDefaultNegative)
        outlineInverseInfo.overrideBy(LightColorTokens.OutlineDefaultInfo)
        outlineInverseTransparentPrimary.overrideBy(LightColorTokens.OutlineDefaultTransparentPrimary)
        outlineInverseSolidDefault.overrideBy(LightColorTokens.OutlineDefaultSolidDefault)
        outlineInversePositive.overrideBy(LightColorTokens.OutlineDefaultPositive)
        dataInverseYellow.overrideBy(LightColorTokens.DataDefaultYellow)
        dataInverseYellowHover.overrideBy(LightColorTokens.DataDefaultYellowHover)
        dataInverseYellowActive.overrideBy(LightColorTokens.DataDefaultYellowActive)
        dataInverseYellowMinor.overrideBy(LightColorTokens.DataDefaultYellowMinor)
        dataInverseYellowMinorHover.overrideBy(LightColorTokens.DataDefaultYellowMinorHover)
        dataInverseYellowMinorActive.overrideBy(LightColorTokens.DataDefaultYellowMinorActive)
        dataInverseYellowTransparent.overrideBy(LightColorTokens.DataDefaultYellowTransparent)
        dataInverseYellowTransparentHover.overrideBy(LightColorTokens.DataDefaultYellowTransparentHover)
        dataInverseYellowTransparentActive.overrideBy(LightColorTokens.DataDefaultYellowTransparentActive)
        textDefaultPrimaryHover.overrideBy(LightColorTokens.TextInversePrimaryHover)
        textDefaultPrimaryActive.overrideBy(LightColorTokens.TextInversePrimaryActive)
        textDefaultPrimaryBrightness.overrideBy(LightColorTokens.TextInversePrimaryBrightness)
        textDefaultSecondaryHover.overrideBy(LightColorTokens.TextInverseSecondaryHover)
        textDefaultSecondaryActive.overrideBy(LightColorTokens.TextInverseSecondaryActive)
        textDefaultTertiaryHover.overrideBy(LightColorTokens.TextInverseTertiaryHover)
        textDefaultTertiaryActive.overrideBy(LightColorTokens.TextInverseTertiaryActive)
        textDefaultParagraphHover.overrideBy(LightColorTokens.TextInverseParagraphHover)
        textDefaultParagraphActive.overrideBy(LightColorTokens.TextInverseParagraphActive)
        textDefaultAccentHover.overrideBy(LightColorTokens.TextInverseAccentHover)
        textDefaultAccentActive.overrideBy(LightColorTokens.TextInverseAccentActive)
        textDefaultAccentMinorHover.overrideBy(LightColorTokens.TextInverseAccentMinorHover)
        textDefaultAccentMinorActive.overrideBy(LightColorTokens.TextInverseAccentMinorActive)
        textDefaultPositiveHover.overrideBy(LightColorTokens.TextInversePositiveHover)
        textDefaultPositiveActive.overrideBy(LightColorTokens.TextInversePositiveActive)
        textDefaultWarningHover.overrideBy(LightColorTokens.TextInverseWarningHover)
        textDefaultWarningActive.overrideBy(LightColorTokens.TextInverseWarningActive)
        textDefaultNegativeHover.overrideBy(LightColorTokens.TextInverseNegativeHover)
        textDefaultNegativeActive.overrideBy(LightColorTokens.TextInverseNegativeActive)
        textDefaultInfoHover.overrideBy(LightColorTokens.TextInverseInfoHover)
        textDefaultInfoActive.overrideBy(LightColorTokens.TextInverseInfoActive)
        textDefaultPositiveMinorHover.overrideBy(LightColorTokens.TextInversePositiveMinorHover)
        textDefaultPositiveMinorActive.overrideBy(LightColorTokens.TextInversePositiveMinorActive)
        textDefaultWarningMinorHover.overrideBy(LightColorTokens.TextInverseWarningMinorHover)
        textDefaultWarningMinorActive.overrideBy(LightColorTokens.TextInverseWarningMinorActive)
        textDefaultNegativeMinorHover.overrideBy(LightColorTokens.TextInverseNegativeMinorHover)
        textDefaultNegativeMinorActive.overrideBy(LightColorTokens.TextInverseNegativeMinorActive)
        textDefaultInfoMinorHover.overrideBy(LightColorTokens.TextInverseInfoMinorHover)
        textDefaultInfoMinorActive.overrideBy(LightColorTokens.TextInverseInfoMinorActive)
        textDefaultPrimary.overrideBy(LightColorTokens.TextInversePrimary)
        textDefaultSecondary.overrideBy(LightColorTokens.TextInverseSecondary)
        textDefaultTertiary.overrideBy(LightColorTokens.TextInverseTertiary)
        textDefaultParagraph.overrideBy(LightColorTokens.TextInverseParagraph)
        textDefaultAccent.overrideBy(LightColorTokens.TextInverseAccent)
        textDefaultAccentMinor.overrideBy(LightColorTokens.TextInverseAccentMinor)
        textDefaultPositive.overrideBy(LightColorTokens.TextInversePositive)
        textDefaultWarning.overrideBy(LightColorTokens.TextInverseWarning)
        textDefaultNegative.overrideBy(LightColorTokens.TextInverseNegative)
        textDefaultInfo.overrideBy(LightColorTokens.TextInverseInfo)
        textDefaultPositiveMinor.overrideBy(LightColorTokens.TextInversePositiveMinor)
        textDefaultWarningMinor.overrideBy(LightColorTokens.TextInverseWarningMinor)
        textDefaultNegativeMinor.overrideBy(LightColorTokens.TextInverseNegativeMinor)
        textDefaultInfoMinor.overrideBy(LightColorTokens.TextInverseInfoMinor)
        surfaceDefaultSolidPrimaryHover.overrideBy(LightColorTokens.SurfaceInverseSolidPrimaryHover)
        surfaceDefaultSolidPrimaryActive.overrideBy(LightColorTokens.SurfaceInverseSolidPrimaryActive)
        surfaceDefaultSolidPrimaryBrightness.overrideBy(LightColorTokens.SurfaceInverseSolidPrimaryBrightness)
        surfaceDefaultSolidSecondaryHover.overrideBy(LightColorTokens.SurfaceInverseSolidSecondaryHover)
        surfaceDefaultSolidSecondaryActive.overrideBy(LightColorTokens.SurfaceInverseSolidSecondaryActive)
        surfaceDefaultSolidTertiaryHover.overrideBy(LightColorTokens.SurfaceInverseSolidTertiaryHover)
        surfaceDefaultSolidTertiaryActive.overrideBy(LightColorTokens.SurfaceInverseSolidTertiaryActive)
        surfaceDefaultSolidCardHover.overrideBy(LightColorTokens.SurfaceInverseSolidCardHover)
        surfaceDefaultSolidCardActive.overrideBy(LightColorTokens.SurfaceInverseSolidCardActive)
        surfaceDefaultSolidCardBrightness.overrideBy(LightColorTokens.SurfaceInverseSolidCardBrightness)
        surfaceDefaultSolidDefaultHover.overrideBy(LightColorTokens.SurfaceInverseSolidDefaultHover)
        surfaceDefaultSolidDefaultActive.overrideBy(LightColorTokens.SurfaceInverseSolidDefaultActive)
        surfaceDefaultTransparentPrimaryHover.overrideBy(LightColorTokens.SurfaceInverseTransparentPrimaryHover)
        surfaceDefaultTransparentPrimaryActive.overrideBy(LightColorTokens.SurfaceInverseTransparentPrimaryActive)
        surfaceDefaultTransparentSecondaryHover.overrideBy(LightColorTokens.SurfaceInverseTransparentSecondaryHover)
        surfaceDefaultTransparentSecondaryActive.overrideBy(
            LightColorTokens.SurfaceInverseTransparentSecondaryActive,
        )
        surfaceDefaultTransparentTertiaryHover.overrideBy(LightColorTokens.SurfaceInverseTransparentTertiaryHover)
        surfaceDefaultTransparentTertiaryActive.overrideBy(LightColorTokens.SurfaceInverseTransparentTertiaryActive)
        surfaceDefaultTransparentDeepHover.overrideBy(LightColorTokens.SurfaceInverseTransparentDeepHover)
        surfaceDefaultTransparentDeepActive.overrideBy(LightColorTokens.SurfaceInverseTransparentDeepActive)
        surfaceDefaultTransparentCardHover.overrideBy(LightColorTokens.SurfaceInverseTransparentCardHover)
        surfaceDefaultTransparentCardActive.overrideBy(LightColorTokens.SurfaceInverseTransparentCardActive)
        surfaceDefaultTransparentCardBrightness.overrideBy(LightColorTokens.SurfaceInverseTransparentCardBrightness)
        surfaceDefaultClearHover.overrideBy(LightColorTokens.SurfaceInverseClearHover)
        surfaceDefaultClearActive.overrideBy(LightColorTokens.SurfaceInverseClearActive)
        surfaceDefaultAccentHover.overrideBy(LightColorTokens.SurfaceInverseAccentHover)
        surfaceDefaultAccentActive.overrideBy(LightColorTokens.SurfaceInverseAccentActive)
        surfaceDefaultAccentMinorHover.overrideBy(LightColorTokens.SurfaceInverseAccentMinorHover)
        surfaceDefaultAccentMinorActive.overrideBy(LightColorTokens.SurfaceInverseAccentMinorActive)
        surfaceDefaultTransparentAccentHover.overrideBy(LightColorTokens.SurfaceInverseTransparentAccentHover)
        surfaceDefaultTransparentAccentActive.overrideBy(LightColorTokens.SurfaceInverseTransparentAccentActive)
        surfaceDefaultPositiveHover.overrideBy(LightColorTokens.SurfaceInversePositiveHover)
        surfaceDefaultPositiveActive.overrideBy(LightColorTokens.SurfaceInversePositiveActive)
        surfaceDefaultWarningHover.overrideBy(LightColorTokens.SurfaceInverseWarningHover)
        surfaceDefaultWarningActive.overrideBy(LightColorTokens.SurfaceInverseWarningActive)
        surfaceDefaultNegativeHover.overrideBy(LightColorTokens.SurfaceInverseNegativeHover)
        surfaceDefaultNegativeActive.overrideBy(LightColorTokens.SurfaceInverseNegativeActive)
        surfaceDefaultInfoHover.overrideBy(LightColorTokens.SurfaceInverseInfoHover)
        surfaceDefaultInfoActive.overrideBy(LightColorTokens.SurfaceInverseInfoActive)
        surfaceDefaultPositiveMinorHover.overrideBy(LightColorTokens.SurfaceInversePositiveMinorHover)
        surfaceDefaultPositiveMinorActive.overrideBy(LightColorTokens.SurfaceInversePositiveMinorActive)
        surfaceDefaultWarningMinorHover.overrideBy(LightColorTokens.SurfaceInverseWarningMinorHover)
        surfaceDefaultWarningMinorActive.overrideBy(LightColorTokens.SurfaceInverseWarningMinorActive)
        surfaceDefaultNegativeMinorHover.overrideBy(LightColorTokens.SurfaceInverseNegativeMinorHover)
        surfaceDefaultNegativeMinorActive.overrideBy(LightColorTokens.SurfaceInverseNegativeMinorActive)
        surfaceDefaultInfoMinorHover.overrideBy(LightColorTokens.SurfaceInverseInfoMinorHover)
        surfaceDefaultInfoMinorActive.overrideBy(LightColorTokens.SurfaceInverseInfoMinorActive)
        surfaceDefaultTransparentNaviHover.overrideBy(LightColorTokens.SurfaceInverseTransparentNaviHover)
        surfaceDefaultTransparentNaviActive.overrideBy(LightColorTokens.SurfaceInverseTransparentNaviActive)
        surfaceDefaultSolidCard.overrideBy(LightColorTokens.SurfaceInverseSolidCard)
        surfaceDefaultSolidPrimary.overrideBy(LightColorTokens.SurfaceInverseSolidPrimary)
        surfaceDefaultSolidSecondary.overrideBy(LightColorTokens.SurfaceInverseSolidSecondary)
        surfaceDefaultSolidTertiary.overrideBy(LightColorTokens.SurfaceInverseSolidTertiary)
        surfaceDefaultSolidDefault.overrideBy(LightColorTokens.SurfaceInverseSolidDefault)
        surfaceDefaultTransparentPrimary.overrideBy(LightColorTokens.SurfaceInverseTransparentPrimary)
        surfaceDefaultTransparentSecondary.overrideBy(LightColorTokens.SurfaceInverseTransparentSecondary)
        surfaceDefaultTransparentTertiary.overrideBy(LightColorTokens.SurfaceInverseTransparentTertiary)
        surfaceDefaultTransparentDeep.overrideBy(LightColorTokens.SurfaceInverseTransparentDeep)
        surfaceDefaultClear.overrideBy(LightColorTokens.SurfaceInverseClear)
        surfaceDefaultAccent.overrideBy(LightColorTokens.SurfaceInverseAccent)
        surfaceDefaultTransparentAccent.overrideBy(LightColorTokens.SurfaceInverseTransparentAccent)
        surfaceDefaultAccentMinor.overrideBy(LightColorTokens.SurfaceInverseAccentMinor)
        surfaceDefaultPositive.overrideBy(LightColorTokens.SurfaceInversePositive)
        surfaceDefaultWarning.overrideBy(LightColorTokens.SurfaceInverseWarning)
        surfaceDefaultNegative.overrideBy(LightColorTokens.SurfaceInverseNegative)
        surfaceDefaultInfo.overrideBy(LightColorTokens.SurfaceInverseInfo)
        surfaceDefaultWarningMinor.overrideBy(LightColorTokens.SurfaceInverseWarningMinor)
        surfaceDefaultNegativeMinor.overrideBy(LightColorTokens.SurfaceInverseNegativeMinor)
        surfaceDefaultInfoMinor.overrideBy(LightColorTokens.SurfaceInverseInfoMinor)
        surfaceDefaultPositiveMinor.overrideBy(LightColorTokens.SurfaceInversePositiveMinor)
        backgroundDefaultPrimaryBrightness.overrideBy(LightColorTokens.BackgroundInversePrimaryBrightness)
        backgroundDefaultPrimary.overrideBy(LightColorTokens.BackgroundInversePrimary)
        backgroundDefaultSecondary.overrideBy(LightColorTokens.BackgroundInverseSecondary)
        overlayDefaultHard.overrideBy(LightColorTokens.OverlayInverseHard)
        overlayDefaultSoft.overrideBy(LightColorTokens.OverlayInverseSoft)
        outlineDefaultTransparentPrimaryHover.overrideBy(LightColorTokens.OutlineInverseTransparentPrimaryHover)
        outlineDefaultTransparentPrimaryActive.overrideBy(LightColorTokens.OutlineInverseTransparentPrimaryActive)
        outlineDefaultClearHover.overrideBy(LightColorTokens.OutlineInverseClearHover)
        outlineDefaultClearActive.overrideBy(LightColorTokens.OutlineInverseClearActive)
        outlineDefaultPositiveHover.overrideBy(LightColorTokens.OutlineInversePositiveHover)
        outlineDefaultPositiveActive.overrideBy(LightColorTokens.OutlineInversePositiveActive)
        outlineDefaultWarningHover.overrideBy(LightColorTokens.OutlineInverseWarningHover)
        outlineDefaultWarningActive.overrideBy(LightColorTokens.OutlineInverseWarningActive)
        outlineDefaultNegativeHover.overrideBy(LightColorTokens.OutlineInverseNegativeHover)
        outlineDefaultNegativeActive.overrideBy(LightColorTokens.OutlineInverseNegativeActive)
        outlineDefaultInfoHover.overrideBy(LightColorTokens.OutlineInverseInfoHover)
        outlineDefaultInfoActive.overrideBy(LightColorTokens.OutlineInverseInfoActive)
        outlineDefaultSolidDefaultHover.overrideBy(LightColorTokens.OutlineInverseSolidDefaultHover)
        outlineDefaultSolidDefaultActive.overrideBy(LightColorTokens.OutlineInverseSolidDefaultActive)
        outlineDefaultTransparentSurfaceHover.overrideBy(LightColorTokens.OutlineInverseTransparentSurfaceHover)
        outlineDefaultTransparentSurfaceActive.overrideBy(LightColorTokens.OutlineInverseTransparentSurfaceActive)
        outlineDefaultSolidDefault.overrideBy(LightColorTokens.OutlineInverseSolidDefault)
        outlineDefaultTransparentPrimary.overrideBy(LightColorTokens.OutlineInverseTransparentPrimary)
        outlineDefaultPositive.overrideBy(LightColorTokens.OutlineInversePositive)
        outlineDefaultWarning.overrideBy(LightColorTokens.OutlineInverseWarning)
        outlineDefaultNegative.overrideBy(LightColorTokens.OutlineInverseNegative)
        outlineDefaultInfo.overrideBy(LightColorTokens.OutlineInverseInfo)
        outlineDefaultClear.overrideBy(LightColorTokens.OutlineInverseClear)
        dataDefaultYellow.overrideBy(LightColorTokens.DataInverseYellow)
        dataDefaultYellowHover.overrideBy(LightColorTokens.DataInverseYellowHover)
        dataDefaultYellowActive.overrideBy(LightColorTokens.DataInverseYellowActive)
        dataDefaultYellowMinor.overrideBy(LightColorTokens.DataInverseYellowMinor)
        dataDefaultYellowMinorHover.overrideBy(LightColorTokens.DataInverseYellowMinorHover)
        dataDefaultYellowMinorActive.overrideBy(LightColorTokens.DataInverseYellowMinorActive)
        dataDefaultYellowTransparent.overrideBy(LightColorTokens.DataInverseYellowTransparent)
        dataDefaultYellowTransparentHover.overrideBy(LightColorTokens.DataInverseYellowTransparentHover)
        dataDefaultYellowTransparentActive.overrideBy(LightColorTokens.DataInverseYellowTransparentActive)
    }
}

private val darkInverseGradients: SddsSbComGradients by lazy {
    darkSddsSbComGradients {
        textInverseAccentGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextDefaultAccentGradientHover.colors,
                    DarkGradientTokens.TextDefaultAccentGradientHover.positions,
                    DarkGradientTokens.TextDefaultAccentGradientHover.angle,
                ),
            ),
        )
        textInverseAccentGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextDefaultAccentGradientActive.colors,
                    DarkGradientTokens.TextDefaultAccentGradientActive.positions,
                    DarkGradientTokens.TextDefaultAccentGradientActive.angle,
                ),
            ),
        )
        textInverseAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextDefaultAccentGradient.colors,
                    DarkGradientTokens.TextDefaultAccentGradient.positions,
                    DarkGradientTokens.TextDefaultAccentGradient.angle,
                ),
            ),
        )
        textInverseAccentGradientAi.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextDefaultAccentGradientAi.colors,
                    DarkGradientTokens.TextDefaultAccentGradientAi.positions,
                    DarkGradientTokens.TextDefaultAccentGradientAi.angle,
                ),
            ),
        )
        textInverseAccentGradientAiHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextDefaultAccentGradientAiHover.colors,
                    DarkGradientTokens.TextDefaultAccentGradientAiHover.positions,
                    DarkGradientTokens.TextDefaultAccentGradientAiHover.angle,
                ),
            ),
        )
        textInverseAccentGradientAiActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextDefaultAccentGradientAiActive.colors,
                    DarkGradientTokens.TextDefaultAccentGradientAiActive.positions,
                    DarkGradientTokens.TextDefaultAccentGradientAiActive.angle,
                ),
            ),
        )
        surfaceInverseTransparentCard.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultTransparentCard.colors,
                    DarkGradientTokens.SurfaceDefaultTransparentCard.positions,
                    DarkGradientTokens.SurfaceDefaultTransparentCard.angle,
                ),
            ),
        )
        surfaceInverseTransparentNavi.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultTransparentNavi.colors,
                    DarkGradientTokens.SurfaceDefaultTransparentNavi.positions,
                    DarkGradientTokens.SurfaceDefaultTransparentNavi.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultSkeletonGradient.colors,
                    DarkGradientTokens.SurfaceDefaultSkeletonGradient.positions,
                    DarkGradientTokens.SurfaceDefaultSkeletonGradient.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultSkeletonGradientHover.colors,
                    DarkGradientTokens.SurfaceDefaultSkeletonGradientHover.positions,
                    DarkGradientTokens.SurfaceDefaultSkeletonGradientHover.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultSkeletonGradientActive.colors,
                    DarkGradientTokens.SurfaceDefaultSkeletonGradientActive.positions,
                    DarkGradientTokens.SurfaceDefaultSkeletonGradientActive.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultSkeletonDeepGradient.colors,
                    DarkGradientTokens.SurfaceDefaultSkeletonDeepGradient.positions,
                    DarkGradientTokens.SurfaceDefaultSkeletonDeepGradient.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultSkeletonDeepGradientHover.colors,
                    DarkGradientTokens.SurfaceDefaultSkeletonDeepGradientHover.positions,
                    DarkGradientTokens.SurfaceDefaultSkeletonDeepGradientHover.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultSkeletonDeepGradientActive.colors,
                    DarkGradientTokens.SurfaceDefaultSkeletonDeepGradientActive.positions,
                    DarkGradientTokens.SurfaceDefaultSkeletonDeepGradientActive.angle,
                ),
            ),
        )
        backgroundInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.BackgroundDefaultGradient.colors,
                    DarkGradientTokens.BackgroundDefaultGradient.positions,
                    DarkGradientTokens.BackgroundDefaultGradient.angle,
                ),
            ),
        )
        overlayInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OverlayDefaultGradient.colors,
                    DarkGradientTokens.OverlayDefaultGradient.positions,
                    DarkGradientTokens.OverlayDefaultGradient.angle,
                ),
            ),
        )
        outlineInverseTransparentSurface.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OutlineDefaultTransparentSurface.colors,
                    DarkGradientTokens.OutlineDefaultTransparentSurface.positions,
                    DarkGradientTokens.OutlineDefaultTransparentSurface.angle,
                ),
            ),
        )
        textDefaultAccentGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextInverseAccentGradientHover.colors,
                    DarkGradientTokens.TextInverseAccentGradientHover.positions,
                    DarkGradientTokens.TextInverseAccentGradientHover.angle,
                ),
            ),
        )
        textDefaultAccentGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextInverseAccentGradientActive.colors,
                    DarkGradientTokens.TextInverseAccentGradientActive.positions,
                    DarkGradientTokens.TextInverseAccentGradientActive.angle,
                ),
            ),
        )
        textDefaultAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextInverseAccentGradient.colors,
                    DarkGradientTokens.TextInverseAccentGradient.positions,
                    DarkGradientTokens.TextInverseAccentGradient.angle,
                ),
            ),
        )
        textDefaultAccentGradientAiHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextInverseAccentGradientAiHover.colors,
                    DarkGradientTokens.TextInverseAccentGradientAiHover.positions,
                    DarkGradientTokens.TextInverseAccentGradientAiHover.angle,
                ),
            ),
        )
        textDefaultAccentGradientAiActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextInverseAccentGradientAiActive.colors,
                    DarkGradientTokens.TextInverseAccentGradientAiActive.positions,
                    DarkGradientTokens.TextInverseAccentGradientAiActive.angle,
                ),
            ),
        )
        textDefaultAccentGradientAi.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextInverseAccentGradientAi.colors,
                    DarkGradientTokens.TextInverseAccentGradientAi.positions,
                    DarkGradientTokens.TextInverseAccentGradientAi.angle,
                ),
            ),
        )
        surfaceDefaultTransparentCard.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseTransparentCard.colors,
                    DarkGradientTokens.SurfaceInverseTransparentCard.positions,
                    DarkGradientTokens.SurfaceInverseTransparentCard.angle,
                ),
            ),
        )
        surfaceDefaultTransparentNavi.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseTransparentNavi.colors,
                    DarkGradientTokens.SurfaceInverseTransparentNavi.positions,
                    DarkGradientTokens.SurfaceInverseTransparentNavi.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseSkeletonGradient.colors,
                    DarkGradientTokens.SurfaceInverseSkeletonGradient.positions,
                    DarkGradientTokens.SurfaceInverseSkeletonGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseSkeletonGradientHover.colors,
                    DarkGradientTokens.SurfaceInverseSkeletonGradientHover.positions,
                    DarkGradientTokens.SurfaceInverseSkeletonGradientHover.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseSkeletonGradientActive.colors,
                    DarkGradientTokens.SurfaceInverseSkeletonGradientActive.positions,
                    DarkGradientTokens.SurfaceInverseSkeletonGradientActive.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseSkeletonDeepGradient.colors,
                    DarkGradientTokens.SurfaceInverseSkeletonDeepGradient.positions,
                    DarkGradientTokens.SurfaceInverseSkeletonDeepGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseSkeletonDeepGradientHover.colors,
                    DarkGradientTokens.SurfaceInverseSkeletonDeepGradientHover.positions,
                    DarkGradientTokens.SurfaceInverseSkeletonDeepGradientHover.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseSkeletonDeepGradientActive.colors,
                    DarkGradientTokens.SurfaceInverseSkeletonDeepGradientActive.positions,
                    DarkGradientTokens.SurfaceInverseSkeletonDeepGradientActive.angle,
                ),
            ),
        )
        backgroundDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.BackgroundInverseGradient.colors,
                    DarkGradientTokens.BackgroundInverseGradient.positions,
                    DarkGradientTokens.BackgroundInverseGradient.angle,
                ),
            ),
        )
        overlayDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OverlayInverseGradient.colors,
                    DarkGradientTokens.OverlayInverseGradient.positions,
                    DarkGradientTokens.OverlayInverseGradient.angle,
                ),
            ),
        )
        outlineDefaultTransparentSurface.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OutlineInverseTransparentSurface.colors,
                    DarkGradientTokens.OutlineInverseTransparentSurface.positions,
                    DarkGradientTokens.OutlineInverseTransparentSurface.angle,
                ),
            ),
        )
    }
}

private val lightInverseGradients: SddsSbComGradients by lazy {
    lightSddsSbComGradients {
        textInverseAccentGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextDefaultAccentGradientHover.colors,
                    LightGradientTokens.TextDefaultAccentGradientHover.positions,
                    LightGradientTokens.TextDefaultAccentGradientHover.angle,
                ),
            ),
        )
        textInverseAccentGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextDefaultAccentGradientActive.colors,
                    LightGradientTokens.TextDefaultAccentGradientActive.positions,
                    LightGradientTokens.TextDefaultAccentGradientActive.angle,
                ),
            ),
        )
        textInverseAccentGradientAiHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextDefaultAccentGradientAiHover.colors,
                    LightGradientTokens.TextDefaultAccentGradientAiHover.positions,
                    LightGradientTokens.TextDefaultAccentGradientAiHover.angle,
                ),
            ),
        )
        textInverseAccentGradientAiActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextDefaultAccentGradientAiActive.colors,
                    LightGradientTokens.TextDefaultAccentGradientAiActive.positions,
                    LightGradientTokens.TextDefaultAccentGradientAiActive.angle,
                ),
            ),
        )
        textInverseAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextDefaultAccentGradient.colors,
                    LightGradientTokens.TextDefaultAccentGradient.positions,
                    LightGradientTokens.TextDefaultAccentGradient.angle,
                ),
            ),
        )
        textInverseAccentGradientAi.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextDefaultAccentGradientAi.colors,
                    LightGradientTokens.TextDefaultAccentGradientAi.positions,
                    LightGradientTokens.TextDefaultAccentGradientAi.angle,
                ),
            ),
        )
        surfaceInverseTransparentCard.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultTransparentCard.colors,
                    LightGradientTokens.SurfaceDefaultTransparentCard.positions,
                    LightGradientTokens.SurfaceDefaultTransparentCard.angle,
                ),
            ),
        )
        surfaceInverseTransparentNavi.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultTransparentNavi.colors,
                    LightGradientTokens.SurfaceDefaultTransparentNavi.positions,
                    LightGradientTokens.SurfaceDefaultTransparentNavi.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultSkeletonGradient.colors,
                    LightGradientTokens.SurfaceDefaultSkeletonGradient.positions,
                    LightGradientTokens.SurfaceDefaultSkeletonGradient.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultSkeletonGradientHover.colors,
                    LightGradientTokens.SurfaceDefaultSkeletonGradientHover.positions,
                    LightGradientTokens.SurfaceDefaultSkeletonGradientHover.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultSkeletonGradientActive.colors,
                    LightGradientTokens.SurfaceDefaultSkeletonGradientActive.positions,
                    LightGradientTokens.SurfaceDefaultSkeletonGradientActive.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultSkeletonDeepGradient.colors,
                    LightGradientTokens.SurfaceDefaultSkeletonDeepGradient.positions,
                    LightGradientTokens.SurfaceDefaultSkeletonDeepGradient.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultSkeletonDeepGradientHover.colors,
                    LightGradientTokens.SurfaceDefaultSkeletonDeepGradientHover.positions,
                    LightGradientTokens.SurfaceDefaultSkeletonDeepGradientHover.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultSkeletonDeepGradientActive.colors,
                    LightGradientTokens.SurfaceDefaultSkeletonDeepGradientActive.positions,
                    LightGradientTokens.SurfaceDefaultSkeletonDeepGradientActive.angle,
                ),
            ),
        )
        backgroundInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.BackgroundDefaultGradient.colors,
                    LightGradientTokens.BackgroundDefaultGradient.positions,
                    LightGradientTokens.BackgroundDefaultGradient.angle,
                ),
            ),
        )
        overlayInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OverlayDefaultGradient.colors,
                    LightGradientTokens.OverlayDefaultGradient.positions,
                    LightGradientTokens.OverlayDefaultGradient.angle,
                ),
            ),
        )
        outlineInverseTransparentSurface.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OutlineDefaultTransparentSurface.colors,
                    LightGradientTokens.OutlineDefaultTransparentSurface.positions,
                    LightGradientTokens.OutlineDefaultTransparentSurface.angle,
                ),
            ),
        )
        textDefaultAccentGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextInverseAccentGradientHover.colors,
                    LightGradientTokens.TextInverseAccentGradientHover.positions,
                    LightGradientTokens.TextInverseAccentGradientHover.angle,
                ),
            ),
        )
        textDefaultAccentGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextInverseAccentGradientActive.colors,
                    LightGradientTokens.TextInverseAccentGradientActive.positions,
                    LightGradientTokens.TextInverseAccentGradientActive.angle,
                ),
            ),
        )
        textDefaultAccentGradientAiHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextInverseAccentGradientAiHover.colors,
                    LightGradientTokens.TextInverseAccentGradientAiHover.positions,
                    LightGradientTokens.TextInverseAccentGradientAiHover.angle,
                ),
            ),
        )
        textDefaultAccentGradientAiActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextInverseAccentGradientAiActive.colors,
                    LightGradientTokens.TextInverseAccentGradientAiActive.positions,
                    LightGradientTokens.TextInverseAccentGradientAiActive.angle,
                ),
            ),
        )
        textDefaultAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextInverseAccentGradient.colors,
                    LightGradientTokens.TextInverseAccentGradient.positions,
                    LightGradientTokens.TextInverseAccentGradient.angle,
                ),
            ),
        )
        textDefaultAccentGradientAi.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextInverseAccentGradientAi.colors,
                    LightGradientTokens.TextInverseAccentGradientAi.positions,
                    LightGradientTokens.TextInverseAccentGradientAi.angle,
                ),
            ),
        )
        surfaceDefaultTransparentCard.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseTransparentCard.colors,
                    LightGradientTokens.SurfaceInverseTransparentCard.positions,
                    LightGradientTokens.SurfaceInverseTransparentCard.angle,
                ),
            ),
        )
        surfaceDefaultTransparentNavi.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseTransparentNavi.colors,
                    LightGradientTokens.SurfaceInverseTransparentNavi.positions,
                    LightGradientTokens.SurfaceInverseTransparentNavi.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseSkeletonGradient.colors,
                    LightGradientTokens.SurfaceInverseSkeletonGradient.positions,
                    LightGradientTokens.SurfaceInverseSkeletonGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseSkeletonGradientHover.colors,
                    LightGradientTokens.SurfaceInverseSkeletonGradientHover.positions,
                    LightGradientTokens.SurfaceInverseSkeletonGradientHover.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseSkeletonGradientActive.colors,
                    LightGradientTokens.SurfaceInverseSkeletonGradientActive.positions,
                    LightGradientTokens.SurfaceInverseSkeletonGradientActive.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseSkeletonDeepGradient.colors,
                    LightGradientTokens.SurfaceInverseSkeletonDeepGradient.positions,
                    LightGradientTokens.SurfaceInverseSkeletonDeepGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseSkeletonDeepGradientHover.colors,
                    LightGradientTokens.SurfaceInverseSkeletonDeepGradientHover.positions,
                    LightGradientTokens.SurfaceInverseSkeletonDeepGradientHover.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseSkeletonDeepGradientActive.colors,
                    LightGradientTokens.SurfaceInverseSkeletonDeepGradientActive.positions,
                    LightGradientTokens.SurfaceInverseSkeletonDeepGradientActive.angle,
                ),
            ),
        )
        backgroundDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.BackgroundInverseGradient.colors,
                    LightGradientTokens.BackgroundInverseGradient.positions,
                    LightGradientTokens.BackgroundInverseGradient.angle,
                ),
            ),
        )
        overlayDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OverlayInverseGradient.colors,
                    LightGradientTokens.OverlayInverseGradient.positions,
                    LightGradientTokens.OverlayInverseGradient.angle,
                ),
            ),
        )
        outlineDefaultTransparentSurface.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OutlineInverseTransparentSurface.colors,
                    LightGradientTokens.OutlineInverseTransparentSurface.positions,
                    LightGradientTokens.OutlineInverseTransparentSurface.angle,
                ),
            ),
        )
    }
}

/**
 * Подтема SddsSbComTheme.Inverse
 */
@Composable
public fun SddsSbComTheme.Inverse(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable
    () -> Unit,
) {
    val colors = if (isDark) {
        darkInverseColors
    } else {
        lightInverseColors
    }
    val gradients = if (isDark) {
        darkInverseGradients
    } else {
        lightInverseGradients
    }
    SddsSbComTheme(
        colors = colors,
        gradients = gradients,
        content = content,
    )
}
