// AUTO-GENERATED. DO NOT MODIFY this file.
package com.sdds.sbcom.theme.subthemes

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import com.sdds.sbcom.theme.SddsSbComColors
import com.sdds.sbcom.theme.SddsSbComGradients
import com.sdds.sbcom.theme.SddsSbComTheme
import com.sdds.sbcom.theme.darkSddsSbComColors
import com.sdds.sbcom.theme.darkSddsSbComGradients
import com.sdds.sbcom.theme.lightSddsSbComColors
import com.sdds.sbcom.theme.lightSddsSbComGradients
import com.sdds.sbcom.theme.linearGradient
import com.sdds.sbcom.tokens.DarkColorTokens
import com.sdds.sbcom.tokens.DarkGradientTokens
import com.sdds.sbcom.tokens.LightColorTokens
import com.sdds.sbcom.tokens.LightGradientTokens
import kotlin.Boolean
import kotlin.Unit

private val darkOnLightColors: SddsSbComColors by lazy {
    darkSddsSbComColors {
        outlineInverseDefaultActive.overrideBy(DarkColorTokens.OutlineOnDarkDefaultActive)
        personasInverseSeaBlueTextAccentActive.overrideBy(DarkColorTokens.PersonasOnDarkSeaBlueTextAccentActive)
        personasInverseVioletTextAccentActive.overrideBy(DarkColorTokens.PersonasOnDarkVioletTextAccentActive)
        outlineInversePrimaryActive.overrideBy(DarkColorTokens.OutlineOnDarkPrimaryActive)
        surfaceInverseAccentSecondaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkAccentSecondaryHover)
        personasInverseGreenTextAccentHover.overrideBy(DarkColorTokens.PersonasOnDarkGreenTextAccentHover)
        outlineInverseDefault.overrideBy(DarkColorTokens.OutlineOnDarkDefault)
        personasInverseIndigoTextAccent.overrideBy(DarkColorTokens.PersonasOnDarkIndigoTextAccent)
        personasInversePinkTextAccent.overrideBy(DarkColorTokens.PersonasOnDarkPinkTextAccent)
        personasInverseOchreTextAccent.overrideBy(DarkColorTokens.PersonasOnDarkOchreTextAccent)
        surfaceInverseTransparentNavi.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentNavi)
        surfaceInverseSolidPrimaryBrightnessHover.overrideBy(
            DarkColorTokens.SurfaceOnDarkSolidPrimaryBrightnessHover,
        )
        surfaceInverseSolidPrimaryBrightnessActive.overrideBy(
            DarkColorTokens.SurfaceOnDarkSolidPrimaryBrightnessActive,
        )
        surfaceInverseTransparentCardBrightnessHover.overrideBy(
            DarkColorTokens.SurfaceOnDarkTransparentCardBrightnessHover,
        )
        personasInverseGreenTextAccent.overrideBy(DarkColorTokens.PersonasOnDarkGreenTextAccent)
        surfaceInverseSolidTertiary.overrideBy(DarkColorTokens.SurfaceOnDarkSolidTertiary)
        surfaceInverseTransparentCardBrightnessActive.overrideBy(
            DarkColorTokens.SurfaceOnDarkTransparentCardBrightnessActive,
        )
        surfaceInverseAccentMinor.overrideBy(DarkColorTokens.SurfaceOnDarkAccentMinor)
        surfaceInverseSolidCardBrightnessActive.overrideBy(DarkColorTokens.SurfaceOnDarkSolidCardBrightnessActive)
        surfaceInverseAccentSecondaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkAccentSecondaryActive)
        personasInverseIndigoTextAccentActive.overrideBy(DarkColorTokens.PersonasOnDarkIndigoTextAccentActive)
        personasInversePinkTextAccentActive.overrideBy(DarkColorTokens.PersonasOnDarkPinkTextAccentActive)
        personasInverseGreenTextAccentActive.overrideBy(DarkColorTokens.PersonasOnDarkGreenTextAccentActive)
        personasInverseOliveTextAccentHover.overrideBy(DarkColorTokens.PersonasOnDarkOliveTextAccentHover)
        surfaceInverseAccentSecondary.overrideBy(DarkColorTokens.SurfaceOnDarkAccentSecondary)
        personasInverseBlueTextAccentActive.overrideBy(DarkColorTokens.PersonasOnDarkBlueTextAccentActive)
        surfaceInverseTransparentAccentMinorActive.overrideBy(
            DarkColorTokens.SurfaceOnDarkTransparentAccentMinorActive,
        )
        personasInverseIndigoTextAccentHover.overrideBy(DarkColorTokens.PersonasOnDarkIndigoTextAccentHover)
        personasInversePinkTextAccentHover.overrideBy(DarkColorTokens.PersonasOnDarkPinkTextAccentHover)
        personasInverseOchreTextAccentHover.overrideBy(DarkColorTokens.PersonasOnDarkOchreTextAccentHover)
        surfaceInverseTransparentNaviHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentNaviHover)
        outlineInverseDefaultHover.overrideBy(DarkColorTokens.OutlineOnDarkDefaultHover)
        outlineInversePrimaryHover.overrideBy(DarkColorTokens.OutlineOnDarkPrimaryHover)
        personasInverseSeaBlueTextAccentHover.overrideBy(DarkColorTokens.PersonasOnDarkSeaBlueTextAccentHover)
        personasInverseBlueTextAccentHover.overrideBy(DarkColorTokens.PersonasOnDarkBlueTextAccentHover)
        personasInverseVioletTextAccentHover.overrideBy(DarkColorTokens.PersonasOnDarkVioletTextAccentHover)
        surfaceInverseTransparentAccentMinorHover.overrideBy(
            DarkColorTokens.SurfaceOnDarkTransparentAccentMinorHover,
        )
        textInversePrimaryBrightnessHover.overrideBy(DarkColorTokens.TextOnDarkPrimaryBrightnessHover)
        surfaceInverseSolidCardBrightnessHover.overrideBy(DarkColorTokens.SurfaceOnDarkSolidCardBrightnessHover)
        personasInverseBlueTextAccent.overrideBy(DarkColorTokens.PersonasOnDarkBlueTextAccent)
        personasInverseSeaBlueTextAccent.overrideBy(DarkColorTokens.PersonasOnDarkSeaBlueTextAccent)
        personasInverseVioletTextAccent.overrideBy(DarkColorTokens.PersonasOnDarkVioletTextAccent)
        surfaceInverseTransparentAccentMinor.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentAccentMinor)
        outlineInversePrimary.overrideBy(DarkColorTokens.OutlineOnDarkPrimary)
        personasInverseOliveTextAccentActive.overrideBy(DarkColorTokens.PersonasOnDarkOliveTextAccentActive)
        textInversePrimaryBrightnessActive.overrideBy(DarkColorTokens.TextOnDarkPrimaryBrightnessActive)
        personasInverseOchreTextAccentActive.overrideBy(DarkColorTokens.PersonasOnDarkOchreTextAccentActive)
        surfaceInverseTransparentNaviActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentNaviActive)
        personasInverseOliveTextAccent.overrideBy(DarkColorTokens.PersonasOnDarkOliveTextAccent)
        textInversePrimary.overrideBy(DarkColorTokens.TextOnDarkPrimary)
        textInversePrimaryHover.overrideBy(DarkColorTokens.TextOnDarkPrimaryHover)
        textInversePrimaryActive.overrideBy(DarkColorTokens.TextOnDarkPrimaryActive)
        textInversePrimaryBrightness.overrideBy(DarkColorTokens.TextOnDarkPrimaryBrightness)
        textInverseSecondary.overrideBy(DarkColorTokens.TextOnDarkSecondary)
        textInverseSecondaryHover.overrideBy(DarkColorTokens.TextOnDarkSecondaryHover)
        textInverseSecondaryActive.overrideBy(DarkColorTokens.TextOnDarkSecondaryActive)
        textInverseTertiary.overrideBy(DarkColorTokens.TextOnDarkTertiary)
        textInverseTertiaryHover.overrideBy(DarkColorTokens.TextOnDarkTertiaryHover)
        textInverseTertiaryActive.overrideBy(DarkColorTokens.TextOnDarkTertiaryActive)
        textInverseParagraph.overrideBy(DarkColorTokens.TextOnDarkParagraph)
        textInverseParagraphHover.overrideBy(DarkColorTokens.TextOnDarkParagraphHover)
        textInverseParagraphActive.overrideBy(DarkColorTokens.TextOnDarkParagraphActive)
        textInverseAccent.overrideBy(DarkColorTokens.TextOnDarkAccent)
        textInverseAccentHover.overrideBy(DarkColorTokens.TextOnDarkAccentHover)
        textInverseAccentActive.overrideBy(DarkColorTokens.TextOnDarkAccentActive)
        textInverseAccentMinor.overrideBy(DarkColorTokens.TextOnDarkAccentMinor)
        textInverseAccentMinorHover.overrideBy(DarkColorTokens.TextOnDarkAccentMinorHover)
        textInverseAccentMinorActive.overrideBy(DarkColorTokens.TextOnDarkAccentMinorActive)
        textInverseNegativeActive.overrideBy(DarkColorTokens.TextOnDarkNegativeActive)
        textInverseInfo.overrideBy(DarkColorTokens.TextOnDarkInfo)
        textInverseInfoHover.overrideBy(DarkColorTokens.TextOnDarkInfoHover)
        textInverseInfoActive.overrideBy(DarkColorTokens.TextOnDarkInfoActive)
        textInverseWarningActive.overrideBy(DarkColorTokens.TextOnDarkWarningActive)
        textInversePositive.overrideBy(DarkColorTokens.TextOnDarkPositive)
        textInversePositiveHover.overrideBy(DarkColorTokens.TextOnDarkPositiveHover)
        textInverseWarning.overrideBy(DarkColorTokens.TextOnDarkWarning)
        textInverseWarningHover.overrideBy(DarkColorTokens.TextOnDarkWarningHover)
        textInversePositiveActive.overrideBy(DarkColorTokens.TextOnDarkPositiveActive)
        textInverseNegative.overrideBy(DarkColorTokens.TextOnDarkNegative)
        textInverseNegativeHover.overrideBy(DarkColorTokens.TextOnDarkNegativeHover)
        surfaceInverseSolidPrimary.overrideBy(DarkColorTokens.SurfaceOnDarkSolidPrimary)
        surfaceInverseSolidPrimaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkSolidPrimaryHover)
        surfaceInverseSolidPrimaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkSolidPrimaryActive)
        surfaceInverseSolidPrimaryBrightness.overrideBy(DarkColorTokens.SurfaceOnDarkSolidPrimaryBrightness)
        surfaceInverseSolidSecondary.overrideBy(DarkColorTokens.SurfaceOnDarkSolidSecondary)
        surfaceInverseSolidSecondaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkSolidSecondaryHover)
        surfaceInverseSolidSecondaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkSolidSecondaryActive)
        surfaceInverseTransparentSecondaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentSecondaryHover)
        surfaceInverseTransparentSecondaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentSecondaryActive)
        surfaceInverseTransparentTertiary.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentTertiary)
        surfaceInverseTransparentTertiaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentTertiaryHover)
        surfaceInverseTransparentTertiaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentTertiaryActive)
        surfaceInverseTransparentDeep.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentDeep)
        surfaceInverseTransparentDeepHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentDeepHover)
        surfaceInverseTransparentDeepActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentDeepActive)
        surfaceInverseTransparentCard.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentCard)
        surfaceInverseTransparentCardHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentCardHover)
        surfaceInverseTransparentCardActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentCardActive)
        surfaceInverseTransparentCardBrightness.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentCardBrightness)
        surfaceInverseClear.overrideBy(DarkColorTokens.SurfaceOnDarkClear)
        surfaceInverseClearHover.overrideBy(DarkColorTokens.SurfaceOnDarkClearHover)
        surfaceInverseClearActive.overrideBy(DarkColorTokens.SurfaceOnDarkClearActive)
        surfaceInverseAccent.overrideBy(DarkColorTokens.SurfaceOnDarkAccent)
        surfaceInverseSolidTertiaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkSolidTertiaryActive)
        surfaceInverseSolidTertiaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkSolidTertiaryHover)
        surfaceInverseSolidCard.overrideBy(DarkColorTokens.SurfaceOnDarkSolidCard)
        surfaceInverseSolidCardActive.overrideBy(DarkColorTokens.SurfaceOnDarkSolidCardActive)
        surfaceInverseSolidCardHover.overrideBy(DarkColorTokens.SurfaceOnDarkSolidCardHover)
        surfaceInverseSolidDefaultHover.overrideBy(DarkColorTokens.SurfaceOnDarkSolidDefaultHover)
        surfaceInverseSolidDefaultActive.overrideBy(DarkColorTokens.SurfaceOnDarkSolidDefaultActive)
        surfaceInverseSolidCardBrightness.overrideBy(DarkColorTokens.SurfaceOnDarkSolidCardBrightness)
        surfaceInverseSolidDefault.overrideBy(DarkColorTokens.SurfaceOnDarkSolidDefault)
        surfaceInverseTransparentPrimary.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentPrimary)
        surfaceInverseTransparentPrimaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentPrimaryHover)
        surfaceInverseTransparentPrimaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentPrimaryActive)
        surfaceInverseTransparentSecondary.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentSecondary)
        surfaceInversePositive.overrideBy(DarkColorTokens.SurfaceOnDarkPositive)
        surfaceInversePositiveHover.overrideBy(DarkColorTokens.SurfaceOnDarkPositiveHover)
        surfaceInversePositiveActive.overrideBy(DarkColorTokens.SurfaceOnDarkPositiveActive)
        surfaceInverseWarning.overrideBy(DarkColorTokens.SurfaceOnDarkWarning)
        surfaceInverseWarningHover.overrideBy(DarkColorTokens.SurfaceOnDarkWarningHover)
        surfaceInverseWarningActive.overrideBy(DarkColorTokens.SurfaceOnDarkWarningActive)
        surfaceInverseNegative.overrideBy(DarkColorTokens.SurfaceOnDarkNegative)
        surfaceInverseNegativeHover.overrideBy(DarkColorTokens.SurfaceOnDarkNegativeHover)
        surfaceInverseNegativeActive.overrideBy(DarkColorTokens.SurfaceOnDarkNegativeActive)
        surfaceInverseInfo.overrideBy(DarkColorTokens.SurfaceOnDarkInfo)
        surfaceInverseInfoHover.overrideBy(DarkColorTokens.SurfaceOnDarkInfoHover)
        surfaceInverseInfoActive.overrideBy(DarkColorTokens.SurfaceOnDarkInfoActive)
        surfaceInverseAccentMinorActive.overrideBy(DarkColorTokens.SurfaceOnDarkAccentMinorActive)
        surfaceInverseAccentHover.overrideBy(DarkColorTokens.SurfaceOnDarkAccentHover)
        surfaceInverseTransparentAccent.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentAccent)
        surfaceInverseTransparentAccentHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentAccentHover)
        surfaceInverseTransparentAccentActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentAccentActive)
        surfaceInverseAccentActive.overrideBy(DarkColorTokens.SurfaceOnDarkAccentActive)
        surfaceInverseTransparentNegativeActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentNegativeActive)
        surfaceInverseTransparentNegative.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentNegative)
        surfaceInverseReadOnly.overrideBy(DarkColorTokens.SurfaceOnDarkReadOnly)
        surfaceInverseReadOnlyHover.overrideBy(DarkColorTokens.SurfaceOnDarkReadOnlyHover)
        surfaceInverseReadOnlyActive.overrideBy(DarkColorTokens.SurfaceOnDarkReadOnlyActive)
        surfaceInverseTransparentNegativeHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentNegativeHover)
        overlayInverseSoft.overrideBy(DarkColorTokens.OverlayOnDarkSoft)
        overlayInverseHard.overrideBy(DarkColorTokens.OverlayOnDarkHard)
        outlineInverseTransparentPrimary.overrideBy(DarkColorTokens.OutlineOnDarkTransparentPrimary)
        outlineInverseTransparentPrimaryHover.overrideBy(DarkColorTokens.OutlineOnDarkTransparentPrimaryHover)
        outlineInverseTransparentPrimaryActive.overrideBy(DarkColorTokens.OutlineOnDarkTransparentPrimaryActive)
        outlineInverseClear.overrideBy(DarkColorTokens.OutlineOnDarkClear)
        outlineInverseClearHover.overrideBy(DarkColorTokens.OutlineOnDarkClearHover)
        outlineInverseClearActive.overrideBy(DarkColorTokens.OutlineOnDarkClearActive)
        outlineInverseWarningActive.overrideBy(DarkColorTokens.OutlineOnDarkWarningActive)
        outlineInverseNegative.overrideBy(DarkColorTokens.OutlineOnDarkNegative)
        outlineInverseNegativeHover.overrideBy(DarkColorTokens.OutlineOnDarkNegativeHover)
        outlineInverseNegativeActive.overrideBy(DarkColorTokens.OutlineOnDarkNegativeActive)
        outlineInverseInfo.overrideBy(DarkColorTokens.OutlineOnDarkInfo)
        outlineInverseInfoHover.overrideBy(DarkColorTokens.OutlineOnDarkInfoHover)
        outlineInverseInfoActive.overrideBy(DarkColorTokens.OutlineOnDarkInfoActive)
        outlineInversePositiveActive.overrideBy(DarkColorTokens.OutlineOnDarkPositiveActive)
        outlineInversePositive.overrideBy(DarkColorTokens.OutlineOnDarkPositive)
        outlineInversePositiveHover.overrideBy(DarkColorTokens.OutlineOnDarkPositiveHover)
        outlineInverseWarning.overrideBy(DarkColorTokens.OutlineOnDarkWarning)
        outlineInverseWarningHover.overrideBy(DarkColorTokens.OutlineOnDarkWarningHover)
        surfaceInverseAccentMinorHover.overrideBy(DarkColorTokens.SurfaceOnDarkAccentMinorHover)
        personasDefaultGreenTextAccentHover.overrideBy(DarkColorTokens.PersonasOnLightGreenTextAccentHover)
        personasDefaultSeaBlueTextAccentHover.overrideBy(DarkColorTokens.PersonasOnLightSeaBlueTextAccentHover)
        surfaceDefaultTransparentNaviActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentNaviActive)
        outlineDefaultDefaultActive.overrideBy(DarkColorTokens.OutlineOnLightDefaultActive)
        personasDefaultOliveTextAccentActive.overrideBy(DarkColorTokens.PersonasOnLightOliveTextAccentActive)
        surfaceDefaultAccentSecondaryHover.overrideBy(DarkColorTokens.SurfaceOnLightAccentSecondaryHover)
        personasDefaultIndigoTextAccentHover.overrideBy(DarkColorTokens.PersonasOnLightIndigoTextAccentHover)
        personasDefaultOchreTextAccentActive.overrideBy(DarkColorTokens.PersonasOnLightOchreTextAccentActive)
        surfaceDefaultTransparentNavi.overrideBy(DarkColorTokens.SurfaceOnLightTransparentNavi)
        personasDefaultVioletTextAccentActive.overrideBy(DarkColorTokens.PersonasOnLightVioletTextAccentActive)
        personasDefaultBlueTextAccentHover.overrideBy(DarkColorTokens.PersonasOnLightBlueTextAccentHover)
        textDefaultPrimaryBrightnessActive.overrideBy(DarkColorTokens.TextOnLightPrimaryBrightnessActive)
        surfaceDefaultSolidCardBrightnessHover.overrideBy(DarkColorTokens.SurfaceOnLightSolidCardBrightnessHover)
        surfaceDefaultTransparentCardBrightnessHover.overrideBy(
            DarkColorTokens.SurfaceOnLightTransparentCardBrightnessHover,
        )
        surfaceDefaultSolidCardBrightnessActive.overrideBy(DarkColorTokens.SurfaceOnLightSolidCardBrightnessActive)
        surfaceDefaultSolidPrimaryBrightnessHover.overrideBy(
            DarkColorTokens.SurfaceOnLightSolidPrimaryBrightnessHover,
        )
        surfaceDefaultTransparentCardBrightnessActive.overrideBy(
            DarkColorTokens.SurfaceOnLightTransparentCardBrightnessActive,
        )
        personasDefaultOliveTextAccent.overrideBy(DarkColorTokens.PersonasOnLightOliveTextAccent)
        surfaceDefaultSolidTertiaryActive.overrideBy(DarkColorTokens.SurfaceOnLightSolidTertiaryActive)
        textDefaultPrimary.overrideBy(DarkColorTokens.TextOnLightPrimary)
        outlineDefaultPrimary.overrideBy(DarkColorTokens.OutlineOnLightPrimary)
        surfaceDefaultAccentSecondary.overrideBy(DarkColorTokens.SurfaceOnLightAccentSecondary)
        surfaceDefaultAccentMinor.overrideBy(DarkColorTokens.SurfaceOnLightAccentMinor)
        personasDefaultOchreTextAccent.overrideBy(DarkColorTokens.PersonasOnLightOchreTextAccent)
        personasDefaultGreenTextAccentActive.overrideBy(DarkColorTokens.PersonasOnLightGreenTextAccentActive)
        personasDefaultSeaBlueTextAccentActive.overrideBy(DarkColorTokens.PersonasOnLightSeaBlueTextAccentActive)
        outlineDefaultPrimaryActive.overrideBy(DarkColorTokens.OutlineOnLightPrimaryActive)
        personasDefaultIndigoTextAccentActive.overrideBy(DarkColorTokens.PersonasOnLightIndigoTextAccentActive)
        personasDefaultOchreTextAccentHover.overrideBy(DarkColorTokens.PersonasOnLightOchreTextAccentHover)
        textDefaultPrimaryBrightnessHover.overrideBy(DarkColorTokens.TextOnLightPrimaryBrightnessHover)
        surfaceDefaultTransparentNaviHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentNaviHover)
        outlineDefaultDefaultHover.overrideBy(DarkColorTokens.OutlineOnLightDefaultHover)
        outlineDefaultPrimaryHover.overrideBy(DarkColorTokens.OutlineOnLightPrimaryHover)
        personasDefaultOliveTextAccentHover.overrideBy(DarkColorTokens.PersonasOnLightOliveTextAccentHover)
        surfaceDefaultTransparentAccentMinorActive.overrideBy(
            DarkColorTokens.SurfaceOnLightTransparentAccentMinorActive,
        )
        personasDefaultVioletTextAccent.overrideBy(DarkColorTokens.PersonasOnLightVioletTextAccent)
        personasDefaultBlueTextAccent.overrideBy(DarkColorTokens.PersonasOnLightBlueTextAccent)
        personasDefaultSeaBlueTextAccent.overrideBy(DarkColorTokens.PersonasOnLightSeaBlueTextAccent)
        personasDefaultVioletTextAccentHover.overrideBy(DarkColorTokens.PersonasOnLightVioletTextAccentHover)
        surfaceDefaultSolidPrimaryBrightnessActive.overrideBy(
            DarkColorTokens.SurfaceOnLightSolidPrimaryBrightnessActive,
        )
        personasDefaultBlueTextAccentActive.overrideBy(DarkColorTokens.PersonasOnLightBlueTextAccentActive)
        surfaceDefaultAccentSecondaryActive.overrideBy(DarkColorTokens.SurfaceOnLightAccentSecondaryActive)
        surfaceDefaultTransparentAccentMinor.overrideBy(DarkColorTokens.SurfaceOnLightTransparentAccentMinor)
        personasDefaultPinkTextAccent.overrideBy(DarkColorTokens.PersonasOnLightPinkTextAccent)
        personasDefaultGreenTextAccent.overrideBy(DarkColorTokens.PersonasOnLightGreenTextAccent)
        personasDefaultIndigoTextAccent.overrideBy(DarkColorTokens.PersonasOnLightIndigoTextAccent)
        personasDefaultPinkTextAccentHover.overrideBy(DarkColorTokens.PersonasOnLightPinkTextAccentHover)
        surfaceDefaultTransparentAccentMinorHover.overrideBy(
            DarkColorTokens.SurfaceOnLightTransparentAccentMinorHover,
        )
        personasDefaultPinkTextAccentActive.overrideBy(DarkColorTokens.PersonasOnLightPinkTextAccentActive)
        textDefaultParagraphActive.overrideBy(DarkColorTokens.TextOnLightParagraphActive)
        textDefaultAccent.overrideBy(DarkColorTokens.TextOnLightAccent)
        textDefaultAccentHover.overrideBy(DarkColorTokens.TextOnLightAccentHover)
        textDefaultAccentActive.overrideBy(DarkColorTokens.TextOnLightAccentActive)
        textDefaultAccentMinor.overrideBy(DarkColorTokens.TextOnLightAccentMinor)
        textDefaultAccentMinorHover.overrideBy(DarkColorTokens.TextOnLightAccentMinorHover)
        textDefaultAccentMinorActive.overrideBy(DarkColorTokens.TextOnLightAccentMinorActive)
        textDefaultPositive.overrideBy(DarkColorTokens.TextOnLightPositive)
        textDefaultPositiveHover.overrideBy(DarkColorTokens.TextOnLightPositiveHover)
        textDefaultPositiveActive.overrideBy(DarkColorTokens.TextOnLightPositiveActive)
        textDefaultWarning.overrideBy(DarkColorTokens.TextOnLightWarning)
        textDefaultWarningHover.overrideBy(DarkColorTokens.TextOnLightWarningHover)
        textDefaultWarningActive.overrideBy(DarkColorTokens.TextOnLightWarningActive)
        textDefaultNegative.overrideBy(DarkColorTokens.TextOnLightNegative)
        textDefaultNegativeHover.overrideBy(DarkColorTokens.TextOnLightNegativeHover)
        textDefaultNegativeActive.overrideBy(DarkColorTokens.TextOnLightNegativeActive)
        textDefaultInfo.overrideBy(DarkColorTokens.TextOnLightInfo)
        textDefaultInfoHover.overrideBy(DarkColorTokens.TextOnLightInfoHover)
        textDefaultInfoActive.overrideBy(DarkColorTokens.TextOnLightInfoActive)
        textDefaultSecondaryHover.overrideBy(DarkColorTokens.TextOnLightSecondaryHover)
        textDefaultSecondary.overrideBy(DarkColorTokens.TextOnLightSecondary)
        textDefaultPrimaryActive.overrideBy(DarkColorTokens.TextOnLightPrimaryActive)
        textDefaultSecondaryActive.overrideBy(DarkColorTokens.TextOnLightSecondaryActive)
        textDefaultTertiary.overrideBy(DarkColorTokens.TextOnLightTertiary)
        textDefaultTertiaryHover.overrideBy(DarkColorTokens.TextOnLightTertiaryHover)
        textDefaultTertiaryActive.overrideBy(DarkColorTokens.TextOnLightTertiaryActive)
        textDefaultPrimaryBrightness.overrideBy(DarkColorTokens.TextOnLightPrimaryBrightness)
        textDefaultParagraph.overrideBy(DarkColorTokens.TextOnLightParagraph)
        textDefaultParagraphHover.overrideBy(DarkColorTokens.TextOnLightParagraphHover)
        surfaceDefaultSolidPrimary.overrideBy(DarkColorTokens.SurfaceOnLightSolidPrimary)
        surfaceDefaultSolidPrimaryHover.overrideBy(DarkColorTokens.SurfaceOnLightSolidPrimaryHover)
        surfaceDefaultSolidPrimaryActive.overrideBy(DarkColorTokens.SurfaceOnLightSolidPrimaryActive)
        surfaceDefaultSolidPrimaryBrightness.overrideBy(DarkColorTokens.SurfaceOnLightSolidPrimaryBrightness)
        surfaceDefaultSolidSecondary.overrideBy(DarkColorTokens.SurfaceOnLightSolidSecondary)
        surfaceDefaultSolidSecondaryHover.overrideBy(DarkColorTokens.SurfaceOnLightSolidSecondaryHover)
        surfaceDefaultSolidSecondaryActive.overrideBy(DarkColorTokens.SurfaceOnLightSolidSecondaryActive)
        surfaceDefaultSolidTertiary.overrideBy(DarkColorTokens.SurfaceOnLightSolidTertiary)
        surfaceDefaultSolidTertiaryHover.overrideBy(DarkColorTokens.SurfaceOnLightSolidTertiaryHover)
        surfaceDefaultTransparentSecondaryActive.overrideBy(
            DarkColorTokens.SurfaceOnLightTransparentSecondaryActive,
        )
        surfaceDefaultTransparentTertiary.overrideBy(DarkColorTokens.SurfaceOnLightTransparentTertiary)
        surfaceDefaultTransparentTertiaryHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentTertiaryHover)
        surfaceDefaultTransparentTertiaryActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentTertiaryActive)
        surfaceDefaultTransparentDeep.overrideBy(DarkColorTokens.SurfaceOnLightTransparentDeep)
        surfaceDefaultTransparentDeepHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentDeepHover)
        surfaceDefaultTransparentDeepActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentDeepActive)
        surfaceDefaultTransparentCard.overrideBy(DarkColorTokens.SurfaceOnLightTransparentCard)
        surfaceDefaultTransparentCardHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentCardHover)
        surfaceDefaultTransparentCardActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentCardActive)
        surfaceDefaultTransparentCardBrightness.overrideBy(DarkColorTokens.SurfaceOnLightTransparentCardBrightness)
        surfaceDefaultClear.overrideBy(DarkColorTokens.SurfaceOnLightClear)
        surfaceDefaultClearHover.overrideBy(DarkColorTokens.SurfaceOnLightClearHover)
        surfaceDefaultClearActive.overrideBy(DarkColorTokens.SurfaceOnLightClearActive)
        surfaceDefaultAccent.overrideBy(DarkColorTokens.SurfaceOnLightAccent)
        surfaceDefaultAccentHover.overrideBy(DarkColorTokens.SurfaceOnLightAccentHover)
        surfaceDefaultAccentActive.overrideBy(DarkColorTokens.SurfaceOnLightAccentActive)
        surfaceDefaultAccentMinorHover.overrideBy(DarkColorTokens.SurfaceOnLightAccentMinorHover)
        surfaceDefaultAccentMinorActive.overrideBy(DarkColorTokens.SurfaceOnLightAccentMinorActive)
        surfaceDefaultTransparentAccent.overrideBy(DarkColorTokens.SurfaceOnLightTransparentAccent)
        surfaceDefaultTransparentAccentHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentAccentHover)
        surfaceDefaultTransparentAccentActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentAccentActive)
        surfaceDefaultSolidCardActive.overrideBy(DarkColorTokens.SurfaceOnLightSolidCardActive)
        surfaceDefaultSolidCard.overrideBy(DarkColorTokens.SurfaceOnLightSolidCard)
        surfaceDefaultSolidCardBrightness.overrideBy(DarkColorTokens.SurfaceOnLightSolidCardBrightness)
        surfaceDefaultSolidDefault.overrideBy(DarkColorTokens.SurfaceOnLightSolidDefault)
        surfaceDefaultSolidDefaultHover.overrideBy(DarkColorTokens.SurfaceOnLightSolidDefaultHover)
        surfaceDefaultTransparentPrimary.overrideBy(DarkColorTokens.SurfaceOnLightTransparentPrimary)
        surfaceDefaultTransparentPrimaryHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentPrimaryHover)
        surfaceDefaultSolidDefaultActive.overrideBy(DarkColorTokens.SurfaceOnLightSolidDefaultActive)
        surfaceDefaultSolidCardHover.overrideBy(DarkColorTokens.SurfaceOnLightSolidCardHover)
        surfaceDefaultTransparentPrimaryActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentPrimaryActive)
        surfaceDefaultTransparentSecondary.overrideBy(DarkColorTokens.SurfaceOnLightTransparentSecondary)
        surfaceDefaultTransparentSecondaryHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentSecondaryHover)
        surfaceDefaultWarningActive.overrideBy(DarkColorTokens.SurfaceOnLightWarningActive)
        surfaceDefaultNegative.overrideBy(DarkColorTokens.SurfaceOnLightNegative)
        surfaceDefaultNegativeHover.overrideBy(DarkColorTokens.SurfaceOnLightNegativeHover)
        surfaceDefaultNegativeActive.overrideBy(DarkColorTokens.SurfaceOnLightNegativeActive)
        surfaceDefaultInfo.overrideBy(DarkColorTokens.SurfaceOnLightInfo)
        surfaceDefaultInfoHover.overrideBy(DarkColorTokens.SurfaceOnLightInfoHover)
        surfaceDefaultInfoActive.overrideBy(DarkColorTokens.SurfaceOnLightInfoActive)
        surfaceDefaultPositiveActive.overrideBy(DarkColorTokens.SurfaceOnLightPositiveActive)
        surfaceDefaultPositive.overrideBy(DarkColorTokens.SurfaceOnLightPositive)
        surfaceDefaultPositiveHover.overrideBy(DarkColorTokens.SurfaceOnLightPositiveHover)
        surfaceDefaultWarning.overrideBy(DarkColorTokens.SurfaceOnLightWarning)
        surfaceDefaultWarningHover.overrideBy(DarkColorTokens.SurfaceOnLightWarningHover)
        surfaceDefaultTransparentNegative.overrideBy(DarkColorTokens.SurfaceOnLightTransparentNegative)
        surfaceDefaultTransparentNegativeHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentNegativeHover)
        surfaceDefaultReadOnly.overrideBy(DarkColorTokens.SurfaceOnLightReadOnly)
        surfaceDefaultReadOnlyHover.overrideBy(DarkColorTokens.SurfaceOnLightReadOnlyHover)
        surfaceDefaultReadOnlyActive.overrideBy(DarkColorTokens.SurfaceOnLightReadOnlyActive)
        surfaceDefaultTransparentNegativeActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentNegativeActive)
        outlineDefaultTransparentPrimary.overrideBy(DarkColorTokens.OutlineOnLightTransparentPrimary)
        outlineDefaultTransparentPrimaryHover.overrideBy(DarkColorTokens.OutlineOnLightTransparentPrimaryHover)
        outlineDefaultTransparentPrimaryActive.overrideBy(DarkColorTokens.OutlineOnLightTransparentPrimaryActive)
        outlineDefaultClear.overrideBy(DarkColorTokens.OutlineOnLightClear)
        overlayDefaultSoft.overrideBy(DarkColorTokens.OverlayOnLightSoft)
        overlayDefaultHard.overrideBy(DarkColorTokens.OverlayOnLightHard)
        outlineDefaultPositive.overrideBy(DarkColorTokens.OutlineOnLightPositive)
        outlineDefaultPositiveHover.overrideBy(DarkColorTokens.OutlineOnLightPositiveHover)
        outlineDefaultPositiveActive.overrideBy(DarkColorTokens.OutlineOnLightPositiveActive)
        outlineDefaultWarning.overrideBy(DarkColorTokens.OutlineOnLightWarning)
        outlineDefaultWarningHover.overrideBy(DarkColorTokens.OutlineOnLightWarningHover)
        outlineDefaultWarningActive.overrideBy(DarkColorTokens.OutlineOnLightWarningActive)
        outlineDefaultNegative.overrideBy(DarkColorTokens.OutlineOnLightNegative)
        outlineDefaultNegativeHover.overrideBy(DarkColorTokens.OutlineOnLightNegativeHover)
        outlineDefaultNegativeActive.overrideBy(DarkColorTokens.OutlineOnLightNegativeActive)
        outlineDefaultInfo.overrideBy(DarkColorTokens.OutlineOnLightInfo)
        outlineDefaultInfoHover.overrideBy(DarkColorTokens.OutlineOnLightInfoHover)
        outlineDefaultInfoActive.overrideBy(DarkColorTokens.OutlineOnLightInfoActive)
        outlineDefaultClearActive.overrideBy(DarkColorTokens.OutlineOnLightClearActive)
        outlineDefaultClearHover.overrideBy(DarkColorTokens.OutlineOnLightClearHover)
        textDefaultPrimaryHover.overrideBy(DarkColorTokens.TextOnLightPrimaryHover)
    }
}

private val lightOnLightColors: SddsSbComColors by lazy {
    lightSddsSbComColors {
        outlineInverseDefaultActive.overrideBy(LightColorTokens.OutlineOnDarkDefaultActive)
        personasInverseSeaBlueTextAccentActive.overrideBy(LightColorTokens.PersonasOnDarkSeaBlueTextAccentActive)
        personasInverseVioletTextAccentActive.overrideBy(LightColorTokens.PersonasOnDarkVioletTextAccentActive)
        outlineInversePrimaryActive.overrideBy(LightColorTokens.OutlineOnDarkPrimaryActive)
        surfaceInverseAccentSecondaryHover.overrideBy(LightColorTokens.SurfaceOnDarkAccentSecondaryHover)
        personasInverseGreenTextAccentHover.overrideBy(LightColorTokens.PersonasOnDarkGreenTextAccentHover)
        outlineInverseDefault.overrideBy(LightColorTokens.OutlineOnDarkDefault)
        personasInverseIndigoTextAccent.overrideBy(LightColorTokens.PersonasOnDarkIndigoTextAccent)
        personasInversePinkTextAccent.overrideBy(LightColorTokens.PersonasOnDarkPinkTextAccent)
        personasInverseOchreTextAccent.overrideBy(LightColorTokens.PersonasOnDarkOchreTextAccent)
        surfaceInverseTransparentNavi.overrideBy(LightColorTokens.SurfaceOnDarkTransparentNavi)
        surfaceInverseSolidPrimaryBrightnessHover.overrideBy(
            LightColorTokens.SurfaceOnDarkSolidPrimaryBrightnessHover,
        )
        surfaceInverseSolidPrimaryBrightnessActive.overrideBy(
            LightColorTokens.SurfaceOnDarkSolidPrimaryBrightnessActive,
        )
        surfaceInverseTransparentCardBrightnessHover.overrideBy(
            LightColorTokens.SurfaceOnDarkTransparentCardBrightnessHover,
        )
        personasInverseGreenTextAccent.overrideBy(LightColorTokens.PersonasOnDarkGreenTextAccent)
        surfaceInverseSolidTertiary.overrideBy(LightColorTokens.SurfaceOnDarkSolidTertiary)
        surfaceInverseTransparentCardBrightnessActive.overrideBy(
            LightColorTokens.SurfaceOnDarkTransparentCardBrightnessActive,
        )
        surfaceInverseAccentMinor.overrideBy(LightColorTokens.SurfaceOnDarkAccentMinor)
        surfaceInverseSolidCardBrightnessActive.overrideBy(LightColorTokens.SurfaceOnDarkSolidCardBrightnessActive)
        surfaceInverseAccentSecondaryActive.overrideBy(LightColorTokens.SurfaceOnDarkAccentSecondaryActive)
        personasInverseIndigoTextAccentActive.overrideBy(LightColorTokens.PersonasOnDarkIndigoTextAccentActive)
        personasInversePinkTextAccentActive.overrideBy(LightColorTokens.PersonasOnDarkPinkTextAccentActive)
        personasInverseGreenTextAccentActive.overrideBy(LightColorTokens.PersonasOnDarkGreenTextAccentActive)
        personasInverseOliveTextAccentHover.overrideBy(LightColorTokens.PersonasOnDarkOliveTextAccentHover)
        surfaceInverseAccentSecondary.overrideBy(LightColorTokens.SurfaceOnDarkAccentSecondary)
        personasInverseBlueTextAccentActive.overrideBy(LightColorTokens.PersonasOnDarkBlueTextAccentActive)
        surfaceInverseTransparentAccentMinorActive.overrideBy(
            LightColorTokens.SurfaceOnDarkTransparentAccentMinorActive,
        )
        personasInverseIndigoTextAccentHover.overrideBy(LightColorTokens.PersonasOnDarkIndigoTextAccentHover)
        personasInversePinkTextAccentHover.overrideBy(LightColorTokens.PersonasOnDarkPinkTextAccentHover)
        personasInverseOchreTextAccentHover.overrideBy(LightColorTokens.PersonasOnDarkOchreTextAccentHover)
        surfaceInverseTransparentNaviHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentNaviHover)
        outlineInverseDefaultHover.overrideBy(LightColorTokens.OutlineOnDarkDefaultHover)
        outlineInversePrimaryHover.overrideBy(LightColorTokens.OutlineOnDarkPrimaryHover)
        personasInverseSeaBlueTextAccentHover.overrideBy(LightColorTokens.PersonasOnDarkSeaBlueTextAccentHover)
        personasInverseBlueTextAccentHover.overrideBy(LightColorTokens.PersonasOnDarkBlueTextAccentHover)
        personasInverseVioletTextAccentHover.overrideBy(LightColorTokens.PersonasOnDarkVioletTextAccentHover)
        surfaceInverseTransparentAccentMinorHover.overrideBy(
            LightColorTokens.SurfaceOnDarkTransparentAccentMinorHover,
        )
        textInversePrimaryBrightnessHover.overrideBy(LightColorTokens.TextOnDarkPrimaryBrightnessHover)
        surfaceInverseSolidCardBrightnessHover.overrideBy(LightColorTokens.SurfaceOnDarkSolidCardBrightnessHover)
        personasInverseBlueTextAccent.overrideBy(LightColorTokens.PersonasOnDarkBlueTextAccent)
        personasInverseSeaBlueTextAccent.overrideBy(LightColorTokens.PersonasOnDarkSeaBlueTextAccent)
        personasInverseVioletTextAccent.overrideBy(LightColorTokens.PersonasOnDarkVioletTextAccent)
        surfaceInverseTransparentAccentMinor.overrideBy(LightColorTokens.SurfaceOnDarkTransparentAccentMinor)
        outlineInversePrimary.overrideBy(LightColorTokens.OutlineOnDarkPrimary)
        personasInverseOliveTextAccentActive.overrideBy(LightColorTokens.PersonasOnDarkOliveTextAccentActive)
        textInversePrimaryBrightnessActive.overrideBy(LightColorTokens.TextOnDarkPrimaryBrightnessActive)
        personasInverseOchreTextAccentActive.overrideBy(LightColorTokens.PersonasOnDarkOchreTextAccentActive)
        surfaceInverseTransparentNaviActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentNaviActive)
        personasInverseOliveTextAccent.overrideBy(LightColorTokens.PersonasOnDarkOliveTextAccent)
        textInversePrimary.overrideBy(LightColorTokens.TextOnDarkPrimary)
        textInversePrimaryHover.overrideBy(LightColorTokens.TextOnDarkPrimaryHover)
        textInversePrimaryActive.overrideBy(LightColorTokens.TextOnDarkPrimaryActive)
        textInversePrimaryBrightness.overrideBy(LightColorTokens.TextOnDarkPrimaryBrightness)
        textInverseSecondary.overrideBy(LightColorTokens.TextOnDarkSecondary)
        textInverseSecondaryHover.overrideBy(LightColorTokens.TextOnDarkSecondaryHover)
        textInverseSecondaryActive.overrideBy(LightColorTokens.TextOnDarkSecondaryActive)
        textInverseTertiary.overrideBy(LightColorTokens.TextOnDarkTertiary)
        textInverseTertiaryHover.overrideBy(LightColorTokens.TextOnDarkTertiaryHover)
        textInverseTertiaryActive.overrideBy(LightColorTokens.TextOnDarkTertiaryActive)
        textInverseParagraph.overrideBy(LightColorTokens.TextOnDarkParagraph)
        textInverseParagraphHover.overrideBy(LightColorTokens.TextOnDarkParagraphHover)
        textInverseParagraphActive.overrideBy(LightColorTokens.TextOnDarkParagraphActive)
        textInverseAccent.overrideBy(LightColorTokens.TextOnDarkAccent)
        textInverseAccentHover.overrideBy(LightColorTokens.TextOnDarkAccentHover)
        textInverseAccentActive.overrideBy(LightColorTokens.TextOnDarkAccentActive)
        textInverseAccentMinor.overrideBy(LightColorTokens.TextOnDarkAccentMinor)
        textInverseAccentMinorHover.overrideBy(LightColorTokens.TextOnDarkAccentMinorHover)
        textInverseAccentMinorActive.overrideBy(LightColorTokens.TextOnDarkAccentMinorActive)
        textInverseNegativeActive.overrideBy(LightColorTokens.TextOnDarkNegativeActive)
        textInverseInfo.overrideBy(LightColorTokens.TextOnDarkInfo)
        textInverseInfoHover.overrideBy(LightColorTokens.TextOnDarkInfoHover)
        textInverseInfoActive.overrideBy(LightColorTokens.TextOnDarkInfoActive)
        textInverseWarningActive.overrideBy(LightColorTokens.TextOnDarkWarningActive)
        textInversePositive.overrideBy(LightColorTokens.TextOnDarkPositive)
        textInversePositiveHover.overrideBy(LightColorTokens.TextOnDarkPositiveHover)
        textInverseWarning.overrideBy(LightColorTokens.TextOnDarkWarning)
        textInverseWarningHover.overrideBy(LightColorTokens.TextOnDarkWarningHover)
        textInversePositiveActive.overrideBy(LightColorTokens.TextOnDarkPositiveActive)
        textInverseNegative.overrideBy(LightColorTokens.TextOnDarkNegative)
        textInverseNegativeHover.overrideBy(LightColorTokens.TextOnDarkNegativeHover)
        surfaceInverseSolidPrimary.overrideBy(LightColorTokens.SurfaceOnDarkSolidPrimary)
        surfaceInverseSolidPrimaryHover.overrideBy(LightColorTokens.SurfaceOnDarkSolidPrimaryHover)
        surfaceInverseSolidPrimaryActive.overrideBy(LightColorTokens.SurfaceOnDarkSolidPrimaryActive)
        surfaceInverseSolidPrimaryBrightness.overrideBy(LightColorTokens.SurfaceOnDarkSolidPrimaryBrightness)
        surfaceInverseSolidSecondary.overrideBy(LightColorTokens.SurfaceOnDarkSolidSecondary)
        surfaceInverseSolidSecondaryHover.overrideBy(LightColorTokens.SurfaceOnDarkSolidSecondaryHover)
        surfaceInverseSolidSecondaryActive.overrideBy(LightColorTokens.SurfaceOnDarkSolidSecondaryActive)
        surfaceInverseTransparentSecondaryHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentSecondaryHover)
        surfaceInverseTransparentSecondaryActive.overrideBy(
            LightColorTokens.SurfaceOnDarkTransparentSecondaryActive,
        )
        surfaceInverseTransparentTertiary.overrideBy(LightColorTokens.SurfaceOnDarkTransparentTertiary)
        surfaceInverseTransparentTertiaryHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentTertiaryHover)
        surfaceInverseTransparentTertiaryActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentTertiaryActive)
        surfaceInverseTransparentDeep.overrideBy(LightColorTokens.SurfaceOnDarkTransparentDeep)
        surfaceInverseTransparentDeepHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentDeepHover)
        surfaceInverseTransparentDeepActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentDeepActive)
        surfaceInverseTransparentCard.overrideBy(LightColorTokens.SurfaceOnDarkTransparentCard)
        surfaceInverseTransparentCardHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentCardHover)
        surfaceInverseTransparentCardActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentCardActive)
        surfaceInverseTransparentCardBrightness.overrideBy(LightColorTokens.SurfaceOnDarkTransparentCardBrightness)
        surfaceInverseClear.overrideBy(LightColorTokens.SurfaceOnDarkClear)
        surfaceInverseClearHover.overrideBy(LightColorTokens.SurfaceOnDarkClearHover)
        surfaceInverseClearActive.overrideBy(LightColorTokens.SurfaceOnDarkClearActive)
        surfaceInverseAccent.overrideBy(LightColorTokens.SurfaceOnDarkAccent)
        surfaceInverseSolidTertiaryActive.overrideBy(LightColorTokens.SurfaceOnDarkSolidTertiaryActive)
        surfaceInverseSolidTertiaryHover.overrideBy(LightColorTokens.SurfaceOnDarkSolidTertiaryHover)
        surfaceInverseSolidCard.overrideBy(LightColorTokens.SurfaceOnDarkSolidCard)
        surfaceInverseSolidCardActive.overrideBy(LightColorTokens.SurfaceOnDarkSolidCardActive)
        surfaceInverseSolidCardHover.overrideBy(LightColorTokens.SurfaceOnDarkSolidCardHover)
        surfaceInverseSolidDefaultHover.overrideBy(LightColorTokens.SurfaceOnDarkSolidDefaultHover)
        surfaceInverseSolidDefaultActive.overrideBy(LightColorTokens.SurfaceOnDarkSolidDefaultActive)
        surfaceInverseSolidCardBrightness.overrideBy(LightColorTokens.SurfaceOnDarkSolidCardBrightness)
        surfaceInverseSolidDefault.overrideBy(LightColorTokens.SurfaceOnDarkSolidDefault)
        surfaceInverseTransparentPrimary.overrideBy(LightColorTokens.SurfaceOnDarkTransparentPrimary)
        surfaceInverseTransparentPrimaryHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentPrimaryHover)
        surfaceInverseTransparentPrimaryActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentPrimaryActive)
        surfaceInverseTransparentSecondary.overrideBy(LightColorTokens.SurfaceOnDarkTransparentSecondary)
        surfaceInversePositive.overrideBy(LightColorTokens.SurfaceOnDarkPositive)
        surfaceInversePositiveHover.overrideBy(LightColorTokens.SurfaceOnDarkPositiveHover)
        surfaceInversePositiveActive.overrideBy(LightColorTokens.SurfaceOnDarkPositiveActive)
        surfaceInverseWarning.overrideBy(LightColorTokens.SurfaceOnDarkWarning)
        surfaceInverseWarningHover.overrideBy(LightColorTokens.SurfaceOnDarkWarningHover)
        surfaceInverseWarningActive.overrideBy(LightColorTokens.SurfaceOnDarkWarningActive)
        surfaceInverseNegative.overrideBy(LightColorTokens.SurfaceOnDarkNegative)
        surfaceInverseNegativeHover.overrideBy(LightColorTokens.SurfaceOnDarkNegativeHover)
        surfaceInverseNegativeActive.overrideBy(LightColorTokens.SurfaceOnDarkNegativeActive)
        surfaceInverseInfo.overrideBy(LightColorTokens.SurfaceOnDarkInfo)
        surfaceInverseInfoHover.overrideBy(LightColorTokens.SurfaceOnDarkInfoHover)
        surfaceInverseInfoActive.overrideBy(LightColorTokens.SurfaceOnDarkInfoActive)
        surfaceInverseAccentMinorActive.overrideBy(LightColorTokens.SurfaceOnDarkAccentMinorActive)
        surfaceInverseAccentHover.overrideBy(LightColorTokens.SurfaceOnDarkAccentHover)
        surfaceInverseTransparentAccent.overrideBy(LightColorTokens.SurfaceOnDarkTransparentAccent)
        surfaceInverseTransparentAccentHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentAccentHover)
        surfaceInverseTransparentAccentActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentAccentActive)
        surfaceInverseAccentActive.overrideBy(LightColorTokens.SurfaceOnDarkAccentActive)
        surfaceInverseTransparentNegativeActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentNegativeActive)
        surfaceInverseTransparentNegative.overrideBy(LightColorTokens.SurfaceOnDarkTransparentNegative)
        surfaceInverseReadOnly.overrideBy(LightColorTokens.SurfaceOnDarkReadOnly)
        surfaceInverseReadOnlyHover.overrideBy(LightColorTokens.SurfaceOnDarkReadOnlyHover)
        surfaceInverseReadOnlyActive.overrideBy(LightColorTokens.SurfaceOnDarkReadOnlyActive)
        surfaceInverseTransparentNegativeHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentNegativeHover)
        overlayInverseSoft.overrideBy(LightColorTokens.OverlayOnDarkSoft)
        overlayInverseHard.overrideBy(LightColorTokens.OverlayOnDarkHard)
        outlineInverseTransparentPrimary.overrideBy(LightColorTokens.OutlineOnDarkTransparentPrimary)
        outlineInverseTransparentPrimaryHover.overrideBy(LightColorTokens.OutlineOnDarkTransparentPrimaryHover)
        outlineInverseTransparentPrimaryActive.overrideBy(LightColorTokens.OutlineOnDarkTransparentPrimaryActive)
        outlineInverseClear.overrideBy(LightColorTokens.OutlineOnDarkClear)
        outlineInverseClearHover.overrideBy(LightColorTokens.OutlineOnDarkClearHover)
        outlineInverseClearActive.overrideBy(LightColorTokens.OutlineOnDarkClearActive)
        outlineInverseWarningActive.overrideBy(LightColorTokens.OutlineOnDarkWarningActive)
        outlineInverseNegative.overrideBy(LightColorTokens.OutlineOnDarkNegative)
        outlineInverseNegativeHover.overrideBy(LightColorTokens.OutlineOnDarkNegativeHover)
        outlineInverseNegativeActive.overrideBy(LightColorTokens.OutlineOnDarkNegativeActive)
        outlineInverseInfo.overrideBy(LightColorTokens.OutlineOnDarkInfo)
        outlineInverseInfoHover.overrideBy(LightColorTokens.OutlineOnDarkInfoHover)
        outlineInverseInfoActive.overrideBy(LightColorTokens.OutlineOnDarkInfoActive)
        outlineInversePositiveActive.overrideBy(LightColorTokens.OutlineOnDarkPositiveActive)
        outlineInversePositive.overrideBy(LightColorTokens.OutlineOnDarkPositive)
        outlineInversePositiveHover.overrideBy(LightColorTokens.OutlineOnDarkPositiveHover)
        outlineInverseWarning.overrideBy(LightColorTokens.OutlineOnDarkWarning)
        outlineInverseWarningHover.overrideBy(LightColorTokens.OutlineOnDarkWarningHover)
        surfaceInverseAccentMinorHover.overrideBy(LightColorTokens.SurfaceOnDarkAccentMinorHover)
        personasDefaultGreenTextAccentHover.overrideBy(LightColorTokens.PersonasOnLightGreenTextAccentHover)
        personasDefaultSeaBlueTextAccentHover.overrideBy(LightColorTokens.PersonasOnLightSeaBlueTextAccentHover)
        surfaceDefaultTransparentNaviActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentNaviActive)
        outlineDefaultDefaultActive.overrideBy(LightColorTokens.OutlineOnLightDefaultActive)
        personasDefaultOliveTextAccentActive.overrideBy(LightColorTokens.PersonasOnLightOliveTextAccentActive)
        surfaceDefaultAccentSecondaryHover.overrideBy(LightColorTokens.SurfaceOnLightAccentSecondaryHover)
        personasDefaultIndigoTextAccentHover.overrideBy(LightColorTokens.PersonasOnLightIndigoTextAccentHover)
        personasDefaultOchreTextAccentActive.overrideBy(LightColorTokens.PersonasOnLightOchreTextAccentActive)
        surfaceDefaultTransparentNavi.overrideBy(LightColorTokens.SurfaceOnLightTransparentNavi)
        personasDefaultVioletTextAccentActive.overrideBy(LightColorTokens.PersonasOnLightVioletTextAccentActive)
        personasDefaultBlueTextAccentHover.overrideBy(LightColorTokens.PersonasOnLightBlueTextAccentHover)
        textDefaultPrimaryBrightnessActive.overrideBy(LightColorTokens.TextOnLightPrimaryBrightnessActive)
        surfaceDefaultSolidCardBrightnessHover.overrideBy(LightColorTokens.SurfaceOnLightSolidCardBrightnessHover)
        surfaceDefaultTransparentCardBrightnessHover.overrideBy(
            LightColorTokens.SurfaceOnLightTransparentCardBrightnessHover,
        )
        surfaceDefaultSolidCardBrightnessActive.overrideBy(LightColorTokens.SurfaceOnLightSolidCardBrightnessActive)
        surfaceDefaultSolidPrimaryBrightnessHover.overrideBy(
            LightColorTokens.SurfaceOnLightSolidPrimaryBrightnessHover,
        )
        surfaceDefaultTransparentCardBrightnessActive.overrideBy(
            LightColorTokens.SurfaceOnLightTransparentCardBrightnessActive,
        )
        personasDefaultOliveTextAccent.overrideBy(LightColorTokens.PersonasOnLightOliveTextAccent)
        surfaceDefaultSolidTertiaryActive.overrideBy(LightColorTokens.SurfaceOnLightSolidTertiaryActive)
        textDefaultPrimary.overrideBy(LightColorTokens.TextOnLightPrimary)
        outlineDefaultPrimary.overrideBy(LightColorTokens.OutlineOnLightPrimary)
        surfaceDefaultAccentSecondary.overrideBy(LightColorTokens.SurfaceOnLightAccentSecondary)
        surfaceDefaultAccentMinor.overrideBy(LightColorTokens.SurfaceOnLightAccentMinor)
        personasDefaultOchreTextAccent.overrideBy(LightColorTokens.PersonasOnLightOchreTextAccent)
        personasDefaultGreenTextAccentActive.overrideBy(LightColorTokens.PersonasOnLightGreenTextAccentActive)
        personasDefaultSeaBlueTextAccentActive.overrideBy(LightColorTokens.PersonasOnLightSeaBlueTextAccentActive)
        outlineDefaultPrimaryActive.overrideBy(LightColorTokens.OutlineOnLightPrimaryActive)
        personasDefaultIndigoTextAccentActive.overrideBy(LightColorTokens.PersonasOnLightIndigoTextAccentActive)
        personasDefaultOchreTextAccentHover.overrideBy(LightColorTokens.PersonasOnLightOchreTextAccentHover)
        textDefaultPrimaryBrightnessHover.overrideBy(LightColorTokens.TextOnLightPrimaryBrightnessHover)
        surfaceDefaultTransparentNaviHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentNaviHover)
        outlineDefaultDefaultHover.overrideBy(LightColorTokens.OutlineOnLightDefaultHover)
        outlineDefaultPrimaryHover.overrideBy(LightColorTokens.OutlineOnLightPrimaryHover)
        personasDefaultOliveTextAccentHover.overrideBy(LightColorTokens.PersonasOnLightOliveTextAccentHover)
        surfaceDefaultTransparentAccentMinorActive.overrideBy(
            LightColorTokens.SurfaceOnLightTransparentAccentMinorActive,
        )
        personasDefaultVioletTextAccent.overrideBy(LightColorTokens.PersonasOnLightVioletTextAccent)
        personasDefaultBlueTextAccent.overrideBy(LightColorTokens.PersonasOnLightBlueTextAccent)
        personasDefaultSeaBlueTextAccent.overrideBy(LightColorTokens.PersonasOnLightSeaBlueTextAccent)
        personasDefaultVioletTextAccentHover.overrideBy(LightColorTokens.PersonasOnLightVioletTextAccentHover)
        surfaceDefaultSolidPrimaryBrightnessActive.overrideBy(
            LightColorTokens.SurfaceOnLightSolidPrimaryBrightnessActive,
        )
        personasDefaultBlueTextAccentActive.overrideBy(LightColorTokens.PersonasOnLightBlueTextAccentActive)
        surfaceDefaultAccentSecondaryActive.overrideBy(LightColorTokens.SurfaceOnLightAccentSecondaryActive)
        surfaceDefaultTransparentAccentMinor.overrideBy(LightColorTokens.SurfaceOnLightTransparentAccentMinor)
        personasDefaultPinkTextAccent.overrideBy(LightColorTokens.PersonasOnLightPinkTextAccent)
        personasDefaultGreenTextAccent.overrideBy(LightColorTokens.PersonasOnLightGreenTextAccent)
        personasDefaultIndigoTextAccent.overrideBy(LightColorTokens.PersonasOnLightIndigoTextAccent)
        personasDefaultPinkTextAccentHover.overrideBy(LightColorTokens.PersonasOnLightPinkTextAccentHover)
        surfaceDefaultTransparentAccentMinorHover.overrideBy(
            LightColorTokens.SurfaceOnLightTransparentAccentMinorHover,
        )
        personasDefaultPinkTextAccentActive.overrideBy(LightColorTokens.PersonasOnLightPinkTextAccentActive)
        textDefaultParagraphActive.overrideBy(LightColorTokens.TextOnLightParagraphActive)
        textDefaultAccent.overrideBy(LightColorTokens.TextOnLightAccent)
        textDefaultAccentHover.overrideBy(LightColorTokens.TextOnLightAccentHover)
        textDefaultAccentActive.overrideBy(LightColorTokens.TextOnLightAccentActive)
        textDefaultAccentMinor.overrideBy(LightColorTokens.TextOnLightAccentMinor)
        textDefaultAccentMinorHover.overrideBy(LightColorTokens.TextOnLightAccentMinorHover)
        textDefaultAccentMinorActive.overrideBy(LightColorTokens.TextOnLightAccentMinorActive)
        textDefaultPositive.overrideBy(LightColorTokens.TextOnLightPositive)
        textDefaultPositiveHover.overrideBy(LightColorTokens.TextOnLightPositiveHover)
        textDefaultPositiveActive.overrideBy(LightColorTokens.TextOnLightPositiveActive)
        textDefaultWarning.overrideBy(LightColorTokens.TextOnLightWarning)
        textDefaultWarningHover.overrideBy(LightColorTokens.TextOnLightWarningHover)
        textDefaultWarningActive.overrideBy(LightColorTokens.TextOnLightWarningActive)
        textDefaultNegative.overrideBy(LightColorTokens.TextOnLightNegative)
        textDefaultNegativeHover.overrideBy(LightColorTokens.TextOnLightNegativeHover)
        textDefaultNegativeActive.overrideBy(LightColorTokens.TextOnLightNegativeActive)
        textDefaultInfo.overrideBy(LightColorTokens.TextOnLightInfo)
        textDefaultInfoHover.overrideBy(LightColorTokens.TextOnLightInfoHover)
        textDefaultInfoActive.overrideBy(LightColorTokens.TextOnLightInfoActive)
        textDefaultSecondaryHover.overrideBy(LightColorTokens.TextOnLightSecondaryHover)
        textDefaultSecondary.overrideBy(LightColorTokens.TextOnLightSecondary)
        textDefaultPrimaryActive.overrideBy(LightColorTokens.TextOnLightPrimaryActive)
        textDefaultSecondaryActive.overrideBy(LightColorTokens.TextOnLightSecondaryActive)
        textDefaultTertiary.overrideBy(LightColorTokens.TextOnLightTertiary)
        textDefaultTertiaryHover.overrideBy(LightColorTokens.TextOnLightTertiaryHover)
        textDefaultTertiaryActive.overrideBy(LightColorTokens.TextOnLightTertiaryActive)
        textDefaultPrimaryBrightness.overrideBy(LightColorTokens.TextOnLightPrimaryBrightness)
        textDefaultParagraph.overrideBy(LightColorTokens.TextOnLightParagraph)
        textDefaultParagraphHover.overrideBy(LightColorTokens.TextOnLightParagraphHover)
        surfaceDefaultSolidPrimary.overrideBy(LightColorTokens.SurfaceOnLightSolidPrimary)
        surfaceDefaultSolidPrimaryHover.overrideBy(LightColorTokens.SurfaceOnLightSolidPrimaryHover)
        surfaceDefaultSolidPrimaryActive.overrideBy(LightColorTokens.SurfaceOnLightSolidPrimaryActive)
        surfaceDefaultSolidPrimaryBrightness.overrideBy(LightColorTokens.SurfaceOnLightSolidPrimaryBrightness)
        surfaceDefaultSolidSecondary.overrideBy(LightColorTokens.SurfaceOnLightSolidSecondary)
        surfaceDefaultSolidSecondaryHover.overrideBy(LightColorTokens.SurfaceOnLightSolidSecondaryHover)
        surfaceDefaultSolidSecondaryActive.overrideBy(LightColorTokens.SurfaceOnLightSolidSecondaryActive)
        surfaceDefaultSolidTertiary.overrideBy(LightColorTokens.SurfaceOnLightSolidTertiary)
        surfaceDefaultSolidTertiaryHover.overrideBy(LightColorTokens.SurfaceOnLightSolidTertiaryHover)
        surfaceDefaultTransparentSecondaryActive.overrideBy(
            LightColorTokens.SurfaceOnLightTransparentSecondaryActive,
        )
        surfaceDefaultTransparentTertiary.overrideBy(LightColorTokens.SurfaceOnLightTransparentTertiary)
        surfaceDefaultTransparentTertiaryHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentTertiaryHover)
        surfaceDefaultTransparentTertiaryActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentTertiaryActive)
        surfaceDefaultTransparentDeep.overrideBy(LightColorTokens.SurfaceOnLightTransparentDeep)
        surfaceDefaultTransparentDeepHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentDeepHover)
        surfaceDefaultTransparentDeepActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentDeepActive)
        surfaceDefaultTransparentCard.overrideBy(LightColorTokens.SurfaceOnLightTransparentCard)
        surfaceDefaultTransparentCardHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentCardHover)
        surfaceDefaultTransparentCardActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentCardActive)
        surfaceDefaultTransparentCardBrightness.overrideBy(LightColorTokens.SurfaceOnLightTransparentCardBrightness)
        surfaceDefaultClear.overrideBy(LightColorTokens.SurfaceOnLightClear)
        surfaceDefaultClearHover.overrideBy(LightColorTokens.SurfaceOnLightClearHover)
        surfaceDefaultClearActive.overrideBy(LightColorTokens.SurfaceOnLightClearActive)
        surfaceDefaultAccent.overrideBy(LightColorTokens.SurfaceOnLightAccent)
        surfaceDefaultAccentHover.overrideBy(LightColorTokens.SurfaceOnLightAccentHover)
        surfaceDefaultAccentActive.overrideBy(LightColorTokens.SurfaceOnLightAccentActive)
        surfaceDefaultAccentMinorHover.overrideBy(LightColorTokens.SurfaceOnLightAccentMinorHover)
        surfaceDefaultAccentMinorActive.overrideBy(LightColorTokens.SurfaceOnLightAccentMinorActive)
        surfaceDefaultTransparentAccent.overrideBy(LightColorTokens.SurfaceOnLightTransparentAccent)
        surfaceDefaultTransparentAccentHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentAccentHover)
        surfaceDefaultTransparentAccentActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentAccentActive)
        surfaceDefaultSolidCardActive.overrideBy(LightColorTokens.SurfaceOnLightSolidCardActive)
        surfaceDefaultSolidCard.overrideBy(LightColorTokens.SurfaceOnLightSolidCard)
        surfaceDefaultSolidCardBrightness.overrideBy(LightColorTokens.SurfaceOnLightSolidCardBrightness)
        surfaceDefaultSolidDefault.overrideBy(LightColorTokens.SurfaceOnLightSolidDefault)
        surfaceDefaultSolidDefaultHover.overrideBy(LightColorTokens.SurfaceOnLightSolidDefaultHover)
        surfaceDefaultTransparentPrimary.overrideBy(LightColorTokens.SurfaceOnLightTransparentPrimary)
        surfaceDefaultTransparentPrimaryHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentPrimaryHover)
        surfaceDefaultSolidDefaultActive.overrideBy(LightColorTokens.SurfaceOnLightSolidDefaultActive)
        surfaceDefaultSolidCardHover.overrideBy(LightColorTokens.SurfaceOnLightSolidCardHover)
        surfaceDefaultTransparentPrimaryActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentPrimaryActive)
        surfaceDefaultTransparentSecondary.overrideBy(LightColorTokens.SurfaceOnLightTransparentSecondary)
        surfaceDefaultTransparentSecondaryHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentSecondaryHover)
        surfaceDefaultWarningActive.overrideBy(LightColorTokens.SurfaceOnLightWarningActive)
        surfaceDefaultNegative.overrideBy(LightColorTokens.SurfaceOnLightNegative)
        surfaceDefaultNegativeHover.overrideBy(LightColorTokens.SurfaceOnLightNegativeHover)
        surfaceDefaultNegativeActive.overrideBy(LightColorTokens.SurfaceOnLightNegativeActive)
        surfaceDefaultInfo.overrideBy(LightColorTokens.SurfaceOnLightInfo)
        surfaceDefaultInfoHover.overrideBy(LightColorTokens.SurfaceOnLightInfoHover)
        surfaceDefaultInfoActive.overrideBy(LightColorTokens.SurfaceOnLightInfoActive)
        surfaceDefaultPositiveActive.overrideBy(LightColorTokens.SurfaceOnLightPositiveActive)
        surfaceDefaultPositive.overrideBy(LightColorTokens.SurfaceOnLightPositive)
        surfaceDefaultPositiveHover.overrideBy(LightColorTokens.SurfaceOnLightPositiveHover)
        surfaceDefaultWarning.overrideBy(LightColorTokens.SurfaceOnLightWarning)
        surfaceDefaultWarningHover.overrideBy(LightColorTokens.SurfaceOnLightWarningHover)
        surfaceDefaultTransparentNegative.overrideBy(LightColorTokens.SurfaceOnLightTransparentNegative)
        surfaceDefaultTransparentNegativeHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentNegativeHover)
        surfaceDefaultReadOnly.overrideBy(LightColorTokens.SurfaceOnLightReadOnly)
        surfaceDefaultReadOnlyHover.overrideBy(LightColorTokens.SurfaceOnLightReadOnlyHover)
        surfaceDefaultReadOnlyActive.overrideBy(LightColorTokens.SurfaceOnLightReadOnlyActive)
        surfaceDefaultTransparentNegativeActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentNegativeActive)
        outlineDefaultTransparentPrimary.overrideBy(LightColorTokens.OutlineOnLightTransparentPrimary)
        outlineDefaultTransparentPrimaryHover.overrideBy(LightColorTokens.OutlineOnLightTransparentPrimaryHover)
        outlineDefaultTransparentPrimaryActive.overrideBy(LightColorTokens.OutlineOnLightTransparentPrimaryActive)
        outlineDefaultClear.overrideBy(LightColorTokens.OutlineOnLightClear)
        overlayDefaultSoft.overrideBy(LightColorTokens.OverlayOnLightSoft)
        overlayDefaultHard.overrideBy(LightColorTokens.OverlayOnLightHard)
        outlineDefaultPositive.overrideBy(LightColorTokens.OutlineOnLightPositive)
        outlineDefaultPositiveHover.overrideBy(LightColorTokens.OutlineOnLightPositiveHover)
        outlineDefaultPositiveActive.overrideBy(LightColorTokens.OutlineOnLightPositiveActive)
        outlineDefaultWarning.overrideBy(LightColorTokens.OutlineOnLightWarning)
        outlineDefaultWarningHover.overrideBy(LightColorTokens.OutlineOnLightWarningHover)
        outlineDefaultWarningActive.overrideBy(LightColorTokens.OutlineOnLightWarningActive)
        outlineDefaultNegative.overrideBy(LightColorTokens.OutlineOnLightNegative)
        outlineDefaultNegativeHover.overrideBy(LightColorTokens.OutlineOnLightNegativeHover)
        outlineDefaultNegativeActive.overrideBy(LightColorTokens.OutlineOnLightNegativeActive)
        outlineDefaultInfo.overrideBy(LightColorTokens.OutlineOnLightInfo)
        outlineDefaultInfoHover.overrideBy(LightColorTokens.OutlineOnLightInfoHover)
        outlineDefaultInfoActive.overrideBy(LightColorTokens.OutlineOnLightInfoActive)
        outlineDefaultClearActive.overrideBy(LightColorTokens.OutlineOnLightClearActive)
        outlineDefaultClearHover.overrideBy(LightColorTokens.OutlineOnLightClearHover)
        textDefaultPrimaryHover.overrideBy(LightColorTokens.TextOnLightPrimaryHover)
    }
}

private val darkOnLightGradients: SddsSbComGradients by lazy {
    darkSddsSbComGradients {
        personasInverseIndigoSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnDarkIndigoSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnDarkIndigoSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnDarkIndigoSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseSeaBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnDarkSeaBlueSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnDarkSeaBlueSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnDarkSeaBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        textInverseAccentGradientAI.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnDarkAccentGradientAI.colors,
                    DarkGradientTokens.TextOnDarkAccentGradientAI.positions,
                    DarkGradientTokens.TextOnDarkAccentGradientAI.angle,
                ),
            ),
        )
        personasInversePinkSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnDarkPinkSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnDarkPinkSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnDarkPinkSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseOchreSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnDarkOchreSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnDarkOchreSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnDarkOchreSurfaceAccentGradient.angle,
                ),
            ),
        )
        overlayInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OverlayOnDarkGradient.colors,
                    DarkGradientTokens.OverlayOnDarkGradient.positions,
                    DarkGradientTokens.OverlayOnDarkGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentGradientSecondary.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkAccentGradientSecondary.colors,
                    DarkGradientTokens.SurfaceOnDarkAccentGradientSecondary.positions,
                    DarkGradientTokens.SurfaceOnDarkAccentGradientSecondary.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradient.colors,
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradient.positions,
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradient.angle,
                ),
            ),
        )
        personasInverseGreenSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnDarkGreenSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnDarkGreenSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnDarkGreenSurfaceAccentGradient.angle,
                ),
            ),
        )
        outlineInverseWhiteGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OutlineOnDarkWhiteGradient.colors,
                    DarkGradientTokens.OutlineOnDarkWhiteGradient.positions,
                    DarkGradientTokens.OutlineOnDarkWhiteGradient.angle,
                ),
            ),
        )
        personasInverseBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnDarkBlueSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnDarkBlueSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnDarkBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseOliveSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnDarkOliveSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnDarkOliveSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnDarkOliveSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseVioletSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnDarkVioletSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnDarkVioletSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnDarkVioletSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkAccentGradient.colors,
                    DarkGradientTokens.SurfaceOnDarkAccentGradient.positions,
                    DarkGradientTokens.SurfaceOnDarkAccentGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentMinorGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkAccentMinorGradient.colors,
                    DarkGradientTokens.SurfaceOnDarkAccentMinorGradient.positions,
                    DarkGradientTokens.SurfaceOnDarkAccentMinorGradient.angle,
                ),
            ),
        )
        outlineDefaultWhiteGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OutlineOnLightWhiteGradient.colors,
                    DarkGradientTokens.OutlineOnLightWhiteGradient.positions,
                    DarkGradientTokens.OutlineOnLightWhiteGradient.angle,
                ),
            ),
        )
        personasDefaultGreenSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnLightGreenSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnLightGreenSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnLightGreenSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultSeaBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnLightSeaBlueSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnLightSeaBlueSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnLightSeaBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultPinkSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnLightPinkSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnLightPinkSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnLightPinkSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightSkeletonGradient.colors,
                    DarkGradientTokens.SurfaceOnLightSkeletonGradient.positions,
                    DarkGradientTokens.SurfaceOnLightSkeletonGradient.angle,
                ),
            ),
        )
        overlayDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OverlayOnLightGradient.colors,
                    DarkGradientTokens.OverlayOnLightGradient.positions,
                    DarkGradientTokens.OverlayOnLightGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentGradientSecondary.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightAccentGradientSecondary.colors,
                    DarkGradientTokens.SurfaceOnLightAccentGradientSecondary.positions,
                    DarkGradientTokens.SurfaceOnLightAccentGradientSecondary.angle,
                ),
            ),
        )
        personasDefaultOchreSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnLightOchreSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnLightOchreSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnLightOchreSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultVioletSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnLightVioletSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnLightVioletSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnLightVioletSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultOliveSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnLightOliveSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnLightOliveSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnLightOliveSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultIndigoSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnLightIndigoSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnLightIndigoSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnLightIndigoSurfaceAccentGradient.angle,
                ),
            ),
        )
        textDefaultAccentGradientAI.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnLightAccentGradientAI.colors,
                    DarkGradientTokens.TextOnLightAccentGradientAI.positions,
                    DarkGradientTokens.TextOnLightAccentGradientAI.angle,
                ),
            ),
        )
        personasDefaultBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasOnLightBlueSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasOnLightBlueSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasOnLightBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightAccentGradient.colors,
                    DarkGradientTokens.SurfaceOnLightAccentGradient.positions,
                    DarkGradientTokens.SurfaceOnLightAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentMinorGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightAccentMinorGradient.colors,
                    DarkGradientTokens.SurfaceOnLightAccentMinorGradient.positions,
                    DarkGradientTokens.SurfaceOnLightAccentMinorGradient.angle,
                ),
            ),
        )
    }
}

private val lightOnLightGradients: SddsSbComGradients by lazy {
    lightSddsSbComGradients {
        personasInverseIndigoSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnDarkIndigoSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnDarkIndigoSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnDarkIndigoSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseSeaBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnDarkSeaBlueSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnDarkSeaBlueSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnDarkSeaBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        textInverseAccentGradientAI.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnDarkAccentGradientAI.colors,
                    LightGradientTokens.TextOnDarkAccentGradientAI.positions,
                    LightGradientTokens.TextOnDarkAccentGradientAI.angle,
                ),
            ),
        )
        personasInversePinkSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnDarkPinkSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnDarkPinkSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnDarkPinkSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseOchreSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnDarkOchreSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnDarkOchreSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnDarkOchreSurfaceAccentGradient.angle,
                ),
            ),
        )
        overlayInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OverlayOnDarkGradient.colors,
                    LightGradientTokens.OverlayOnDarkGradient.positions,
                    LightGradientTokens.OverlayOnDarkGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentGradientSecondary.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkAccentGradientSecondary.colors,
                    LightGradientTokens.SurfaceOnDarkAccentGradientSecondary.positions,
                    LightGradientTokens.SurfaceOnDarkAccentGradientSecondary.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkSkeletonGradient.colors,
                    LightGradientTokens.SurfaceOnDarkSkeletonGradient.positions,
                    LightGradientTokens.SurfaceOnDarkSkeletonGradient.angle,
                ),
            ),
        )
        personasInverseGreenSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnDarkGreenSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnDarkGreenSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnDarkGreenSurfaceAccentGradient.angle,
                ),
            ),
        )
        outlineInverseWhiteGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OutlineOnDarkWhiteGradient.colors,
                    LightGradientTokens.OutlineOnDarkWhiteGradient.positions,
                    LightGradientTokens.OutlineOnDarkWhiteGradient.angle,
                ),
            ),
        )
        personasInverseBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnDarkBlueSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnDarkBlueSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnDarkBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseOliveSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnDarkOliveSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnDarkOliveSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnDarkOliveSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseVioletSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnDarkVioletSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnDarkVioletSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnDarkVioletSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkAccentGradient.colors,
                    LightGradientTokens.SurfaceOnDarkAccentGradient.positions,
                    LightGradientTokens.SurfaceOnDarkAccentGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentMinorGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkAccentMinorGradient.colors,
                    LightGradientTokens.SurfaceOnDarkAccentMinorGradient.positions,
                    LightGradientTokens.SurfaceOnDarkAccentMinorGradient.angle,
                ),
            ),
        )
        outlineDefaultWhiteGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OutlineOnLightWhiteGradient.colors,
                    LightGradientTokens.OutlineOnLightWhiteGradient.positions,
                    LightGradientTokens.OutlineOnLightWhiteGradient.angle,
                ),
            ),
        )
        personasDefaultGreenSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnLightGreenSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnLightGreenSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnLightGreenSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultSeaBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnLightSeaBlueSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnLightSeaBlueSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnLightSeaBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultPinkSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnLightPinkSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnLightPinkSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnLightPinkSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightSkeletonGradient.colors,
                    LightGradientTokens.SurfaceOnLightSkeletonGradient.positions,
                    LightGradientTokens.SurfaceOnLightSkeletonGradient.angle,
                ),
            ),
        )
        overlayDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OverlayOnLightGradient.colors,
                    LightGradientTokens.OverlayOnLightGradient.positions,
                    LightGradientTokens.OverlayOnLightGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentGradientSecondary.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightAccentGradientSecondary.colors,
                    LightGradientTokens.SurfaceOnLightAccentGradientSecondary.positions,
                    LightGradientTokens.SurfaceOnLightAccentGradientSecondary.angle,
                ),
            ),
        )
        personasDefaultOchreSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnLightOchreSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnLightOchreSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnLightOchreSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultVioletSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnLightVioletSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnLightVioletSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnLightVioletSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultOliveSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnLightOliveSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnLightOliveSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnLightOliveSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultIndigoSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnLightIndigoSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnLightIndigoSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnLightIndigoSurfaceAccentGradient.angle,
                ),
            ),
        )
        textDefaultAccentGradientAI.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnLightAccentGradientAI.colors,
                    LightGradientTokens.TextOnLightAccentGradientAI.positions,
                    LightGradientTokens.TextOnLightAccentGradientAI.angle,
                ),
            ),
        )
        personasDefaultBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasOnLightBlueSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasOnLightBlueSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasOnLightBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightAccentGradient.colors,
                    LightGradientTokens.SurfaceOnLightAccentGradient.positions,
                    LightGradientTokens.SurfaceOnLightAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentMinorGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightAccentMinorGradient.colors,
                    LightGradientTokens.SurfaceOnLightAccentMinorGradient.positions,
                    LightGradientTokens.SurfaceOnLightAccentMinorGradient.angle,
                ),
            ),
        )
    }
}

/**
 * Подтема SddsSbComTheme.OnLight
 */
@Composable
public fun SddsSbComTheme.OnLight(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable
    () -> Unit,
) {
    val colors = if (isDark) {
        darkOnLightColors
    } else {
        lightOnLightColors
    }
    val gradients = if (isDark) {
        darkOnLightGradients
    } else {
        lightOnLightGradients
    }
    SddsSbComTheme(
        colors = colors,
        gradients = gradients,
        content = content,
    )
}
