// AUTO-GENERATED. DO NOT MODIFY this file.
package com.sdds.sbcom.theme.subthemes

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import com.sdds.sbcom.theme.SddsSbComColors
import com.sdds.sbcom.theme.SddsSbComGradients
import com.sdds.sbcom.theme.SddsSbComTheme
import com.sdds.sbcom.theme.darkSddsSbComColors
import com.sdds.sbcom.theme.darkSddsSbComGradients
import com.sdds.sbcom.theme.lightSddsSbComColors
import com.sdds.sbcom.theme.lightSddsSbComGradients
import com.sdds.sbcom.theme.linearGradient
import com.sdds.sbcom.tokens.DarkColorTokens
import com.sdds.sbcom.tokens.DarkGradientTokens
import com.sdds.sbcom.tokens.LightColorTokens
import com.sdds.sbcom.tokens.LightGradientTokens
import kotlin.Boolean
import kotlin.Unit

private val darkOnLightColors: SddsSbComColors by lazy {
    darkSddsSbComColors {
        textInversePrimaryHover.overrideBy(DarkColorTokens.TextOnDarkPrimaryHover)
        textInversePrimaryActive.overrideBy(DarkColorTokens.TextOnDarkPrimaryActive)
        textInversePrimaryBrightness.overrideBy(DarkColorTokens.TextOnDarkPrimaryBrightness)
        textInverseSecondaryHover.overrideBy(DarkColorTokens.TextOnDarkSecondaryHover)
        textInverseSecondaryActive.overrideBy(DarkColorTokens.TextOnDarkSecondaryActive)
        textInverseTertiaryHover.overrideBy(DarkColorTokens.TextOnDarkTertiaryHover)
        textInverseTertiaryActive.overrideBy(DarkColorTokens.TextOnDarkTertiaryActive)
        textInverseParagraphHover.overrideBy(DarkColorTokens.TextOnDarkParagraphHover)
        textInverseParagraphActive.overrideBy(DarkColorTokens.TextOnDarkParagraphActive)
        textInverseAccentHover.overrideBy(DarkColorTokens.TextOnDarkAccentHover)
        textInverseAccentActive.overrideBy(DarkColorTokens.TextOnDarkAccentActive)
        textInverseAccentMinorHover.overrideBy(DarkColorTokens.TextOnDarkAccentMinorHover)
        textInverseAccentMinorActive.overrideBy(DarkColorTokens.TextOnDarkAccentMinorActive)
        textInversePositiveHover.overrideBy(DarkColorTokens.TextOnDarkPositiveHover)
        textInversePositiveActive.overrideBy(DarkColorTokens.TextOnDarkPositiveActive)
        textInverseWarningHover.overrideBy(DarkColorTokens.TextOnDarkWarningHover)
        textInverseWarningActive.overrideBy(DarkColorTokens.TextOnDarkWarningActive)
        textInverseNegativeHover.overrideBy(DarkColorTokens.TextOnDarkNegativeHover)
        textInverseNegativeActive.overrideBy(DarkColorTokens.TextOnDarkNegativeActive)
        textInverseInfoHover.overrideBy(DarkColorTokens.TextOnDarkInfoHover)
        textInverseInfoActive.overrideBy(DarkColorTokens.TextOnDarkInfoActive)
        textInversePositiveMinorHover.overrideBy(DarkColorTokens.TextOnDarkPositiveMinorHover)
        textInversePositiveMinorActive.overrideBy(DarkColorTokens.TextOnDarkPositiveMinorActive)
        textInverseWarningMinorHover.overrideBy(DarkColorTokens.TextOnDarkWarningMinorHover)
        textInverseWarningMinorActive.overrideBy(DarkColorTokens.TextOnDarkWarningMinorActive)
        textInverseNegativeMinorHover.overrideBy(DarkColorTokens.TextOnDarkNegativeMinorHover)
        textInverseNegativeMinorActive.overrideBy(DarkColorTokens.TextOnDarkNegativeMinorActive)
        textInverseInfoMinorHover.overrideBy(DarkColorTokens.TextOnDarkInfoMinorHover)
        textInverseInfoMinorActive.overrideBy(DarkColorTokens.TextOnDarkInfoMinorActive)
        textInverseAccent.overrideBy(DarkColorTokens.TextOnDarkAccent)
        textInversePositive.overrideBy(DarkColorTokens.TextOnDarkPositive)
        textInverseAccentMinor.overrideBy(DarkColorTokens.TextOnDarkAccentMinor)
        textInversePositiveMinor.overrideBy(DarkColorTokens.TextOnDarkPositiveMinor)
        textInversePrimary.overrideBy(DarkColorTokens.TextOnDarkPrimary)
        textInverseSecondary.overrideBy(DarkColorTokens.TextOnDarkSecondary)
        textInverseTertiary.overrideBy(DarkColorTokens.TextOnDarkTertiary)
        textInverseParagraph.overrideBy(DarkColorTokens.TextOnDarkParagraph)
        textInverseWarning.overrideBy(DarkColorTokens.TextOnDarkWarning)
        textInverseNegative.overrideBy(DarkColorTokens.TextOnDarkNegative)
        textInverseInfo.overrideBy(DarkColorTokens.TextOnDarkInfo)
        textInverseNegativeMinor.overrideBy(DarkColorTokens.TextOnDarkNegativeMinor)
        textInverseWarningMinor.overrideBy(DarkColorTokens.TextOnDarkWarningMinor)
        textInverseInfoMinor.overrideBy(DarkColorTokens.TextOnDarkInfoMinor)
        surfaceInverseSolidPrimaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkSolidPrimaryHover)
        surfaceInverseSolidPrimaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkSolidPrimaryActive)
        surfaceInverseSolidPrimaryBrightness.overrideBy(DarkColorTokens.SurfaceOnDarkSolidPrimaryBrightness)
        surfaceInverseSolidSecondaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkSolidSecondaryHover)
        surfaceInverseSolidSecondaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkSolidSecondaryActive)
        surfaceInverseSolidTertiaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkSolidTertiaryHover)
        surfaceInverseSolidTertiaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkSolidTertiaryActive)
        surfaceInverseSolidCardHover.overrideBy(DarkColorTokens.SurfaceOnDarkSolidCardHover)
        surfaceInverseSolidCardActive.overrideBy(DarkColorTokens.SurfaceOnDarkSolidCardActive)
        surfaceInverseSolidCardBrightness.overrideBy(DarkColorTokens.SurfaceOnDarkSolidCardBrightness)
        surfaceInverseSolidDefaultHover.overrideBy(DarkColorTokens.SurfaceOnDarkSolidDefaultHover)
        surfaceInverseSolidDefaultActive.overrideBy(DarkColorTokens.SurfaceOnDarkSolidDefaultActive)
        surfaceInverseTransparentPrimaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentPrimaryHover)
        surfaceInverseTransparentPrimaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentPrimaryActive)
        surfaceInverseTransparentSecondaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentSecondaryHover)
        surfaceInverseTransparentSecondaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentSecondaryActive)
        surfaceInverseTransparentTertiaryHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentTertiaryHover)
        surfaceInverseTransparentTertiaryActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentTertiaryActive)
        surfaceInverseTransparentDeepHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentDeepHover)
        surfaceInverseTransparentDeepActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentDeepActive)
        surfaceInverseTransparentCardHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentCardHover)
        surfaceInverseTransparentCardActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentCardActive)
        surfaceInverseTransparentCardBrightness.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentCardBrightness)
        surfaceInverseClearHover.overrideBy(DarkColorTokens.SurfaceOnDarkClearHover)
        surfaceInverseClearActive.overrideBy(DarkColorTokens.SurfaceOnDarkClearActive)
        surfaceInverseAccentHover.overrideBy(DarkColorTokens.SurfaceOnDarkAccentHover)
        surfaceInverseAccentActive.overrideBy(DarkColorTokens.SurfaceOnDarkAccentActive)
        surfaceInverseAccentMinorHover.overrideBy(DarkColorTokens.SurfaceOnDarkAccentMinorHover)
        surfaceInverseAccentMinorActive.overrideBy(DarkColorTokens.SurfaceOnDarkAccentMinorActive)
        surfaceInverseTransparentAccentHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentAccentHover)
        surfaceInverseTransparentAccentActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentAccentActive)
        surfaceInversePositiveHover.overrideBy(DarkColorTokens.SurfaceOnDarkPositiveHover)
        surfaceInversePositiveActive.overrideBy(DarkColorTokens.SurfaceOnDarkPositiveActive)
        surfaceInverseWarningHover.overrideBy(DarkColorTokens.SurfaceOnDarkWarningHover)
        surfaceInverseWarningActive.overrideBy(DarkColorTokens.SurfaceOnDarkWarningActive)
        surfaceInverseNegativeHover.overrideBy(DarkColorTokens.SurfaceOnDarkNegativeHover)
        surfaceInverseNegativeActive.overrideBy(DarkColorTokens.SurfaceOnDarkNegativeActive)
        surfaceInverseInfoHover.overrideBy(DarkColorTokens.SurfaceOnDarkInfoHover)
        surfaceInverseInfoActive.overrideBy(DarkColorTokens.SurfaceOnDarkInfoActive)
        surfaceInversePositiveMinorHover.overrideBy(DarkColorTokens.SurfaceOnDarkPositiveMinorHover)
        surfaceInversePositiveMinorActive.overrideBy(DarkColorTokens.SurfaceOnDarkPositiveMinorActive)
        surfaceInverseWarningMinorHover.overrideBy(DarkColorTokens.SurfaceOnDarkWarningMinorHover)
        surfaceInverseWarningMinorActive.overrideBy(DarkColorTokens.SurfaceOnDarkWarningMinorActive)
        surfaceInverseNegativeMinorHover.overrideBy(DarkColorTokens.SurfaceOnDarkNegativeMinorHover)
        surfaceInverseNegativeMinorActive.overrideBy(DarkColorTokens.SurfaceOnDarkNegativeMinorActive)
        surfaceInverseInfoMinorHover.overrideBy(DarkColorTokens.SurfaceOnDarkInfoMinorHover)
        surfaceInverseInfoMinorActive.overrideBy(DarkColorTokens.SurfaceOnDarkInfoMinorActive)
        surfaceInverseSolidCard.overrideBy(DarkColorTokens.SurfaceOnDarkSolidCard)
        surfaceInverseSolidPrimary.overrideBy(DarkColorTokens.SurfaceOnDarkSolidPrimary)
        surfaceInverseSolidSecondary.overrideBy(DarkColorTokens.SurfaceOnDarkSolidSecondary)
        surfaceInverseSolidTertiary.overrideBy(DarkColorTokens.SurfaceOnDarkSolidTertiary)
        surfaceInverseSolidDefault.overrideBy(DarkColorTokens.SurfaceOnDarkSolidDefault)
        surfaceInverseTransparentPrimary.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentPrimary)
        surfaceInverseTransparentSecondary.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentSecondary)
        surfaceInverseTransparentTertiary.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentTertiary)
        surfaceInverseTransparentDeep.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentDeep)
        surfaceInverseClear.overrideBy(DarkColorTokens.SurfaceOnDarkClear)
        surfaceInverseWarning.overrideBy(DarkColorTokens.SurfaceOnDarkWarning)
        surfaceInverseNegative.overrideBy(DarkColorTokens.SurfaceOnDarkNegative)
        surfaceInverseTransparentAccent.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentAccent)
        surfaceInverseInfo.overrideBy(DarkColorTokens.SurfaceOnDarkInfo)
        surfaceInverseWarningMinor.overrideBy(DarkColorTokens.SurfaceOnDarkWarningMinor)
        surfaceInverseNegativeMinor.overrideBy(DarkColorTokens.SurfaceOnDarkNegativeMinor)
        surfaceInverseInfoMinor.overrideBy(DarkColorTokens.SurfaceOnDarkInfoMinor)
        surfaceInverseAccent.overrideBy(DarkColorTokens.SurfaceOnDarkAccent)
        surfaceInversePositive.overrideBy(DarkColorTokens.SurfaceOnDarkPositive)
        surfaceInversePositiveMinor.overrideBy(DarkColorTokens.SurfaceOnDarkPositiveMinor)
        surfaceInverseAccentMinor.overrideBy(DarkColorTokens.SurfaceOnDarkAccentMinor)
        surfaceInverseTransparentNaviHover.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentNaviHover)
        surfaceInverseTransparentNaviActive.overrideBy(DarkColorTokens.SurfaceOnDarkTransparentNaviActive)
        overlayInverseSoft.overrideBy(DarkColorTokens.OverlayOnDarkSoft)
        overlayInverseHard.overrideBy(DarkColorTokens.OverlayOnDarkHard)
        outlineInverseTransparentPrimaryHover.overrideBy(DarkColorTokens.OutlineOnDarkTransparentPrimaryHover)
        outlineInverseTransparentPrimaryActive.overrideBy(DarkColorTokens.OutlineOnDarkTransparentPrimaryActive)
        outlineInverseClearHover.overrideBy(DarkColorTokens.OutlineOnDarkClearHover)
        outlineInverseClearActive.overrideBy(DarkColorTokens.OutlineOnDarkClearActive)
        outlineInversePositiveHover.overrideBy(DarkColorTokens.OutlineOnDarkPositiveHover)
        outlineInversePositiveActive.overrideBy(DarkColorTokens.OutlineOnDarkPositiveActive)
        outlineInverseWarningHover.overrideBy(DarkColorTokens.OutlineOnDarkWarningHover)
        outlineInverseWarningActive.overrideBy(DarkColorTokens.OutlineOnDarkWarningActive)
        outlineInverseNegativeHover.overrideBy(DarkColorTokens.OutlineOnDarkNegativeHover)
        outlineInverseNegativeActive.overrideBy(DarkColorTokens.OutlineOnDarkNegativeActive)
        outlineInverseInfoHover.overrideBy(DarkColorTokens.OutlineOnDarkInfoHover)
        outlineInverseInfoActive.overrideBy(DarkColorTokens.OutlineOnDarkInfoActive)
        outlineInverseSolidDefaultHover.overrideBy(DarkColorTokens.OutlineOnDarkSolidDefaultHover)
        outlineInverseSolidDefaultActive.overrideBy(DarkColorTokens.OutlineOnDarkSolidDefaultActive)
        outlineInverseTransparentSurfaceHover.overrideBy(DarkColorTokens.OutlineOnDarkTransparentSurfaceHover)
        outlineInverseTransparentSurfaceActive.overrideBy(DarkColorTokens.OutlineOnDarkTransparentSurfaceActive)
        outlineInverseSolidDefault.overrideBy(DarkColorTokens.OutlineOnDarkSolidDefault)
        outlineInverseTransparentPrimary.overrideBy(DarkColorTokens.OutlineOnDarkTransparentPrimary)
        outlineInverseClear.overrideBy(DarkColorTokens.OutlineOnDarkClear)
        outlineInversePositive.overrideBy(DarkColorTokens.OutlineOnDarkPositive)
        outlineInverseWarning.overrideBy(DarkColorTokens.OutlineOnDarkWarning)
        outlineInverseNegative.overrideBy(DarkColorTokens.OutlineOnDarkNegative)
        outlineInverseInfo.overrideBy(DarkColorTokens.OutlineOnDarkInfo)
        dataInverseYellow.overrideBy(DarkColorTokens.DataOnDarkYellow)
        dataInverseYellowHover.overrideBy(DarkColorTokens.DataOnDarkYellowHover)
        dataInverseYellowActive.overrideBy(DarkColorTokens.DataOnDarkYellowActive)
        dataInverseYellowMinor.overrideBy(DarkColorTokens.DataOnDarkYellowMinor)
        dataInverseYellowMinorHover.overrideBy(DarkColorTokens.DataOnDarkYellowMinorHover)
        dataInverseYellowMinorActive.overrideBy(DarkColorTokens.DataOnDarkYellowMinorActive)
        dataInverseYellowTransparent.overrideBy(DarkColorTokens.DataOnDarkYellowTransparent)
        dataInverseYellowTransparentHover.overrideBy(DarkColorTokens.DataOnDarkYellowTransparentHover)
        dataInverseYellowTransparentActive.overrideBy(DarkColorTokens.DataOnDarkYellowTransparentActive)
        textDefaultPrimaryHover.overrideBy(DarkColorTokens.TextOnLightPrimaryHover)
        textDefaultPrimaryActive.overrideBy(DarkColorTokens.TextOnLightPrimaryActive)
        textDefaultPrimaryBrightness.overrideBy(DarkColorTokens.TextOnLightPrimaryBrightness)
        textDefaultSecondaryHover.overrideBy(DarkColorTokens.TextOnLightSecondaryHover)
        textDefaultSecondaryActive.overrideBy(DarkColorTokens.TextOnLightSecondaryActive)
        textDefaultTertiaryHover.overrideBy(DarkColorTokens.TextOnLightTertiaryHover)
        textDefaultTertiaryActive.overrideBy(DarkColorTokens.TextOnLightTertiaryActive)
        textDefaultParagraphHover.overrideBy(DarkColorTokens.TextOnLightParagraphHover)
        textDefaultParagraphActive.overrideBy(DarkColorTokens.TextOnLightParagraphActive)
        textDefaultAccentHover.overrideBy(DarkColorTokens.TextOnLightAccentHover)
        textDefaultAccentActive.overrideBy(DarkColorTokens.TextOnLightAccentActive)
        textDefaultAccentMinorHover.overrideBy(DarkColorTokens.TextOnLightAccentMinorHover)
        textDefaultAccentMinorActive.overrideBy(DarkColorTokens.TextOnLightAccentMinorActive)
        textDefaultPositiveHover.overrideBy(DarkColorTokens.TextOnLightPositiveHover)
        textDefaultPositiveActive.overrideBy(DarkColorTokens.TextOnLightPositiveActive)
        textDefaultWarningHover.overrideBy(DarkColorTokens.TextOnLightWarningHover)
        textDefaultWarningActive.overrideBy(DarkColorTokens.TextOnLightWarningActive)
        textDefaultNegativeHover.overrideBy(DarkColorTokens.TextOnLightNegativeHover)
        textDefaultNegativeActive.overrideBy(DarkColorTokens.TextOnLightNegativeActive)
        textDefaultInfoHover.overrideBy(DarkColorTokens.TextOnLightInfoHover)
        textDefaultInfoActive.overrideBy(DarkColorTokens.TextOnLightInfoActive)
        textDefaultPositiveMinorHover.overrideBy(DarkColorTokens.TextOnLightPositiveMinorHover)
        textDefaultPositiveMinorActive.overrideBy(DarkColorTokens.TextOnLightPositiveMinorActive)
        textDefaultWarningMinorHover.overrideBy(DarkColorTokens.TextOnLightWarningMinorHover)
        textDefaultWarningMinorActive.overrideBy(DarkColorTokens.TextOnLightWarningMinorActive)
        textDefaultNegativeMinorHover.overrideBy(DarkColorTokens.TextOnLightNegativeMinorHover)
        textDefaultNegativeMinorActive.overrideBy(DarkColorTokens.TextOnLightNegativeMinorActive)
        textDefaultInfoMinorHover.overrideBy(DarkColorTokens.TextOnLightInfoMinorHover)
        textDefaultInfoMinorActive.overrideBy(DarkColorTokens.TextOnLightInfoMinorActive)
        textDefaultPositiveMinor.overrideBy(DarkColorTokens.TextOnLightPositiveMinor)
        textDefaultWarningMinor.overrideBy(DarkColorTokens.TextOnLightWarningMinor)
        textDefaultInfoMinor.overrideBy(DarkColorTokens.TextOnLightInfoMinor)
        textDefaultNegativeMinor.overrideBy(DarkColorTokens.TextOnLightNegativeMinor)
        textDefaultPrimary.overrideBy(DarkColorTokens.TextOnLightPrimary)
        textDefaultSecondary.overrideBy(DarkColorTokens.TextOnLightSecondary)
        textDefaultTertiary.overrideBy(DarkColorTokens.TextOnLightTertiary)
        textDefaultParagraph.overrideBy(DarkColorTokens.TextOnLightParagraph)
        textDefaultAccent.overrideBy(DarkColorTokens.TextOnLightAccent)
        textDefaultAccentMinor.overrideBy(DarkColorTokens.TextOnLightAccentMinor)
        textDefaultPositive.overrideBy(DarkColorTokens.TextOnLightPositive)
        textDefaultNegative.overrideBy(DarkColorTokens.TextOnLightNegative)
        textDefaultWarning.overrideBy(DarkColorTokens.TextOnLightWarning)
        textDefaultInfo.overrideBy(DarkColorTokens.TextOnLightInfo)
        surfaceDefaultSolidPrimaryHover.overrideBy(DarkColorTokens.SurfaceOnLightSolidPrimaryHover)
        surfaceDefaultSolidPrimaryActive.overrideBy(DarkColorTokens.SurfaceOnLightSolidPrimaryActive)
        surfaceDefaultSolidPrimaryBrightness.overrideBy(DarkColorTokens.SurfaceOnLightSolidPrimaryBrightness)
        surfaceDefaultSolidSecondaryHover.overrideBy(DarkColorTokens.SurfaceOnLightSolidSecondaryHover)
        surfaceDefaultSolidSecondaryActive.overrideBy(DarkColorTokens.SurfaceOnLightSolidSecondaryActive)
        surfaceDefaultSolidTertiaryHover.overrideBy(DarkColorTokens.SurfaceOnLightSolidTertiaryHover)
        surfaceDefaultSolidTertiaryActive.overrideBy(DarkColorTokens.SurfaceOnLightSolidTertiaryActive)
        surfaceDefaultSolidCardHover.overrideBy(DarkColorTokens.SurfaceOnLightSolidCardHover)
        surfaceDefaultSolidCardActive.overrideBy(DarkColorTokens.SurfaceOnLightSolidCardActive)
        surfaceDefaultSolidCardBrightness.overrideBy(DarkColorTokens.SurfaceOnLightSolidCardBrightness)
        surfaceDefaultSolidDefaultHover.overrideBy(DarkColorTokens.SurfaceOnLightSolidDefaultHover)
        surfaceDefaultSolidDefaultActive.overrideBy(DarkColorTokens.SurfaceOnLightSolidDefaultActive)
        surfaceDefaultTransparentPrimaryHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentPrimaryHover)
        surfaceDefaultTransparentPrimaryActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentPrimaryActive)
        surfaceDefaultTransparentSecondaryHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentSecondaryHover)
        surfaceDefaultTransparentSecondaryActive.overrideBy(
            DarkColorTokens.SurfaceOnLightTransparentSecondaryActive,
        )
        surfaceDefaultTransparentTertiaryHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentTertiaryHover)
        surfaceDefaultTransparentTertiaryActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentTertiaryActive)
        surfaceDefaultTransparentDeepHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentDeepHover)
        surfaceDefaultTransparentDeepActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentDeepActive)
        surfaceDefaultTransparentCardHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentCardHover)
        surfaceDefaultTransparentCardActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentCardActive)
        surfaceDefaultTransparentCardBrightness.overrideBy(DarkColorTokens.SurfaceOnLightTransparentCardBrightness)
        surfaceDefaultClearHover.overrideBy(DarkColorTokens.SurfaceOnLightClearHover)
        surfaceDefaultClearActive.overrideBy(DarkColorTokens.SurfaceOnLightClearActive)
        surfaceDefaultAccentHover.overrideBy(DarkColorTokens.SurfaceOnLightAccentHover)
        surfaceDefaultAccentActive.overrideBy(DarkColorTokens.SurfaceOnLightAccentActive)
        surfaceDefaultAccentMinorHover.overrideBy(DarkColorTokens.SurfaceOnLightAccentMinorHover)
        surfaceDefaultAccentMinorActive.overrideBy(DarkColorTokens.SurfaceOnLightAccentMinorActive)
        surfaceDefaultTransparentAccentHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentAccentHover)
        surfaceDefaultTransparentAccentActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentAccentActive)
        surfaceDefaultPositiveHover.overrideBy(DarkColorTokens.SurfaceOnLightPositiveHover)
        surfaceDefaultPositiveActive.overrideBy(DarkColorTokens.SurfaceOnLightPositiveActive)
        surfaceDefaultWarningHover.overrideBy(DarkColorTokens.SurfaceOnLightWarningHover)
        surfaceDefaultWarningActive.overrideBy(DarkColorTokens.SurfaceOnLightWarningActive)
        surfaceDefaultNegativeHover.overrideBy(DarkColorTokens.SurfaceOnLightNegativeHover)
        surfaceDefaultNegativeActive.overrideBy(DarkColorTokens.SurfaceOnLightNegativeActive)
        surfaceDefaultInfoHover.overrideBy(DarkColorTokens.SurfaceOnLightInfoHover)
        surfaceDefaultInfoActive.overrideBy(DarkColorTokens.SurfaceOnLightInfoActive)
        surfaceDefaultPositiveMinorHover.overrideBy(DarkColorTokens.SurfaceOnLightPositiveMinorHover)
        surfaceDefaultPositiveMinorActive.overrideBy(DarkColorTokens.SurfaceOnLightPositiveMinorActive)
        surfaceDefaultWarningMinorHover.overrideBy(DarkColorTokens.SurfaceOnLightWarningMinorHover)
        surfaceDefaultWarningMinorActive.overrideBy(DarkColorTokens.SurfaceOnLightWarningMinorActive)
        surfaceDefaultNegativeMinorHover.overrideBy(DarkColorTokens.SurfaceOnLightNegativeMinorHover)
        surfaceDefaultNegativeMinorActive.overrideBy(DarkColorTokens.SurfaceOnLightNegativeMinorActive)
        surfaceDefaultInfoMinorHover.overrideBy(DarkColorTokens.SurfaceOnLightInfoMinorHover)
        surfaceDefaultInfoMinorActive.overrideBy(DarkColorTokens.SurfaceOnLightInfoMinorActive)
        surfaceDefaultSolidCard.overrideBy(DarkColorTokens.SurfaceOnLightSolidCard)
        surfaceDefaultSolidPrimary.overrideBy(DarkColorTokens.SurfaceOnLightSolidPrimary)
        surfaceDefaultSolidSecondary.overrideBy(DarkColorTokens.SurfaceOnLightSolidSecondary)
        surfaceDefaultSolidTertiary.overrideBy(DarkColorTokens.SurfaceOnLightSolidTertiary)
        surfaceDefaultSolidDefault.overrideBy(DarkColorTokens.SurfaceOnLightSolidDefault)
        surfaceDefaultTransparentPrimary.overrideBy(DarkColorTokens.SurfaceOnLightTransparentPrimary)
        surfaceDefaultTransparentSecondary.overrideBy(DarkColorTokens.SurfaceOnLightTransparentSecondary)
        surfaceDefaultTransparentTertiary.overrideBy(DarkColorTokens.SurfaceOnLightTransparentTertiary)
        surfaceDefaultTransparentDeep.overrideBy(DarkColorTokens.SurfaceOnLightTransparentDeep)
        surfaceDefaultClear.overrideBy(DarkColorTokens.SurfaceOnLightClear)
        surfaceDefaultWarning.overrideBy(DarkColorTokens.SurfaceOnLightWarning)
        surfaceDefaultNegative.overrideBy(DarkColorTokens.SurfaceOnLightNegative)
        surfaceDefaultInfo.overrideBy(DarkColorTokens.SurfaceOnLightInfo)
        surfaceDefaultPositive.overrideBy(DarkColorTokens.SurfaceOnLightPositive)
        surfaceDefaultPositiveMinor.overrideBy(DarkColorTokens.SurfaceOnLightPositiveMinor)
        surfaceDefaultWarningMinor.overrideBy(DarkColorTokens.SurfaceOnLightWarningMinor)
        surfaceDefaultNegativeMinor.overrideBy(DarkColorTokens.SurfaceOnLightNegativeMinor)
        surfaceDefaultInfoMinor.overrideBy(DarkColorTokens.SurfaceOnLightInfoMinor)
        surfaceDefaultAccent.overrideBy(DarkColorTokens.SurfaceOnLightAccent)
        surfaceDefaultTransparentAccent.overrideBy(DarkColorTokens.SurfaceOnLightTransparentAccent)
        surfaceDefaultAccentMinor.overrideBy(DarkColorTokens.SurfaceOnLightAccentMinor)
        surfaceDefaultTransparentNaviHover.overrideBy(DarkColorTokens.SurfaceOnLightTransparentNaviHover)
        surfaceDefaultTransparentNaviActive.overrideBy(DarkColorTokens.SurfaceOnLightTransparentNaviActive)
        overlayDefaultHard.overrideBy(DarkColorTokens.OverlayOnLightHard)
        overlayDefaultSoft.overrideBy(DarkColorTokens.OverlayOnLightSoft)
        outlineDefaultTransparentPrimaryHover.overrideBy(DarkColorTokens.OutlineOnLightTransparentPrimaryHover)
        outlineDefaultTransparentPrimaryActive.overrideBy(DarkColorTokens.OutlineOnLightTransparentPrimaryActive)
        outlineDefaultClearHover.overrideBy(DarkColorTokens.OutlineOnLightClearHover)
        outlineDefaultClearActive.overrideBy(DarkColorTokens.OutlineOnLightClearActive)
        outlineDefaultPositiveHover.overrideBy(DarkColorTokens.OutlineOnLightPositiveHover)
        outlineDefaultPositiveActive.overrideBy(DarkColorTokens.OutlineOnLightPositiveActive)
        outlineDefaultWarningHover.overrideBy(DarkColorTokens.OutlineOnLightWarningHover)
        outlineDefaultWarningActive.overrideBy(DarkColorTokens.OutlineOnLightWarningActive)
        outlineDefaultNegativeHover.overrideBy(DarkColorTokens.OutlineOnLightNegativeHover)
        outlineDefaultNegativeActive.overrideBy(DarkColorTokens.OutlineOnLightNegativeActive)
        outlineDefaultInfoHover.overrideBy(DarkColorTokens.OutlineOnLightInfoHover)
        outlineDefaultInfoActive.overrideBy(DarkColorTokens.OutlineOnLightInfoActive)
        outlineDefaultSolidDefaultHover.overrideBy(DarkColorTokens.OutlineOnLightSolidDefaultHover)
        outlineDefaultSolidDefaultActive.overrideBy(DarkColorTokens.OutlineOnLightSolidDefaultActive)
        outlineDefaultClear.overrideBy(DarkColorTokens.OutlineOnLightClear)
        outlineDefaultTransparentSurfaceHover.overrideBy(DarkColorTokens.OutlineOnLightTransparentSurfaceHover)
        outlineDefaultTransparentSurfaceActive.overrideBy(DarkColorTokens.OutlineOnLightTransparentSurfaceActive)
        outlineDefaultSolidDefault.overrideBy(DarkColorTokens.OutlineOnLightSolidDefault)
        outlineDefaultTransparentPrimary.overrideBy(DarkColorTokens.OutlineOnLightTransparentPrimary)
        outlineDefaultPositive.overrideBy(DarkColorTokens.OutlineOnLightPositive)
        outlineDefaultWarning.overrideBy(DarkColorTokens.OutlineOnLightWarning)
        outlineDefaultNegative.overrideBy(DarkColorTokens.OutlineOnLightNegative)
        outlineDefaultInfo.overrideBy(DarkColorTokens.OutlineOnLightInfo)
        dataDefaultYellow.overrideBy(DarkColorTokens.DataOnLightYellow)
        dataDefaultYellowHover.overrideBy(DarkColorTokens.DataOnLightYellowHover)
        dataDefaultYellowActive.overrideBy(DarkColorTokens.DataOnLightYellowActive)
        dataDefaultYellowMinor.overrideBy(DarkColorTokens.DataOnLightYellowMinor)
        dataDefaultYellowMinorHover.overrideBy(DarkColorTokens.DataOnLightYellowMinorHover)
        dataDefaultYellowMinorActive.overrideBy(DarkColorTokens.DataOnLightYellowMinorActive)
        dataDefaultYellowTransparent.overrideBy(DarkColorTokens.DataOnLightYellowTransparent)
        dataDefaultYellowTransparentHover.overrideBy(DarkColorTokens.DataOnLightYellowTransparentHover)
        dataDefaultYellowTransparentActive.overrideBy(DarkColorTokens.DataOnLightYellowTransparentActive)
    }
}

private val lightOnLightColors: SddsSbComColors by lazy {
    lightSddsSbComColors {
        textInversePrimaryHover.overrideBy(LightColorTokens.TextOnDarkPrimaryHover)
        textInversePrimaryActive.overrideBy(LightColorTokens.TextOnDarkPrimaryActive)
        textInversePrimaryBrightness.overrideBy(LightColorTokens.TextOnDarkPrimaryBrightness)
        textInverseSecondaryHover.overrideBy(LightColorTokens.TextOnDarkSecondaryHover)
        textInverseSecondaryActive.overrideBy(LightColorTokens.TextOnDarkSecondaryActive)
        textInverseTertiaryHover.overrideBy(LightColorTokens.TextOnDarkTertiaryHover)
        textInverseTertiaryActive.overrideBy(LightColorTokens.TextOnDarkTertiaryActive)
        textInverseParagraphHover.overrideBy(LightColorTokens.TextOnDarkParagraphHover)
        textInverseParagraphActive.overrideBy(LightColorTokens.TextOnDarkParagraphActive)
        textInverseAccentHover.overrideBy(LightColorTokens.TextOnDarkAccentHover)
        textInverseAccentActive.overrideBy(LightColorTokens.TextOnDarkAccentActive)
        textInverseAccentMinorHover.overrideBy(LightColorTokens.TextOnDarkAccentMinorHover)
        textInverseAccentMinorActive.overrideBy(LightColorTokens.TextOnDarkAccentMinorActive)
        textInversePositiveHover.overrideBy(LightColorTokens.TextOnDarkPositiveHover)
        textInversePositiveActive.overrideBy(LightColorTokens.TextOnDarkPositiveActive)
        textInverseWarningHover.overrideBy(LightColorTokens.TextOnDarkWarningHover)
        textInverseWarningActive.overrideBy(LightColorTokens.TextOnDarkWarningActive)
        textInverseNegativeHover.overrideBy(LightColorTokens.TextOnDarkNegativeHover)
        textInverseNegativeActive.overrideBy(LightColorTokens.TextOnDarkNegativeActive)
        textInverseInfoHover.overrideBy(LightColorTokens.TextOnDarkInfoHover)
        textInverseInfoActive.overrideBy(LightColorTokens.TextOnDarkInfoActive)
        textInversePositiveMinorHover.overrideBy(LightColorTokens.TextOnDarkPositiveMinorHover)
        textInversePositiveMinorActive.overrideBy(LightColorTokens.TextOnDarkPositiveMinorActive)
        textInverseWarningMinorHover.overrideBy(LightColorTokens.TextOnDarkWarningMinorHover)
        textInverseWarningMinorActive.overrideBy(LightColorTokens.TextOnDarkWarningMinorActive)
        textInverseNegativeMinorHover.overrideBy(LightColorTokens.TextOnDarkNegativeMinorHover)
        textInverseNegativeMinorActive.overrideBy(LightColorTokens.TextOnDarkNegativeMinorActive)
        textInverseInfoMinorHover.overrideBy(LightColorTokens.TextOnDarkInfoMinorHover)
        textInverseInfoMinorActive.overrideBy(LightColorTokens.TextOnDarkInfoMinorActive)
        textInversePrimary.overrideBy(LightColorTokens.TextOnDarkPrimary)
        textInverseSecondary.overrideBy(LightColorTokens.TextOnDarkSecondary)
        textInverseTertiary.overrideBy(LightColorTokens.TextOnDarkTertiary)
        textInverseParagraph.overrideBy(LightColorTokens.TextOnDarkParagraph)
        textInverseAccent.overrideBy(LightColorTokens.TextOnDarkAccent)
        textInverseAccentMinor.overrideBy(LightColorTokens.TextOnDarkAccentMinor)
        textInversePositive.overrideBy(LightColorTokens.TextOnDarkPositive)
        textInverseNegative.overrideBy(LightColorTokens.TextOnDarkNegative)
        textInverseWarning.overrideBy(LightColorTokens.TextOnDarkWarning)
        textInverseInfo.overrideBy(LightColorTokens.TextOnDarkInfo)
        textInverseWarningMinor.overrideBy(LightColorTokens.TextOnDarkWarningMinor)
        textInverseNegativeMinor.overrideBy(LightColorTokens.TextOnDarkNegativeMinor)
        textInverseInfoMinor.overrideBy(LightColorTokens.TextOnDarkInfoMinor)
        textInversePositiveMinor.overrideBy(LightColorTokens.TextOnDarkPositiveMinor)
        surfaceInverseSolidPrimaryHover.overrideBy(LightColorTokens.SurfaceOnDarkSolidPrimaryHover)
        surfaceInverseSolidPrimaryActive.overrideBy(LightColorTokens.SurfaceOnDarkSolidPrimaryActive)
        surfaceInverseSolidPrimaryBrightness.overrideBy(LightColorTokens.SurfaceOnDarkSolidPrimaryBrightness)
        surfaceInverseSolidSecondaryHover.overrideBy(LightColorTokens.SurfaceOnDarkSolidSecondaryHover)
        surfaceInverseSolidSecondaryActive.overrideBy(LightColorTokens.SurfaceOnDarkSolidSecondaryActive)
        surfaceInverseSolidTertiaryHover.overrideBy(LightColorTokens.SurfaceOnDarkSolidTertiaryHover)
        surfaceInverseSolidTertiaryActive.overrideBy(LightColorTokens.SurfaceOnDarkSolidTertiaryActive)
        surfaceInverseSolidCardHover.overrideBy(LightColorTokens.SurfaceOnDarkSolidCardHover)
        surfaceInverseSolidCardActive.overrideBy(LightColorTokens.SurfaceOnDarkSolidCardActive)
        surfaceInverseSolidCardBrightness.overrideBy(LightColorTokens.SurfaceOnDarkSolidCardBrightness)
        surfaceInverseSolidDefaultHover.overrideBy(LightColorTokens.SurfaceOnDarkSolidDefaultHover)
        surfaceInverseSolidDefaultActive.overrideBy(LightColorTokens.SurfaceOnDarkSolidDefaultActive)
        surfaceInverseTransparentPrimaryHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentPrimaryHover)
        surfaceInverseTransparentPrimaryActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentPrimaryActive)
        surfaceInverseTransparentSecondaryHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentSecondaryHover)
        surfaceInverseTransparentSecondaryActive.overrideBy(
            LightColorTokens.SurfaceOnDarkTransparentSecondaryActive,
        )
        surfaceInverseTransparentTertiaryHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentTertiaryHover)
        surfaceInverseTransparentTertiaryActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentTertiaryActive)
        surfaceInverseTransparentDeepHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentDeepHover)
        surfaceInverseTransparentDeepActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentDeepActive)
        surfaceInverseTransparentCardHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentCardHover)
        surfaceInverseTransparentCardActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentCardActive)
        surfaceInverseTransparentCardBrightness.overrideBy(LightColorTokens.SurfaceOnDarkTransparentCardBrightness)
        surfaceInverseClearHover.overrideBy(LightColorTokens.SurfaceOnDarkClearHover)
        surfaceInverseClearActive.overrideBy(LightColorTokens.SurfaceOnDarkClearActive)
        surfaceInverseAccentHover.overrideBy(LightColorTokens.SurfaceOnDarkAccentHover)
        surfaceInverseAccentActive.overrideBy(LightColorTokens.SurfaceOnDarkAccentActive)
        surfaceInverseAccentMinorHover.overrideBy(LightColorTokens.SurfaceOnDarkAccentMinorHover)
        surfaceInverseAccentMinorActive.overrideBy(LightColorTokens.SurfaceOnDarkAccentMinorActive)
        surfaceInverseTransparentAccentHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentAccentHover)
        surfaceInverseTransparentAccentActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentAccentActive)
        surfaceInversePositiveHover.overrideBy(LightColorTokens.SurfaceOnDarkPositiveHover)
        surfaceInversePositiveActive.overrideBy(LightColorTokens.SurfaceOnDarkPositiveActive)
        surfaceInverseWarningHover.overrideBy(LightColorTokens.SurfaceOnDarkWarningHover)
        surfaceInverseWarningActive.overrideBy(LightColorTokens.SurfaceOnDarkWarningActive)
        surfaceInverseNegativeHover.overrideBy(LightColorTokens.SurfaceOnDarkNegativeHover)
        surfaceInverseNegativeActive.overrideBy(LightColorTokens.SurfaceOnDarkNegativeActive)
        surfaceInverseInfoHover.overrideBy(LightColorTokens.SurfaceOnDarkInfoHover)
        surfaceInverseInfoActive.overrideBy(LightColorTokens.SurfaceOnDarkInfoActive)
        surfaceInversePositiveMinorHover.overrideBy(LightColorTokens.SurfaceOnDarkPositiveMinorHover)
        surfaceInversePositiveMinorActive.overrideBy(LightColorTokens.SurfaceOnDarkPositiveMinorActive)
        surfaceInverseWarningMinorHover.overrideBy(LightColorTokens.SurfaceOnDarkWarningMinorHover)
        surfaceInverseWarningMinorActive.overrideBy(LightColorTokens.SurfaceOnDarkWarningMinorActive)
        surfaceInverseNegativeMinorHover.overrideBy(LightColorTokens.SurfaceOnDarkNegativeMinorHover)
        surfaceInverseNegativeMinorActive.overrideBy(LightColorTokens.SurfaceOnDarkNegativeMinorActive)
        surfaceInverseInfoMinorHover.overrideBy(LightColorTokens.SurfaceOnDarkInfoMinorHover)
        surfaceInverseInfoMinorActive.overrideBy(LightColorTokens.SurfaceOnDarkInfoMinorActive)
        surfaceInverseTransparentNaviHover.overrideBy(LightColorTokens.SurfaceOnDarkTransparentNaviHover)
        surfaceInverseTransparentNaviActive.overrideBy(LightColorTokens.SurfaceOnDarkTransparentNaviActive)
        surfaceInverseSolidCard.overrideBy(LightColorTokens.SurfaceOnDarkSolidCard)
        surfaceInverseSolidPrimary.overrideBy(LightColorTokens.SurfaceOnDarkSolidPrimary)
        surfaceInverseSolidSecondary.overrideBy(LightColorTokens.SurfaceOnDarkSolidSecondary)
        surfaceInverseSolidTertiary.overrideBy(LightColorTokens.SurfaceOnDarkSolidTertiary)
        surfaceInverseSolidDefault.overrideBy(LightColorTokens.SurfaceOnDarkSolidDefault)
        surfaceInverseTransparentPrimary.overrideBy(LightColorTokens.SurfaceOnDarkTransparentPrimary)
        surfaceInverseTransparentSecondary.overrideBy(LightColorTokens.SurfaceOnDarkTransparentSecondary)
        surfaceInverseTransparentTertiary.overrideBy(LightColorTokens.SurfaceOnDarkTransparentTertiary)
        surfaceInverseTransparentDeep.overrideBy(LightColorTokens.SurfaceOnDarkTransparentDeep)
        surfaceInverseClear.overrideBy(LightColorTokens.SurfaceOnDarkClear)
        surfaceInverseWarning.overrideBy(LightColorTokens.SurfaceOnDarkWarning)
        surfaceInverseNegative.overrideBy(LightColorTokens.SurfaceOnDarkNegative)
        surfaceInverseTransparentAccent.overrideBy(LightColorTokens.SurfaceOnDarkTransparentAccent)
        surfaceInverseInfo.overrideBy(LightColorTokens.SurfaceOnDarkInfo)
        surfaceInverseWarningMinor.overrideBy(LightColorTokens.SurfaceOnDarkWarningMinor)
        surfaceInverseNegativeMinor.overrideBy(LightColorTokens.SurfaceOnDarkNegativeMinor)
        surfaceInverseInfoMinor.overrideBy(LightColorTokens.SurfaceOnDarkInfoMinor)
        surfaceInverseAccent.overrideBy(LightColorTokens.SurfaceOnDarkAccent)
        surfaceInverseAccentMinor.overrideBy(LightColorTokens.SurfaceOnDarkAccentMinor)
        surfaceInversePositive.overrideBy(LightColorTokens.SurfaceOnDarkPositive)
        surfaceInversePositiveMinor.overrideBy(LightColorTokens.SurfaceOnDarkPositiveMinor)
        overlayInverseHard.overrideBy(LightColorTokens.OverlayOnDarkHard)
        overlayInverseSoft.overrideBy(LightColorTokens.OverlayOnDarkSoft)
        outlineInverseTransparentPrimaryHover.overrideBy(LightColorTokens.OutlineOnDarkTransparentPrimaryHover)
        outlineInverseTransparentPrimaryActive.overrideBy(LightColorTokens.OutlineOnDarkTransparentPrimaryActive)
        outlineInverseClearHover.overrideBy(LightColorTokens.OutlineOnDarkClearHover)
        outlineInverseClearActive.overrideBy(LightColorTokens.OutlineOnDarkClearActive)
        outlineInversePositiveHover.overrideBy(LightColorTokens.OutlineOnDarkPositiveHover)
        outlineInversePositiveActive.overrideBy(LightColorTokens.OutlineOnDarkPositiveActive)
        outlineInverseWarningHover.overrideBy(LightColorTokens.OutlineOnDarkWarningHover)
        outlineInverseWarningActive.overrideBy(LightColorTokens.OutlineOnDarkWarningActive)
        outlineInverseNegativeHover.overrideBy(LightColorTokens.OutlineOnDarkNegativeHover)
        outlineInverseNegativeActive.overrideBy(LightColorTokens.OutlineOnDarkNegativeActive)
        outlineInverseInfoHover.overrideBy(LightColorTokens.OutlineOnDarkInfoHover)
        outlineInverseInfoActive.overrideBy(LightColorTokens.OutlineOnDarkInfoActive)
        outlineInverseSolidDefaultHover.overrideBy(LightColorTokens.OutlineOnDarkSolidDefaultHover)
        outlineInverseSolidDefaultActive.overrideBy(LightColorTokens.OutlineOnDarkSolidDefaultActive)
        outlineInverseTransparentSurfaceHover.overrideBy(LightColorTokens.OutlineOnDarkTransparentSurfaceHover)
        outlineInverseTransparentSurfaceActive.overrideBy(LightColorTokens.OutlineOnDarkTransparentSurfaceActive)
        outlineInverseClear.overrideBy(LightColorTokens.OutlineOnDarkClear)
        outlineInverseWarning.overrideBy(LightColorTokens.OutlineOnDarkWarning)
        outlineInverseNegative.overrideBy(LightColorTokens.OutlineOnDarkNegative)
        outlineInverseInfo.overrideBy(LightColorTokens.OutlineOnDarkInfo)
        outlineInverseTransparentPrimary.overrideBy(LightColorTokens.OutlineOnDarkTransparentPrimary)
        outlineInverseSolidDefault.overrideBy(LightColorTokens.OutlineOnDarkSolidDefault)
        outlineInversePositive.overrideBy(LightColorTokens.OutlineOnDarkPositive)
        dataInverseYellow.overrideBy(LightColorTokens.DataOnDarkYellow)
        dataInverseYellowHover.overrideBy(LightColorTokens.DataOnDarkYellowHover)
        dataInverseYellowActive.overrideBy(LightColorTokens.DataOnDarkYellowActive)
        dataInverseYellowMinor.overrideBy(LightColorTokens.DataOnDarkYellowMinor)
        dataInverseYellowMinorHover.overrideBy(LightColorTokens.DataOnDarkYellowMinorHover)
        dataInverseYellowMinorActive.overrideBy(LightColorTokens.DataOnDarkYellowMinorActive)
        dataInverseYellowTransparent.overrideBy(LightColorTokens.DataOnDarkYellowTransparent)
        dataInverseYellowTransparentHover.overrideBy(LightColorTokens.DataOnDarkYellowTransparentHover)
        dataInverseYellowTransparentActive.overrideBy(LightColorTokens.DataOnDarkYellowTransparentActive)
        textDefaultPrimaryHover.overrideBy(LightColorTokens.TextOnLightPrimaryHover)
        textDefaultPrimaryActive.overrideBy(LightColorTokens.TextOnLightPrimaryActive)
        textDefaultPrimaryBrightness.overrideBy(LightColorTokens.TextOnLightPrimaryBrightness)
        textDefaultSecondaryHover.overrideBy(LightColorTokens.TextOnLightSecondaryHover)
        textDefaultSecondaryActive.overrideBy(LightColorTokens.TextOnLightSecondaryActive)
        textDefaultTertiaryHover.overrideBy(LightColorTokens.TextOnLightTertiaryHover)
        textDefaultTertiaryActive.overrideBy(LightColorTokens.TextOnLightTertiaryActive)
        textDefaultParagraphHover.overrideBy(LightColorTokens.TextOnLightParagraphHover)
        textDefaultParagraphActive.overrideBy(LightColorTokens.TextOnLightParagraphActive)
        textDefaultAccentHover.overrideBy(LightColorTokens.TextOnLightAccentHover)
        textDefaultAccentActive.overrideBy(LightColorTokens.TextOnLightAccentActive)
        textDefaultAccentMinorHover.overrideBy(LightColorTokens.TextOnLightAccentMinorHover)
        textDefaultAccentMinorActive.overrideBy(LightColorTokens.TextOnLightAccentMinorActive)
        textDefaultPositiveHover.overrideBy(LightColorTokens.TextOnLightPositiveHover)
        textDefaultPositiveActive.overrideBy(LightColorTokens.TextOnLightPositiveActive)
        textDefaultWarningHover.overrideBy(LightColorTokens.TextOnLightWarningHover)
        textDefaultWarningActive.overrideBy(LightColorTokens.TextOnLightWarningActive)
        textDefaultNegativeHover.overrideBy(LightColorTokens.TextOnLightNegativeHover)
        textDefaultNegativeActive.overrideBy(LightColorTokens.TextOnLightNegativeActive)
        textDefaultInfoHover.overrideBy(LightColorTokens.TextOnLightInfoHover)
        textDefaultInfoActive.overrideBy(LightColorTokens.TextOnLightInfoActive)
        textDefaultPositiveMinorHover.overrideBy(LightColorTokens.TextOnLightPositiveMinorHover)
        textDefaultPositiveMinorActive.overrideBy(LightColorTokens.TextOnLightPositiveMinorActive)
        textDefaultWarningMinorHover.overrideBy(LightColorTokens.TextOnLightWarningMinorHover)
        textDefaultWarningMinorActive.overrideBy(LightColorTokens.TextOnLightWarningMinorActive)
        textDefaultNegativeMinorHover.overrideBy(LightColorTokens.TextOnLightNegativeMinorHover)
        textDefaultNegativeMinorActive.overrideBy(LightColorTokens.TextOnLightNegativeMinorActive)
        textDefaultInfoMinorHover.overrideBy(LightColorTokens.TextOnLightInfoMinorHover)
        textDefaultInfoMinorActive.overrideBy(LightColorTokens.TextOnLightInfoMinorActive)
        textDefaultPrimary.overrideBy(LightColorTokens.TextOnLightPrimary)
        textDefaultSecondary.overrideBy(LightColorTokens.TextOnLightSecondary)
        textDefaultTertiary.overrideBy(LightColorTokens.TextOnLightTertiary)
        textDefaultParagraph.overrideBy(LightColorTokens.TextOnLightParagraph)
        textDefaultAccent.overrideBy(LightColorTokens.TextOnLightAccent)
        textDefaultAccentMinor.overrideBy(LightColorTokens.TextOnLightAccentMinor)
        textDefaultPositive.overrideBy(LightColorTokens.TextOnLightPositive)
        textDefaultWarning.overrideBy(LightColorTokens.TextOnLightWarning)
        textDefaultNegative.overrideBy(LightColorTokens.TextOnLightNegative)
        textDefaultInfo.overrideBy(LightColorTokens.TextOnLightInfo)
        textDefaultPositiveMinor.overrideBy(LightColorTokens.TextOnLightPositiveMinor)
        textDefaultWarningMinor.overrideBy(LightColorTokens.TextOnLightWarningMinor)
        textDefaultNegativeMinor.overrideBy(LightColorTokens.TextOnLightNegativeMinor)
        textDefaultInfoMinor.overrideBy(LightColorTokens.TextOnLightInfoMinor)
        surfaceDefaultSolidPrimaryHover.overrideBy(LightColorTokens.SurfaceOnLightSolidPrimaryHover)
        surfaceDefaultSolidPrimaryActive.overrideBy(LightColorTokens.SurfaceOnLightSolidPrimaryActive)
        surfaceDefaultSolidPrimaryBrightness.overrideBy(LightColorTokens.SurfaceOnLightSolidPrimaryBrightness)
        surfaceDefaultSolidSecondaryHover.overrideBy(LightColorTokens.SurfaceOnLightSolidSecondaryHover)
        surfaceDefaultSolidSecondaryActive.overrideBy(LightColorTokens.SurfaceOnLightSolidSecondaryActive)
        surfaceDefaultSolidTertiaryHover.overrideBy(LightColorTokens.SurfaceOnLightSolidTertiaryHover)
        surfaceDefaultSolidTertiaryActive.overrideBy(LightColorTokens.SurfaceOnLightSolidTertiaryActive)
        surfaceDefaultSolidCardHover.overrideBy(LightColorTokens.SurfaceOnLightSolidCardHover)
        surfaceDefaultSolidCardActive.overrideBy(LightColorTokens.SurfaceOnLightSolidCardActive)
        surfaceDefaultSolidCardBrightness.overrideBy(LightColorTokens.SurfaceOnLightSolidCardBrightness)
        surfaceDefaultSolidDefaultHover.overrideBy(LightColorTokens.SurfaceOnLightSolidDefaultHover)
        surfaceDefaultSolidDefaultActive.overrideBy(LightColorTokens.SurfaceOnLightSolidDefaultActive)
        surfaceDefaultTransparentPrimaryHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentPrimaryHover)
        surfaceDefaultTransparentPrimaryActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentPrimaryActive)
        surfaceDefaultTransparentSecondaryHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentSecondaryHover)
        surfaceDefaultTransparentSecondaryActive.overrideBy(
            LightColorTokens.SurfaceOnLightTransparentSecondaryActive,
        )
        surfaceDefaultTransparentTertiaryHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentTertiaryHover)
        surfaceDefaultTransparentTertiaryActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentTertiaryActive)
        surfaceDefaultTransparentDeepHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentDeepHover)
        surfaceDefaultTransparentDeepActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentDeepActive)
        surfaceDefaultTransparentCardHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentCardHover)
        surfaceDefaultTransparentCardActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentCardActive)
        surfaceDefaultTransparentCardBrightness.overrideBy(LightColorTokens.SurfaceOnLightTransparentCardBrightness)
        surfaceDefaultClearHover.overrideBy(LightColorTokens.SurfaceOnLightClearHover)
        surfaceDefaultClearActive.overrideBy(LightColorTokens.SurfaceOnLightClearActive)
        surfaceDefaultAccentHover.overrideBy(LightColorTokens.SurfaceOnLightAccentHover)
        surfaceDefaultAccentActive.overrideBy(LightColorTokens.SurfaceOnLightAccentActive)
        surfaceDefaultAccentMinorHover.overrideBy(LightColorTokens.SurfaceOnLightAccentMinorHover)
        surfaceDefaultAccentMinorActive.overrideBy(LightColorTokens.SurfaceOnLightAccentMinorActive)
        surfaceDefaultTransparentAccentHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentAccentHover)
        surfaceDefaultTransparentAccentActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentAccentActive)
        surfaceDefaultPositiveHover.overrideBy(LightColorTokens.SurfaceOnLightPositiveHover)
        surfaceDefaultPositiveActive.overrideBy(LightColorTokens.SurfaceOnLightPositiveActive)
        surfaceDefaultWarningHover.overrideBy(LightColorTokens.SurfaceOnLightWarningHover)
        surfaceDefaultWarningActive.overrideBy(LightColorTokens.SurfaceOnLightWarningActive)
        surfaceDefaultNegativeHover.overrideBy(LightColorTokens.SurfaceOnLightNegativeHover)
        surfaceDefaultNegativeActive.overrideBy(LightColorTokens.SurfaceOnLightNegativeActive)
        surfaceDefaultInfoHover.overrideBy(LightColorTokens.SurfaceOnLightInfoHover)
        surfaceDefaultInfoActive.overrideBy(LightColorTokens.SurfaceOnLightInfoActive)
        surfaceDefaultPositiveMinorHover.overrideBy(LightColorTokens.SurfaceOnLightPositiveMinorHover)
        surfaceDefaultPositiveMinorActive.overrideBy(LightColorTokens.SurfaceOnLightPositiveMinorActive)
        surfaceDefaultWarningMinorHover.overrideBy(LightColorTokens.SurfaceOnLightWarningMinorHover)
        surfaceDefaultWarningMinorActive.overrideBy(LightColorTokens.SurfaceOnLightWarningMinorActive)
        surfaceDefaultNegativeMinorHover.overrideBy(LightColorTokens.SurfaceOnLightNegativeMinorHover)
        surfaceDefaultNegativeMinorActive.overrideBy(LightColorTokens.SurfaceOnLightNegativeMinorActive)
        surfaceDefaultInfoMinorHover.overrideBy(LightColorTokens.SurfaceOnLightInfoMinorHover)
        surfaceDefaultInfoMinorActive.overrideBy(LightColorTokens.SurfaceOnLightInfoMinorActive)
        surfaceDefaultTransparentNaviHover.overrideBy(LightColorTokens.SurfaceOnLightTransparentNaviHover)
        surfaceDefaultTransparentNaviActive.overrideBy(LightColorTokens.SurfaceOnLightTransparentNaviActive)
        surfaceDefaultSolidCard.overrideBy(LightColorTokens.SurfaceOnLightSolidCard)
        surfaceDefaultSolidPrimary.overrideBy(LightColorTokens.SurfaceOnLightSolidPrimary)
        surfaceDefaultSolidSecondary.overrideBy(LightColorTokens.SurfaceOnLightSolidSecondary)
        surfaceDefaultSolidTertiary.overrideBy(LightColorTokens.SurfaceOnLightSolidTertiary)
        surfaceDefaultSolidDefault.overrideBy(LightColorTokens.SurfaceOnLightSolidDefault)
        surfaceDefaultTransparentPrimary.overrideBy(LightColorTokens.SurfaceOnLightTransparentPrimary)
        surfaceDefaultTransparentSecondary.overrideBy(LightColorTokens.SurfaceOnLightTransparentSecondary)
        surfaceDefaultTransparentTertiary.overrideBy(LightColorTokens.SurfaceOnLightTransparentTertiary)
        surfaceDefaultTransparentDeep.overrideBy(LightColorTokens.SurfaceOnLightTransparentDeep)
        surfaceDefaultClear.overrideBy(LightColorTokens.SurfaceOnLightClear)
        surfaceDefaultAccent.overrideBy(LightColorTokens.SurfaceOnLightAccent)
        surfaceDefaultTransparentAccent.overrideBy(LightColorTokens.SurfaceOnLightTransparentAccent)
        surfaceDefaultAccentMinor.overrideBy(LightColorTokens.SurfaceOnLightAccentMinor)
        surfaceDefaultPositive.overrideBy(LightColorTokens.SurfaceOnLightPositive)
        surfaceDefaultWarning.overrideBy(LightColorTokens.SurfaceOnLightWarning)
        surfaceDefaultNegative.overrideBy(LightColorTokens.SurfaceOnLightNegative)
        surfaceDefaultInfo.overrideBy(LightColorTokens.SurfaceOnLightInfo)
        surfaceDefaultWarningMinor.overrideBy(LightColorTokens.SurfaceOnLightWarningMinor)
        surfaceDefaultNegativeMinor.overrideBy(LightColorTokens.SurfaceOnLightNegativeMinor)
        surfaceDefaultInfoMinor.overrideBy(LightColorTokens.SurfaceOnLightInfoMinor)
        surfaceDefaultPositiveMinor.overrideBy(LightColorTokens.SurfaceOnLightPositiveMinor)
        overlayDefaultHard.overrideBy(LightColorTokens.OverlayOnLightHard)
        overlayDefaultSoft.overrideBy(LightColorTokens.OverlayOnLightSoft)
        outlineDefaultTransparentPrimaryHover.overrideBy(LightColorTokens.OutlineOnLightTransparentPrimaryHover)
        outlineDefaultTransparentPrimaryActive.overrideBy(LightColorTokens.OutlineOnLightTransparentPrimaryActive)
        outlineDefaultClearHover.overrideBy(LightColorTokens.OutlineOnLightClearHover)
        outlineDefaultClearActive.overrideBy(LightColorTokens.OutlineOnLightClearActive)
        outlineDefaultPositiveHover.overrideBy(LightColorTokens.OutlineOnLightPositiveHover)
        outlineDefaultPositiveActive.overrideBy(LightColorTokens.OutlineOnLightPositiveActive)
        outlineDefaultWarningHover.overrideBy(LightColorTokens.OutlineOnLightWarningHover)
        outlineDefaultWarningActive.overrideBy(LightColorTokens.OutlineOnLightWarningActive)
        outlineDefaultNegativeHover.overrideBy(LightColorTokens.OutlineOnLightNegativeHover)
        outlineDefaultNegativeActive.overrideBy(LightColorTokens.OutlineOnLightNegativeActive)
        outlineDefaultInfoHover.overrideBy(LightColorTokens.OutlineOnLightInfoHover)
        outlineDefaultInfoActive.overrideBy(LightColorTokens.OutlineOnLightInfoActive)
        outlineDefaultSolidDefaultHover.overrideBy(LightColorTokens.OutlineOnLightSolidDefaultHover)
        outlineDefaultSolidDefaultActive.overrideBy(LightColorTokens.OutlineOnLightSolidDefaultActive)
        outlineDefaultTransparentSurfaceHover.overrideBy(LightColorTokens.OutlineOnLightTransparentSurfaceHover)
        outlineDefaultTransparentSurfaceActive.overrideBy(LightColorTokens.OutlineOnLightTransparentSurfaceActive)
        outlineDefaultSolidDefault.overrideBy(LightColorTokens.OutlineOnLightSolidDefault)
        outlineDefaultTransparentPrimary.overrideBy(LightColorTokens.OutlineOnLightTransparentPrimary)
        outlineDefaultPositive.overrideBy(LightColorTokens.OutlineOnLightPositive)
        outlineDefaultWarning.overrideBy(LightColorTokens.OutlineOnLightWarning)
        outlineDefaultNegative.overrideBy(LightColorTokens.OutlineOnLightNegative)
        outlineDefaultInfo.overrideBy(LightColorTokens.OutlineOnLightInfo)
        outlineDefaultClear.overrideBy(LightColorTokens.OutlineOnLightClear)
        dataDefaultYellow.overrideBy(LightColorTokens.DataOnLightYellow)
        dataDefaultYellowHover.overrideBy(LightColorTokens.DataOnLightYellowHover)
        dataDefaultYellowActive.overrideBy(LightColorTokens.DataOnLightYellowActive)
        dataDefaultYellowMinor.overrideBy(LightColorTokens.DataOnLightYellowMinor)
        dataDefaultYellowMinorHover.overrideBy(LightColorTokens.DataOnLightYellowMinorHover)
        dataDefaultYellowMinorActive.overrideBy(LightColorTokens.DataOnLightYellowMinorActive)
        dataDefaultYellowTransparent.overrideBy(LightColorTokens.DataOnLightYellowTransparent)
        dataDefaultYellowTransparentHover.overrideBy(LightColorTokens.DataOnLightYellowTransparentHover)
        dataDefaultYellowTransparentActive.overrideBy(LightColorTokens.DataOnLightYellowTransparentActive)
    }
}

private val darkOnLightGradients: SddsSbComGradients by lazy {
    darkSddsSbComGradients {
        textInverseAccentGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnDarkAccentGradientHover.colors,
                    DarkGradientTokens.TextOnDarkAccentGradientHover.positions,
                    DarkGradientTokens.TextOnDarkAccentGradientHover.angle,
                ),
            ),
        )
        textInverseAccentGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnDarkAccentGradientActive.colors,
                    DarkGradientTokens.TextOnDarkAccentGradientActive.positions,
                    DarkGradientTokens.TextOnDarkAccentGradientActive.angle,
                ),
            ),
        )
        textInverseAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnDarkAccentGradient.colors,
                    DarkGradientTokens.TextOnDarkAccentGradient.positions,
                    DarkGradientTokens.TextOnDarkAccentGradient.angle,
                ),
            ),
        )
        textInverseAccentGradientAi.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnDarkAccentGradientAi.colors,
                    DarkGradientTokens.TextOnDarkAccentGradientAi.positions,
                    DarkGradientTokens.TextOnDarkAccentGradientAi.angle,
                ),
            ),
        )
        textInverseAccentGradientAiHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnDarkAccentGradientAiHover.colors,
                    DarkGradientTokens.TextOnDarkAccentGradientAiHover.positions,
                    DarkGradientTokens.TextOnDarkAccentGradientAiHover.angle,
                ),
            ),
        )
        textInverseAccentGradientAiActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnDarkAccentGradientAiActive.colors,
                    DarkGradientTokens.TextOnDarkAccentGradientAiActive.positions,
                    DarkGradientTokens.TextOnDarkAccentGradientAiActive.angle,
                ),
            ),
        )
        surfaceInverseTransparentCard.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkTransparentCard.colors,
                    DarkGradientTokens.SurfaceOnDarkTransparentCard.positions,
                    DarkGradientTokens.SurfaceOnDarkTransparentCard.angle,
                ),
            ),
        )
        surfaceInverseTransparentNavi.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkTransparentNavi.colors,
                    DarkGradientTokens.SurfaceOnDarkTransparentNavi.positions,
                    DarkGradientTokens.SurfaceOnDarkTransparentNavi.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradient.colors,
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradient.positions,
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradient.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradientHover.colors,
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradientHover.positions,
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradientHover.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradientActive.colors,
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradientActive.positions,
                    DarkGradientTokens.SurfaceOnDarkSkeletonGradientActive.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkSkeletonDeepGradient.colors,
                    DarkGradientTokens.SurfaceOnDarkSkeletonDeepGradient.positions,
                    DarkGradientTokens.SurfaceOnDarkSkeletonDeepGradient.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkSkeletonDeepGradientHover.colors,
                    DarkGradientTokens.SurfaceOnDarkSkeletonDeepGradientHover.positions,
                    DarkGradientTokens.SurfaceOnDarkSkeletonDeepGradientHover.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnDarkSkeletonDeepGradientActive.colors,
                    DarkGradientTokens.SurfaceOnDarkSkeletonDeepGradientActive.positions,
                    DarkGradientTokens.SurfaceOnDarkSkeletonDeepGradientActive.angle,
                ),
            ),
        )
        overlayInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OverlayOnDarkGradient.colors,
                    DarkGradientTokens.OverlayOnDarkGradient.positions,
                    DarkGradientTokens.OverlayOnDarkGradient.angle,
                ),
            ),
        )
        outlineInverseTransparentSurface.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OutlineOnDarkTransparentSurface.colors,
                    DarkGradientTokens.OutlineOnDarkTransparentSurface.positions,
                    DarkGradientTokens.OutlineOnDarkTransparentSurface.angle,
                ),
            ),
        )
        textDefaultAccentGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnLightAccentGradientHover.colors,
                    DarkGradientTokens.TextOnLightAccentGradientHover.positions,
                    DarkGradientTokens.TextOnLightAccentGradientHover.angle,
                ),
            ),
        )
        textDefaultAccentGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnLightAccentGradientActive.colors,
                    DarkGradientTokens.TextOnLightAccentGradientActive.positions,
                    DarkGradientTokens.TextOnLightAccentGradientActive.angle,
                ),
            ),
        )
        textDefaultAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnLightAccentGradient.colors,
                    DarkGradientTokens.TextOnLightAccentGradient.positions,
                    DarkGradientTokens.TextOnLightAccentGradient.angle,
                ),
            ),
        )
        textDefaultAccentGradientAiHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnLightAccentGradientAiHover.colors,
                    DarkGradientTokens.TextOnLightAccentGradientAiHover.positions,
                    DarkGradientTokens.TextOnLightAccentGradientAiHover.angle,
                ),
            ),
        )
        textDefaultAccentGradientAiActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnLightAccentGradientAiActive.colors,
                    DarkGradientTokens.TextOnLightAccentGradientAiActive.positions,
                    DarkGradientTokens.TextOnLightAccentGradientAiActive.angle,
                ),
            ),
        )
        textDefaultAccentGradientAi.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextOnLightAccentGradientAi.colors,
                    DarkGradientTokens.TextOnLightAccentGradientAi.positions,
                    DarkGradientTokens.TextOnLightAccentGradientAi.angle,
                ),
            ),
        )
        surfaceDefaultTransparentCard.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightTransparentCard.colors,
                    DarkGradientTokens.SurfaceOnLightTransparentCard.positions,
                    DarkGradientTokens.SurfaceOnLightTransparentCard.angle,
                ),
            ),
        )
        surfaceDefaultTransparentNavi.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightTransparentNavi.colors,
                    DarkGradientTokens.SurfaceOnLightTransparentNavi.positions,
                    DarkGradientTokens.SurfaceOnLightTransparentNavi.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightSkeletonGradient.colors,
                    DarkGradientTokens.SurfaceOnLightSkeletonGradient.positions,
                    DarkGradientTokens.SurfaceOnLightSkeletonGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightSkeletonGradientHover.colors,
                    DarkGradientTokens.SurfaceOnLightSkeletonGradientHover.positions,
                    DarkGradientTokens.SurfaceOnLightSkeletonGradientHover.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightSkeletonGradientActive.colors,
                    DarkGradientTokens.SurfaceOnLightSkeletonGradientActive.positions,
                    DarkGradientTokens.SurfaceOnLightSkeletonGradientActive.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightSkeletonDeepGradient.colors,
                    DarkGradientTokens.SurfaceOnLightSkeletonDeepGradient.positions,
                    DarkGradientTokens.SurfaceOnLightSkeletonDeepGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradientHover.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightSkeletonDeepGradientHover.colors,
                    DarkGradientTokens.SurfaceOnLightSkeletonDeepGradientHover.positions,
                    DarkGradientTokens.SurfaceOnLightSkeletonDeepGradientHover.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradientActive.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceOnLightSkeletonDeepGradientActive.colors,
                    DarkGradientTokens.SurfaceOnLightSkeletonDeepGradientActive.positions,
                    DarkGradientTokens.SurfaceOnLightSkeletonDeepGradientActive.angle,
                ),
            ),
        )
        overlayDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OverlayOnLightGradient.colors,
                    DarkGradientTokens.OverlayOnLightGradient.positions,
                    DarkGradientTokens.OverlayOnLightGradient.angle,
                ),
            ),
        )
        outlineDefaultTransparentSurface.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OutlineOnLightTransparentSurface.colors,
                    DarkGradientTokens.OutlineOnLightTransparentSurface.positions,
                    DarkGradientTokens.OutlineOnLightTransparentSurface.angle,
                ),
            ),
        )
    }
}

private val lightOnLightGradients: SddsSbComGradients by lazy {
    lightSddsSbComGradients {
        textInverseAccentGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnDarkAccentGradientHover.colors,
                    LightGradientTokens.TextOnDarkAccentGradientHover.positions,
                    LightGradientTokens.TextOnDarkAccentGradientHover.angle,
                ),
            ),
        )
        textInverseAccentGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnDarkAccentGradientActive.colors,
                    LightGradientTokens.TextOnDarkAccentGradientActive.positions,
                    LightGradientTokens.TextOnDarkAccentGradientActive.angle,
                ),
            ),
        )
        textInverseAccentGradientAiHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnDarkAccentGradientAiHover.colors,
                    LightGradientTokens.TextOnDarkAccentGradientAiHover.positions,
                    LightGradientTokens.TextOnDarkAccentGradientAiHover.angle,
                ),
            ),
        )
        textInverseAccentGradientAiActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnDarkAccentGradientAiActive.colors,
                    LightGradientTokens.TextOnDarkAccentGradientAiActive.positions,
                    LightGradientTokens.TextOnDarkAccentGradientAiActive.angle,
                ),
            ),
        )
        textInverseAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnDarkAccentGradient.colors,
                    LightGradientTokens.TextOnDarkAccentGradient.positions,
                    LightGradientTokens.TextOnDarkAccentGradient.angle,
                ),
            ),
        )
        textInverseAccentGradientAi.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnDarkAccentGradientAi.colors,
                    LightGradientTokens.TextOnDarkAccentGradientAi.positions,
                    LightGradientTokens.TextOnDarkAccentGradientAi.angle,
                ),
            ),
        )
        surfaceInverseTransparentCard.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkTransparentCard.colors,
                    LightGradientTokens.SurfaceOnDarkTransparentCard.positions,
                    LightGradientTokens.SurfaceOnDarkTransparentCard.angle,
                ),
            ),
        )
        surfaceInverseTransparentNavi.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkTransparentNavi.colors,
                    LightGradientTokens.SurfaceOnDarkTransparentNavi.positions,
                    LightGradientTokens.SurfaceOnDarkTransparentNavi.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkSkeletonGradient.colors,
                    LightGradientTokens.SurfaceOnDarkSkeletonGradient.positions,
                    LightGradientTokens.SurfaceOnDarkSkeletonGradient.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkSkeletonGradientHover.colors,
                    LightGradientTokens.SurfaceOnDarkSkeletonGradientHover.positions,
                    LightGradientTokens.SurfaceOnDarkSkeletonGradientHover.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkSkeletonGradientActive.colors,
                    LightGradientTokens.SurfaceOnDarkSkeletonGradientActive.positions,
                    LightGradientTokens.SurfaceOnDarkSkeletonGradientActive.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkSkeletonDeepGradient.colors,
                    LightGradientTokens.SurfaceOnDarkSkeletonDeepGradient.positions,
                    LightGradientTokens.SurfaceOnDarkSkeletonDeepGradient.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkSkeletonDeepGradientHover.colors,
                    LightGradientTokens.SurfaceOnDarkSkeletonDeepGradientHover.positions,
                    LightGradientTokens.SurfaceOnDarkSkeletonDeepGradientHover.angle,
                ),
            ),
        )
        surfaceInverseSkeletonDeepGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnDarkSkeletonDeepGradientActive.colors,
                    LightGradientTokens.SurfaceOnDarkSkeletonDeepGradientActive.positions,
                    LightGradientTokens.SurfaceOnDarkSkeletonDeepGradientActive.angle,
                ),
            ),
        )
        overlayInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OverlayOnDarkGradient.colors,
                    LightGradientTokens.OverlayOnDarkGradient.positions,
                    LightGradientTokens.OverlayOnDarkGradient.angle,
                ),
            ),
        )
        outlineInverseTransparentSurface.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OutlineOnDarkTransparentSurface.colors,
                    LightGradientTokens.OutlineOnDarkTransparentSurface.positions,
                    LightGradientTokens.OutlineOnDarkTransparentSurface.angle,
                ),
            ),
        )
        textDefaultAccentGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnLightAccentGradientHover.colors,
                    LightGradientTokens.TextOnLightAccentGradientHover.positions,
                    LightGradientTokens.TextOnLightAccentGradientHover.angle,
                ),
            ),
        )
        textDefaultAccentGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnLightAccentGradientActive.colors,
                    LightGradientTokens.TextOnLightAccentGradientActive.positions,
                    LightGradientTokens.TextOnLightAccentGradientActive.angle,
                ),
            ),
        )
        textDefaultAccentGradientAiHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnLightAccentGradientAiHover.colors,
                    LightGradientTokens.TextOnLightAccentGradientAiHover.positions,
                    LightGradientTokens.TextOnLightAccentGradientAiHover.angle,
                ),
            ),
        )
        textDefaultAccentGradientAiActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnLightAccentGradientAiActive.colors,
                    LightGradientTokens.TextOnLightAccentGradientAiActive.positions,
                    LightGradientTokens.TextOnLightAccentGradientAiActive.angle,
                ),
            ),
        )
        textDefaultAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnLightAccentGradient.colors,
                    LightGradientTokens.TextOnLightAccentGradient.positions,
                    LightGradientTokens.TextOnLightAccentGradient.angle,
                ),
            ),
        )
        textDefaultAccentGradientAi.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextOnLightAccentGradientAi.colors,
                    LightGradientTokens.TextOnLightAccentGradientAi.positions,
                    LightGradientTokens.TextOnLightAccentGradientAi.angle,
                ),
            ),
        )
        surfaceDefaultTransparentCard.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightTransparentCard.colors,
                    LightGradientTokens.SurfaceOnLightTransparentCard.positions,
                    LightGradientTokens.SurfaceOnLightTransparentCard.angle,
                ),
            ),
        )
        surfaceDefaultTransparentNavi.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightTransparentNavi.colors,
                    LightGradientTokens.SurfaceOnLightTransparentNavi.positions,
                    LightGradientTokens.SurfaceOnLightTransparentNavi.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightSkeletonGradient.colors,
                    LightGradientTokens.SurfaceOnLightSkeletonGradient.positions,
                    LightGradientTokens.SurfaceOnLightSkeletonGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightSkeletonGradientHover.colors,
                    LightGradientTokens.SurfaceOnLightSkeletonGradientHover.positions,
                    LightGradientTokens.SurfaceOnLightSkeletonGradientHover.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightSkeletonGradientActive.colors,
                    LightGradientTokens.SurfaceOnLightSkeletonGradientActive.positions,
                    LightGradientTokens.SurfaceOnLightSkeletonGradientActive.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightSkeletonDeepGradient.colors,
                    LightGradientTokens.SurfaceOnLightSkeletonDeepGradient.positions,
                    LightGradientTokens.SurfaceOnLightSkeletonDeepGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradientHover.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightSkeletonDeepGradientHover.colors,
                    LightGradientTokens.SurfaceOnLightSkeletonDeepGradientHover.positions,
                    LightGradientTokens.SurfaceOnLightSkeletonDeepGradientHover.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonDeepGradientActive.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceOnLightSkeletonDeepGradientActive.colors,
                    LightGradientTokens.SurfaceOnLightSkeletonDeepGradientActive.positions,
                    LightGradientTokens.SurfaceOnLightSkeletonDeepGradientActive.angle,
                ),
            ),
        )
        overlayDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OverlayOnLightGradient.colors,
                    LightGradientTokens.OverlayOnLightGradient.positions,
                    LightGradientTokens.OverlayOnLightGradient.angle,
                ),
            ),
        )
        outlineDefaultTransparentSurface.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OutlineOnLightTransparentSurface.colors,
                    LightGradientTokens.OutlineOnLightTransparentSurface.positions,
                    LightGradientTokens.OutlineOnLightTransparentSurface.angle,
                ),
            ),
        )
    }
}

/**
 * Подтема SddsSbComTheme.OnLight
 */
@Composable
public fun SddsSbComTheme.OnLight(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable
    () -> Unit,
) {
    val colors = if (isDark) {
        darkOnLightColors
    } else {
        lightOnLightColors
    }
    val gradients = if (isDark) {
        darkOnLightGradients
    } else {
        lightOnLightGradients
    }
    SddsSbComTheme(
        colors = colors,
        gradients = gradients,
        content = content,
    )
}
