// AUTO-GENERATED. DO NOT MODIFY this file.
package com.sdds.sbcom.theme.subthemes

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import com.sdds.sbcom.theme.SddsSbComColors
import com.sdds.sbcom.theme.SddsSbComGradients
import com.sdds.sbcom.theme.SddsSbComTheme
import com.sdds.sbcom.theme.darkSddsSbComColors
import com.sdds.sbcom.theme.darkSddsSbComGradients
import com.sdds.sbcom.theme.lightSddsSbComColors
import com.sdds.sbcom.theme.lightSddsSbComGradients
import com.sdds.sbcom.theme.linearGradient
import com.sdds.sbcom.tokens.DarkColorTokens
import com.sdds.sbcom.tokens.DarkGradientTokens
import com.sdds.sbcom.tokens.LightColorTokens
import com.sdds.sbcom.tokens.LightGradientTokens
import kotlin.Boolean
import kotlin.Unit

private val darkInverseColors: SddsSbComColors by lazy {
    darkSddsSbComColors {
        outlineInverseDefaultActive.overrideBy(DarkColorTokens.OutlineDefaultDefaultActive)
        personasInverseSeaBlueTextAccentActive.overrideBy(DarkColorTokens.PersonasDefaultSeaBlueTextAccentActive)
        personasInverseVioletTextAccentActive.overrideBy(DarkColorTokens.PersonasDefaultVioletTextAccentActive)
        outlineInversePrimaryActive.overrideBy(DarkColorTokens.OutlineDefaultPrimaryActive)
        surfaceInverseAccentSecondaryHover.overrideBy(DarkColorTokens.SurfaceDefaultAccentSecondaryHover)
        personasInverseGreenTextAccentHover.overrideBy(DarkColorTokens.PersonasDefaultGreenTextAccentHover)
        outlineInverseDefault.overrideBy(DarkColorTokens.OutlineDefaultDefault)
        backgroundInverseHardline.overrideBy(DarkColorTokens.BackgroundDefaultHardline)
        personasInverseIndigoTextAccent.overrideBy(DarkColorTokens.PersonasDefaultIndigoTextAccent)
        personasInversePinkTextAccent.overrideBy(DarkColorTokens.PersonasDefaultPinkTextAccent)
        personasInverseOchreTextAccent.overrideBy(DarkColorTokens.PersonasDefaultOchreTextAccent)
        surfaceInverseTransparentNavi.overrideBy(DarkColorTokens.SurfaceDefaultTransparentNavi)
        surfaceInverseSolidPrimaryBrightnessHover.overrideBy(
            DarkColorTokens.SurfaceDefaultSolidPrimaryBrightnessHover,
        )
        surfaceInverseSolidPrimaryBrightnessActive.overrideBy(
            DarkColorTokens.SurfaceDefaultSolidPrimaryBrightnessActive,
        )
        surfaceInverseTransparentCardBrightnessHover.overrideBy(
            DarkColorTokens.SurfaceDefaultTransparentCardBrightnessHover,
        )
        personasInverseGreenTextAccent.overrideBy(DarkColorTokens.PersonasDefaultGreenTextAccent)
        surfaceInverseSolidTertiary.overrideBy(DarkColorTokens.SurfaceDefaultSolidTertiary)
        surfaceInverseTransparentCardBrightnessActive.overrideBy(
            DarkColorTokens.SurfaceDefaultTransparentCardBrightnessActive,
        )
        surfaceInverseAccentMinor.overrideBy(DarkColorTokens.SurfaceDefaultAccentMinor)
        surfaceInverseSolidCardBrightnessActive.overrideBy(DarkColorTokens.SurfaceDefaultSolidCardBrightnessActive)
        surfaceInverseAccentSecondaryActive.overrideBy(DarkColorTokens.SurfaceDefaultAccentSecondaryActive)
        personasInverseIndigoTextAccentActive.overrideBy(DarkColorTokens.PersonasDefaultIndigoTextAccentActive)
        personasInversePinkTextAccentActive.overrideBy(DarkColorTokens.PersonasDefaultPinkTextAccentActive)
        personasInverseGreenTextAccentActive.overrideBy(DarkColorTokens.PersonasDefaultGreenTextAccentActive)
        personasInverseOliveTextAccentHover.overrideBy(DarkColorTokens.PersonasDefaultOliveTextAccentHover)
        surfaceInverseAccentSecondary.overrideBy(DarkColorTokens.SurfaceDefaultAccentSecondary)
        personasInverseBlueTextAccentActive.overrideBy(DarkColorTokens.PersonasDefaultBlueTextAccentActive)
        surfaceInverseTransparentAccentMinorActive.overrideBy(
            DarkColorTokens.SurfaceDefaultTransparentAccentMinorActive,
        )
        personasInverseIndigoTextAccentHover.overrideBy(DarkColorTokens.PersonasDefaultIndigoTextAccentHover)
        personasInversePinkTextAccentHover.overrideBy(DarkColorTokens.PersonasDefaultPinkTextAccentHover)
        personasInverseOchreTextAccentHover.overrideBy(DarkColorTokens.PersonasDefaultOchreTextAccentHover)
        surfaceInverseTransparentNaviHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentNaviHover)
        outlineInverseDefaultHover.overrideBy(DarkColorTokens.OutlineDefaultDefaultHover)
        outlineInversePrimaryHover.overrideBy(DarkColorTokens.OutlineDefaultPrimaryHover)
        personasInverseSeaBlueTextAccentHover.overrideBy(DarkColorTokens.PersonasDefaultSeaBlueTextAccentHover)
        personasInverseBlueTextAccentHover.overrideBy(DarkColorTokens.PersonasDefaultBlueTextAccentHover)
        personasInverseVioletTextAccentHover.overrideBy(DarkColorTokens.PersonasDefaultVioletTextAccentHover)
        surfaceInverseTransparentAccentMinorHover.overrideBy(
            DarkColorTokens.SurfaceDefaultTransparentAccentMinorHover,
        )
        textInversePrimaryBrightnessHover.overrideBy(DarkColorTokens.TextDefaultPrimaryBrightnessHover)
        surfaceInverseSolidCardBrightnessHover.overrideBy(DarkColorTokens.SurfaceDefaultSolidCardBrightnessHover)
        personasInverseBlueTextAccent.overrideBy(DarkColorTokens.PersonasDefaultBlueTextAccent)
        personasInverseSeaBlueTextAccent.overrideBy(DarkColorTokens.PersonasDefaultSeaBlueTextAccent)
        personasInverseVioletTextAccent.overrideBy(DarkColorTokens.PersonasDefaultVioletTextAccent)
        surfaceInverseTransparentAccentMinor.overrideBy(DarkColorTokens.SurfaceDefaultTransparentAccentMinor)
        outlineInversePrimary.overrideBy(DarkColorTokens.OutlineDefaultPrimary)
        personasInverseOliveTextAccentActive.overrideBy(DarkColorTokens.PersonasDefaultOliveTextAccentActive)
        textInversePrimaryBrightnessActive.overrideBy(DarkColorTokens.TextDefaultPrimaryBrightnessActive)
        personasInverseOchreTextAccentActive.overrideBy(DarkColorTokens.PersonasDefaultOchreTextAccentActive)
        surfaceInverseTransparentNaviActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentNaviActive)
        personasInverseOliveTextAccent.overrideBy(DarkColorTokens.PersonasDefaultOliveTextAccent)
        textInversePrimary.overrideBy(DarkColorTokens.TextDefaultPrimary)
        textInversePrimaryHover.overrideBy(DarkColorTokens.TextDefaultPrimaryHover)
        textInversePrimaryActive.overrideBy(DarkColorTokens.TextDefaultPrimaryActive)
        textInversePrimaryBrightness.overrideBy(DarkColorTokens.TextDefaultPrimaryBrightness)
        textInverseSecondary.overrideBy(DarkColorTokens.TextDefaultSecondary)
        textInverseSecondaryHover.overrideBy(DarkColorTokens.TextDefaultSecondaryHover)
        textInverseSecondaryActive.overrideBy(DarkColorTokens.TextDefaultSecondaryActive)
        textInverseTertiary.overrideBy(DarkColorTokens.TextDefaultTertiary)
        textInverseTertiaryHover.overrideBy(DarkColorTokens.TextDefaultTertiaryHover)
        textInverseTertiaryActive.overrideBy(DarkColorTokens.TextDefaultTertiaryActive)
        textInverseParagraph.overrideBy(DarkColorTokens.TextDefaultParagraph)
        textInverseParagraphHover.overrideBy(DarkColorTokens.TextDefaultParagraphHover)
        textInverseParagraphActive.overrideBy(DarkColorTokens.TextDefaultParagraphActive)
        textInverseAccent.overrideBy(DarkColorTokens.TextDefaultAccent)
        textInverseAccentHover.overrideBy(DarkColorTokens.TextDefaultAccentHover)
        textInverseAccentActive.overrideBy(DarkColorTokens.TextDefaultAccentActive)
        textInverseAccentMinor.overrideBy(DarkColorTokens.TextDefaultAccentMinor)
        textInverseAccentMinorHover.overrideBy(DarkColorTokens.TextDefaultAccentMinorHover)
        textInverseAccentMinorActive.overrideBy(DarkColorTokens.TextDefaultAccentMinorActive)
        textInverseNegativeActive.overrideBy(DarkColorTokens.TextDefaultNegativeActive)
        textInverseInfo.overrideBy(DarkColorTokens.TextDefaultInfo)
        textInverseInfoHover.overrideBy(DarkColorTokens.TextDefaultInfoHover)
        textInverseInfoActive.overrideBy(DarkColorTokens.TextDefaultInfoActive)
        textInverseWarningActive.overrideBy(DarkColorTokens.TextDefaultWarningActive)
        textInversePositive.overrideBy(DarkColorTokens.TextDefaultPositive)
        textInversePositiveHover.overrideBy(DarkColorTokens.TextDefaultPositiveHover)
        textInverseWarning.overrideBy(DarkColorTokens.TextDefaultWarning)
        textInverseWarningHover.overrideBy(DarkColorTokens.TextDefaultWarningHover)
        textInversePositiveActive.overrideBy(DarkColorTokens.TextDefaultPositiveActive)
        textInverseNegative.overrideBy(DarkColorTokens.TextDefaultNegative)
        textInverseNegativeHover.overrideBy(DarkColorTokens.TextDefaultNegativeHover)
        surfaceInverseSolidPrimary.overrideBy(DarkColorTokens.SurfaceDefaultSolidPrimary)
        surfaceInverseSolidPrimaryHover.overrideBy(DarkColorTokens.SurfaceDefaultSolidPrimaryHover)
        surfaceInverseSolidPrimaryActive.overrideBy(DarkColorTokens.SurfaceDefaultSolidPrimaryActive)
        surfaceInverseSolidPrimaryBrightness.overrideBy(DarkColorTokens.SurfaceDefaultSolidPrimaryBrightness)
        surfaceInverseSolidSecondary.overrideBy(DarkColorTokens.SurfaceDefaultSolidSecondary)
        surfaceInverseSolidSecondaryHover.overrideBy(DarkColorTokens.SurfaceDefaultSolidSecondaryHover)
        surfaceInverseSolidSecondaryActive.overrideBy(DarkColorTokens.SurfaceDefaultSolidSecondaryActive)
        surfaceInverseTransparentSecondaryHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentSecondaryHover)
        surfaceInverseTransparentSecondaryActive.overrideBy(
            DarkColorTokens.SurfaceDefaultTransparentSecondaryActive,
        )
        surfaceInverseTransparentTertiary.overrideBy(DarkColorTokens.SurfaceDefaultTransparentTertiary)
        surfaceInverseTransparentTertiaryHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentTertiaryHover)
        surfaceInverseTransparentTertiaryActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentTertiaryActive)
        surfaceInverseTransparentDeep.overrideBy(DarkColorTokens.SurfaceDefaultTransparentDeep)
        surfaceInverseTransparentDeepHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentDeepHover)
        surfaceInverseTransparentDeepActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentDeepActive)
        surfaceInverseTransparentCard.overrideBy(DarkColorTokens.SurfaceDefaultTransparentCard)
        surfaceInverseTransparentCardHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentCardHover)
        surfaceInverseTransparentCardActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentCardActive)
        surfaceInverseTransparentCardBrightness.overrideBy(DarkColorTokens.SurfaceDefaultTransparentCardBrightness)
        surfaceInverseClear.overrideBy(DarkColorTokens.SurfaceDefaultClear)
        surfaceInverseClearHover.overrideBy(DarkColorTokens.SurfaceDefaultClearHover)
        surfaceInverseClearActive.overrideBy(DarkColorTokens.SurfaceDefaultClearActive)
        surfaceInverseAccent.overrideBy(DarkColorTokens.SurfaceDefaultAccent)
        surfaceInverseSolidTertiaryActive.overrideBy(DarkColorTokens.SurfaceDefaultSolidTertiaryActive)
        surfaceInverseSolidTertiaryHover.overrideBy(DarkColorTokens.SurfaceDefaultSolidTertiaryHover)
        surfaceInverseSolidCard.overrideBy(DarkColorTokens.SurfaceDefaultSolidCard)
        surfaceInverseSolidCardActive.overrideBy(DarkColorTokens.SurfaceDefaultSolidCardActive)
        surfaceInverseSolidCardHover.overrideBy(DarkColorTokens.SurfaceDefaultSolidCardHover)
        surfaceInverseSolidDefaultHover.overrideBy(DarkColorTokens.SurfaceDefaultSolidDefaultHover)
        surfaceInverseSolidDefaultActive.overrideBy(DarkColorTokens.SurfaceDefaultSolidDefaultActive)
        surfaceInverseSolidCardBrightness.overrideBy(DarkColorTokens.SurfaceDefaultSolidCardBrightness)
        surfaceInverseSolidDefault.overrideBy(DarkColorTokens.SurfaceDefaultSolidDefault)
        surfaceInverseTransparentPrimary.overrideBy(DarkColorTokens.SurfaceDefaultTransparentPrimary)
        surfaceInverseTransparentPrimaryHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentPrimaryHover)
        surfaceInverseTransparentPrimaryActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentPrimaryActive)
        surfaceInverseTransparentSecondary.overrideBy(DarkColorTokens.SurfaceDefaultTransparentSecondary)
        surfaceInversePositive.overrideBy(DarkColorTokens.SurfaceDefaultPositive)
        surfaceInversePositiveHover.overrideBy(DarkColorTokens.SurfaceDefaultPositiveHover)
        surfaceInversePositiveActive.overrideBy(DarkColorTokens.SurfaceDefaultPositiveActive)
        surfaceInverseWarning.overrideBy(DarkColorTokens.SurfaceDefaultWarning)
        surfaceInverseWarningHover.overrideBy(DarkColorTokens.SurfaceDefaultWarningHover)
        surfaceInverseWarningActive.overrideBy(DarkColorTokens.SurfaceDefaultWarningActive)
        surfaceInverseNegative.overrideBy(DarkColorTokens.SurfaceDefaultNegative)
        surfaceInverseNegativeHover.overrideBy(DarkColorTokens.SurfaceDefaultNegativeHover)
        surfaceInverseNegativeActive.overrideBy(DarkColorTokens.SurfaceDefaultNegativeActive)
        surfaceInverseInfo.overrideBy(DarkColorTokens.SurfaceDefaultInfo)
        surfaceInverseInfoHover.overrideBy(DarkColorTokens.SurfaceDefaultInfoHover)
        surfaceInverseInfoActive.overrideBy(DarkColorTokens.SurfaceDefaultInfoActive)
        surfaceInverseAccentMinorActive.overrideBy(DarkColorTokens.SurfaceDefaultAccentMinorActive)
        surfaceInverseAccentHover.overrideBy(DarkColorTokens.SurfaceDefaultAccentHover)
        surfaceInverseTransparentAccent.overrideBy(DarkColorTokens.SurfaceDefaultTransparentAccent)
        surfaceInverseTransparentAccentHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentAccentHover)
        surfaceInverseTransparentAccentActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentAccentActive)
        surfaceInverseAccentActive.overrideBy(DarkColorTokens.SurfaceDefaultAccentActive)
        surfaceInverseTransparentNegativeActive.overrideBy(DarkColorTokens.SurfaceDefaultTransparentNegativeActive)
        surfaceInverseTransparentNegative.overrideBy(DarkColorTokens.SurfaceDefaultTransparentNegative)
        surfaceInverseReadOnly.overrideBy(DarkColorTokens.SurfaceDefaultReadOnly)
        surfaceInverseReadOnlyHover.overrideBy(DarkColorTokens.SurfaceDefaultReadOnlyHover)
        surfaceInverseReadOnlyActive.overrideBy(DarkColorTokens.SurfaceDefaultReadOnlyActive)
        surfaceInverseTransparentNegativeHover.overrideBy(DarkColorTokens.SurfaceDefaultTransparentNegativeHover)
        overlayInverseSoft.overrideBy(DarkColorTokens.OverlayDefaultSoft)
        overlayInverseHard.overrideBy(DarkColorTokens.OverlayDefaultHard)
        backgroundInverseSecondary.overrideBy(DarkColorTokens.BackgroundDefaultSecondary)
        backgroundInverseTertiary.overrideBy(DarkColorTokens.BackgroundDefaultTertiary)
        backgroundInversePrimary.overrideBy(DarkColorTokens.BackgroundDefaultPrimary)
        outlineInverseTransparentPrimary.overrideBy(DarkColorTokens.OutlineDefaultTransparentPrimary)
        outlineInverseTransparentPrimaryHover.overrideBy(DarkColorTokens.OutlineDefaultTransparentPrimaryHover)
        outlineInverseTransparentPrimaryActive.overrideBy(DarkColorTokens.OutlineDefaultTransparentPrimaryActive)
        outlineInverseClear.overrideBy(DarkColorTokens.OutlineDefaultClear)
        outlineInverseClearHover.overrideBy(DarkColorTokens.OutlineDefaultClearHover)
        outlineInverseClearActive.overrideBy(DarkColorTokens.OutlineDefaultClearActive)
        outlineInverseWarningActive.overrideBy(DarkColorTokens.OutlineDefaultWarningActive)
        outlineInverseNegative.overrideBy(DarkColorTokens.OutlineDefaultNegative)
        outlineInverseNegativeHover.overrideBy(DarkColorTokens.OutlineDefaultNegativeHover)
        outlineInverseNegativeActive.overrideBy(DarkColorTokens.OutlineDefaultNegativeActive)
        outlineInverseInfo.overrideBy(DarkColorTokens.OutlineDefaultInfo)
        outlineInverseInfoHover.overrideBy(DarkColorTokens.OutlineDefaultInfoHover)
        outlineInverseInfoActive.overrideBy(DarkColorTokens.OutlineDefaultInfoActive)
        outlineInversePositiveActive.overrideBy(DarkColorTokens.OutlineDefaultPositiveActive)
        outlineInversePositive.overrideBy(DarkColorTokens.OutlineDefaultPositive)
        outlineInversePositiveHover.overrideBy(DarkColorTokens.OutlineDefaultPositiveHover)
        outlineInverseWarning.overrideBy(DarkColorTokens.OutlineDefaultWarning)
        outlineInverseWarningHover.overrideBy(DarkColorTokens.OutlineDefaultWarningHover)
        surfaceInverseAccentMinorHover.overrideBy(DarkColorTokens.SurfaceDefaultAccentMinorHover)
        personasDefaultGreenTextAccentHover.overrideBy(DarkColorTokens.PersonasInverseGreenTextAccentHover)
        personasDefaultSeaBlueTextAccentHover.overrideBy(DarkColorTokens.PersonasInverseSeaBlueTextAccentHover)
        surfaceDefaultTransparentNaviActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentNaviActive)
        outlineDefaultDefaultActive.overrideBy(DarkColorTokens.OutlineInverseDefaultActive)
        personasDefaultOliveTextAccentActive.overrideBy(DarkColorTokens.PersonasInverseOliveTextAccentActive)
        surfaceDefaultAccentSecondaryHover.overrideBy(DarkColorTokens.SurfaceInverseAccentSecondaryHover)
        personasDefaultIndigoTextAccentHover.overrideBy(DarkColorTokens.PersonasInverseIndigoTextAccentHover)
        personasDefaultOchreTextAccentActive.overrideBy(DarkColorTokens.PersonasInverseOchreTextAccentActive)
        surfaceDefaultTransparentNavi.overrideBy(DarkColorTokens.SurfaceInverseTransparentNavi)
        personasDefaultVioletTextAccentActive.overrideBy(DarkColorTokens.PersonasInverseVioletTextAccentActive)
        personasDefaultBlueTextAccentHover.overrideBy(DarkColorTokens.PersonasInverseBlueTextAccentHover)
        textDefaultPrimaryBrightnessActive.overrideBy(DarkColorTokens.TextInversePrimaryBrightnessActive)
        surfaceDefaultSolidCardBrightnessHover.overrideBy(DarkColorTokens.SurfaceInverseSolidCardBrightnessHover)
        surfaceDefaultTransparentCardBrightnessHover.overrideBy(
            DarkColorTokens.SurfaceInverseTransparentCardBrightnessHover,
        )
        surfaceDefaultSolidCardBrightnessActive.overrideBy(DarkColorTokens.SurfaceInverseSolidCardBrightnessActive)
        surfaceDefaultSolidPrimaryBrightnessHover.overrideBy(
            DarkColorTokens.SurfaceInverseSolidPrimaryBrightnessHover,
        )
        surfaceDefaultTransparentCardBrightnessActive.overrideBy(
            DarkColorTokens.SurfaceInverseTransparentCardBrightnessActive,
        )
        personasDefaultOliveTextAccent.overrideBy(DarkColorTokens.PersonasInverseOliveTextAccent)
        surfaceDefaultSolidTertiaryActive.overrideBy(DarkColorTokens.SurfaceInverseSolidTertiaryActive)
        textDefaultPrimary.overrideBy(DarkColorTokens.TextInversePrimary)
        outlineDefaultPrimary.overrideBy(DarkColorTokens.OutlineInversePrimary)
        surfaceDefaultAccentSecondary.overrideBy(DarkColorTokens.SurfaceInverseAccentSecondary)
        surfaceDefaultAccentMinor.overrideBy(DarkColorTokens.SurfaceInverseAccentMinor)
        personasDefaultOchreTextAccent.overrideBy(DarkColorTokens.PersonasInverseOchreTextAccent)
        personasDefaultGreenTextAccentActive.overrideBy(DarkColorTokens.PersonasInverseGreenTextAccentActive)
        personasDefaultSeaBlueTextAccentActive.overrideBy(DarkColorTokens.PersonasInverseSeaBlueTextAccentActive)
        outlineDefaultPrimaryActive.overrideBy(DarkColorTokens.OutlineInversePrimaryActive)
        personasDefaultIndigoTextAccentActive.overrideBy(DarkColorTokens.PersonasInverseIndigoTextAccentActive)
        personasDefaultOchreTextAccentHover.overrideBy(DarkColorTokens.PersonasInverseOchreTextAccentHover)
        textDefaultPrimaryBrightnessHover.overrideBy(DarkColorTokens.TextInversePrimaryBrightnessHover)
        surfaceDefaultTransparentNaviHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentNaviHover)
        outlineDefaultDefaultHover.overrideBy(DarkColorTokens.OutlineInverseDefaultHover)
        outlineDefaultPrimaryHover.overrideBy(DarkColorTokens.OutlineInversePrimaryHover)
        personasDefaultOliveTextAccentHover.overrideBy(DarkColorTokens.PersonasInverseOliveTextAccentHover)
        surfaceDefaultTransparentAccentMinorActive.overrideBy(
            DarkColorTokens.SurfaceInverseTransparentAccentMinorActive,
        )
        personasDefaultVioletTextAccent.overrideBy(DarkColorTokens.PersonasInverseVioletTextAccent)
        personasDefaultBlueTextAccent.overrideBy(DarkColorTokens.PersonasInverseBlueTextAccent)
        personasDefaultSeaBlueTextAccent.overrideBy(DarkColorTokens.PersonasInverseSeaBlueTextAccent)
        personasDefaultVioletTextAccentHover.overrideBy(DarkColorTokens.PersonasInverseVioletTextAccentHover)
        backgroundDefaultHardline.overrideBy(DarkColorTokens.BackgroundInverseHardline)
        surfaceDefaultSolidPrimaryBrightnessActive.overrideBy(
            DarkColorTokens.SurfaceInverseSolidPrimaryBrightnessActive,
        )
        personasDefaultBlueTextAccentActive.overrideBy(DarkColorTokens.PersonasInverseBlueTextAccentActive)
        surfaceDefaultAccentSecondaryActive.overrideBy(DarkColorTokens.SurfaceInverseAccentSecondaryActive)
        surfaceDefaultTransparentAccentMinor.overrideBy(DarkColorTokens.SurfaceInverseTransparentAccentMinor)
        personasDefaultPinkTextAccent.overrideBy(DarkColorTokens.PersonasInversePinkTextAccent)
        personasDefaultGreenTextAccent.overrideBy(DarkColorTokens.PersonasInverseGreenTextAccent)
        personasDefaultIndigoTextAccent.overrideBy(DarkColorTokens.PersonasInverseIndigoTextAccent)
        personasDefaultPinkTextAccentHover.overrideBy(DarkColorTokens.PersonasInversePinkTextAccentHover)
        surfaceDefaultTransparentAccentMinorHover.overrideBy(
            DarkColorTokens.SurfaceInverseTransparentAccentMinorHover,
        )
        personasDefaultPinkTextAccentActive.overrideBy(DarkColorTokens.PersonasInversePinkTextAccentActive)
        textDefaultParagraphActive.overrideBy(DarkColorTokens.TextInverseParagraphActive)
        textDefaultAccent.overrideBy(DarkColorTokens.TextInverseAccent)
        textDefaultAccentHover.overrideBy(DarkColorTokens.TextInverseAccentHover)
        textDefaultAccentActive.overrideBy(DarkColorTokens.TextInverseAccentActive)
        textDefaultAccentMinor.overrideBy(DarkColorTokens.TextInverseAccentMinor)
        textDefaultAccentMinorHover.overrideBy(DarkColorTokens.TextInverseAccentMinorHover)
        textDefaultAccentMinorActive.overrideBy(DarkColorTokens.TextInverseAccentMinorActive)
        textDefaultPositive.overrideBy(DarkColorTokens.TextInversePositive)
        textDefaultPositiveHover.overrideBy(DarkColorTokens.TextInversePositiveHover)
        textDefaultPositiveActive.overrideBy(DarkColorTokens.TextInversePositiveActive)
        textDefaultWarning.overrideBy(DarkColorTokens.TextInverseWarning)
        textDefaultWarningHover.overrideBy(DarkColorTokens.TextInverseWarningHover)
        textDefaultWarningActive.overrideBy(DarkColorTokens.TextInverseWarningActive)
        textDefaultNegative.overrideBy(DarkColorTokens.TextInverseNegative)
        textDefaultNegativeHover.overrideBy(DarkColorTokens.TextInverseNegativeHover)
        textDefaultNegativeActive.overrideBy(DarkColorTokens.TextInverseNegativeActive)
        textDefaultInfo.overrideBy(DarkColorTokens.TextInverseInfo)
        textDefaultInfoHover.overrideBy(DarkColorTokens.TextInverseInfoHover)
        textDefaultInfoActive.overrideBy(DarkColorTokens.TextInverseInfoActive)
        textDefaultSecondaryHover.overrideBy(DarkColorTokens.TextInverseSecondaryHover)
        textDefaultSecondary.overrideBy(DarkColorTokens.TextInverseSecondary)
        textDefaultPrimaryActive.overrideBy(DarkColorTokens.TextInversePrimaryActive)
        textDefaultSecondaryActive.overrideBy(DarkColorTokens.TextInverseSecondaryActive)
        textDefaultTertiary.overrideBy(DarkColorTokens.TextInverseTertiary)
        textDefaultTertiaryHover.overrideBy(DarkColorTokens.TextInverseTertiaryHover)
        textDefaultTertiaryActive.overrideBy(DarkColorTokens.TextInverseTertiaryActive)
        textDefaultPrimaryBrightness.overrideBy(DarkColorTokens.TextInversePrimaryBrightness)
        textDefaultParagraph.overrideBy(DarkColorTokens.TextInverseParagraph)
        textDefaultParagraphHover.overrideBy(DarkColorTokens.TextInverseParagraphHover)
        surfaceDefaultSolidPrimary.overrideBy(DarkColorTokens.SurfaceInverseSolidPrimary)
        surfaceDefaultSolidPrimaryHover.overrideBy(DarkColorTokens.SurfaceInverseSolidPrimaryHover)
        surfaceDefaultSolidPrimaryActive.overrideBy(DarkColorTokens.SurfaceInverseSolidPrimaryActive)
        surfaceDefaultSolidPrimaryBrightness.overrideBy(DarkColorTokens.SurfaceInverseSolidPrimaryBrightness)
        surfaceDefaultSolidSecondary.overrideBy(DarkColorTokens.SurfaceInverseSolidSecondary)
        surfaceDefaultSolidSecondaryHover.overrideBy(DarkColorTokens.SurfaceInverseSolidSecondaryHover)
        surfaceDefaultSolidSecondaryActive.overrideBy(DarkColorTokens.SurfaceInverseSolidSecondaryActive)
        surfaceDefaultSolidTertiary.overrideBy(DarkColorTokens.SurfaceInverseSolidTertiary)
        surfaceDefaultSolidTertiaryHover.overrideBy(DarkColorTokens.SurfaceInverseSolidTertiaryHover)
        surfaceDefaultTransparentSecondaryActive.overrideBy(
            DarkColorTokens.SurfaceInverseTransparentSecondaryActive,
        )
        surfaceDefaultTransparentTertiary.overrideBy(DarkColorTokens.SurfaceInverseTransparentTertiary)
        surfaceDefaultTransparentTertiaryHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentTertiaryHover)
        surfaceDefaultTransparentTertiaryActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentTertiaryActive)
        surfaceDefaultTransparentDeep.overrideBy(DarkColorTokens.SurfaceInverseTransparentDeep)
        surfaceDefaultTransparentDeepHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentDeepHover)
        surfaceDefaultTransparentDeepActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentDeepActive)
        surfaceDefaultTransparentCard.overrideBy(DarkColorTokens.SurfaceInverseTransparentCard)
        surfaceDefaultTransparentCardHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentCardHover)
        surfaceDefaultTransparentCardActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentCardActive)
        surfaceDefaultTransparentCardBrightness.overrideBy(DarkColorTokens.SurfaceInverseTransparentCardBrightness)
        surfaceDefaultClear.overrideBy(DarkColorTokens.SurfaceInverseClear)
        surfaceDefaultClearHover.overrideBy(DarkColorTokens.SurfaceInverseClearHover)
        surfaceDefaultClearActive.overrideBy(DarkColorTokens.SurfaceInverseClearActive)
        surfaceDefaultAccent.overrideBy(DarkColorTokens.SurfaceInverseAccent)
        surfaceDefaultAccentHover.overrideBy(DarkColorTokens.SurfaceInverseAccentHover)
        surfaceDefaultAccentActive.overrideBy(DarkColorTokens.SurfaceInverseAccentActive)
        surfaceDefaultAccentMinorHover.overrideBy(DarkColorTokens.SurfaceInverseAccentMinorHover)
        surfaceDefaultAccentMinorActive.overrideBy(DarkColorTokens.SurfaceInverseAccentMinorActive)
        surfaceDefaultTransparentAccent.overrideBy(DarkColorTokens.SurfaceInverseTransparentAccent)
        surfaceDefaultTransparentAccentHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentAccentHover)
        surfaceDefaultTransparentAccentActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentAccentActive)
        surfaceDefaultSolidCardActive.overrideBy(DarkColorTokens.SurfaceInverseSolidCardActive)
        surfaceDefaultSolidCard.overrideBy(DarkColorTokens.SurfaceInverseSolidCard)
        surfaceDefaultSolidCardBrightness.overrideBy(DarkColorTokens.SurfaceInverseSolidCardBrightness)
        surfaceDefaultSolidDefault.overrideBy(DarkColorTokens.SurfaceInverseSolidDefault)
        surfaceDefaultSolidDefaultHover.overrideBy(DarkColorTokens.SurfaceInverseSolidDefaultHover)
        surfaceDefaultTransparentPrimary.overrideBy(DarkColorTokens.SurfaceInverseTransparentPrimary)
        surfaceDefaultTransparentPrimaryHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentPrimaryHover)
        surfaceDefaultSolidDefaultActive.overrideBy(DarkColorTokens.SurfaceInverseSolidDefaultActive)
        surfaceDefaultSolidCardHover.overrideBy(DarkColorTokens.SurfaceInverseSolidCardHover)
        surfaceDefaultTransparentPrimaryActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentPrimaryActive)
        surfaceDefaultTransparentSecondary.overrideBy(DarkColorTokens.SurfaceInverseTransparentSecondary)
        surfaceDefaultTransparentSecondaryHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentSecondaryHover)
        surfaceDefaultWarningActive.overrideBy(DarkColorTokens.SurfaceInverseWarningActive)
        surfaceDefaultNegative.overrideBy(DarkColorTokens.SurfaceInverseNegative)
        surfaceDefaultNegativeHover.overrideBy(DarkColorTokens.SurfaceInverseNegativeHover)
        surfaceDefaultNegativeActive.overrideBy(DarkColorTokens.SurfaceInverseNegativeActive)
        surfaceDefaultInfo.overrideBy(DarkColorTokens.SurfaceInverseInfo)
        surfaceDefaultInfoHover.overrideBy(DarkColorTokens.SurfaceInverseInfoHover)
        surfaceDefaultInfoActive.overrideBy(DarkColorTokens.SurfaceInverseInfoActive)
        surfaceDefaultPositiveActive.overrideBy(DarkColorTokens.SurfaceInversePositiveActive)
        surfaceDefaultPositive.overrideBy(DarkColorTokens.SurfaceInversePositive)
        surfaceDefaultPositiveHover.overrideBy(DarkColorTokens.SurfaceInversePositiveHover)
        surfaceDefaultWarning.overrideBy(DarkColorTokens.SurfaceInverseWarning)
        surfaceDefaultWarningHover.overrideBy(DarkColorTokens.SurfaceInverseWarningHover)
        surfaceDefaultTransparentNegative.overrideBy(DarkColorTokens.SurfaceInverseTransparentNegative)
        surfaceDefaultTransparentNegativeHover.overrideBy(DarkColorTokens.SurfaceInverseTransparentNegativeHover)
        surfaceDefaultReadOnly.overrideBy(DarkColorTokens.SurfaceInverseReadOnly)
        surfaceDefaultReadOnlyHover.overrideBy(DarkColorTokens.SurfaceInverseReadOnlyHover)
        surfaceDefaultReadOnlyActive.overrideBy(DarkColorTokens.SurfaceInverseReadOnlyActive)
        surfaceDefaultTransparentNegativeActive.overrideBy(DarkColorTokens.SurfaceInverseTransparentNegativeActive)
        backgroundDefaultPrimary.overrideBy(DarkColorTokens.BackgroundInversePrimary)
        backgroundDefaultSecondary.overrideBy(DarkColorTokens.BackgroundInverseSecondary)
        backgroundDefaultTertiary.overrideBy(DarkColorTokens.BackgroundInverseTertiary)
        outlineDefaultTransparentPrimary.overrideBy(DarkColorTokens.OutlineInverseTransparentPrimary)
        outlineDefaultTransparentPrimaryHover.overrideBy(DarkColorTokens.OutlineInverseTransparentPrimaryHover)
        outlineDefaultTransparentPrimaryActive.overrideBy(DarkColorTokens.OutlineInverseTransparentPrimaryActive)
        outlineDefaultClear.overrideBy(DarkColorTokens.OutlineInverseClear)
        overlayDefaultSoft.overrideBy(DarkColorTokens.OverlayInverseSoft)
        overlayDefaultHard.overrideBy(DarkColorTokens.OverlayInverseHard)
        outlineDefaultPositive.overrideBy(DarkColorTokens.OutlineInversePositive)
        outlineDefaultPositiveHover.overrideBy(DarkColorTokens.OutlineInversePositiveHover)
        outlineDefaultPositiveActive.overrideBy(DarkColorTokens.OutlineInversePositiveActive)
        outlineDefaultWarning.overrideBy(DarkColorTokens.OutlineInverseWarning)
        outlineDefaultWarningHover.overrideBy(DarkColorTokens.OutlineInverseWarningHover)
        outlineDefaultWarningActive.overrideBy(DarkColorTokens.OutlineInverseWarningActive)
        outlineDefaultNegative.overrideBy(DarkColorTokens.OutlineInverseNegative)
        outlineDefaultNegativeHover.overrideBy(DarkColorTokens.OutlineInverseNegativeHover)
        outlineDefaultNegativeActive.overrideBy(DarkColorTokens.OutlineInverseNegativeActive)
        outlineDefaultInfo.overrideBy(DarkColorTokens.OutlineInverseInfo)
        outlineDefaultInfoHover.overrideBy(DarkColorTokens.OutlineInverseInfoHover)
        outlineDefaultInfoActive.overrideBy(DarkColorTokens.OutlineInverseInfoActive)
        outlineDefaultClearActive.overrideBy(DarkColorTokens.OutlineInverseClearActive)
        outlineDefaultClearHover.overrideBy(DarkColorTokens.OutlineInverseClearHover)
        textDefaultPrimaryHover.overrideBy(DarkColorTokens.TextInversePrimaryHover)
    }
}

private val lightInverseColors: SddsSbComColors by lazy {
    lightSddsSbComColors {
        outlineInverseDefaultActive.overrideBy(LightColorTokens.OutlineDefaultDefaultActive)
        personasInverseSeaBlueTextAccentActive.overrideBy(LightColorTokens.PersonasDefaultSeaBlueTextAccentActive)
        personasInverseVioletTextAccentActive.overrideBy(LightColorTokens.PersonasDefaultVioletTextAccentActive)
        outlineInversePrimaryActive.overrideBy(LightColorTokens.OutlineDefaultPrimaryActive)
        surfaceInverseAccentSecondaryHover.overrideBy(LightColorTokens.SurfaceDefaultAccentSecondaryHover)
        personasInverseGreenTextAccentHover.overrideBy(LightColorTokens.PersonasDefaultGreenTextAccentHover)
        outlineInverseDefault.overrideBy(LightColorTokens.OutlineDefaultDefault)
        backgroundInverseHardline.overrideBy(LightColorTokens.BackgroundDefaultHardline)
        personasInverseIndigoTextAccent.overrideBy(LightColorTokens.PersonasDefaultIndigoTextAccent)
        personasInversePinkTextAccent.overrideBy(LightColorTokens.PersonasDefaultPinkTextAccent)
        personasInverseOchreTextAccent.overrideBy(LightColorTokens.PersonasDefaultOchreTextAccent)
        surfaceInverseTransparentNavi.overrideBy(LightColorTokens.SurfaceDefaultTransparentNavi)
        surfaceInverseSolidPrimaryBrightnessHover.overrideBy(
            LightColorTokens.SurfaceDefaultSolidPrimaryBrightnessHover,
        )
        surfaceInverseSolidPrimaryBrightnessActive.overrideBy(
            LightColorTokens.SurfaceDefaultSolidPrimaryBrightnessActive,
        )
        surfaceInverseTransparentCardBrightnessHover.overrideBy(
            LightColorTokens.SurfaceDefaultTransparentCardBrightnessHover,
        )
        personasInverseGreenTextAccent.overrideBy(LightColorTokens.PersonasDefaultGreenTextAccent)
        surfaceInverseSolidTertiary.overrideBy(LightColorTokens.SurfaceDefaultSolidTertiary)
        surfaceInverseTransparentCardBrightnessActive.overrideBy(
            LightColorTokens.SurfaceDefaultTransparentCardBrightnessActive,
        )
        surfaceInverseAccentMinor.overrideBy(LightColorTokens.SurfaceDefaultAccentMinor)
        surfaceInverseSolidCardBrightnessActive.overrideBy(LightColorTokens.SurfaceDefaultSolidCardBrightnessActive)
        surfaceInverseAccentSecondaryActive.overrideBy(LightColorTokens.SurfaceDefaultAccentSecondaryActive)
        personasInverseIndigoTextAccentActive.overrideBy(LightColorTokens.PersonasDefaultIndigoTextAccentActive)
        personasInversePinkTextAccentActive.overrideBy(LightColorTokens.PersonasDefaultPinkTextAccentActive)
        personasInverseGreenTextAccentActive.overrideBy(LightColorTokens.PersonasDefaultGreenTextAccentActive)
        personasInverseOliveTextAccentHover.overrideBy(LightColorTokens.PersonasDefaultOliveTextAccentHover)
        surfaceInverseAccentSecondary.overrideBy(LightColorTokens.SurfaceDefaultAccentSecondary)
        personasInverseBlueTextAccentActive.overrideBy(LightColorTokens.PersonasDefaultBlueTextAccentActive)
        surfaceInverseTransparentAccentMinorActive.overrideBy(
            LightColorTokens.SurfaceDefaultTransparentAccentMinorActive,
        )
        personasInverseIndigoTextAccentHover.overrideBy(LightColorTokens.PersonasDefaultIndigoTextAccentHover)
        personasInversePinkTextAccentHover.overrideBy(LightColorTokens.PersonasDefaultPinkTextAccentHover)
        personasInverseOchreTextAccentHover.overrideBy(LightColorTokens.PersonasDefaultOchreTextAccentHover)
        surfaceInverseTransparentNaviHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentNaviHover)
        outlineInverseDefaultHover.overrideBy(LightColorTokens.OutlineDefaultDefaultHover)
        outlineInversePrimaryHover.overrideBy(LightColorTokens.OutlineDefaultPrimaryHover)
        personasInverseSeaBlueTextAccentHover.overrideBy(LightColorTokens.PersonasDefaultSeaBlueTextAccentHover)
        personasInverseBlueTextAccentHover.overrideBy(LightColorTokens.PersonasDefaultBlueTextAccentHover)
        personasInverseVioletTextAccentHover.overrideBy(LightColorTokens.PersonasDefaultVioletTextAccentHover)
        surfaceInverseTransparentAccentMinorHover.overrideBy(
            LightColorTokens.SurfaceDefaultTransparentAccentMinorHover,
        )
        textInversePrimaryBrightnessHover.overrideBy(LightColorTokens.TextDefaultPrimaryBrightnessHover)
        surfaceInverseSolidCardBrightnessHover.overrideBy(LightColorTokens.SurfaceDefaultSolidCardBrightnessHover)
        personasInverseBlueTextAccent.overrideBy(LightColorTokens.PersonasDefaultBlueTextAccent)
        personasInverseSeaBlueTextAccent.overrideBy(LightColorTokens.PersonasDefaultSeaBlueTextAccent)
        personasInverseVioletTextAccent.overrideBy(LightColorTokens.PersonasDefaultVioletTextAccent)
        surfaceInverseTransparentAccentMinor.overrideBy(LightColorTokens.SurfaceDefaultTransparentAccentMinor)
        outlineInversePrimary.overrideBy(LightColorTokens.OutlineDefaultPrimary)
        personasInverseOliveTextAccentActive.overrideBy(LightColorTokens.PersonasDefaultOliveTextAccentActive)
        textInversePrimaryBrightnessActive.overrideBy(LightColorTokens.TextDefaultPrimaryBrightnessActive)
        personasInverseOchreTextAccentActive.overrideBy(LightColorTokens.PersonasDefaultOchreTextAccentActive)
        surfaceInverseTransparentNaviActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentNaviActive)
        personasInverseOliveTextAccent.overrideBy(LightColorTokens.PersonasDefaultOliveTextAccent)
        textInversePrimary.overrideBy(LightColorTokens.TextDefaultPrimary)
        textInversePrimaryHover.overrideBy(LightColorTokens.TextDefaultPrimaryHover)
        textInversePrimaryActive.overrideBy(LightColorTokens.TextDefaultPrimaryActive)
        textInversePrimaryBrightness.overrideBy(LightColorTokens.TextDefaultPrimaryBrightness)
        textInverseSecondary.overrideBy(LightColorTokens.TextDefaultSecondary)
        textInverseSecondaryHover.overrideBy(LightColorTokens.TextDefaultSecondaryHover)
        textInverseSecondaryActive.overrideBy(LightColorTokens.TextDefaultSecondaryActive)
        textInverseTertiary.overrideBy(LightColorTokens.TextDefaultTertiary)
        textInverseTertiaryHover.overrideBy(LightColorTokens.TextDefaultTertiaryHover)
        textInverseTertiaryActive.overrideBy(LightColorTokens.TextDefaultTertiaryActive)
        textInverseParagraph.overrideBy(LightColorTokens.TextDefaultParagraph)
        textInverseParagraphHover.overrideBy(LightColorTokens.TextDefaultParagraphHover)
        textInverseParagraphActive.overrideBy(LightColorTokens.TextDefaultParagraphActive)
        textInverseAccent.overrideBy(LightColorTokens.TextDefaultAccent)
        textInverseAccentHover.overrideBy(LightColorTokens.TextDefaultAccentHover)
        textInverseAccentActive.overrideBy(LightColorTokens.TextDefaultAccentActive)
        textInverseAccentMinor.overrideBy(LightColorTokens.TextDefaultAccentMinor)
        textInverseAccentMinorHover.overrideBy(LightColorTokens.TextDefaultAccentMinorHover)
        textInverseAccentMinorActive.overrideBy(LightColorTokens.TextDefaultAccentMinorActive)
        textInverseNegativeActive.overrideBy(LightColorTokens.TextDefaultNegativeActive)
        textInverseInfo.overrideBy(LightColorTokens.TextDefaultInfo)
        textInverseInfoHover.overrideBy(LightColorTokens.TextDefaultInfoHover)
        textInverseInfoActive.overrideBy(LightColorTokens.TextDefaultInfoActive)
        textInverseWarningActive.overrideBy(LightColorTokens.TextDefaultWarningActive)
        textInversePositive.overrideBy(LightColorTokens.TextDefaultPositive)
        textInversePositiveHover.overrideBy(LightColorTokens.TextDefaultPositiveHover)
        textInverseWarning.overrideBy(LightColorTokens.TextDefaultWarning)
        textInverseWarningHover.overrideBy(LightColorTokens.TextDefaultWarningHover)
        textInversePositiveActive.overrideBy(LightColorTokens.TextDefaultPositiveActive)
        textInverseNegative.overrideBy(LightColorTokens.TextDefaultNegative)
        textInverseNegativeHover.overrideBy(LightColorTokens.TextDefaultNegativeHover)
        surfaceInverseSolidPrimary.overrideBy(LightColorTokens.SurfaceDefaultSolidPrimary)
        surfaceInverseSolidPrimaryHover.overrideBy(LightColorTokens.SurfaceDefaultSolidPrimaryHover)
        surfaceInverseSolidPrimaryActive.overrideBy(LightColorTokens.SurfaceDefaultSolidPrimaryActive)
        surfaceInverseSolidPrimaryBrightness.overrideBy(LightColorTokens.SurfaceDefaultSolidPrimaryBrightness)
        surfaceInverseSolidSecondary.overrideBy(LightColorTokens.SurfaceDefaultSolidSecondary)
        surfaceInverseSolidSecondaryHover.overrideBy(LightColorTokens.SurfaceDefaultSolidSecondaryHover)
        surfaceInverseSolidSecondaryActive.overrideBy(LightColorTokens.SurfaceDefaultSolidSecondaryActive)
        surfaceInverseTransparentSecondaryHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentSecondaryHover)
        surfaceInverseTransparentSecondaryActive.overrideBy(
            LightColorTokens.SurfaceDefaultTransparentSecondaryActive,
        )
        surfaceInverseTransparentTertiary.overrideBy(LightColorTokens.SurfaceDefaultTransparentTertiary)
        surfaceInverseTransparentTertiaryHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentTertiaryHover)
        surfaceInverseTransparentTertiaryActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentTertiaryActive)
        surfaceInverseTransparentDeep.overrideBy(LightColorTokens.SurfaceDefaultTransparentDeep)
        surfaceInverseTransparentDeepHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentDeepHover)
        surfaceInverseTransparentDeepActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentDeepActive)
        surfaceInverseTransparentCard.overrideBy(LightColorTokens.SurfaceDefaultTransparentCard)
        surfaceInverseTransparentCardHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentCardHover)
        surfaceInverseTransparentCardActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentCardActive)
        surfaceInverseTransparentCardBrightness.overrideBy(LightColorTokens.SurfaceDefaultTransparentCardBrightness)
        surfaceInverseClear.overrideBy(LightColorTokens.SurfaceDefaultClear)
        surfaceInverseClearHover.overrideBy(LightColorTokens.SurfaceDefaultClearHover)
        surfaceInverseClearActive.overrideBy(LightColorTokens.SurfaceDefaultClearActive)
        surfaceInverseAccent.overrideBy(LightColorTokens.SurfaceDefaultAccent)
        surfaceInverseSolidTertiaryActive.overrideBy(LightColorTokens.SurfaceDefaultSolidTertiaryActive)
        surfaceInverseSolidTertiaryHover.overrideBy(LightColorTokens.SurfaceDefaultSolidTertiaryHover)
        surfaceInverseSolidCard.overrideBy(LightColorTokens.SurfaceDefaultSolidCard)
        surfaceInverseSolidCardActive.overrideBy(LightColorTokens.SurfaceDefaultSolidCardActive)
        surfaceInverseSolidCardHover.overrideBy(LightColorTokens.SurfaceDefaultSolidCardHover)
        surfaceInverseSolidDefaultHover.overrideBy(LightColorTokens.SurfaceDefaultSolidDefaultHover)
        surfaceInverseSolidDefaultActive.overrideBy(LightColorTokens.SurfaceDefaultSolidDefaultActive)
        surfaceInverseSolidCardBrightness.overrideBy(LightColorTokens.SurfaceDefaultSolidCardBrightness)
        surfaceInverseSolidDefault.overrideBy(LightColorTokens.SurfaceDefaultSolidDefault)
        surfaceInverseTransparentPrimary.overrideBy(LightColorTokens.SurfaceDefaultTransparentPrimary)
        surfaceInverseTransparentPrimaryHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentPrimaryHover)
        surfaceInverseTransparentPrimaryActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentPrimaryActive)
        surfaceInverseTransparentSecondary.overrideBy(LightColorTokens.SurfaceDefaultTransparentSecondary)
        surfaceInversePositive.overrideBy(LightColorTokens.SurfaceDefaultPositive)
        surfaceInversePositiveHover.overrideBy(LightColorTokens.SurfaceDefaultPositiveHover)
        surfaceInversePositiveActive.overrideBy(LightColorTokens.SurfaceDefaultPositiveActive)
        surfaceInverseWarning.overrideBy(LightColorTokens.SurfaceDefaultWarning)
        surfaceInverseWarningHover.overrideBy(LightColorTokens.SurfaceDefaultWarningHover)
        surfaceInverseWarningActive.overrideBy(LightColorTokens.SurfaceDefaultWarningActive)
        surfaceInverseNegative.overrideBy(LightColorTokens.SurfaceDefaultNegative)
        surfaceInverseNegativeHover.overrideBy(LightColorTokens.SurfaceDefaultNegativeHover)
        surfaceInverseNegativeActive.overrideBy(LightColorTokens.SurfaceDefaultNegativeActive)
        surfaceInverseInfo.overrideBy(LightColorTokens.SurfaceDefaultInfo)
        surfaceInverseInfoHover.overrideBy(LightColorTokens.SurfaceDefaultInfoHover)
        surfaceInverseInfoActive.overrideBy(LightColorTokens.SurfaceDefaultInfoActive)
        surfaceInverseAccentMinorActive.overrideBy(LightColorTokens.SurfaceDefaultAccentMinorActive)
        surfaceInverseAccentHover.overrideBy(LightColorTokens.SurfaceDefaultAccentHover)
        surfaceInverseTransparentAccent.overrideBy(LightColorTokens.SurfaceDefaultTransparentAccent)
        surfaceInverseTransparentAccentHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentAccentHover)
        surfaceInverseTransparentAccentActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentAccentActive)
        surfaceInverseAccentActive.overrideBy(LightColorTokens.SurfaceDefaultAccentActive)
        surfaceInverseTransparentNegativeActive.overrideBy(LightColorTokens.SurfaceDefaultTransparentNegativeActive)
        surfaceInverseTransparentNegative.overrideBy(LightColorTokens.SurfaceDefaultTransparentNegative)
        surfaceInverseReadOnly.overrideBy(LightColorTokens.SurfaceDefaultReadOnly)
        surfaceInverseReadOnlyHover.overrideBy(LightColorTokens.SurfaceDefaultReadOnlyHover)
        surfaceInverseReadOnlyActive.overrideBy(LightColorTokens.SurfaceDefaultReadOnlyActive)
        surfaceInverseTransparentNegativeHover.overrideBy(LightColorTokens.SurfaceDefaultTransparentNegativeHover)
        overlayInverseSoft.overrideBy(LightColorTokens.OverlayDefaultSoft)
        overlayInverseHard.overrideBy(LightColorTokens.OverlayDefaultHard)
        backgroundInverseSecondary.overrideBy(LightColorTokens.BackgroundDefaultSecondary)
        backgroundInverseTertiary.overrideBy(LightColorTokens.BackgroundDefaultTertiary)
        backgroundInversePrimary.overrideBy(LightColorTokens.BackgroundDefaultPrimary)
        outlineInverseTransparentPrimary.overrideBy(LightColorTokens.OutlineDefaultTransparentPrimary)
        outlineInverseTransparentPrimaryHover.overrideBy(LightColorTokens.OutlineDefaultTransparentPrimaryHover)
        outlineInverseTransparentPrimaryActive.overrideBy(LightColorTokens.OutlineDefaultTransparentPrimaryActive)
        outlineInverseClear.overrideBy(LightColorTokens.OutlineDefaultClear)
        outlineInverseClearHover.overrideBy(LightColorTokens.OutlineDefaultClearHover)
        outlineInverseClearActive.overrideBy(LightColorTokens.OutlineDefaultClearActive)
        outlineInverseWarningActive.overrideBy(LightColorTokens.OutlineDefaultWarningActive)
        outlineInverseNegative.overrideBy(LightColorTokens.OutlineDefaultNegative)
        outlineInverseNegativeHover.overrideBy(LightColorTokens.OutlineDefaultNegativeHover)
        outlineInverseNegativeActive.overrideBy(LightColorTokens.OutlineDefaultNegativeActive)
        outlineInverseInfo.overrideBy(LightColorTokens.OutlineDefaultInfo)
        outlineInverseInfoHover.overrideBy(LightColorTokens.OutlineDefaultInfoHover)
        outlineInverseInfoActive.overrideBy(LightColorTokens.OutlineDefaultInfoActive)
        outlineInversePositiveActive.overrideBy(LightColorTokens.OutlineDefaultPositiveActive)
        outlineInversePositive.overrideBy(LightColorTokens.OutlineDefaultPositive)
        outlineInversePositiveHover.overrideBy(LightColorTokens.OutlineDefaultPositiveHover)
        outlineInverseWarning.overrideBy(LightColorTokens.OutlineDefaultWarning)
        outlineInverseWarningHover.overrideBy(LightColorTokens.OutlineDefaultWarningHover)
        surfaceInverseAccentMinorHover.overrideBy(LightColorTokens.SurfaceDefaultAccentMinorHover)
        personasDefaultGreenTextAccentHover.overrideBy(LightColorTokens.PersonasInverseGreenTextAccentHover)
        personasDefaultSeaBlueTextAccentHover.overrideBy(LightColorTokens.PersonasInverseSeaBlueTextAccentHover)
        surfaceDefaultTransparentNaviActive.overrideBy(LightColorTokens.SurfaceInverseTransparentNaviActive)
        outlineDefaultDefaultActive.overrideBy(LightColorTokens.OutlineInverseDefaultActive)
        personasDefaultOliveTextAccentActive.overrideBy(LightColorTokens.PersonasInverseOliveTextAccentActive)
        surfaceDefaultAccentSecondaryHover.overrideBy(LightColorTokens.SurfaceInverseAccentSecondaryHover)
        personasDefaultIndigoTextAccentHover.overrideBy(LightColorTokens.PersonasInverseIndigoTextAccentHover)
        personasDefaultOchreTextAccentActive.overrideBy(LightColorTokens.PersonasInverseOchreTextAccentActive)
        surfaceDefaultTransparentNavi.overrideBy(LightColorTokens.SurfaceInverseTransparentNavi)
        personasDefaultVioletTextAccentActive.overrideBy(LightColorTokens.PersonasInverseVioletTextAccentActive)
        personasDefaultBlueTextAccentHover.overrideBy(LightColorTokens.PersonasInverseBlueTextAccentHover)
        textDefaultPrimaryBrightnessActive.overrideBy(LightColorTokens.TextInversePrimaryBrightnessActive)
        surfaceDefaultSolidCardBrightnessHover.overrideBy(LightColorTokens.SurfaceInverseSolidCardBrightnessHover)
        surfaceDefaultTransparentCardBrightnessHover.overrideBy(
            LightColorTokens.SurfaceInverseTransparentCardBrightnessHover,
        )
        surfaceDefaultSolidCardBrightnessActive.overrideBy(LightColorTokens.SurfaceInverseSolidCardBrightnessActive)
        surfaceDefaultSolidPrimaryBrightnessHover.overrideBy(
            LightColorTokens.SurfaceInverseSolidPrimaryBrightnessHover,
        )
        surfaceDefaultTransparentCardBrightnessActive.overrideBy(
            LightColorTokens.SurfaceInverseTransparentCardBrightnessActive,
        )
        personasDefaultOliveTextAccent.overrideBy(LightColorTokens.PersonasInverseOliveTextAccent)
        surfaceDefaultSolidTertiaryActive.overrideBy(LightColorTokens.SurfaceInverseSolidTertiaryActive)
        textDefaultPrimary.overrideBy(LightColorTokens.TextInversePrimary)
        outlineDefaultPrimary.overrideBy(LightColorTokens.OutlineInversePrimary)
        surfaceDefaultAccentSecondary.overrideBy(LightColorTokens.SurfaceInverseAccentSecondary)
        surfaceDefaultAccentMinor.overrideBy(LightColorTokens.SurfaceInverseAccentMinor)
        personasDefaultOchreTextAccent.overrideBy(LightColorTokens.PersonasInverseOchreTextAccent)
        personasDefaultGreenTextAccentActive.overrideBy(LightColorTokens.PersonasInverseGreenTextAccentActive)
        personasDefaultSeaBlueTextAccentActive.overrideBy(LightColorTokens.PersonasInverseSeaBlueTextAccentActive)
        outlineDefaultPrimaryActive.overrideBy(LightColorTokens.OutlineInversePrimaryActive)
        personasDefaultIndigoTextAccentActive.overrideBy(LightColorTokens.PersonasInverseIndigoTextAccentActive)
        personasDefaultOchreTextAccentHover.overrideBy(LightColorTokens.PersonasInverseOchreTextAccentHover)
        textDefaultPrimaryBrightnessHover.overrideBy(LightColorTokens.TextInversePrimaryBrightnessHover)
        surfaceDefaultTransparentNaviHover.overrideBy(LightColorTokens.SurfaceInverseTransparentNaviHover)
        outlineDefaultDefaultHover.overrideBy(LightColorTokens.OutlineInverseDefaultHover)
        outlineDefaultPrimaryHover.overrideBy(LightColorTokens.OutlineInversePrimaryHover)
        personasDefaultOliveTextAccentHover.overrideBy(LightColorTokens.PersonasInverseOliveTextAccentHover)
        surfaceDefaultTransparentAccentMinorActive.overrideBy(
            LightColorTokens.SurfaceInverseTransparentAccentMinorActive,
        )
        personasDefaultVioletTextAccent.overrideBy(LightColorTokens.PersonasInverseVioletTextAccent)
        personasDefaultBlueTextAccent.overrideBy(LightColorTokens.PersonasInverseBlueTextAccent)
        personasDefaultSeaBlueTextAccent.overrideBy(LightColorTokens.PersonasInverseSeaBlueTextAccent)
        personasDefaultVioletTextAccentHover.overrideBy(LightColorTokens.PersonasInverseVioletTextAccentHover)
        backgroundDefaultHardline.overrideBy(LightColorTokens.BackgroundInverseHardline)
        surfaceDefaultSolidPrimaryBrightnessActive.overrideBy(
            LightColorTokens.SurfaceInverseSolidPrimaryBrightnessActive,
        )
        personasDefaultBlueTextAccentActive.overrideBy(LightColorTokens.PersonasInverseBlueTextAccentActive)
        surfaceDefaultAccentSecondaryActive.overrideBy(LightColorTokens.SurfaceInverseAccentSecondaryActive)
        surfaceDefaultTransparentAccentMinor.overrideBy(LightColorTokens.SurfaceInverseTransparentAccentMinor)
        personasDefaultPinkTextAccent.overrideBy(LightColorTokens.PersonasInversePinkTextAccent)
        personasDefaultGreenTextAccent.overrideBy(LightColorTokens.PersonasInverseGreenTextAccent)
        personasDefaultIndigoTextAccent.overrideBy(LightColorTokens.PersonasInverseIndigoTextAccent)
        personasDefaultPinkTextAccentHover.overrideBy(LightColorTokens.PersonasInversePinkTextAccentHover)
        surfaceDefaultTransparentAccentMinorHover.overrideBy(
            LightColorTokens.SurfaceInverseTransparentAccentMinorHover,
        )
        personasDefaultPinkTextAccentActive.overrideBy(LightColorTokens.PersonasInversePinkTextAccentActive)
        textDefaultParagraphActive.overrideBy(LightColorTokens.TextInverseParagraphActive)
        textDefaultAccent.overrideBy(LightColorTokens.TextInverseAccent)
        textDefaultAccentHover.overrideBy(LightColorTokens.TextInverseAccentHover)
        textDefaultAccentActive.overrideBy(LightColorTokens.TextInverseAccentActive)
        textDefaultAccentMinor.overrideBy(LightColorTokens.TextInverseAccentMinor)
        textDefaultAccentMinorHover.overrideBy(LightColorTokens.TextInverseAccentMinorHover)
        textDefaultAccentMinorActive.overrideBy(LightColorTokens.TextInverseAccentMinorActive)
        textDefaultPositive.overrideBy(LightColorTokens.TextInversePositive)
        textDefaultPositiveHover.overrideBy(LightColorTokens.TextInversePositiveHover)
        textDefaultPositiveActive.overrideBy(LightColorTokens.TextInversePositiveActive)
        textDefaultWarning.overrideBy(LightColorTokens.TextInverseWarning)
        textDefaultWarningHover.overrideBy(LightColorTokens.TextInverseWarningHover)
        textDefaultWarningActive.overrideBy(LightColorTokens.TextInverseWarningActive)
        textDefaultNegative.overrideBy(LightColorTokens.TextInverseNegative)
        textDefaultNegativeHover.overrideBy(LightColorTokens.TextInverseNegativeHover)
        textDefaultNegativeActive.overrideBy(LightColorTokens.TextInverseNegativeActive)
        textDefaultInfo.overrideBy(LightColorTokens.TextInverseInfo)
        textDefaultInfoHover.overrideBy(LightColorTokens.TextInverseInfoHover)
        textDefaultInfoActive.overrideBy(LightColorTokens.TextInverseInfoActive)
        textDefaultSecondaryHover.overrideBy(LightColorTokens.TextInverseSecondaryHover)
        textDefaultSecondary.overrideBy(LightColorTokens.TextInverseSecondary)
        textDefaultPrimaryActive.overrideBy(LightColorTokens.TextInversePrimaryActive)
        textDefaultSecondaryActive.overrideBy(LightColorTokens.TextInverseSecondaryActive)
        textDefaultTertiary.overrideBy(LightColorTokens.TextInverseTertiary)
        textDefaultTertiaryHover.overrideBy(LightColorTokens.TextInverseTertiaryHover)
        textDefaultTertiaryActive.overrideBy(LightColorTokens.TextInverseTertiaryActive)
        textDefaultPrimaryBrightness.overrideBy(LightColorTokens.TextInversePrimaryBrightness)
        textDefaultParagraph.overrideBy(LightColorTokens.TextInverseParagraph)
        textDefaultParagraphHover.overrideBy(LightColorTokens.TextInverseParagraphHover)
        surfaceDefaultSolidPrimary.overrideBy(LightColorTokens.SurfaceInverseSolidPrimary)
        surfaceDefaultSolidPrimaryHover.overrideBy(LightColorTokens.SurfaceInverseSolidPrimaryHover)
        surfaceDefaultSolidPrimaryActive.overrideBy(LightColorTokens.SurfaceInverseSolidPrimaryActive)
        surfaceDefaultSolidPrimaryBrightness.overrideBy(LightColorTokens.SurfaceInverseSolidPrimaryBrightness)
        surfaceDefaultSolidSecondary.overrideBy(LightColorTokens.SurfaceInverseSolidSecondary)
        surfaceDefaultSolidSecondaryHover.overrideBy(LightColorTokens.SurfaceInverseSolidSecondaryHover)
        surfaceDefaultSolidSecondaryActive.overrideBy(LightColorTokens.SurfaceInverseSolidSecondaryActive)
        surfaceDefaultSolidTertiary.overrideBy(LightColorTokens.SurfaceInverseSolidTertiary)
        surfaceDefaultSolidTertiaryHover.overrideBy(LightColorTokens.SurfaceInverseSolidTertiaryHover)
        surfaceDefaultTransparentSecondaryActive.overrideBy(
            LightColorTokens.SurfaceInverseTransparentSecondaryActive,
        )
        surfaceDefaultTransparentTertiary.overrideBy(LightColorTokens.SurfaceInverseTransparentTertiary)
        surfaceDefaultTransparentTertiaryHover.overrideBy(LightColorTokens.SurfaceInverseTransparentTertiaryHover)
        surfaceDefaultTransparentTertiaryActive.overrideBy(LightColorTokens.SurfaceInverseTransparentTertiaryActive)
        surfaceDefaultTransparentDeep.overrideBy(LightColorTokens.SurfaceInverseTransparentDeep)
        surfaceDefaultTransparentDeepHover.overrideBy(LightColorTokens.SurfaceInverseTransparentDeepHover)
        surfaceDefaultTransparentDeepActive.overrideBy(LightColorTokens.SurfaceInverseTransparentDeepActive)
        surfaceDefaultTransparentCard.overrideBy(LightColorTokens.SurfaceInverseTransparentCard)
        surfaceDefaultTransparentCardHover.overrideBy(LightColorTokens.SurfaceInverseTransparentCardHover)
        surfaceDefaultTransparentCardActive.overrideBy(LightColorTokens.SurfaceInverseTransparentCardActive)
        surfaceDefaultTransparentCardBrightness.overrideBy(LightColorTokens.SurfaceInverseTransparentCardBrightness)
        surfaceDefaultClear.overrideBy(LightColorTokens.SurfaceInverseClear)
        surfaceDefaultClearHover.overrideBy(LightColorTokens.SurfaceInverseClearHover)
        surfaceDefaultClearActive.overrideBy(LightColorTokens.SurfaceInverseClearActive)
        surfaceDefaultAccent.overrideBy(LightColorTokens.SurfaceInverseAccent)
        surfaceDefaultAccentHover.overrideBy(LightColorTokens.SurfaceInverseAccentHover)
        surfaceDefaultAccentActive.overrideBy(LightColorTokens.SurfaceInverseAccentActive)
        surfaceDefaultAccentMinorHover.overrideBy(LightColorTokens.SurfaceInverseAccentMinorHover)
        surfaceDefaultAccentMinorActive.overrideBy(LightColorTokens.SurfaceInverseAccentMinorActive)
        surfaceDefaultTransparentAccent.overrideBy(LightColorTokens.SurfaceInverseTransparentAccent)
        surfaceDefaultTransparentAccentHover.overrideBy(LightColorTokens.SurfaceInverseTransparentAccentHover)
        surfaceDefaultTransparentAccentActive.overrideBy(LightColorTokens.SurfaceInverseTransparentAccentActive)
        surfaceDefaultSolidCardActive.overrideBy(LightColorTokens.SurfaceInverseSolidCardActive)
        surfaceDefaultSolidCard.overrideBy(LightColorTokens.SurfaceInverseSolidCard)
        surfaceDefaultSolidCardBrightness.overrideBy(LightColorTokens.SurfaceInverseSolidCardBrightness)
        surfaceDefaultSolidDefault.overrideBy(LightColorTokens.SurfaceInverseSolidDefault)
        surfaceDefaultSolidDefaultHover.overrideBy(LightColorTokens.SurfaceInverseSolidDefaultHover)
        surfaceDefaultTransparentPrimary.overrideBy(LightColorTokens.SurfaceInverseTransparentPrimary)
        surfaceDefaultTransparentPrimaryHover.overrideBy(LightColorTokens.SurfaceInverseTransparentPrimaryHover)
        surfaceDefaultSolidDefaultActive.overrideBy(LightColorTokens.SurfaceInverseSolidDefaultActive)
        surfaceDefaultSolidCardHover.overrideBy(LightColorTokens.SurfaceInverseSolidCardHover)
        surfaceDefaultTransparentPrimaryActive.overrideBy(LightColorTokens.SurfaceInverseTransparentPrimaryActive)
        surfaceDefaultTransparentSecondary.overrideBy(LightColorTokens.SurfaceInverseTransparentSecondary)
        surfaceDefaultTransparentSecondaryHover.overrideBy(LightColorTokens.SurfaceInverseTransparentSecondaryHover)
        surfaceDefaultWarningActive.overrideBy(LightColorTokens.SurfaceInverseWarningActive)
        surfaceDefaultNegative.overrideBy(LightColorTokens.SurfaceInverseNegative)
        surfaceDefaultNegativeHover.overrideBy(LightColorTokens.SurfaceInverseNegativeHover)
        surfaceDefaultNegativeActive.overrideBy(LightColorTokens.SurfaceInverseNegativeActive)
        surfaceDefaultInfo.overrideBy(LightColorTokens.SurfaceInverseInfo)
        surfaceDefaultInfoHover.overrideBy(LightColorTokens.SurfaceInverseInfoHover)
        surfaceDefaultInfoActive.overrideBy(LightColorTokens.SurfaceInverseInfoActive)
        surfaceDefaultPositiveActive.overrideBy(LightColorTokens.SurfaceInversePositiveActive)
        surfaceDefaultPositive.overrideBy(LightColorTokens.SurfaceInversePositive)
        surfaceDefaultPositiveHover.overrideBy(LightColorTokens.SurfaceInversePositiveHover)
        surfaceDefaultWarning.overrideBy(LightColorTokens.SurfaceInverseWarning)
        surfaceDefaultWarningHover.overrideBy(LightColorTokens.SurfaceInverseWarningHover)
        surfaceDefaultTransparentNegative.overrideBy(LightColorTokens.SurfaceInverseTransparentNegative)
        surfaceDefaultTransparentNegativeHover.overrideBy(LightColorTokens.SurfaceInverseTransparentNegativeHover)
        surfaceDefaultReadOnly.overrideBy(LightColorTokens.SurfaceInverseReadOnly)
        surfaceDefaultReadOnlyHover.overrideBy(LightColorTokens.SurfaceInverseReadOnlyHover)
        surfaceDefaultReadOnlyActive.overrideBy(LightColorTokens.SurfaceInverseReadOnlyActive)
        surfaceDefaultTransparentNegativeActive.overrideBy(LightColorTokens.SurfaceInverseTransparentNegativeActive)
        backgroundDefaultPrimary.overrideBy(LightColorTokens.BackgroundInversePrimary)
        backgroundDefaultSecondary.overrideBy(LightColorTokens.BackgroundInverseSecondary)
        backgroundDefaultTertiary.overrideBy(LightColorTokens.BackgroundInverseTertiary)
        outlineDefaultTransparentPrimary.overrideBy(LightColorTokens.OutlineInverseTransparentPrimary)
        outlineDefaultTransparentPrimaryHover.overrideBy(LightColorTokens.OutlineInverseTransparentPrimaryHover)
        outlineDefaultTransparentPrimaryActive.overrideBy(LightColorTokens.OutlineInverseTransparentPrimaryActive)
        outlineDefaultClear.overrideBy(LightColorTokens.OutlineInverseClear)
        overlayDefaultSoft.overrideBy(LightColorTokens.OverlayInverseSoft)
        overlayDefaultHard.overrideBy(LightColorTokens.OverlayInverseHard)
        outlineDefaultPositive.overrideBy(LightColorTokens.OutlineInversePositive)
        outlineDefaultPositiveHover.overrideBy(LightColorTokens.OutlineInversePositiveHover)
        outlineDefaultPositiveActive.overrideBy(LightColorTokens.OutlineInversePositiveActive)
        outlineDefaultWarning.overrideBy(LightColorTokens.OutlineInverseWarning)
        outlineDefaultWarningHover.overrideBy(LightColorTokens.OutlineInverseWarningHover)
        outlineDefaultWarningActive.overrideBy(LightColorTokens.OutlineInverseWarningActive)
        outlineDefaultNegative.overrideBy(LightColorTokens.OutlineInverseNegative)
        outlineDefaultNegativeHover.overrideBy(LightColorTokens.OutlineInverseNegativeHover)
        outlineDefaultNegativeActive.overrideBy(LightColorTokens.OutlineInverseNegativeActive)
        outlineDefaultInfo.overrideBy(LightColorTokens.OutlineInverseInfo)
        outlineDefaultInfoHover.overrideBy(LightColorTokens.OutlineInverseInfoHover)
        outlineDefaultInfoActive.overrideBy(LightColorTokens.OutlineInverseInfoActive)
        outlineDefaultClearActive.overrideBy(LightColorTokens.OutlineInverseClearActive)
        outlineDefaultClearHover.overrideBy(LightColorTokens.OutlineInverseClearHover)
        textDefaultPrimaryHover.overrideBy(LightColorTokens.TextInversePrimaryHover)
    }
}

private val darkInverseGradients: SddsSbComGradients by lazy {
    darkSddsSbComGradients {
        personasInverseIndigoSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasDefaultIndigoSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasDefaultIndigoSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasDefaultIndigoSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseSeaBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasDefaultSeaBlueSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasDefaultSeaBlueSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasDefaultSeaBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        textInverseAccentGradientAI.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextDefaultAccentGradientAI.colors,
                    DarkGradientTokens.TextDefaultAccentGradientAI.positions,
                    DarkGradientTokens.TextDefaultAccentGradientAI.angle,
                ),
            ),
        )
        personasInversePinkSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasDefaultPinkSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasDefaultPinkSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasDefaultPinkSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseOchreSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasDefaultOchreSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasDefaultOchreSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasDefaultOchreSurfaceAccentGradient.angle,
                ),
            ),
        )
        backgroundInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.BackgroundDefaultGradient.colors,
                    DarkGradientTokens.BackgroundDefaultGradient.positions,
                    DarkGradientTokens.BackgroundDefaultGradient.angle,
                ),
            ),
        )
        overlayInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OverlayDefaultGradient.colors,
                    DarkGradientTokens.OverlayDefaultGradient.positions,
                    DarkGradientTokens.OverlayDefaultGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentGradientSecondary.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultAccentGradientSecondary.colors,
                    DarkGradientTokens.SurfaceDefaultAccentGradientSecondary.positions,
                    DarkGradientTokens.SurfaceDefaultAccentGradientSecondary.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultSkeletonGradient.colors,
                    DarkGradientTokens.SurfaceDefaultSkeletonGradient.positions,
                    DarkGradientTokens.SurfaceDefaultSkeletonGradient.angle,
                ),
            ),
        )
        personasInverseGreenSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasDefaultGreenSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasDefaultGreenSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasDefaultGreenSurfaceAccentGradient.angle,
                ),
            ),
        )
        outlineInverseWhiteGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OutlineDefaultWhiteGradient.colors,
                    DarkGradientTokens.OutlineDefaultWhiteGradient.positions,
                    DarkGradientTokens.OutlineDefaultWhiteGradient.angle,
                ),
            ),
        )
        personasInverseBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasDefaultBlueSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasDefaultBlueSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasDefaultBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseOliveSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasDefaultOliveSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasDefaultOliveSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasDefaultOliveSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseVioletSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasDefaultVioletSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasDefaultVioletSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasDefaultVioletSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultAccentGradient.colors,
                    DarkGradientTokens.SurfaceDefaultAccentGradient.positions,
                    DarkGradientTokens.SurfaceDefaultAccentGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentMinorGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceDefaultAccentMinorGradient.colors,
                    DarkGradientTokens.SurfaceDefaultAccentMinorGradient.positions,
                    DarkGradientTokens.SurfaceDefaultAccentMinorGradient.angle,
                ),
            ),
        )
        outlineDefaultWhiteGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OutlineInverseWhiteGradient.colors,
                    DarkGradientTokens.OutlineInverseWhiteGradient.positions,
                    DarkGradientTokens.OutlineInverseWhiteGradient.angle,
                ),
            ),
        )
        personasDefaultGreenSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasInverseGreenSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasInverseGreenSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasInverseGreenSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultSeaBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasInverseSeaBlueSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasInverseSeaBlueSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasInverseSeaBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultPinkSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasInversePinkSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasInversePinkSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasInversePinkSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseSkeletonGradient.colors,
                    DarkGradientTokens.SurfaceInverseSkeletonGradient.positions,
                    DarkGradientTokens.SurfaceInverseSkeletonGradient.angle,
                ),
            ),
        )
        overlayDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.OverlayInverseGradient.colors,
                    DarkGradientTokens.OverlayInverseGradient.positions,
                    DarkGradientTokens.OverlayInverseGradient.angle,
                ),
            ),
        )
        backgroundDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.BackgroundInverseGradient.colors,
                    DarkGradientTokens.BackgroundInverseGradient.positions,
                    DarkGradientTokens.BackgroundInverseGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentGradientSecondary.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseAccentGradientSecondary.colors,
                    DarkGradientTokens.SurfaceInverseAccentGradientSecondary.positions,
                    DarkGradientTokens.SurfaceInverseAccentGradientSecondary.angle,
                ),
            ),
        )
        personasDefaultOchreSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasInverseOchreSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasInverseOchreSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasInverseOchreSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultVioletSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasInverseVioletSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasInverseVioletSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasInverseVioletSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultOliveSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasInverseOliveSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasInverseOliveSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasInverseOliveSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultIndigoSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasInverseIndigoSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasInverseIndigoSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasInverseIndigoSurfaceAccentGradient.angle,
                ),
            ),
        )
        textDefaultAccentGradientAI.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.TextInverseAccentGradientAI.colors,
                    DarkGradientTokens.TextInverseAccentGradientAI.positions,
                    DarkGradientTokens.TextInverseAccentGradientAI.angle,
                ),
            ),
        )
        personasDefaultBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.PersonasInverseBlueSurfaceAccentGradient.colors,
                    DarkGradientTokens.PersonasInverseBlueSurfaceAccentGradient.positions,
                    DarkGradientTokens.PersonasInverseBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseAccentGradient.colors,
                    DarkGradientTokens.SurfaceInverseAccentGradient.positions,
                    DarkGradientTokens.SurfaceInverseAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentMinorGradient.overrideBy(
            listOf(
                linearGradient(
                    DarkGradientTokens.SurfaceInverseAccentMinorGradient.colors,
                    DarkGradientTokens.SurfaceInverseAccentMinorGradient.positions,
                    DarkGradientTokens.SurfaceInverseAccentMinorGradient.angle,
                ),
            ),
        )
    }
}

private val lightInverseGradients: SddsSbComGradients by lazy {
    lightSddsSbComGradients {
        personasInverseIndigoSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasDefaultIndigoSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasDefaultIndigoSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasDefaultIndigoSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseSeaBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasDefaultSeaBlueSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasDefaultSeaBlueSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasDefaultSeaBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        textInverseAccentGradientAI.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextDefaultAccentGradientAI.colors,
                    LightGradientTokens.TextDefaultAccentGradientAI.positions,
                    LightGradientTokens.TextDefaultAccentGradientAI.angle,
                ),
            ),
        )
        personasInversePinkSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasDefaultPinkSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasDefaultPinkSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasDefaultPinkSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseOchreSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasDefaultOchreSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasDefaultOchreSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasDefaultOchreSurfaceAccentGradient.angle,
                ),
            ),
        )
        backgroundInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.BackgroundDefaultGradient.colors,
                    LightGradientTokens.BackgroundDefaultGradient.positions,
                    LightGradientTokens.BackgroundDefaultGradient.angle,
                ),
            ),
        )
        overlayInverseGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OverlayDefaultGradient.colors,
                    LightGradientTokens.OverlayDefaultGradient.positions,
                    LightGradientTokens.OverlayDefaultGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentGradientSecondary.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultAccentGradientSecondary.colors,
                    LightGradientTokens.SurfaceDefaultAccentGradientSecondary.positions,
                    LightGradientTokens.SurfaceDefaultAccentGradientSecondary.angle,
                ),
            ),
        )
        surfaceInverseSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultSkeletonGradient.colors,
                    LightGradientTokens.SurfaceDefaultSkeletonGradient.positions,
                    LightGradientTokens.SurfaceDefaultSkeletonGradient.angle,
                ),
            ),
        )
        personasInverseGreenSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasDefaultGreenSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasDefaultGreenSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasDefaultGreenSurfaceAccentGradient.angle,
                ),
            ),
        )
        outlineInverseWhiteGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OutlineDefaultWhiteGradient.colors,
                    LightGradientTokens.OutlineDefaultWhiteGradient.positions,
                    LightGradientTokens.OutlineDefaultWhiteGradient.angle,
                ),
            ),
        )
        personasInverseBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasDefaultBlueSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasDefaultBlueSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasDefaultBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseOliveSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasDefaultOliveSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasDefaultOliveSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasDefaultOliveSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasInverseVioletSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasDefaultVioletSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasDefaultVioletSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasDefaultVioletSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultAccentGradient.colors,
                    LightGradientTokens.SurfaceDefaultAccentGradient.positions,
                    LightGradientTokens.SurfaceDefaultAccentGradient.angle,
                ),
            ),
        )
        surfaceInverseAccentMinorGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceDefaultAccentMinorGradient.colors,
                    LightGradientTokens.SurfaceDefaultAccentMinorGradient.positions,
                    LightGradientTokens.SurfaceDefaultAccentMinorGradient.angle,
                ),
            ),
        )
        outlineDefaultWhiteGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OutlineInverseWhiteGradient.colors,
                    LightGradientTokens.OutlineInverseWhiteGradient.positions,
                    LightGradientTokens.OutlineInverseWhiteGradient.angle,
                ),
            ),
        )
        personasDefaultGreenSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasInverseGreenSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasInverseGreenSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasInverseGreenSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultSeaBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasInverseSeaBlueSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasInverseSeaBlueSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasInverseSeaBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultPinkSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasInversePinkSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasInversePinkSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasInversePinkSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultSkeletonGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseSkeletonGradient.colors,
                    LightGradientTokens.SurfaceInverseSkeletonGradient.positions,
                    LightGradientTokens.SurfaceInverseSkeletonGradient.angle,
                ),
            ),
        )
        overlayDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.OverlayInverseGradient.colors,
                    LightGradientTokens.OverlayInverseGradient.positions,
                    LightGradientTokens.OverlayInverseGradient.angle,
                ),
            ),
        )
        backgroundDefaultGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.BackgroundInverseGradient.colors,
                    LightGradientTokens.BackgroundInverseGradient.positions,
                    LightGradientTokens.BackgroundInverseGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentGradientSecondary.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseAccentGradientSecondary.colors,
                    LightGradientTokens.SurfaceInverseAccentGradientSecondary.positions,
                    LightGradientTokens.SurfaceInverseAccentGradientSecondary.angle,
                ),
            ),
        )
        personasDefaultOchreSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasInverseOchreSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasInverseOchreSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasInverseOchreSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultVioletSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasInverseVioletSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasInverseVioletSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasInverseVioletSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultOliveSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasInverseOliveSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasInverseOliveSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasInverseOliveSurfaceAccentGradient.angle,
                ),
            ),
        )
        personasDefaultIndigoSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasInverseIndigoSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasInverseIndigoSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasInverseIndigoSurfaceAccentGradient.angle,
                ),
            ),
        )
        textDefaultAccentGradientAI.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.TextInverseAccentGradientAI.colors,
                    LightGradientTokens.TextInverseAccentGradientAI.positions,
                    LightGradientTokens.TextInverseAccentGradientAI.angle,
                ),
            ),
        )
        personasDefaultBlueSurfaceAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.PersonasInverseBlueSurfaceAccentGradient.colors,
                    LightGradientTokens.PersonasInverseBlueSurfaceAccentGradient.positions,
                    LightGradientTokens.PersonasInverseBlueSurfaceAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseAccentGradient.colors,
                    LightGradientTokens.SurfaceInverseAccentGradient.positions,
                    LightGradientTokens.SurfaceInverseAccentGradient.angle,
                ),
            ),
        )
        surfaceDefaultAccentMinorGradient.overrideBy(
            listOf(
                linearGradient(
                    LightGradientTokens.SurfaceInverseAccentMinorGradient.colors,
                    LightGradientTokens.SurfaceInverseAccentMinorGradient.positions,
                    LightGradientTokens.SurfaceInverseAccentMinorGradient.angle,
                ),
            ),
        )
    }
}

/**
 * Подтема SddsSbComTheme.Inverse
 */
@Composable
public fun SddsSbComTheme.Inverse(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable
    () -> Unit,
) {
    val colors = if (isDark) {
        darkInverseColors
    } else {
        lightInverseColors
    }
    val gradients = if (isDark) {
        darkInverseGradients
    } else {
        lightInverseGradients
    }
    SddsSbComTheme(
        colors = colors,
        gradients = gradients,
        content = content,
    )
}
