package com.sdds.playground.sandbox.plasma.sd.service.integration.button.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.plasma.sd.service.integration.s

internal object PlasmaSdServiceIconButtonVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "LDefault" to s.Plasma_SdService_ComponentOverlays_IconButtonLDefault,
            "LPilledDefault" to s.Plasma_SdService_ComponentOverlays_IconButtonLPilledDefault,
            "MDefault" to s.Plasma_SdService_ComponentOverlays_IconButtonMDefault,
            "MPilledDefault" to s.Plasma_SdService_ComponentOverlays_IconButtonMPilledDefault,
            "SDefault" to s.Plasma_SdService_ComponentOverlays_IconButtonSDefault,
            "SPilledDefault" to s.Plasma_SdService_ComponentOverlays_IconButtonSPilledDefault,
            "XsDefault" to s.Plasma_SdService_ComponentOverlays_IconButtonXsDefault,
            "XsPilledDefault" to s.Plasma_SdService_ComponentOverlays_IconButtonXsPilledDefault,
            "LSecondary" to s.Plasma_SdService_ComponentOverlays_IconButtonLSecondary,
            "LPilledSecondary" to s.Plasma_SdService_ComponentOverlays_IconButtonLPilledSecondary,
            "MSecondary" to s.Plasma_SdService_ComponentOverlays_IconButtonMSecondary,
            "MPilledSecondary" to s.Plasma_SdService_ComponentOverlays_IconButtonMPilledSecondary,
            "SSecondary" to s.Plasma_SdService_ComponentOverlays_IconButtonSSecondary,
            "SPilledSecondary" to s.Plasma_SdService_ComponentOverlays_IconButtonSPilledSecondary,
            "XsSecondary" to s.Plasma_SdService_ComponentOverlays_IconButtonXsSecondary,
            "XsPilledSecondary" to s.Plasma_SdService_ComponentOverlays_IconButtonXsPilledSecondary,
            "LAccent" to s.Plasma_SdService_ComponentOverlays_IconButtonLAccent,
            "LPilledAccent" to s.Plasma_SdService_ComponentOverlays_IconButtonLPilledAccent,
            "MAccent" to s.Plasma_SdService_ComponentOverlays_IconButtonMAccent,
            "MPilledAccent" to s.Plasma_SdService_ComponentOverlays_IconButtonMPilledAccent,
            "SAccent" to s.Plasma_SdService_ComponentOverlays_IconButtonSAccent,
            "SPilledAccent" to s.Plasma_SdService_ComponentOverlays_IconButtonSPilledAccent,
            "XsAccent" to s.Plasma_SdService_ComponentOverlays_IconButtonXsPilledAccent,
            "XsPilledAccent" to s.Plasma_SdService_ComponentOverlays_IconButtonXsAccent,
            "LPositive" to s.Plasma_SdService_ComponentOverlays_IconButtonLPositive,
            "LPilledPositive" to s.Plasma_SdService_ComponentOverlays_IconButtonLPilledPositive,
            "MPositive" to s.Plasma_SdService_ComponentOverlays_IconButtonMPositive,
            "MPilledPositive" to s.Plasma_SdService_ComponentOverlays_IconButtonMPilledPositive,
            "SPositive" to s.Plasma_SdService_ComponentOverlays_IconButtonSPositive,
            "SPilledPositive" to s.Plasma_SdService_ComponentOverlays_IconButtonSPilledPositive,
            "XsPositive" to s.Plasma_SdService_ComponentOverlays_IconButtonXsPositive,
            "XsPilledPositive" to s.Plasma_SdService_ComponentOverlays_IconButtonXsPilledPositive,
            "LNegative" to s.Plasma_SdService_ComponentOverlays_IconButtonLNegative,
            "LPilledNegative" to s.Plasma_SdService_ComponentOverlays_IconButtonLPilledNegative,
            "MNegative" to s.Plasma_SdService_ComponentOverlays_IconButtonMNegative,
            "MPilledNegative" to s.Plasma_SdService_ComponentOverlays_IconButtonMPilledNegative,
            "SNegative" to s.Plasma_SdService_ComponentOverlays_IconButtonSNegative,
            "SPilledNegative" to s.Plasma_SdService_ComponentOverlays_IconButtonSPilledNegative,
            "XsNegative" to s.Plasma_SdService_ComponentOverlays_IconButtonXsNegative,
            "XsPilledNegative" to s.Plasma_SdService_ComponentOverlays_IconButtonXsPilledNegative,
            "LWarning" to s.Plasma_SdService_ComponentOverlays_IconButtonLWarning,
            "LPilledWarning" to s.Plasma_SdService_ComponentOverlays_IconButtonLPilledWarning,
            "MWarning" to s.Plasma_SdService_ComponentOverlays_IconButtonMWarning,
            "MPilledWarning" to s.Plasma_SdService_ComponentOverlays_IconButtonMPilledWarning,
            "SWarning" to s.Plasma_SdService_ComponentOverlays_IconButtonSWarning,
            "SPilledWarning" to s.Plasma_SdService_ComponentOverlays_IconButtonSPilledWarning,
            "XsWarning" to s.Plasma_SdService_ComponentOverlays_IconButtonXsWarning,
            "XsPilledWarning" to s.Plasma_SdService_ComponentOverlays_IconButtonXsPilledWarning,
        )
}
