package com.sdds.playground.sandbox.plasma.sd.service.integration.button.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider

internal object PlasmaSdServiceIconButtonVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int>
        get() = mapOf(
            "LDefault" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLDefault,
            "LPilledDefault" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledDefault,
            "MDefault" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMDefault,
            "MPilledDefault" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledDefault,
            "SDefault" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSDefault,
            "SPilledDefault" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledDefault,
            "XsDefault" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsDefault,
            "XsPilledDefault" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledDefault,
            "LSecondary" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLSecondary,
            "LPilledSecondary" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledSecondary,
            "MSecondary" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMSecondary,
            "MPilledSecondary" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledSecondary,
            "SSecondary" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSSecondary,
            "SPilledSecondary" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledSecondary,
            "XsSecondary" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsSecondary,
            "XsPilledSecondary" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledSecondary,
            "LAccent" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLAccent,
            "LPilledAccent" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledAccent,
            "MAccent" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMAccent,
            "MPilledAccent" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledAccent,
            "SAccent" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSAccent,
            "SPilledAccent" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledAccent,
            "XsAccent" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledAccent,
            "XsPilledAccent" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsAccent,
            "LPositive" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLPositive,
            "LPilledPositive" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledPositive,
            "MPositive" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMPositive,
            "MPilledPositive" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledPositive,
            "SPositive" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSPositive,
            "SPilledPositive" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledPositive,
            "XsPositive" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsPositive,
            "XsPilledPositive" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledPositive,
            "LNegative" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLNegative,
            "LPilledNegative" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledNegative,
            "MNegative" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMNegative,
            "MPilledNegative" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledNegative,
            "SNegative" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSNegative,
            "SPilledNegative" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledNegative,
            "XsNegative" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsNegative,
            "XsPilledNegative" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledNegative,
            "LWarning" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLWarning,
            "LPilledWarning" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonLPilledWarning,
            "MWarning" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMWarning,
            "MPilledWarning" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonMPilledWarning,
            "SWarning" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSWarning,
            "SPilledWarning" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonSPilledWarning,
            "XsWarning" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsWarning,
            "XsPilledWarning" to com.sdds.plasma.sd.service.R.style.Plasma_SdService_ComponentOverlays_IconButtonXsPilledWarning,
        )
}
