package com.sdds.playground.sandbox.plasma.sd.service.integration.textfield

import androidx.compose.runtime.Composable
import com.sdds.compose.uikit.TextFieldStyle
import com.sdds.compose.uikit.style.style
import com.sdds.plasma.sd.service.styles.textfield.Default
import com.sdds.plasma.sd.service.styles.textfield.Error
import com.sdds.plasma.sd.service.styles.textfield.InnerLabel
import com.sdds.plasma.sd.service.styles.textfield.L
import com.sdds.plasma.sd.service.styles.textfield.M
import com.sdds.plasma.sd.service.styles.textfield.OuterLabel
import com.sdds.plasma.sd.service.styles.textfield.RequiredEnd
import com.sdds.plasma.sd.service.styles.textfield.RequiredStart
import com.sdds.plasma.sd.service.styles.textfield.S
import com.sdds.plasma.sd.service.styles.textfield.Success
import com.sdds.plasma.sd.service.styles.textfield.TextField
import com.sdds.plasma.sd.service.styles.textfield.Warning
import com.sdds.plasma.sd.service.styles.textfield.Xl
import com.sdds.plasma.sd.service.styles.textfield.Xs
import com.sdds.playground.sandbox.core.integration.ComposeStyleProvider

internal object PlasmaSdServiceTextFieldVariationsCompose : ComposeStyleProvider<String, TextFieldStyle>() {
    override val variations: Map<String, @Composable () -> TextFieldStyle>
        get() = mapOf<String, @Composable () -> TextFieldStyle>(
            "XLDefault" to ({ TextField.Xl.Default.style() }),
            "XLRequiredStartDefault" to ({ TextField.Xl.RequiredStart.Default.style() }),
            "XLRequiredEndDefault" to ({ TextField.Xl.RequiredEnd.Default.style() }),
            "XLOuterLabelDefault" to ({ TextField.Xl.OuterLabel.Default.style() }),
            "XLOuterLabelRequiredStartDefault" to ({ TextField.Xl.OuterLabel.RequiredStart.Default.style() }),
            "XLOuterLabelRequiredEndDefault" to ({ TextField.Xl.OuterLabel.RequiredEnd.Default.style() }),
            "XLInnerLabelDefault" to ({ TextField.Xl.InnerLabel.Default.style() }),
            "XLInnerLabelRequiredStartDefault" to ({ TextField.Xl.InnerLabel.RequiredStart.Default.style() }),
            "XLInnerLabelRequiredEndDefault" to ({ TextField.Xl.InnerLabel.RequiredEnd.Default.style() }),
            "LDefault" to ({ TextField.L.Default.style() }),
            "LDefault" to ({ TextField.L.Default.style() }),
            "LRequiredStartDefault" to ({ TextField.L.RequiredStart.Default.style() }),
            "LRequiredEndDefault" to ({ TextField.L.RequiredEnd.Default.style() }),
            "LOuterLabelDefault" to ({ TextField.L.OuterLabel.Default.style() }),
            "LOuterLabelRequiredStartDefault" to ({ TextField.L.OuterLabel.RequiredStart.Default.style() }),
            "LOuterLabelRequiredEndDefault" to ({ TextField.L.OuterLabel.RequiredEnd.Default.style() }),
            "LInnerLabelDefault" to ({ TextField.L.InnerLabel.Default.style() }),
            "LInnerLabelRequiredStartDefault" to ({ TextField.L.InnerLabel.RequiredStart.Default.style() }),
            "LInnerLabelRequiredEndDefault" to ({ TextField.L.InnerLabel.RequiredEnd.Default.style() }),
            "MDefault" to ({ TextField.M.Default.style() }),
            "MRequiredStartDefault" to ({ TextField.M.RequiredStart.Default.style() }),
            "MRequiredEndDefault" to ({ TextField.M.RequiredEnd.Default.style() }),
            "MOuterLabelDefault" to ({ TextField.M.OuterLabel.Default.style() }),
            "MOuterLabelRequiredStartDefault" to ({ TextField.M.OuterLabel.RequiredStart.Default.style() }),
            "MOuterLabelRequiredEndDefault" to ({ TextField.M.OuterLabel.RequiredEnd.Default.style() }),
            "MInnerLabelDefault" to ({ TextField.M.InnerLabel.Default.style() }),
            "MInnerLabelRequiredStartDefault" to ({ TextField.M.InnerLabel.RequiredStart.Default.style() }),
            "MInnerLabelRequiredEndDefault" to ({ TextField.M.InnerLabel.RequiredEnd.Default.style() }),
            "SDefault" to ({ TextField.S.Default.style() }),
            "SRequiredStartDefault" to ({ TextField.S.RequiredStart.Default.style() }),
            "SRequiredEndDefault" to ({ TextField.S.RequiredEnd.Default.style() }),
            "SOuterLabelDefault" to ({ TextField.S.OuterLabel.Default.style() }),
            "SOuterLabelRequiredStartDefault" to ({ TextField.S.OuterLabel.RequiredStart.Default.style() }),
            "SOuterLabelRequiredEndDefault" to ({ TextField.S.OuterLabel.RequiredEnd.Default.style() }),
            "SInnerLabelDefault" to ({ TextField.S.InnerLabel.Default.style() }),
            "SInnerLabelRequiredStartDefault" to ({ TextField.S.InnerLabel.RequiredStart.Default.style() }),
            "SInnerLabelRequiredEndDefault" to ({ TextField.S.InnerLabel.RequiredEnd.Default.style() }),
            "XSDefault" to ({ TextField.Xs.Default.style() }),
            "XSRequiredStartDefault" to ({ TextField.Xs.RequiredStart.Default.style() }),
            "XSRequiredEndDefault" to ({ TextField.Xs.RequiredEnd.Default.style() }),
            "XSOuterLabelDefault" to ({ TextField.Xs.OuterLabel.Default.style() }),
            "XSOuterLabelRequiredStartDefault" to ({ TextField.Xs.OuterLabel.RequiredStart.Default.style() }),
            "XSOuterLabelRequiredEndDefault" to ({ TextField.Xs.OuterLabel.RequiredEnd.Default.style() }),

            "XLWarning" to ({ TextField.Xl.Warning.style() }),
            "XLRequiredStartWarning" to ({ TextField.Xl.RequiredStart.Warning.style() }),
            "XLRequiredEndWarning" to ({ TextField.Xl.RequiredEnd.Warning.style() }),
            "XLOuterLabelWarning" to ({ TextField.Xl.OuterLabel.Warning.style() }),
            "XLOuterLabelRequiredStartWarning" to ({ TextField.Xl.OuterLabel.RequiredStart.Warning.style() }),
            "XLOuterLabelRequiredEndWarning" to ({ TextField.Xl.OuterLabel.RequiredEnd.Warning.style() }),
            "XLInnerLabelWarning" to ({ TextField.Xl.InnerLabel.Warning.style() }),
            "XLInnerLabelRequiredStartWarning" to ({ TextField.Xl.InnerLabel.RequiredStart.Warning.style() }),
            "XLInnerLabelRequiredEndWarning" to ({ TextField.Xl.InnerLabel.RequiredEnd.Warning.style() }),
            "LWarning" to ({ TextField.L.Warning.style() }),
            "LWarning" to ({ TextField.L.Warning.style() }),
            "LRequiredStartWarning" to ({ TextField.L.RequiredStart.Warning.style() }),
            "LRequiredEndWarning" to ({ TextField.L.RequiredEnd.Warning.style() }),
            "LOuterLabelWarning" to ({ TextField.L.OuterLabel.Warning.style() }),
            "LOuterLabelRequiredStartWarning" to ({ TextField.L.OuterLabel.RequiredStart.Warning.style() }),
            "LOuterLabelRequiredEndWarning" to ({ TextField.L.OuterLabel.RequiredEnd.Warning.style() }),
            "LInnerLabelWarning" to ({ TextField.L.InnerLabel.Warning.style() }),
            "LInnerLabelRequiredStartWarning" to ({ TextField.L.InnerLabel.RequiredStart.Warning.style() }),
            "LInnerLabelRequiredEndWarning" to ({ TextField.L.InnerLabel.RequiredEnd.Warning.style() }),
            "MWarning" to ({ TextField.M.Warning.style() }),
            "MRequiredStartWarning" to ({ TextField.M.RequiredStart.Warning.style() }),
            "MRequiredEndWarning" to ({ TextField.M.RequiredEnd.Warning.style() }),
            "MOuterLabelWarning" to ({ TextField.M.OuterLabel.Warning.style() }),
            "MOuterLabelRequiredStartWarning" to ({ TextField.M.OuterLabel.RequiredStart.Warning.style() }),
            "MOuterLabelRequiredEndWarning" to ({ TextField.M.OuterLabel.RequiredEnd.Warning.style() }),
            "MInnerLabelWarning" to ({ TextField.M.InnerLabel.Warning.style() }),
            "MInnerLabelRequiredStartWarning" to ({ TextField.M.InnerLabel.RequiredStart.Warning.style() }),
            "MInnerLabelRequiredEndWarning" to ({ TextField.M.InnerLabel.RequiredEnd.Warning.style() }),
            "SWarning" to ({ TextField.S.Warning.style() }),
            "SRequiredStartWarning" to ({ TextField.S.RequiredStart.Warning.style() }),
            "SRequiredEndWarning" to ({ TextField.S.RequiredEnd.Warning.style() }),
            "SOuterLabelWarning" to ({ TextField.S.OuterLabel.Warning.style() }),
            "SOuterLabelRequiredStartWarning" to ({ TextField.S.OuterLabel.RequiredStart.Warning.style() }),
            "SOuterLabelRequiredEndWarning" to ({ TextField.S.OuterLabel.RequiredEnd.Warning.style() }),
            "SInnerLabelWarning" to ({ TextField.S.InnerLabel.Warning.style() }),
            "SInnerLabelRequiredStartWarning" to ({ TextField.S.InnerLabel.RequiredStart.Warning.style() }),
            "SInnerLabelRequiredEndWarning" to ({ TextField.S.InnerLabel.RequiredEnd.Warning.style() }),
            "XSWarning" to ({ TextField.Xs.Warning.style() }),
            "XSRequiredStartWarning" to ({ TextField.Xs.RequiredStart.Warning.style() }),
            "XSRequiredEndWarning" to ({ TextField.Xs.RequiredEnd.Warning.style() }),
            "XSOuterLabelWarning" to ({ TextField.Xs.OuterLabel.Warning.style() }),
            "XSOuterLabelRequiredStartWarning" to ({ TextField.Xs.OuterLabel.RequiredStart.Warning.style() }),
            "XSOuterLabelRequiredEndWarning" to ({ TextField.Xs.OuterLabel.RequiredEnd.Warning.style() }),

            "XLError" to ({ TextField.Xl.Error.style() }),
            "XLRequiredStartError" to ({ TextField.Xl.RequiredStart.Error.style() }),
            "XLRequiredEndError" to ({ TextField.Xl.RequiredEnd.Error.style() }),
            "XLOuterLabelError" to ({ TextField.Xl.OuterLabel.Error.style() }),
            "XLOuterLabelRequiredStartError" to ({ TextField.Xl.OuterLabel.RequiredStart.Error.style() }),
            "XLOuterLabelRequiredEndError" to ({ TextField.Xl.OuterLabel.RequiredEnd.Error.style() }),
            "XLInnerLabelError" to ({ TextField.Xl.InnerLabel.Error.style() }),
            "XLInnerLabelRequiredStartError" to ({ TextField.Xl.InnerLabel.RequiredStart.Error.style() }),
            "XLInnerLabelRequiredEndError" to ({ TextField.Xl.InnerLabel.RequiredEnd.Error.style() }),
            "LError" to ({ TextField.L.Error.style() }),
            "LRequiredStartError" to ({ TextField.L.RequiredStart.Error.style() }),
            "LRequiredEndError" to ({ TextField.L.RequiredEnd.Error.style() }),
            "LOuterLabelError" to ({ TextField.L.OuterLabel.Error.style() }),
            "LOuterLabelRequiredStartError" to ({ TextField.L.OuterLabel.RequiredStart.Error.style() }),
            "LOuterLabelRequiredEndError" to ({ TextField.L.OuterLabel.RequiredEnd.Error.style() }),
            "LInnerLabelError" to ({ TextField.L.InnerLabel.Error.style() }),
            "LInnerLabelRequiredStartError" to ({ TextField.L.InnerLabel.RequiredStart.Error.style() }),
            "LInnerLabelRequiredEndError" to ({ TextField.L.InnerLabel.RequiredEnd.Error.style() }),
            "MError" to ({ TextField.M.Error.style() }),
            "MRequiredStartError" to ({ TextField.M.RequiredStart.Error.style() }),
            "MRequiredEndError" to ({ TextField.M.RequiredEnd.Error.style() }),
            "MOuterLabelError" to ({ TextField.M.OuterLabel.Error.style() }),
            "MOuterLabelRequiredStartError" to ({ TextField.M.OuterLabel.RequiredStart.Error.style() }),
            "MOuterLabelRequiredEndError" to ({ TextField.M.OuterLabel.RequiredEnd.Error.style() }),
            "MInnerLabelError" to ({ TextField.M.InnerLabel.Error.style() }),
            "MInnerLabelRequiredStartError" to ({ TextField.M.InnerLabel.RequiredStart.Error.style() }),
            "MInnerLabelRequiredEndError" to ({ TextField.M.InnerLabel.RequiredEnd.Error.style() }),
            "SError" to ({ TextField.S.Error.style() }),
            "SRequiredStartError" to ({ TextField.S.RequiredStart.Error.style() }),
            "SRequiredEndError" to ({ TextField.S.RequiredEnd.Error.style() }),
            "SOuterLabelError" to ({ TextField.S.OuterLabel.Error.style() }),
            "SOuterLabelRequiredStartError" to ({ TextField.S.OuterLabel.RequiredStart.Error.style() }),
            "SOuterLabelRequiredEndError" to ({ TextField.S.OuterLabel.RequiredEnd.Error.style() }),
            "SInnerLabelError" to ({ TextField.S.InnerLabel.Error.style() }),
            "SInnerLabelRequiredStartError" to ({ TextField.S.InnerLabel.RequiredStart.Error.style() }),
            "SInnerLabelRequiredEndError" to ({ TextField.S.InnerLabel.RequiredEnd.Error.style() }),
            "XSError" to ({ TextField.Xs.Error.style() }),
            "XSRequiredStartError" to ({ TextField.Xs.RequiredStart.Error.style() }),
            "XSRequiredEndError" to ({ TextField.Xs.RequiredEnd.Error.style() }),
            "XSOuterLabelError" to ({ TextField.Xs.OuterLabel.Error.style() }),
            "XSOuterLabelRequiredStartError" to ({ TextField.Xs.OuterLabel.RequiredStart.Error.style() }),
            "XSOuterLabelRequiredEndError" to ({ TextField.Xs.OuterLabel.RequiredEnd.Error.style() }),

            "XLSuccess" to ({ TextField.Xl.Success.style() }),
            "XLRequiredStartSuccess" to ({ TextField.Xl.RequiredStart.Success.style() }),
            "XLRequiredEndSuccess" to ({ TextField.Xl.RequiredEnd.Success.style() }),
            "XLOuterLabelSuccess" to ({ TextField.Xl.OuterLabel.Success.style() }),
            "XLOuterLabelRequiredStartSuccess" to ({ TextField.Xl.OuterLabel.RequiredStart.Success.style() }),
            "XLOuterLabelRequiredEndSuccess" to ({ TextField.Xl.OuterLabel.RequiredEnd.Success.style() }),
            "XLInnerLabelSuccess" to ({ TextField.Xl.InnerLabel.Success.style() }),
            "XLInnerLabelRequiredStartSuccess" to ({ TextField.Xl.InnerLabel.RequiredStart.Success.style() }),
            "XLInnerLabelRequiredEndSuccess" to ({ TextField.Xl.InnerLabel.RequiredEnd.Success.style() }),
            "LSuccess" to ({ TextField.L.Success.style() }),
            "LRequiredStartSuccess" to ({ TextField.L.RequiredStart.Success.style() }),
            "LRequiredEndSuccess" to ({ TextField.L.RequiredEnd.Success.style() }),
            "LOuterLabelSuccess" to ({ TextField.L.OuterLabel.Success.style() }),
            "LOuterLabelRequiredStartSuccess" to ({ TextField.L.OuterLabel.RequiredStart.Success.style() }),
            "LOuterLabelRequiredEndSuccess" to ({ TextField.L.OuterLabel.RequiredEnd.Success.style() }),
            "LInnerLabelSuccess" to ({ TextField.L.InnerLabel.Success.style() }),
            "LInnerLabelRequiredStartSuccess" to ({ TextField.L.InnerLabel.RequiredStart.Success.style() }),
            "LInnerLabelRequiredEndSuccess" to ({ TextField.L.InnerLabel.RequiredEnd.Success.style() }),
            "MSuccess" to ({ TextField.M.Success.style() }),
            "MRequiredStartSuccess" to ({ TextField.M.RequiredStart.Success.style() }),
            "MRequiredEndSuccess" to ({ TextField.M.RequiredEnd.Success.style() }),
            "MOuterLabelSuccess" to ({ TextField.M.OuterLabel.Success.style() }),
            "MOuterLabelRequiredStartSuccess" to ({ TextField.M.OuterLabel.RequiredStart.Success.style() }),
            "MOuterLabelRequiredEndSuccess" to ({ TextField.M.OuterLabel.RequiredEnd.Success.style() }),
            "MInnerLabelSuccess" to ({ TextField.M.InnerLabel.Success.style() }),
            "MInnerLabelRequiredStartSuccess" to ({ TextField.M.InnerLabel.RequiredStart.Success.style() }),
            "MInnerLabelRequiredEndSuccess" to ({ TextField.M.InnerLabel.RequiredEnd.Success.style() }),
            "SSuccess" to ({ TextField.S.Success.style() }),
            "SRequiredStartSuccess" to ({ TextField.S.RequiredStart.Success.style() }),
            "SRequiredEndSuccess" to ({ TextField.S.RequiredEnd.Success.style() }),
            "SOuterLabelSuccess" to ({ TextField.S.OuterLabel.Success.style() }),
            "SOuterLabelRequiredStartSuccess" to ({ TextField.S.OuterLabel.RequiredStart.Success.style() }),
            "SOuterLabelRequiredEndSuccess" to ({ TextField.S.OuterLabel.RequiredEnd.Success.style() }),
            "SInnerLabelSuccess" to ({ TextField.S.InnerLabel.Success.style() }),
            "SInnerLabelRequiredStartSuccess" to ({ TextField.S.InnerLabel.RequiredStart.Success.style() }),
            "SInnerLabelRequiredEndSuccess" to ({ TextField.S.InnerLabel.RequiredEnd.Success.style() }),
            "XSSuccess" to ({ TextField.Xs.Success.style() }),
            "XSRequiredStartSuccess" to ({ TextField.Xs.RequiredStart.Success.style() }),
            "XSRequiredEndSuccess" to ({ TextField.Xs.RequiredEnd.Success.style() }),
            "XSOuterLabelSuccess" to ({ TextField.Xs.OuterLabel.Success.style() }),
            "XSOuterLabelRequiredStartSuccess" to ({ TextField.Xs.OuterLabel.RequiredStart.Success.style() }),
            "XSOuterLabelRequiredEndSuccess" to ({ TextField.Xs.OuterLabel.RequiredEnd.Success.style() }),
        )
}
