package com.sdds.playground.sandbox.plasma.sd.service.integration.badge.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.plasma.sd.service.integration.s

internal object PlasmaSdServiceIconBadgeTransparentVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "TransparentLDefault" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLDefault,
            "TransparentLAccent" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLAccent,
            "TransparentLPositive" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLPositive,
            "TransparentLWarning" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLWarning,
            "TransparentLNegative" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLNegative,
            "TransparentLWhite" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLWhite,
            "TransparentLBlack" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLBlack,
            "TransparentLPilledDefault" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLPilledDefault,
            "TransparentLPilledAccent" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLPilledAccent,
            "TransparentLPilledPositive" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLPilledPositive,
            "TransparentLPilledWarning" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLPilledWarning,
            "TransparentLPilledNegative" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLPilledNegative,
            "TransparentLPilledWhite" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLPilledWhite,
            "TransparentLPilledBlack" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentLPilledBlack,
            "TransparentMDefault" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMDefault,
            "TransparentMAccent" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMAccent,
            "TransparentMPositive" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMPositive,
            "TransparentMWarning" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMWarning,
            "TransparentMNegative" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMNegative,
            "TransparentMWhite" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMWhite,
            "TransparentMBlack" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMBlack,
            "TransparentMPilledDefault" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMPilledDefault,
            "TransparentMPilledAccent" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMPilledAccent,
            "TransparentMPilledPositive" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMPilledPositive,
            "TransparentMPilledWarning" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMPilledWarning,
            "TransparentMPilledNegative" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMPilledNegative,
            "TransparentMPilledWhite" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMPilledWhite,
            "TransparentMPilledBlack" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentMPilledBlack,
            "TransparentSDefault" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSDefault,
            "TransparentSAccent" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSAccent,
            "TransparentSPositive" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSPositive,
            "TransparentSWarning" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSNegative,
            "TransparentSNegative" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSWarning,
            "TransparentSWhite" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSWhite,
            "TransparentSBlack" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSBlack,
            "TransparentSPilledDefault" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSPilledDefault,
            "TransparentSPilledAccent" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSPilledAccent,
            "TransparentSPilledPositive" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSPilledPositive,
            "TransparentSPilledWarning" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSPilledWarning,
            "TransparentSPilledNegative" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSPilledNegative,
            "TransparentSPilledWhite" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSPilledWhite,
            "TransparentSPilledBlack" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentSPilledBlack,
            "TransparentXsDefault" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsDefault,
            "TransparentXsAccent" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsAccent,
            "TransparentXsPositive" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsPositive,
            "TransparentXsWarning" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsWarning,
            "TransparentXsNegative" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsNegative,
            "TransparentXsWhite" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsWhite,
            "TransparentXsBlack" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsBlack,
            "TransparentXsPilledDefault" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsPilledDefault,
            "TransparentXsPilledAccent" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsPilledAccent,
            "TransparentXsPilledPositive" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsPilledPositive,
            "TransparentXsPilledWarning" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsPilledWarning,
            "TransparentXsPilledNegative" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsPilledNegative,
            "TransparentXsPilledWhite" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsPilledWhite,
            "TransparentXsPilledBlack" to s.Plasma_SdService_ComponentOverlays_IconBadgeTransparentXsPilledBlack,
        )
}
