package com.sdds.playground.sandbox.sdds.serv.integration.button.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.sdds.serv.integration.s

internal object SddsServIconButtonVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "LDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonLDefault,
            "LPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledDefault,
            "MDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonMDefault,
            "MPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledDefault,
            "SDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonSDefault,
            "SPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledDefault,
            "XsDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonXsDefault,
            "XsPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledDefault,
            "LSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonLSecondary,
            "LPilledSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledSecondary,
            "MSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonMSecondary,
            "MPilledSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledSecondary,
            "SSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonSSecondary,
            "SPilledSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledSecondary,
            "XsSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonXsSecondary,
            "XsPilledSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledSecondary,
            "LAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonLAccent,
            "LPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledAccent,
            "MAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonMAccent,
            "MPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledAccent,
            "SAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonSAccent,
            "SPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledAccent,
            "XsAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledAccent,
            "XsPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonXsAccent,
            "LPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonLPositive,
            "LPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledPositive,
            "MPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonMPositive,
            "MPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledPositive,
            "SPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonSPositive,
            "SPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledPositive,
            "XsPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPositive,
            "XsPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledPositive,
            "LNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonLNegative,
            "LPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledNegative,
            "MNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonMNegative,
            "MPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledNegative,
            "SNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonSNegative,
            "SPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledNegative,
            "XsNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonXsNegative,
            "XsPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledNegative,
            "LWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonLWarning,
            "LPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledWarning,
            "MWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonMWarning,
            "MPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledWarning,
            "SWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonSWarning,
            "SPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledWarning,
            "XsWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonXsWarning,
            "XsPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledWarning,
        )
}
