package com.sdds.playground.sandbox.sdds.serv.integration.button.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.sdds.serv.integration.s

internal object SddsServIconButtonVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "XLDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonXlDefault,
            "XLPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonXlPilledDefault,
            "LDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonLDefault,
            "LPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledDefault,
            "MDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonMDefault,
            "MPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledDefault,
            "SDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonSDefault,
            "SPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledDefault,
            "XsDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonXsDefault,
            "XsPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledDefault,
            "XXsDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsDefault,
            "XXsPilledDefault" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsPilledDefault,

            "XLSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonXlSecondary,
            "XLPilledSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonXlPilledSecondary,
            "LSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonLSecondary,
            "LPilledSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledSecondary,
            "MSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonMSecondary,
            "MPilledSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledSecondary,
            "SSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonSSecondary,
            "SPilledSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledSecondary,
            "XsSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonXsSecondary,
            "XsPilledSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledSecondary,
            "XxsSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsSecondary,
            "XxsPilledSecondary" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsPilledSecondary,

            "XLAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonXlAccent,
            "XLPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonXlPilledAccent,
            "LAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonLAccent,
            "LPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledAccent,
            "MAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonMAccent,
            "MPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledAccent,
            "SAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonSAccent,
            "SPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledAccent,
            "XsAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledAccent,
            "XsPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonXsAccent,
            "XxsAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsPilledAccent,
            "XxsPilledAccent" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsAccent,

            "XLPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonXlPositive,
            "XLPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonXlPilledPositive,
            "LPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonLPositive,
            "LPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledPositive,
            "MPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonMPositive,
            "MPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledPositive,
            "SPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonSPositive,
            "SPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledPositive,
            "XsPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPositive,
            "XsPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledPositive,
            "XxsPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsPositive,
            "XxsPilledPositive" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsPilledPositive,

            "XLNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonXlNegative,
            "XLPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonXlPilledNegative,
            "LNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonLNegative,
            "LPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledNegative,
            "MNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonMNegative,
            "MPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledNegative,
            "SNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonSNegative,
            "SPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledNegative,
            "XsNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonXsNegative,
            "XsPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledNegative,
            "XxsNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsNegative,
            "XxsPilledNegative" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsPilledNegative,

            "XLWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonXlWarning,
            "XLPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonXlPilledWarning,
            "LWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonLWarning,
            "LPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledWarning,
            "MWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonMWarning,
            "MPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledWarning,
            "SWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonSWarning,
            "SPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledWarning,
            "XsWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonXsWarning,
            "XsPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledWarning,
            "XxsWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsWarning,
            "XxsPilledWarning" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsPilledWarning,

            "XLClear" to s.Serv_Sdds_ComponentOverlays_IconButtonXlClear,
            "XLPilledClear" to s.Serv_Sdds_ComponentOverlays_IconButtonXlPilledClear,
            "LClear" to s.Serv_Sdds_ComponentOverlays_IconButtonLClear,
            "LPilledClear" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledClear,
            "MClear" to s.Serv_Sdds_ComponentOverlays_IconButtonMClear,
            "MPilledClear" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledClear,
            "SClear" to s.Serv_Sdds_ComponentOverlays_IconButtonSClear,
            "SPilledClear" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledClear,
            "XsClear" to s.Serv_Sdds_ComponentOverlays_IconButtonXsClear,
            "XsPilledClear" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledClear,
            "XxsClear" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsClear,
            "XxsPilledClear" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsPilledClear,

            "XLDark" to s.Serv_Sdds_ComponentOverlays_IconButtonXlDark,
            "XLPilledDark" to s.Serv_Sdds_ComponentOverlays_IconButtonXlPilledDark,
            "LDark" to s.Serv_Sdds_ComponentOverlays_IconButtonLDark,
            "LPilledDark" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledDark,
            "MDark" to s.Serv_Sdds_ComponentOverlays_IconButtonMDark,
            "MPilledDark" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledDark,
            "SDark" to s.Serv_Sdds_ComponentOverlays_IconButtonSDark,
            "SPilledDark" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledDark,
            "XsDark" to s.Serv_Sdds_ComponentOverlays_IconButtonXsDark,
            "XsPilledDark" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledDark,
            "XxsDark" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsDark,
            "XxsPilledDark" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsPilledDark,

            "XLBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonXlBlack,
            "XLPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonXlPilledBlack,
            "LBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonLBlack,
            "LPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledBlack,
            "MBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonMBlack,
            "MPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledBlack,
            "SBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonSBlack,
            "SPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledBlack,
            "XsBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonXsBlack,
            "XsPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledBlack,
            "XxsBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsBlack,
            "XxsPilledBlack" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsPilledBlack,

            "XLWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonXlWhite,
            "XLPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonXlPilledWhite,
            "LWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonLWhite,
            "LPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonLPilledWhite,
            "MWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonMWhite,
            "MPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonMPilledWhite,
            "SWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonSWhite,
            "SPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonSPilledWhite,
            "XsWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonXsWhite,
            "XsPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonXsPilledWhite,
            "XxsWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsWhite,
            "XxsPilledWhite" to s.Serv_Sdds_ComponentOverlays_IconButtonXxsPilledWhite,
        )
}
