package com.sdds.playground.sandbox.plasma.stards.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdkit.star.designsystem.R as DsR

internal object PlasmaStardsChipGroupDenseVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseL,
            "L.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLDefault,
            "L.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLAccent,
            "L.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLNegative,
            "L.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLPositive,
            "L.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLSecondary,
            "L.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLWarning,
            "L.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLPilled,
            "L.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLPilledDefault,
            "L.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLPilledAccent,
            "L.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLPilledNegative,
            "L.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLPilledPositive,
            "L.Pilled.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLPilledSecondary,
            "L.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseLPilledWarning,
            "M" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseM,
            "M.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMDefault,
            "M.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMAccent,
            "M.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMNegative,
            "M.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMPositive,
            "M.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMSecondary,
            "M.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMWarning,
            "M.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMPilled,
            "M.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMPilledDefault,
            "M.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMPilledAccent,
            "M.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMPilledNegative,
            "M.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMPilledPositive,
            "M.Pilled.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMPilledSecondary,
            "M.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseMPilledWarning,
            "S" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseS,
            "S.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSDefault,
            "S.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSAccent,
            "S.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSNegative,
            "S.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSPositive,
            "S.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSSecondary,
            "S.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSWarning,
            "S.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSPilled,
            "S.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSPilledDefault,
            "S.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSPilledAccent,
            "S.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSPilledNegative,
            "S.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSPilledPositive,
            "S.Pilled.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSPilledSecondary,
            "S.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseSPilledWarning,
            "Xs" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXs,
            "Xs.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsDefault,
            "Xs.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsAccent,
            "Xs.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsNegative,
            "Xs.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsPositive,
            "Xs.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsSecondary,
            "Xs.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsWarning,
            "Xs.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsPilled,
            "Xs.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsPilledDefault,
            "Xs.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsPilledAccent,
            "Xs.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsPilledNegative,
            "Xs.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsPilledPositive,
            "Xs.Pilled.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsPilledSecondary,
            "Xs.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupDenseXsPilledWarning,
        )
}
