package com.sdds.playground.sandbox.plasma.stards.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdkit.star.designsystem.R as DsR

internal object PlasmaStardsBadgeTransparentVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentL,
            "L.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLDefault,
            "L.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLAccent,
            "L.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLNegative,
            "L.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLPositive,
            "L.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLWarning,
            "L.Dark" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLDark,
            "L.Light" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLLight,
            "L.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLPilled,
            "L.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLPilledDefault,
            "L.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLPilledAccent,
            "L.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLPilledNegative,
            "L.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLPilledPositive,
            "L.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLPilledWarning,
            "L.Pilled.Dark" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLPilledDark,
            "L.Pilled.Light" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentLPilledLight,
            "M" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentM,
            "M.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMDefault,
            "M.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMAccent,
            "M.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMNegative,
            "M.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMPositive,
            "M.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMWarning,
            "M.Dark" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMDark,
            "M.Light" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMLight,
            "M.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMPilled,
            "M.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMPilledDefault,
            "M.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMPilledAccent,
            "M.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMPilledNegative,
            "M.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMPilledPositive,
            "M.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMPilledWarning,
            "M.Pilled.Dark" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMPilledDark,
            "M.Pilled.Light" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentMPilledLight,
            "S" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentS,
            "S.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSDefault,
            "S.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSAccent,
            "S.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSNegative,
            "S.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSPositive,
            "S.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSWarning,
            "S.Dark" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSDark,
            "S.Light" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSLight,
            "S.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSPilled,
            "S.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSPilledDefault,
            "S.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSPilledAccent,
            "S.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSPilledNegative,
            "S.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSPilledPositive,
            "S.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSPilledWarning,
            "S.Pilled.Dark" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSPilledDark,
            "S.Pilled.Light" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentSPilledLight,
            "Xs" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXs,
            "Xs.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsDefault,
            "Xs.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsAccent,
            "Xs.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsNegative,
            "Xs.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsPositive,
            "Xs.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsWarning,
            "Xs.Dark" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsDark,
            "Xs.Light" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsLight,
            "Xs.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsPilled,
            "Xs.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsPilledDefault,
            "Xs.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsPilledAccent,
            "Xs.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsPilledNegative,
            "Xs.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsPilledPositive,
            "Xs.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsPilledWarning,
            "Xs.Pilled.Dark" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsPilledDark,
            "Xs.Pilled.Light" to DsR.style.Sdkit_StarDs_ComponentOverlays_BadgeTransparentXsPilledLight,
        )
}
