package com.sdds.playground.sandbox.plasma.stards.integration.view

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdkit.star.designsystem.R as DsR

internal object PlasmaStardsChipGroupWideVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "L" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideL,
            "L.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLDefault,
            "L.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLAccent,
            "L.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLNegative,
            "L.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLPositive,
            "L.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLSecondary,
            "L.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLWarning,
            "L.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLPilled,
            "L.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLPilledDefault,
            "L.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLPilledAccent,
            "L.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLPilledNegative,
            "L.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLPilledPositive,
            "L.Pilled.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLPilledSecondary,
            "L.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideLPilledWarning,
            "M" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideM,
            "M.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMDefault,
            "M.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMAccent,
            "M.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMNegative,
            "M.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMPositive,
            "M.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMSecondary,
            "M.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMWarning,
            "M.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMPilled,
            "M.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMPilledDefault,
            "M.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMPilledAccent,
            "M.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMPilledNegative,
            "M.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMPilledPositive,
            "M.Pilled.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMPilledSecondary,
            "M.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideMPilledWarning,
            "S" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideS,
            "S.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSDefault,
            "S.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSAccent,
            "S.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSNegative,
            "S.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSPositive,
            "S.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSSecondary,
            "S.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSWarning,
            "S.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSPilled,
            "S.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSPilledDefault,
            "S.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSPilledAccent,
            "S.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSPilledNegative,
            "S.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSPilledPositive,
            "S.Pilled.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSPilledSecondary,
            "S.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideSPilledWarning,
            "Xs" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXs,
            "Xs.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsDefault,
            "Xs.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsAccent,
            "Xs.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsNegative,
            "Xs.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsPositive,
            "Xs.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsSecondary,
            "Xs.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsWarning,
            "Xs.Pilled" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsPilled,
            "Xs.Pilled.Default" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsPilledDefault,
            "Xs.Pilled.Accent" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsPilledAccent,
            "Xs.Pilled.Negative" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsPilledNegative,
            "Xs.Pilled.Positive" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsPilledPositive,
            "Xs.Pilled.Secondary" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsPilledSecondary,
            "Xs.Pilled.Warning" to DsR.style.Sdkit_StarDs_ComponentOverlays_ChipGroupWideXsPilledWarning,
        )
}
