package com.sdds.playground.sandbox.plasma.stards.integration.badge.icon

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.plasma.stards.integration.s

internal object StarDsIconBadgeSolidVariationsView : ViewStyleProvider<String>() {
    override val variations: Map<String, Int> =
        mapOf(
            "LDefault" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLDefault,
            "LAccent" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLAccent,
            "LPositive" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLPositive,
            "LWarning" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLWarning,
            "LNegative" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLNegative,
            "LLight" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLLight,
            "LDark" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLDark,
            "LPilledDefault" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLPilledDefault,
            "LPilledAccent" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLPilledAccent,
            "LPilledPositive" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLPilledPositive,
            "LPilledWarning" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLPilledWarning,
            "LPilledNegative" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLPilledNegative,
            "LPilledLight" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLPilledLight,
            "LPilledDark" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidLPilledDark,
            "MDefault" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMDefault,
            "MAccent" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMAccent,
            "MPositive" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMPositive,
            "MWarning" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMWarning,
            "MNegative" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMNegative,
            "MLight" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMLight,
            "MDark" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMDark,
            "MPilledDefault" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMPilledDefault,
            "MPilledAccent" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMPilledAccent,
            "MPilledPositive" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMPilledPositive,
            "MPilledWarning" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMPilledWarning,
            "MPilledNegative" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMPilledNegative,
            "MPilledLight" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMPilledLight,
            "MPilledDark" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidMPilledDark,
            "SDefault" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSDefault,
            "SAccent" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSAccent,
            "SPositive" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSPositive,
            "SWarning" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSNegative,
            "SNegative" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSWarning,
            "SLight" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSLight,
            "SDark" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSDark,
            "SPilledDefault" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSPilledDefault,
            "SPilledAccent" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSPilledAccent,
            "SPilledPositive" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSPilledPositive,
            "SPilledWarning" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSPilledWarning,
            "SPilledNegative" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSPilledNegative,
            "SPilledLight" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSPilledLight,
            "SPilledDark" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidSPilledDark,
            "XsDefault" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsDefault,
            "XsAccent" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsAccent,
            "XsPositive" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsPositive,
            "XsWarning" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsWarning,
            "XsNegative" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsNegative,
            "XsLight" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsLight,
            "XsDark" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsDark,
            "XsPilledDefault" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsPilledDefault,
            "XsPilledAccent" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsPilledAccent,
            "XsPilledPositive" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsPilledPositive,
            "XsPilledWarning" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsPilledWarning,
            "XsPilledNegative" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsPilledNegative,
            "XsPilledLight" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsPilledLight,
            "XsPilledDark" to s.Sdkit_StarDs_ComponentOverlays_IconBadgeSolidXsPilledDark,
        )
}
