name: 'Publish Maven'

description: 'Publish distribution to Maven Central'
inputs:
  bundle:
    description: 'distribution bundle name'
    required: true

  publishingType:
    description: 'distribution publishing type: USER_MANAGED or AUTOMATIC'
    required: true
    default: 'USER_MANAGED'

  publicationName:
    description: 'distribution publication name'
    required: true

  publicationToken:
    description: 'distribution publication token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload distribution to Maven Central
      shell: bash
      run: |
        P_TYPE=${{ inputs.publishingType }}
        P_NAME=${{ inputs.publicationName }}
        BUNDLE=${{ inputs.bundle }}
        curl --request POST \
          --verbose \
          --fail-with-body \
          --header 'Authorization: ${{ inputs.publicationToken }}' \
          --form bundle=@$BUNDLE \
          "https://central.sonatype.com/api/v1/publisher/upload?publishingType=$P_TYPE&name=$P_NAME"
