name: 'Prepare Android environment'

description: 'Setup gradle with cache'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: oracle
        cache: gradle

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties', '**/gradle.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Make Gradle executable
      shell: bash
      run: chmod +x ./gradlew
