nexus.artifactId=sdds-finai-compose
nexus.snapshot=false
nexus.description=sdds finai library for compose framework
versionMajor=0
versionMinor=2
versionPatch=0

theme-version=0.7.1
components-version=0.1.0

summary.key=sdds-finai

components-name=sdds_finai
theme-name=sdds_finai
theme-alias=SddsFinAi
theme-resPrefix=finai_cmp