package com.sdds.playground.sandbox.plasma.sd.service.integration.button.basic

import com.sdds.playground.sandbox.core.integration.ViewStyleProvider
import com.sdds.playground.sandbox.plasma.sd.service.integration.s

internal object PlasmaSdServiceBasicButtonVariationsView : ViewStyleProvider<String>() {

    override val variations: Map<String, Int> =
        mapOf(
            "LDefault" to s.Plasma_SdService_ComponentOverlays_BasicButtonLDefault,
            "XLDefault" to s.Plasma_SdService_ComponentOverlays_BasicButtonXlDefault,
            "MDefault" to s.Plasma_SdService_ComponentOverlays_BasicButtonMDefault,
            "SDefault" to s.Plasma_SdService_ComponentOverlays_BasicButtonSDefault,
            "XsDefault" to s.Plasma_SdService_ComponentOverlays_BasicButtonXsDefault,
            "XxsDefault" to s.Plasma_SdService_ComponentOverlays_BasicButtonXxsDefault,
            "XLSecondary" to s.Plasma_SdService_ComponentOverlays_BasicButtonXlSecondary,
            "LSecondary" to s.Plasma_SdService_ComponentOverlays_BasicButtonLSecondary,
            "MSecondary" to s.Plasma_SdService_ComponentOverlays_BasicButtonMSecondary,
            "SSecondary" to s.Plasma_SdService_ComponentOverlays_BasicButtonSSecondary,
            "XsSecondary" to s.Plasma_SdService_ComponentOverlays_BasicButtonXsSecondary,
            "XxsSecondary" to s.Plasma_SdService_ComponentOverlays_BasicButtonXxsSecondary,
            "XLAccent" to s.Plasma_SdService_ComponentOverlays_BasicButtonXlAccent,
            "LAccent" to s.Plasma_SdService_ComponentOverlays_BasicButtonLAccent,
            "MAccent" to s.Plasma_SdService_ComponentOverlays_BasicButtonMAccent,
            "SAccent" to s.Plasma_SdService_ComponentOverlays_BasicButtonSAccent,
            "XsAccent" to s.Plasma_SdService_ComponentOverlays_BasicButtonXsAccent,
            "XxsAccent" to s.Plasma_SdService_ComponentOverlays_BasicButtonXxsAccent,
            "XLPositive" to s.Plasma_SdService_ComponentOverlays_BasicButtonXlPositive,
            "LPositive" to s.Plasma_SdService_ComponentOverlays_BasicButtonLPositive,
            "MPositive" to s.Plasma_SdService_ComponentOverlays_BasicButtonMPositive,
            "SPositive" to s.Plasma_SdService_ComponentOverlays_BasicButtonSPositive,
            "XsPositive" to s.Plasma_SdService_ComponentOverlays_BasicButtonXsPositive,
            "XxsPositive" to s.Plasma_SdService_ComponentOverlays_BasicButtonXsPositive,
            "XLNegative" to s.Plasma_SdService_ComponentOverlays_BasicButtonXlNegative,
            "LNegative" to s.Plasma_SdService_ComponentOverlays_BasicButtonLNegative,
            "MNegative" to s.Plasma_SdService_ComponentOverlays_BasicButtonMNegative,
            "SNegative" to s.Plasma_SdService_ComponentOverlays_BasicButtonSNegative,
            "XsNegative" to s.Plasma_SdService_ComponentOverlays_BasicButtonXsNegative,
            "XxsNegative" to s.Plasma_SdService_ComponentOverlays_BasicButtonXxsNegative,
            "XLWarning" to s.Plasma_SdService_ComponentOverlays_BasicButtonXlWarning,
            "LWarning" to s.Plasma_SdService_ComponentOverlays_BasicButtonLWarning,
            "MWarning" to s.Plasma_SdService_ComponentOverlays_BasicButtonMWarning,
            "SWarning" to s.Plasma_SdService_ComponentOverlays_BasicButtonSWarning,
            "XsWarning" to s.Plasma_SdService_ComponentOverlays_BasicButtonXsWarning,
            "XxsWarning" to s.Plasma_SdService_ComponentOverlays_BasicButtonXxsWarning,
            "XLClear" to s.Plasma_SdService_ComponentOverlays_BasicButtonXlClear,
            "LClear" to s.Plasma_SdService_ComponentOverlays_BasicButtonLClear,
            "MClear" to s.Plasma_SdService_ComponentOverlays_BasicButtonMClear,
            "SClear" to s.Plasma_SdService_ComponentOverlays_BasicButtonSClear,
            "XsClear" to s.Plasma_SdService_ComponentOverlays_BasicButtonXsClear,
            "XxsClear" to s.Plasma_SdService_ComponentOverlays_BasicButtonXxsClear,
            "XLDark" to s.Plasma_SdService_ComponentOverlays_BasicButtonXlDark,
            "LDark" to s.Plasma_SdService_ComponentOverlays_BasicButtonLDark,
            "MDark" to s.Plasma_SdService_ComponentOverlays_BasicButtonMDark,
            "SDark" to s.Plasma_SdService_ComponentOverlays_BasicButtonSDark,
            "XsDark" to s.Plasma_SdService_ComponentOverlays_BasicButtonXsDark,
            "XxsDark" to s.Plasma_SdService_ComponentOverlays_BasicButtonXxsDark,
            "XLBlack" to s.Plasma_SdService_ComponentOverlays_BasicButtonXlBlack,
            "LBlack" to s.Plasma_SdService_ComponentOverlays_BasicButtonLBlack,
            "MBlack" to s.Plasma_SdService_ComponentOverlays_BasicButtonMBlack,
            "SBlack" to s.Plasma_SdService_ComponentOverlays_BasicButtonSBlack,
            "XsBlack" to s.Plasma_SdService_ComponentOverlays_BasicButtonXsBlack,
            "XxsBlack" to s.Plasma_SdService_ComponentOverlays_BasicButtonXxsBlack,
            "XLWhite" to s.Plasma_SdService_ComponentOverlays_BasicButtonXlWhite,
            "LWhite" to s.Plasma_SdService_ComponentOverlays_BasicButtonLWhite,
            "MWhite" to s.Plasma_SdService_ComponentOverlays_BasicButtonMWhite,
            "SWhite" to s.Plasma_SdService_ComponentOverlays_BasicButtonSWhite,
            "XsWhite" to s.Plasma_SdService_ComponentOverlays_BasicButtonXsWhite,
            "XxsWhite" to s.Plasma_SdService_ComponentOverlays_BasicButtonXxsWhite,
        )
}
