name: 'Build Release'

on:
  pull_request:
    branches:
      - release/*
      - hotfix/*
      - main

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-release:
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare-android-env

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Run assembleReleaseAll
        run: ./gradlew assembleReleaseAll --info -PbranchName=${{ steps.extract_branch.outputs.branch }}

      - name: Upload APK
        id: upload_apk
        if: success()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: artifacts
          path: | 
            **/build/outputs/apk/**/*.apk

      - name: Generate comment with artifact link
        shell: bash
        if: steps.upload_apk.outputs.artifact-url
        run: |
          sed "s|__APK_URL__|${{ steps.upload_apk.outputs.artifact-url }}|g" \
            .github/templates/apk-installation-instructions.md > build-summary.md

      - name: Attach comment to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.upload_apk.outputs.artifact-url
        with:
          path: build-summary.md
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
