name: Update Icons Pack

on:
  repository_dispatch:
    types: [ build-icons ]

jobs:
  icons:
    runs-on: ubuntu-latest

    steps:
      # делаем сheckout в текущем репозитория
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0
          path: current

      # делаем сheckout репозитория plasma
      - name: Checkout to Plasma Web
        uses: actions/checkout@v4
        with:
          repository: salute-developers/plasma
          ref: ${{ github.event.client_payload.ref }}
          show-progress: false
          path: plasma

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'plasma/.nvmrc'

      - name: Install plasma web project deps
        working-directory: ./plasma
        run: npm ci

      - name: Generate android icons
        working-directory: ./plasma
        run: |
          npx lerna bootstrap --scope="@salutejs/plasma-icons" --ignore-scripts
          npm run generate:android --prefix="packages/plasma-icons"

      - name: Extract current version
        id: extract_version
        working-directory: ./current
        shell: bash
        run: |
          PROPS=./sdds-core/icons/gradle.properties
          MAJOR=`cat $PROPS | grep "versionMajor" | cut -d'=' -f2`
          MINOR=`cat $PROPS | grep "versionMinor" | cut -d'=' -f2`
          PATCH=`cat $PROPS | grep "versionPatch" | cut -d'=' -f2`
          VER=$MAJOR.$MINOR.$PATCH
          echo $VER
          echo "tag=sdds-icons-v$VER" >> $GITHUB_OUTPUT

      - name: Retrieve tag exists flag
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{steps.extract_version.outputs.tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Verify tag not exists
        run: |
          if [ ${{ steps.checkTag.outputs.exists }} == true ]; then exit 1; else exit 0; fi

      - name: Verify release branch not exists
        working-directory: ./current
        shell: bash
        run: |
          git fetch --all
          if git branch -a | grep -q release/${{ steps.extract_version.outputs.tag }}; then exit 1; else exit 0; fi    

      - name: Create release branch
        working-directory: ./current
        shell: bash
        run: |
          git fetch --all
          git checkout -b release/${{steps.extract_version.outputs.tag}} develop

      - name: Create drawables folder
        working-directory: ./current
        continue-on-error: true
        run: mkdir -p ./sdds-core/icons/src/main/res/drawable

      - name: Move generated icons to drawable folder
        run: cp -rf plasma/packages/plasma-icons/android-icons/. current/sdds-core/icons/src/main/res/drawable/

      - name: Create tag and release pull request
        working-directory: ./current
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          TAG=${{steps.extract_version.outputs.tag}}
          PLASMA_VER=${{ github.event.client_payload.version }}
          git config --local user.email "salutedevs@gmail.com"
          git config --local user.name "Salute Android Team"
          git add ./sdds-core/icons/
          git commit -m "feat(sdds-acore/icons): New icons were added from plasma v$PLASMA_VER"
          git tag -a $TAG -m "Release $TAG"
          git push --set-upstream origin release/$TAG
          git push origin $TAG
          gh pr create --base main --head release/$TAG --title "Release $TAG" --body "Icons were updated to v$PLASMA_VER"
