name: 'Publish Sandbox Release'

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: true
  push:
    tags:
      - "sdds-sandbox-v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.head-ref }}
  cancel-in-progress: true

jobs:
  publish_and_release_apk:
    name: Build release artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare-android-env

      - name: Decrypt Keystore
        run: |
          echo "${{ secrets.KEY_STORE_FILE }}" | base64 -d -i > playground/sandbox/keystore.jks

      - name: Build Release APK
        env:
          KEY_STORE_FILE: "keystore.jks"
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.SANDBOX_RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.SANDBOX_RELEASE_KEY_PASSWORD }}
        run: ./gradlew :playground:sandbox:assembleRelease --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sandbox-release
          path: playground/sandbox/build/outputs/apk/release/*.apk

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          draft: true
          omitBody: true
          allowUpdates: true
          artifacts: playground/sandbox/build/outputs/apk/release/*.apk

      - name: Distribute to testers
        env:
          TESTFAIRY_API_KEY: ${{ secrets.TESTFAIRY_API_KEY }}
        run: sh .github/scripts/testfairy-uploader.sh playground/sandbox/build/outputs/apk/release/*.apk

