name: 'Publish SddsServ View Release'

on:
  push:
    tags:
      - "sdds-serv-v[0-9]+.[0-9]+.[0-9]+"
  # Delete after test
  pull_request:
    branches:
      - develop

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  publish-uikit:
    name: Generate sdds serv view distribution zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare-android-env

      - name: Generate distribution zip
        env:
          OSS_SIGNING_KEY_ID: ${{ secrets.OSS_SIGNING_KEY_ID }}
          OSS_SIGNING_KEY: ${{ secrets.OSS_SIGNING_KEY }}
          OSS_SIGNING_PASSWORD: ${{ secrets.OSS_SIGNING_PASSWORD }}
          PP_AUTH_TOKEN: ${{ secrets.PP_AUTH_TOKEN }}
        run: ./gradlew :tokens:sdds.serv.view:mavenPublish --info -PbranchName=main -PpublicationType=USER_MANAGED

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: tokens/sdds.serv.view/build/distributions/*.zip

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          draft: true
          allowUpdates: true
          omitBody: true
          artifacts: tokens/sdds.serv.view/build/distributions/*.zip
