name: 'Publish Sandbox-Compose Release'

on:
  repository_dispatch:
    types: [publish-sandbox-compose]
  workflow_dispatch:
    inputs:
      tag:
        description: "Тэг для релиза"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head-ref }}
  cancel-in-progress: true

jobs:
  publish_and_release_apk:
    name: Build release artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare-android-env

      - name: Decrypt Keystore
        run: |
          echo "${{ secrets.KEY_STORE_FILE }}" | base64 -d -i > playground/sandbox-compose/keystore.jks

      - name: Determine tag
        id: inputs
        run: |
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            TAG="${{ github.event.client_payload.tag }}"
          else
            TAG="${{ github.event.inputs.tag }}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT      

      - name: Build Release APK
        env:
          KEY_STORE_FILE: "keystore.jks"
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.SANDBOX_CMP_RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.SANDBOX_CMP_RELEASE_KEY_PASSWORD }}
        run: ./gradlew :playground:sandbox-compose:assembleAppRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sandbox-compose-release
          path: playground/sandbox-compose/build/outputs/apk/app/release/*.apk

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.inputs.outputs.tag }}
          draft: true
          allowUpdates: true
          omitBody: true
          generateReleaseNotes: true
          artifacts: playground/sandbox-compose/build/outputs/apk/app/release/*.apk

      - name: Distribute to testers
        env:
          TESTFAIRY_API_KEY: ${{ secrets.TESTFAIRY_API_KEY }}
        run: sh .github/scripts/testfairy-uploader.sh playground/sandbox-compose/build/outputs/apk/app/release/*.apk
